puppetlabs/puppetserver

Rakefile, acceptance/lib/helper.rb
* find latest passing puppet-agent
* update puppet submodule to the puppet SHA contained in the
puppet-agent build
* update beaker options file with puppet and puppet-agent versions
=> (SERVER-1870) create Rake tasks to update puppet submodule and acceptance pins

acceptance/suites/tests/00_smoke/puppetdb_integration.rb
We install PDB and smoke test it in
`acceptance/suites/tests/00_smoke/puppetdb_integration.rb`. As of
2017-07-17 the puppetlabs-puppetdb module will attempt to install
postgresql using a repo with in the https url. apt-get cannot use
https by default, the `apt-transport-https` package installs the addon
needed to use apt-get with https.
This patch installs `apt-transport-https` on debian variants.
=> (SERVER-1894) install `apt-transport-https` on Debian for PDB

acceptance/suites/tests/service_framework/reload_updated_crl.rb, dev/bootstrap.cfg, ezbake/system-config/services.d/bootstrap.cfg, project.clj, src/clj/puppetlabs/puppetserver/certificate_authority.clj, src/clj/puppetlabs/services/ca/certificate_authority_service.clj, test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj, test/integration/puppetlabs/services/master/environment_classes_int_test.clj, test/unit/puppetlabs/services/master/master_service_test.clj, test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj
This commit uses the tk-filesystem-watcher service to listen for changes
to the cacrl file.  When a change is detected, the cacrl file is copied
over to the hostcrl file.  This allows a watcher that the newer
tk-jetty9 service has established on changes to the hostcrl file to
trigger a reload of the CRL being used by the webserver, with no restart
to the webserver service being required.
The tk-jetty9 bump in this PR for the crl watcher changes also includes
a fix for previously failing gzip encoding for server responses.
To account for this fix, a couple of updates to the
environment-classes-int-test tests were added to account for the --gzip
text appended to some response etags.
=> (SERVER-1866) Copy the cacrl to the hostcrl file on change at runtime

acceptance/lib/helper.rb
This cherry-pick's b4b9938 from master into 5.0.x.
=> (SERVER-1893) Cherry-pick JRE switching in upgrade tests from master

spec/puppet-server-lib/puppet/jvm/master_spec.rb
Previously we checked the version of Puppet from PuppetServer's Ruby
interface. This test was checking that we could reach values that Puppet
sets in Ruby via JRuby running through Puppet Server's JVM layer.
Testing the version makes any kind of automated version bumping
problematic. There is a similar test that checks run_mode so the risk
in a bug not being caught by this test is small, and the return on
investment in automating some of our workflow is large.
This patch deletes the spec test.
=> (maint) delete puppet version spec test

resources/ext/build-scripts/gem-list.txt
Code to load translations in modules requires gettext-setup > 0.17. This
commit updates the gettext-setup dependency to the most recent version,
0.26.
=> (PUP-7794) Update gettext-setup gem dependency

documentation/install_from_packages.markdown
Per @kreeuwijk, add a target file in `/etc/apt/sources.list.d` for the command to add the `jessie-backports` package repository.
=> (DOC-3255) Fix jessie-backports command.

src/clj/puppetlabs/services/request_handler/request_handler_core.clj, test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj
Msgpack data, like other binary data, cannot be deserialized to a UTF-8
string. In general, we try to decode all payloads this way when we
receive requests. This commit adds an exception for payloads from
msgpack, sending them as is to Ruby Puppet.
This also updates the unit test concerning binary content types.
=> (SERVER-1755) Do not deserialize msgpack payloads to UTF-8 string

dev/user_repl.clj
Without this change running puppetserver from the repl fails trying to
find the filesystem-watch-service. This commit adds it to allow folks to
run from the repl.
=> (SERVER-1866) Add filesystem-watch-service to user_repl

Rakefile
In the master branch we are failing because the assumption in the rake task is that from the parsed JSON returned by jenkins we can find the parameters we need at
```rb
jenkins_result_parsed['actions'][0]['parameters']
```
However our master branch is currently failing because the parameter action is not the first element in the actions. See screen shot below or the output at [the latest failure](https://jenkins-master-prod-1.delivery.puppetlabs.net/job/platform_puppetserver_periodic-singleton_master/7/)
This searches for the correct element in the array instead of assuming it will be in the first position. It also improves the logging of raised exceptions for better debugging in the future. It will need to be merged up to master to fix CI.
=> (maint) Improve submodule bump

test/integration/puppetlabs/services/jruby/jruby_puppet_pool_int_test.clj, test/unit/puppetlabs/services/config/puppet_server_config_core_test.clj
Some clojure tests were inspecting setting information coming from
Puppet and Ruby to verify that the information could be fetched, but
this failed when Puppet itself changed a default value. This commit
changes the tested values to another string type value to check the same
code paths so we don't have to have tests depending on what version
of Puppet is in use.
=> (maint) Remove bindaddress config tests

dev/bootstrap.cfg, ezbake/system-config/services.d/bootstrap.cfg, src/clj/puppetlabs/services/ca/certificate_authority_service.clj, test/integration/puppetlabs/puppetserver/bootstrap_testutils.clj, test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj
* We encountered issues with the file system watcher service running on Java 7.
The puppet server 2.x line was previousy updated to use the file system watch
service for automatic crl reload functionality. However, the 2.x supports
Java 7. To avoid potentially destabilizing installs, especially so late in
the 2 series, make the file system watcher optional, defaulting to off. Users
can enable for Java 8 installs if desired by adding the file system watch
service to the bootstrap.cfg.
* Add a test that validates that the puppet server will not automatically
reload the crl if the file system watcher service has not been included in
the bootstrap.cfg.
* In order to facilitate this, we add a new test helper macro that allows you
to specify an additional set of services to be included along …
=> (SERVER-1866)(TK-149) Make crl reloading optional in puppetserver 2.x

acceptance/suites/tests/metrics/collect_default_metrics.rb
Previously we used a rarely updated in three years modules from an
employee that no longer works here.
That module is broken and the target OS for it is out of date (CentOS
6).
This patch updates the tests to use a new module within the puppetlabs
namespace and target CentOS 7.
=> (SERVER-1920) Use newer grafandash module for graphite integration

project.clj, src/clj/puppetlabs/services/ca/certificate_authority_service.clj
* This includes commits from https://github.com/puppetlabs/puppetserver/pull/1475, which should be merged first. To review the only intended change for this PR, see the commit `(SERVER-1886)(TK-448) Use non-recursive form of watcher`
* This PR switches to using the non-recursive from of the file system
watcher for crl reload functionality. Without this, a directory created in
the SSL dir owned by root would cause the service to fail.
* This is dependent on https://github.com/puppetlabs/trapperkeeper-filesystem-watcher/pull/17 being merged first
=> (SERVER-1886)(TK-448) Use non-recursive form of watcher

test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj
In testing, some java platforms on java 7 appear to return a "Connection reset
by peer" IOException instead of a ConnectionClosedException. Update the crl
reload test to accept either to ensure we pass on Java 7 in CI.
=> (TK-149)(SERVER-1866) catch ioexception in java 7 crl reload test

resources/ext/build-scripts/gem-list.txt
This version of the gem has the `translation_repository` method whose
absence is causing errors when loading modules.
=> (SERVER-1912) Update gettext-setup gem to latest version (0.26)

resources/ext/build-scripts/install-vendored-gems.sh
Invoking the jvm for every gem installation is very slow. In testing
chaining all the gem installs together removed ~6.5 minutes from build
times, and removing docs from the installs removed an additional 1.5
minutes.
=> (maint) optimizations for gem installations

dev-resources/puppetlabs/services/master/tasks_int_test/puppet.conf, documentation/puppet-api/v3/tasks.json, documentation/puppet-api/v3/tasks.markdown, ezbake/config/conf.d/auth.conf, src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj, src/clj/puppetlabs/services/master/master_core.clj, src/clj/puppetlabs/services/protocols/jruby_puppet.clj, src/java/com/puppetlabs/puppetserver/JRubyPuppet.java, src/ruby/puppetserver-lib/puppet/server/master.rb, test/integration/puppetlabs/puppetserver/testutils.clj, test/integration/puppetlabs/services/jruby/tasks_test.clj, test/integration/puppetlabs/services/master/tasks_int_test.clj, test/unit/puppetlabs/services/master/master_core_test.clj
This PR adds an endpoint that lists all tasks found in modules in a given environment. It queries Puppet's InfoService class to find this information. This will be consumed directly by orchestrator in PE, which will relay information to clients like the PE console or a command line tool so users know the tasks they have available to choose from. This endpoint is very similar to the environment_classes endpoint (although less complex), so much of the approach was copied from that code.
Task information is accessible for anyone with a valid certificate signed by the Puppet CA.
I wanted to get this up for review ASAP, so I don't have pre-docs yet. Currently working on them.
=> (SERVER-1925) List all tasks

project.clj, resources/ext/cli_defaults/cli-defaults.sh.erb
This configures EZBake to create a directory for users to place JARs in, and adds that directory to the classpath setup that runs when the user starts puppetserver.
=> (SERVER-249) Enable loading user-supplied JARs when puppetserver starts

documentation/crl_refresh.markdown, documentation/release_notes.markdown, ezbake/config/services.d/ca.cfg
This PR addresses two issues:
First, add documentation for automatic CRL refresh to the documentation directory and prepare for the 2.8.0 release with an updated release notes entry.
Second, Documentation suggests that users only configure services in /etc/puppetlabs/puppetserver/conf.d, not the config directory in /opt/puppetlabs. This commit adds a commented out entry for the file system watcher to the existing ca.cfg user configuration. While not in the `ca` namespace, since this setting affects the behavior of the CA it makes sense to place here rather than create a new additional file.
=> (SERVER-1866) add docs, release notes

project.clj
This commit will automatically trigger CI to build packages in prep for the 2.8.0 release
Should probably wait for https://github.com/puppetlabs/puppetserver/pull/1497 to get merged first
=> (SERVER-1898) Update version for 2.8.0 release

src/clj/puppetlabs/services/ca/certificate_authority_service.clj
This commit switches the filesystem-watcher to not use recursive
watching.
=> (SERVER-1933) Use non-recursive form of filesystem-watcher

documentation/puppet-api/v3/task_detail.json, documentation/puppet-api/v3/task_detail.markdown, src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj, src/clj/puppetlabs/services/master/master_core.clj, src/clj/puppetlabs/services/protocols/jruby_puppet.clj, src/java/com/puppetlabs/puppetserver/JRubyPuppet.java, src/ruby/puppetserver-lib/puppet/server/master.rb, test/integration/puppetlabs/puppetserver/testutils.clj, test/integration/puppetlabs/services/jruby/tasks_test.clj, test/integration/puppetlabs/services/master/tasks_int_test.clj
The purpose of this endpoint is to take some low-level data from puppet's `TaskInformationService`, flesh it out using some additional logic, and serve it to clients who will (probably) end up fetching an actual task executable from the `tasks` mount point.
The PR is divided into two commits:
1. Add the `getTaskData` method to the `JRubyPuppet` interface, which mostly just passes through to the `TaskInformationService`'s `task_data` method.
2. Add the `describe-task` function, which reads the files from the TaskData and returns the detailed task description, and the `/tasks/:module/:task` endpoint that calls that function.
=> (SERVER-1927) Add /tasks/:module/:task endpoint for detailed task information

resources/ext/build-scripts/gem-list.txt
This update contains code that makes the initial state of the locale
English rather than a random locale selected based on the order in which
translation files were found.
=> (PUP-7881) Update gettext-setup to version 0.28

test/unit/puppetlabs/services/master/master_core_test.clj
This patch removes a redundant requirement on ring.mock.request from the
puppetlabs.services.master.master-core-test test suite.
=> (maint) Remove redundant ring.mock.request

project.clj
This commit updates puppetserver's version to the next snapshot version
following the 5.1.0 release.
=> (packaging) Bump version to 5.1.1-SNAPSHOT

dev-resources/puppetlabs/services/master/tasks_int_test/puppet.conf, src/clj/puppetlabs/services/master/master_core.clj, test/integration/puppetlabs/puppetserver/testutils.clj, test/integration/puppetlabs/services/master/tasks_int_test.clj
Alter the task detail endpoint to return an error if the JSON metadata
for a task is unparseable.
This change is necessary for security reasons: if a task's metadata
restricts the allowed parameters to a task, and there's a typo preventing
that metadata from being parsed, we don't want people to be able to run
the task as if there are no restrictions in place (as would be the case
with an empty metadata object).
Getting the tests to passed required setting the environment_timeout to
zero, as it doesn't create all tasks at once (and an environment_timeout
of unlimited will cache what modules and tasks are found).
=> (SERVER-1973) Error on unparseable metadata

documentation/configuration.markdown, documentation/index.markdown, documentation/release_notes.markdown
-   Add Server 5.1.0 release notes.
-   Remove a redundant line from the documentation index.
Changes to be made in other PRs:
-   _config.yml updates to publish the docs to docs.puppet.com.
=> (docs) Puppet Server 5.1 release notes and docs updates

documentation/release_notes.markdown
Move one Markdown H1 to an H2, which will fix ToC rendering on docs.puppet.com.
=> (docs) Fix a markdown heading issue.

spec/puppet-server-lib/puppet/jvm/config_spec.rb, spec/puppet-server-lib/puppet/jvm/puppet_config_spec.rb, src/ruby/puppetserver-lib/puppet/server/logger.rb, src/ruby/puppetserver-lib/puppet/server/puppet_config.rb
In the early days of Puppetserver, the Puppet log level was maxed out in
order to pass all filtering control to logback. This approach didn't
take into account the potential cost of generating log messages and in
the real world can have performance implications.
This pull request resolves this problem by using the logback
puppetserver log level to set the Puppet log level. Because there is not
a 1:1 mapping of logback levels to Puppet levels the notice log level
cannot be set; if notice level information is needed then the info level
must be set.
=> (SERVER-1922) Set puppet log level from logback

Rakefile, acceptance/config/beaker/options.rb
This PR updates the puppet submodule to point to the most recent passing puppet-agent#5.3.x SHA. 
It also updates the submodule bump rake task to accept environment variables for branch configuration. It also updates the hard-coded fallbacks so that the Jenkins job doesn't immediately undo the bump in the previous commit. I will open a follow-up PR updating the Jenkins job to supply these env vars.
=> (SERVER-1995) Fix puppet submodule updating

acceptance/lib/helper.rb
A defect in the Puppet agent acceptance tests was causing spurious
failures in CI; this commit updates the Puppet submodule commit and
Puppet agent pins to pick up the acceptance test fix and keep all of the
packaging in sync.
=> (maint) Update puppet-agent pin to 1.10.8.31.g445a971

acceptance/suites/tests/00_smoke/puppetdb_integration.rb
The 5.2.0 release of the puppetlabs-postgresql module introduced an
ordering bug that can cause installation to fail; this commit pins the
module to an older version to sidestep the issue.
=> (maint) Downgrade psql version for integration

dev-resources/puppetlabs/services/master/tasks_int_test/echo, dev-resources/puppetlabs/services/master/tasks_int_test/hello_world, dev-resources/puppetlabs/services/master/tasks_int_test/warn_echo_and_error, project.clj, src/clj/puppetlabs/services/legacy_routes/legacy_routes_service.clj, src/clj/puppetlabs/services/master/master_core.clj, src/clj/puppetlabs/services/master/master_service.clj, test/integration/puppetlabs/general_puppet/general_puppet_int_test.clj, test/integration/puppetlabs/services/jruby/tasks_test.clj, test/integration/puppetlabs/services/master/tasks_int_test.clj, test/unit/puppetlabs/services/master/master_core_test.clj
Supports serving tasks via the static-file-content endpoint, and uses it in the tasks API when files are available via the endpoint.
Restructures tests to use a `with-running-server` fixture to simplify setup.
Blocked on a release with https://github.com/puppetlabs/clj-parent/pull/84.
=> (SERVER-1993) Add support for serving tasks via static-file-content

acceptance/suites/tests/00_smoke/puppetdb_integration.rb
The 5.2.0 release of the puppetlabs-postgresql module introduced an
ordering bug that can cause installation to fail; this commit pins the
module to an older version to sidestep the issue.
=> (maint) Downgrade psql version for integration (cherry pick from master)

documentation/puppet-api/v3/static_file_content.markdown, documentation/puppet-api/v3/task_detail.markdown, documentation/puppet-api/v3/tasks.markdown
-   Note in `static_file_content` endpoint docs that the `tasks` directory is also a valid source.
-   Add notes to `tasks` and `task_file` endpoints pointing to `static_file_content` endpoint.
-   Update links to new docs site.
-   Improve Markdown.
=> (DOC-3382)(SERVER-1993) Document tasks in static_file_content.

documentation/config_file_logbackxml.markdown
Document the `scan` and `scanPeriod` attributes in Server's Logback configuration, including the `scanPeriod` requirement per TK-426.
=> (docs)(TK-426) Document scan, scanPeriod in Logback.

acceptance/lib/helper.rb
Expect PuppetDB packages on Debian 9 (stretch).
Not quite sure where this needs to be targeted. Also relies on unreleased PuppetDB packages.
=> (SERVER-1972) Support Debian 9 in test setup

documentation/config_file_ca.markdown
Minor change to remove text suggesting the CA service is deprecated, when it's just the file.
=> (docs)(DOC-2445) Remove text indicating CA service is deprecated.

acceptance/lib/helper.rb, documentation/config_file_logbackxml.markdown, documentation/puppet-api/v3/static_file_content.markdown, documentation/puppet-api/v3/task_detail.markdown, documentation/puppet-api/v3/tasks.markdown, documentation/release_notes.markdown, ext/build_defaults.yaml
This merge up discards updates to the project.clj (version number,
master is pointing to 5.2.0 now) and our puppet source code pins (our
master branch automatically uptakes code from puppet/master).
This does pull in documentation and git history for our 5.1.x releases.
Conflicts:
acceptance/config/beaker/options.rb
project.clj
ruby/puppet
=> (maint) Merge 5.1.x into master

documentation/puppet-api/v3/task_detail.markdown
This field is actually called "sha256" vs. "SHA256".
=> (maint) Fix incorrect field name "SHA256" in task API doc

project.clj
Previously would send releases and snapshots to nexus, we want to ship these to artifactory instead
=> (RE-9730) Use artifactory instead of nexus

src/clj/puppetlabs/services/master/master_core.clj, test/integration/puppetlabs/services/jruby/tasks_test.clj, test/integration/puppetlabs/services/master/tasks_int_test.clj
Add a 'name' field to the response from the task details endpoint, whose
value is the task's fully-qualified name (which will be just the module
name for the init task).
=> (maint) Add name to task details response.

acceptance/lib/helper.rb
Prior to this commit, we were referring to an old sha. This commit
updates the test to simply point to the latest released version in the
puppet-agent 1.10.x series.
=> (maint) Update puppet-agent version for testing

acceptance/suites/tests/00_smoke/puppetdb_integration.rb
This is a dupe of https://github.com/puppetlabs/puppetserver/pull/1569 since we're not merging up from 2.x to 5.1.x+. Will need to be merged up to master after the merge.
=> (SERVER-2003) Remove puppetlabs-postgresql pin

project.clj
Some of the automated performance tests search for the latest build with
the word -master in the version string. This broke when -master was
removed from the version string between 5.0.1 and 5.1.0. This commit
adds it back in to get those tests working again.
=> (SERVER-2034) Add -master back into version string

documentation/release_notes.markdown
Fix a broken link to the Logback docs in the 5.1 release notes.
=> (docs)(DOC-3404) Fix broken link to Logback docs.

documentation/config_file_puppetserver.markdown, project.clj, test/integration/puppetlabs/services/jruby/jruby_puppet_pool_int_test.clj, test/unit/puppetlabs/services/config/puppet_server_config_service_test.clj
JRuby profiling support was added to jruby-utils in 0.11.0, so this
commit adds some docs around the relevant config settings and also
augments one of the jruby tests to validate that the profiler settings
work as expected.
Also includes an update to the latest jruby 9k.
=> (SERVER-1780) Test and document jruby profiler settings

project.clj
This commit updates to the latest version of ezbake, which includes packaging#1.0.x. This automation will enable shipping nightlies to weth, which syncs to s3, and will ultimately be served on nightlies.puppet.com.
=> (maint) Bump to ezbake 1.7.3

acceptance/suites/pre_suite/foss/95_install_pdb.rb, acceptance/suites/tests/00_smoke/puppetdb_integration.rb
PDB installation is gated on a list of supported platforms, which
differs(ed?) from the platforms that puppetserver builds and tests for.
Previously the pdb smoke tests were unconditionally run, even if pdb
wouldn't be there. This commit limits them both to only the platforms
listed in the puppetdb_supported_platforms method.
=> (SERVER-2022) Don't run pdb tests if pdb isn't there

spec/puppet-server-lib/puppet/jvm/execution_spec.rb, src/ruby/puppetserver-lib/puppet/server/execution.rb
Commands that use pipes and other shell characters are currently handled
incorrectly by puppetserver's Puppet::Server::Execution.execute method.
They are parsed by apache commons exec and treated as arguments to the
binary being invoked, which is almost certainly the wrong thing. In
order to allow commands with pipes and other shell characters to be
correctly invoked, this commit brings the execute method into line with
what MRI's Kernel.exec does by default. It checks the command string
against a list of known shell characters and if any are found, it
invokes the command with /bin/sh -c. The list of characters can be found
at https://github.com/ruby/ruby/blob/v2_4_2/process.c#L2166.
=> (SERVER-2064) Use /bin/sh for commands that use shell characters

test/integration/puppetlabs/services/master/environment_classes_int_test.clj
Update assertion for new error format introduced in
https://github.com/puppetlabs/puppet/commit/f31193ee68666c18d336a56532500b9f86b1627c
=> (PUP-8127) Update matcher for parse errors in environment cache tests

dev/puppetserver.conf.sample, documentation/config_file_puppetserver.markdown
This commit makes it clear that the http-client configuration will not
affect requests using ruby's net/http libraries directly. Previously
that clarity was absent.
=> (SERVER-2036) Clarify http-client configuration

resources/ext/build-scripts/gem-list.txt
This commit updates the fast_gettext version to 1.1.1, which contains a
file encoding bug fix. It also removes gettext-setup, which has ceased
to be a puppet runtime dependency.
=> (PUP-8249) Remove gettext-setup and update fast_gettext

spec/puppet-server-lib/puppet/jvm/config_spec.rb, spec/puppet-server-lib/puppet/jvm/puppet_config_spec.rb, src/ruby/puppetserver-lib/puppet/server/logger.rb, src/ruby/puppetserver-lib/puppet/server/puppet_config.rb
In the early days of Puppetserver, the Puppet log level was maxed out in
order to pass all filtering control to logback. This approach didn't
take into account the potential cost of generating log messages and in
the real world can have performance implications.
This pull request resolves this problem by using the logback
puppetserver log level to set the Puppet log level. Because there is not
a 1:1 mapping of logback levels to Puppet levels the notice log level
cannot be set; if notice level information is needed then the info level
must be set.
When Puppetserver is booting, it first configures the Ruby/JVM bindings
which includes tying logback in as a log destination, and then
configures Puppet. Because Puppet itself is configured after
Puppetserver it's possible for the default Puppet …
=>  (SERVER-1922) Defer settting Puppet log level, use logback

project.clj, test/integration/puppetlabs/services/master/master_service_test.clj
Starting in bidi 1.25.0, paths that contain invalid URI characters throw
an exception. Unfortunately, puppetserver uses tk-jetty9 and explicitly
tells tk-jetty9 to normalize URIs before handing them to the routing
layer. This means paths with encoded spaces are passed to bidi decoded,
and then have an exception raised, which in turn causes puppetserver to
return a 500. As this is undesireable behavior, this commit rolls the
bidi version in use to 1.23.1, which still allows decoded strings.
=> (SERVER-1954) Roll bidi back to 1.23.1

project.clj
This commit updates comidi to a version that is compatible with bidi
2.1.3, in which the bug with parsing URIs with spaces has been fixed.
This allows us to roll our bidi version forward to a working version,
instead of pinning back.
=> (SERVER-1954) Update comidi to 0.3.2

project.clj
This commit updates clj-parent to 1.6.1, which contains bidi 2.1.3. This
update fixes a bug with parsing URIs with spaces.
=> (SERVER-1954) Update clj-parent with new bidi

project.clj
This commit updates clj-parent to 1.7.0, which contains a version of
jackson-databind with a fix for CVE-2017-15095.
=> (SERVER-2076) Update clj-parent to 1.7.0

acceptance/suites/tests/00_smoke/puppetdb_integration.rb, src/clj/puppetlabs/services/puppet_profiler/puppet_profiler_core.clj, src/java/com/puppetlabs/puppetserver/MetricsPuppetProfiler.java, test/integration/puppetlabs/services/master/master_service_test.clj
This patch adds some additional patterns to the MetricsPuppetProfiler class and extends the `catalog-metrics` arrary reported by `status/v1/services/puppet-profiler` to include:
- `find_node`: Measures the time it took for the External Node Classifier to return node data during compilation.
A new `puppetdb-metrics` array is also present and will be populated if PuppetDB is used. Metrics included here are:
- `query`: Time spent waiting for PuppetDB to return query results.
- `resource_search`: Time spent waiting for PuppetDB to collect exported resources.
- `facts_encode`: Time spent in the Ruby terminus transforming fact data for PuppetDB.
- `command_submit_replace_facts`: Time spent waiting for PuppetDB to accept fact data.
- `catalog_munge`: Time spent in the Ruby terminus transforming …
=> (SERVER-1974) Add additional compiler metrics to status output

src/clj/puppetlabs/puppetserver/jruby_request.clj, src/clj/puppetlabs/services/jruby/jruby_metrics_core.clj, test/integration/puppetlabs/services/jruby/jruby_metrics_service_test.clj
This patch adds a new JRuby metric, `queue-limit-hit-meter`, that counts the
number of times the `max-queued-requests` limit was hit and provides
one minute, five minute and fifteen minute measurements on the rate at which
the hits are occurring. This metric can be used to monitor the amount of
traffic that Puppet Server is rejecting due to the `max-queued-request` limit.
The count and five minute rate are also added to the status output for the
JRuby service.
=> (SERVER-2025) Record metrics for max-queued-requests

documentation/config_file_puppetserver.markdown, project.clj, test/integration/puppetlabs/services/jruby/jruby_puppet_pool_int_test.clj, test/unit/puppetlabs/services/config/puppet_server_config_service_test.clj
This commit updates jruby-utils to 0.12.0, which changes the encoding
settings for the JRuby scripting containers to be UTF-8 by default,
instead of US-ASCII. This avoids a corner-case bug when interpolating
translated strings containing Unicode characters.
=> (SERVER-1954) Bump jruby-utils to 0.12.0

acceptance/lib/helper.rb, acceptance/suites/pre_suite/foss/00_setup_environment.rb
This commit removes the ability to use "latest" in the beaker config to
indicate that the most recent builds of the agent and puppetdb should be
fetched. We now have automation that keeps these versions up to date by
updating SHAs in the beaker config directly when jobs pass, so this
removes brittle hard-coded URLs that went out of date as Jenkins jobs
moved around.
=> (SERVER-2072) Remove logic for specifying 'latest' in test pre-suites

resources/ext/build-scripts/gem-list.txt
This commits adds the hiera-eyaml gem to the list of gems that get
installed with puppetserver. This makes it easier for users to take
advantage of the eyaml encrypted backend for hiera.
=> (SERVER-2066) Add hiera-eyaml gem to list of installed gems

project.clj
This commit pins jackson-databind to a version that contains a
remediation for CVE-2017-15095.
=> (SERVER-2076) Pin jackson-databind to 2.9.1

documentation/release_notes.markdown
Add release notes for Server 5.1.5.
> Puppet Server 5.1.5 is a bug-fix release that also adds packages for Debian 9 ("Stretch").
=> (docs) Add Server 5.1.5 release notes.

ext/build_defaults.yaml
Our automation is attempting to sign tarballs that aren't there. This will make sure we don't try to do that.
=> (maint) Add build_tar: FALSE to build_defaults

acceptance/suites/pre_suite/foss/95_install_pdb.rb, acceptance/suites/tests/00_smoke/master_starts_if_agent_run_before_ssl_files_inited.rb, acceptance/suites/tests/00_smoke/puppetdb_integration.rb
Previously, our PDB installation was using `with_puppet_running_on` which
caused the updated puppet.conf that PDB configured to not be saved
between runs. The PDB smoke test then re-ran the PDB module installation
code to get the puppet.conf updates. That PDB installation code
conflicts with PE, so there were failures when running that smoke test
in our PE pipelines (ie. it was tightly coupled to the FOSS pre-suite).
This updates the FOSS suite to leave the puppet.conf in place once it is
configured for PDB, removes the code from the smoke test that was
attempting to re-apply the module installation code, and updates a test
that was not correctly accounting for PDB being installed and
configured.
=> (PE-23484) Update PDB smoke test to work with existing installs

acceptance/suites/pre_suite/foss/95_install_pdb.rb, acceptance/suites/tests/00_smoke/master_starts_if_agent_run_before_ssl_files_inited.rb, acceptance/suites/tests/00_smoke/puppetdb_integration.rb
Previously we were installing PuppetDB in the FOSS test presuite and
then configuring it in the PuppetDB integration test. This configuring
caused the PuppetDB integration test to fail when ran in PE. Originally,
the effort to put the PuppetDB installation in the presuite was so that
it could be both installed and configured there and the test suite would
run in a more real world like scenario.
Consequently, we attempted to make the presuite both install and
configure PuppetDB and make the PuppetDB test work regardless of the
install type. After several attempts, it's become apparent that the work
to do would require re-writing a considerable number of tests within the
Puppet project as well.
This patch reverts configuring PuppetDB in the presuite, moving the
configuration of it back to …
=> (PE-23484) Disable FOSS PuppetDB integration test when running against PE

project.clj
Since updating clj-parent to 1.7.0, we no longer need to pin bidi. The
new version of clj-parent brings in the updated dependency.
=> (maint) Remove bidi pins

ext/build_defaults.yaml
This reverts commit 755a06aa627bbf2c9f82bc1698ebdbe4f971891c.
The FOSS_ONLY setting (used for shipping) was not properly retrieving tarballs,
but our ship process was still attempting to sign tarballs, causing the ship to
fail. This setting was added to prevent the attempted signing, but now that we
have fixed the underlying problem, this setting is no longer needed.
=> (maint) Revert "(maint) Add build_tar: FALSE to build_defaults"

project.clj
This commit updates puppetserver's version to 5.2.0 in preparation for
release.
=> (SERVER-2113) Update version to 5.2.0

documentation/release_notes.markdown
As of 1 p.m. PT Feb. 13 this should contain all content from JIRA release notes.
=> (docs) Add Puppet Server 5.2.0 release notes.

project.clj
This update brings in an updated version of tk-jetty9 that allows POST
request response bodies to be gzipped. Since catalog requests are made
with POST requests, catalogs will now come back from the server
gzipped.
=> (SERVER-2118) Update clj-parent to 1.7.1

project.clj, test/unit/puppetlabs/services/jruby/jruby_puppet_core_test.clj
The latest jruby-utils release includes a change that will enable jit
compile-mode automatically when using jruby 9k, which is desireable.
=> (maint) Update to latest jruby-utils

.travis.yml, Rakefile, ext/travisci/test.sh
Previously we would only run travis and specs against the default jruby.
This is undesirable as we would like to catch test failures against 9k
before merging, so this commit adds a matrix to the travis configuration
to run against both jruby versions. The Rakefile is also updated to
support running specs against jruby9k.
=> (maint) Run tests against jruby 9k as well as 1.7

acceptance/lib/helper.rb, acceptance/suites/pre_suite/foss/70_install_puppet.rb
The logic around installing puppet-agent on the agent nodes during test
setup had suffered a series of refactors that left some nonsense logic
in place. This commit updates that pre-suite to no longer check the
`puppet_version` variable, which a) referred to puppet itself, not the
agent, and b) was unnecessary for install because the version getting
installed is determined by which dev repo gets installed in a previous
step.
The install logic for Windows correctly uses `puppet_build_version` and
was left unchanged.
=> (SERVER-2024) Clean up puppet install in beaker pre-suite

dev-resources/puppetlabs/services/master/environment_classes_int_test/puppet.conf, dev-resources/puppetlabs/services/master/environment_modules_int_test/puppet.conf, test/integration/puppetlabs/services/jruby/tasks_test.clj
Previously environment_timeout was set to unlimited in the tasks tests.
Due to a puppet bug, we still saw new environments as they were created.
Once that bug was fixed, new environments would not be seen with it set
to unlimited because they would not be created until after puppet had
started up. Now we set it to 0 to ensure new environments are seen.
=> (maint) Set environment_timeout to 0 in tasks tests

Rakefile, acceptance/config/beaker/options.rb, acceptance/lib/helper.rb, acceptance/suites/pre_suite/foss/70_install_puppet.rb
This contains both the merge-up of the pre-suite cleanup from 2.x, as well as some additional cleanup to remove the puppet version field from the beaker options file, only present on 5.1.x and above.
=> (SERVER-2024) Merge 2.x -> 5.1.x, remove puppet_version from options file

dev-resources/puppetlabs/services/master/master_service_test/confdir/puppet.conf, ezbake/config/conf.d/auth.conf, src/clj/puppetlabs/services/master/master_core.clj, test/integration/puppetlabs/services/master/master_service_test.clj
This patch adds a comidi handler to the routing tree of the MasterService that
responds to PUT requests for `/puppet/v3/facts`.
=> (SERVER-2054) [#puppethack] Add support for PUT /puppet/v3/facts

acceptance/suites/puppet3_tests/puppet3_version_test.rb, acceptance/suites/puppet4_tests/puppet4_version_test.rb
This commits add Puppet 6 as an acceptable version to the "modern"
agents in compatibility tests.
=> (maint) Add Puppet 6 to compatibility tests

resources/ext/ezbake.conf
This depends on https://github.com/puppetlabs/ezbake/pull/472 to enable
setting tasks that run on package install, but not upgrade.
This should address the issue of package upgrades overwriting custom
config values.
=> (CPR-515) Only run config tasks on install, not upgrades

resources/ext/build-scripts/gem-list.txt
We ran into some issues with JrJackson's handling Ruby's BigDecimal
type, that causes numbers in scientific notation to be rendered to JSON
as strings, breaking our schema validation. Until this can be resolved,
we can't use the Jackson backend in Puppet Server, so this commit
removes the wrapper gem. MultiJson will now just select the built-in
JSON gem.
=> (SERVER-2098) Remove jrjackson gem

project.clj
Built successfully at http://builds.delivery.puppetlabs.net/puppetserver/2.8.2.SNAPSHOT.2018.03.09T1116/, locally running through acceptance tests right now
=> (RE-10172) Update to ezbake 1.1.13

dev-resources/puppetlabs/general_puppet/general_puppet_int_test/puppet.conf
In puppet 5 app_management doesn't do anything and this is just
producing useless warnings.
=> (maint) Remove deprecated setting in tests

resources/ext/build-scripts/gem-list.txt
This reverts commit c7cb533eb2df9840d3c5d66dd832a5f6f1b5291a, readding
the JrJackson gem now that we are properly configured to not parse
extreme numbers as BigDecimals.
=> Revert "(SERVER-2098) Remove jrjackson gem"

documentation/configuration.markdown
This commit adds some additional configuration instructions for those
enabling JRuby 9k. These settings were determined via extensive Gatling
testing to chase down performance degradations when running with 9k.
=> (SERVER-2147) Update docs with new 9k instructions

project.clj
The lein-exec plugin is needed for the updated lein release job. This
commit ensures the plugin gets installed for use in Jenkins.
=> (SERVER-2100) Install lein-exec plugin when in CI

ext/travisci/test.sh
We are currently causing ENOMEM errors in our travis testing from
running Facter 2.x in our CI with JRuby 9k. We expect switching to using
Facter 3 when they implement java support for the gem to fix this issue.
Lowering the heap size should help with the memory consumption of the
forked processes that facter 2 creates. In local testing lowering the
heap caused negligible test run time differences.
=> (maint) Use default heap size in travis tests

project.clj
The wrong version of ezbake got carried up in the last merge-up. This
commit corrects it to 1.8.1.
=> (maint) Correct ezbake version

acceptance/suites/pre_suite/puppet5_compat/70_install_puppet.rb, acceptance/suites/puppet4_tests/puppet4_version_test.rb, acceptance/suites/puppet5_tests/puppet5_version_test.rb
This commit adds tests for compatability between Puppet 5 agents and a
Puppet 6 master, similar to the existing compat tests for Puppet 3 and
4.
=> (SERVER-2154) Add Puppet 5 compat tests

acceptance/suites/pre_suite/puppet5_compat/70_install_puppet.rb
Previously we were not specifying the repo to use for downloading puppet
5 agents, so the test failed. This commit adds the puppet_collection
option with the 'puppet5' repo.
=> (maint) Use puppet5 repo when downloading agents for compat test

project.clj
This commit updates jruby-utils to 2.0.0, a version that has dropped
JRuby 1.7-specific logic. It also updates the JRuby version to
9.1.16.0-1, in line with our other branches and dependencies.
=> (SERVER-2160) Update jruby-utils to 2.0.0

project.clj, resources/ext/cli_defaults/cli-defaults.sh.erb
This commit updates puppetserver's build process to start bundling its
JRuby jar again, now that we are only supporting JRuby 9k. If the
JRUBY_JAR setting is used, either at the command line or in the init
config, a warning will be issued indicating that it is no longer needed.
=> (SERVER-2157) Re-bundle JRuby jar

project.clj
This commit changes the final and nonfinal repo targets to the puppet6 stream.
Previously, we had only done that in build_defaults, but it's also needed here.
=> (maint) Bump to puppet6

resources/ext/build-scripts/gem-list.txt
JrJackson seems to coerce non-UTF8 strings into UTF8 when generating
JSON, rather than raising and execption like the built in JSON module
does.
Puppet relies on this behavior to correctly downgrade to PSON when
there is binary data in the catalog/facts/report.
This remove JrJackson until we can sort out how to properly serialize
binary data with Jackson.
=> (PUP-8659) Remove JrJackson

resources/ext/build-scripts/gem-list.txt
With PA-1925, hiera-eyaml now ships with the agent package in the
shared gem directory.
=> (SERVER-2187) Remove the hiera-eyaml gem

src/ruby/puppetserver-lib/puppet/server/master.rb
When requesting a list of tasks, pass the requested environment as a
string rather than a symbol. The environment cache is primarily used
with string; pass as a string to ensure we re-use a cached environment
if available and avoid registering a cached environment based an a
symbol rather than string name.
=> (SERVER-2192) Use environment name string for listing tasks

documentation/install_from_packages.markdown, documentation/puppet_conf_setting_diffs.markdown
Originally PR #1685 by @kayayarai.
For clarity, revise instances of "and/or" and other similar constructs (such as "RHEL/CentOS") in the documentation to remove the slash.
=> (docs) Revise "and/or" in docs content

resources/ext/ezbake.conf
Puppet Server 6 needs to be installed with an agent >= 5.5.0, which
provides the shared gem dir that it relies upon for gems shared between
the agent and the JRuby server.
=> (maint) Update puppet-agent min required version to 5.5.0

documentation/http_api_index.markdown
The Puppet Server docs index (/documentation/index.md) contains links to
documentation for all Puppet Server-specific API endpoints. However, it
does not provide the same context as the Puppet HTTP API documentation,
and points to too much unrelated content to be a specific point of
entry about HTTP API endpoints.
Copy and revise the [Puppet HTTP API index](https://puppet.com/docs/puppet/latest/http_api/http_api_index.html)
and add details about Puppet Server-specific API endpoints.
This document must be maintained with changes, additions, removals, or
deprecations to both Puppet and Puppet Server HTTP API endpoints, and
should also be maintained for consistency whenever the Puppet HTTP API
index is updated.
=> (docs)(DOC-3552)(REVIEW ONLY) Create a Server API index.

src/clj/puppetlabs/services/jruby/jruby_metrics_core.clj, test/integration/puppetlabs/services/jruby/jruby_puppet_pool_int_test.clj, test/unit/puppetlabs/services/master/master_core_test.clj, test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj
The Travis tests for PR #1689 were timing out. Turned out that the cause was validation failing on mocked Ring requests that had previously never been exposed to the schemas in `puppetlabs.services.jruby.jruby-metrics-core`. This PR corrects three issues:
- The callback function registered by `puppetlabs.services.jruby.jruby-metrics-core` has no error trap. This caused the exceptions thrown by schema to be unlogged which meant that JRuby instances were silently never returned to the pool --- hence the test suite timeout.
- Several mocked ring requests were using `:GET` or `"get"` as their HTTP request method. Both Comidi and the Ring specs require lower-cased keywords like `:get`.
- The schema for `jruby-metrics-core/instance-request-info` expects the HTTP request map to include …
=> (maint) Fix mocked Ring requests and JRuby metrics error handling

project.clj
Prior to this our cljs building broke because of an incompatibility
between clojurescript and newer versions of clojure.spec.
This upgrades cljsbuild and clojurescript, excludes cljsbuild from
bringing in its version of clojurescript and sets an explicit dependency
in our ezbake profile.
=> (maint) Upgrade cljs tools to re-enable building

docker/Gemfile, docker/puppetserver-standalone/Dockerfile, docker/puppetserver-standalone/docker-entrypoint.sh, docker/puppetserver-standalone/logback.xml, docker/puppetserver-standalone/puppetserver, docker/puppetserver-standalone/request-logging.xml, docker/puppetserver-standalone/spec/dockerfile_spec.rb, docker/puppetserver/Dockerfile, docker/puppetserver/puppetdb.conf, docker/puppetserver/spec/dockerfile_spec.rb
These came from https://github.com/puppetlabs/puppet-in-docker
=> (CPR-553) Migrate puppetserver docker build scripts to the puppetserver repo

project.clj
The most relevant change in this update is that a HUP will now be logged
at INFO level rather than DEBUG.
=> (TK-466) Update clj-parent to 1.7.6

distelli-manifest.yml, docker/ci/build
The scripts allow us to set up a pipeline to build these containers on
pipelines.puppet.com.
=> (CPR-557) Add script to build puppetserver docker images

dev/dev_tools.clj, project.clj
Currently, we have a dependency on leiningen as a library so that we can run ``lein figwheel`` to access the cljs-dashboard-widgets. This commit uses figwheel-sidecar instead to start the figwheel server without calling the lein task. This allows us to remove dependencies on both leiningen and logback-classic.
=> (SERVER-2215) Upgrade cljs workflows to use fighweel-sidecar

dev-resources/puppetlabs/puppetserver/shell_utils_test/list_env_var_names, test/unit/puppetlabs/puppetserver/shell_utils_test.clj
Prior to this commit, the script used ruby to get the environment keys
to work around a problem discovered during [SERVER-1494](https://github.com/puppetlabs/puppetserver/commit/7275b67cae0c514b31e49f9d6033c11bc5f755da). By switching to
ruby we make unintended calls to CoreFoundations on OSX which adds an
additional environment variables __CF_USER_TEXT_ENCODING causing the
tests to fail only on OSX.
To fix this, this commit reverts the test script to the shell
and uses the cut tool to select the keys.
=> (SERVER-2232) Fix unit test failure on OSX

acceptance/README.md, acceptance/suites/tests/authorization/default_rules.rb, ezbake/config/conf.d/auth.conf, project.clj
The status service endpoint previously did not check the puppetserver
auth.conf file.  Now that it does, we will give it a default rule to
allow unauthenticated requests (default behavior).
=> (PE-24670) Add default authorization rule for status service endpoint

Gemfile, project.clj
This commit updates EZBake and beaker-hostgenerator in order to enable
building and testing Puppetserver on Ubuntu 18.04 Bionic.
=> (SERVER-2237) Update ezbake and beaker-hostgenerator for bionic

acceptance/suites/tests/code_commands/code_scripts.rb
Ubuntu 18.04 does not ship with a `python` executable, instead
providing only `python3`. This commit updates our test that uses Python
to check for the `python` executable and use `python3` instead if it
cannot be found.
=> (SERVER-2237) Use `python3` when `python` is not available

acceptance/suites/tests/certificate_authority/intermediate_ca.rb, resources/ext/build-scripts/mri-gem-list.txt, resources/ext/cli/ca.erb
This pulls in the remaining work for SERVER-2172, [_to be_] released in
puppetserver-ca 0.1.0 and updates the intermediate_ca acceptance test
accordingly.
=> (SERVER-2172) Pull in updated puppetserver-ca cmd

acceptance/suites/tests/certificate_authority/intermediate_ca.rb
This skips the test if there's no non-CA agent (we need at least those to hosts to properly test downloading all of the ssl files) and should resolve issues we're seeing in CI where we are running this test with only a single master & agent host.
While investigating `host.puppet['setting']` I remembered that `puppet_config` was added and should be used going forward (works with config sections rather than applications). See https://github.com/puppetlabs/beaker-puppet/commit/f5dcaa031bd7c6a15dc3914328960260238473ed#diff-1ad39dbbbad154ea718af70e36bca745 for details.
Will test locally with a mono install and w/o and report back.
=> (maint) Improve intermediate ca acceptance test

documentation/install_from_packages.markdown
Ubuntu 18.04 needs the universe repository enabled to install `openjdk-8-jre-headless`, which is required by Server. Document this.
=> (SERVER-2266) Note universe is required on 18.04.

acceptance/suites/tests/certificate_authority/intermediate_ca.rb, resources/ext/build-scripts/mri-gem-list.txt
This version of the gem has changed the `setup` subcommand to `import`. So
this commit also updates the tests to use the new subcommand.
=> (SERVER-2261) Update puppetserver-ca gem to 0.2.0

project.clj
This clj-parent bump updates the version of jetty to 9.4.11.v20180605.
=> (SERVER-2213) Upgrade clj-parent to 2.1.0

documentation/config_file_puppetserver.markdown
Update `profiling-mode` setting docs to specify that it profiles service
startup.
=> (docs)(DOCUMENT-889)(SERVER-2253) profiling-mode

resources/ext/build-scripts/mri-gem-list.txt
This update of the gem contains the CLI tools for replacing `puppet
cert`.
=> (SERVER-1747) Update puppetserver-ca gem to 0.3.0

acceptance/config/beaker/options.rb, project.clj
The Jenkins submodule job ran and updated our puppet pins to invalid values. Ezbake 1.8.6 has a bug. This undoes both of those changes.
=> Revert submodule and ezbake updates

docker/puppetserver-standalone/Dockerfile, docker/puppetserver-standalone/docker-entrypoint.sh, docker/puppetserver/Dockerfile
We now expect all of /etc/puppetlabs/puppet to live on a volume, rather
than just expecting ssl/ to live there.
That way, users can modify puppetserver configuration by editing files on
the volume from outside the container, and have those changes persist
across restarts/recreation of the container.
Since users should be able to start puppetserver with an empty volume, and
have the container populate it with sensible defaults, we also stash the
relevant configuration files in /var/tmp/puppet from where we retrieve them
if the container is started with those files on the volume. The files in
question are auth.conf, hiera.yaml, puppet.conf, and puppetdb.conf.
The only settings that we need to know when starting on an empty volume are
the certname and dns_alt_names for the server's …
=> (maint) Docker: change how we deal with puppetserver configuration

project.clj
This was added to help create a 'latest' stream for some perf testing
jobs. We have better ways of tracking 'latest' now, so this commit
removes the extra string, which was confusing version bump automation.
=> (maint) Remove 'master' from the version string

resources/ext/build-scripts/mri-gem-list.txt
This update adds the ability to specify a certname and a CA name as
flags to generate, both of which are used by the PE installer.
=> (maint) Bump CA CLI gem to 0.4.1

documentation/puppet-api/v3/task_detail.json, documentation/puppet-api/v3/task_detail.markdown, documentation/puppet-api/v3/tasks.json, src/clj/puppetlabs/services/master/master_core.clj, test/integration/puppetlabs/services/jruby/tasks_test.clj, test/integration/puppetlabs/services/master/tasks_int_test.clj
This adds support for multi-platform tasks by including all
"implementations in the "files" response for TaskDetails. In order to
prevent duplicating logic in both puppet-server and ruby this moves
metadata reading and validation out of clj in puppet-server and into
puppet itself.
fix tests
=> (SERVER-2156) add support for multi-platform tasks

project.clj
This commit bumps to the latest (legacy) ezbake version. This version adds a
Gemfile to the resulting package build and makes use of the packaging gem,
rather than cloning the packaging repo.
=> (maint) Bump to ezbake 1.1.15

src/clj/puppetlabs/puppetserver/certificate_authority.clj
This commit adds a custom extension in Puppet's arc that is checked when
allowing access to the certificate_status(es) endpoint. This extension
should only be added to the master's cert by the CLI tool's generate
command, and it is disallowed when signing other certs with this CA.
=> (SERVER-2287) Add OID for custom CLI auth extension

documentation/status-api/v1/services.markdown, documentation/status-api/v1/simple.markdown, ezbake/config/conf.d/auth.conf
Previously, we added the ability for the status service to honor tk-auth
configs. To provide backwards compatability we opened up the default
tk-auth rules for the status service to be un-authenticated. However, in
that work we only opened up /status/v1/services, to allow calls to all
endpoints mounted under the status service this relaxes the path to only
be /status/v1.
During the previous work we also updated the tk-status service
documentation, however we missed documenting this change in our public
Puppet Server documentation. This includes that update as well.
=> (SERVER-2302) Allow access to all status endpoints

project.clj, src/clj/puppetlabs/services/ca/certificate_authority_core.clj, test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj
This commit update clj-parent to 2.3.0, which contains an update to
liberator for java 9/10 compatability that required some code and test
changes.
=> (SERVER-2239) Update clj-parent to 2.3.0

src/clj/puppetlabs/puppetserver/certificate_authority.clj
This commit updates puppetserver's configuration to not use a separate
infrastructure CRL by default.
=> (SERVER-2231) Disable using the infrastructure CRL by default

src/clj/puppetlabs/puppetserver/certificate_authority.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
This commit updates the code that generates the master's host cert on
server start to add the auth extension needed by the CA CLI tool to talk
to the certificate_status endpoint.
=> (SERVER-2308) Update CA bootstrap code to add CLI auth extension

documentation/puppet-api/v3/static_file_content.markdown, src/clj/puppetlabs/services/master/master_core.clj, test/integration/puppetlabs/general_puppet/general_puppet_int_test.clj, test/integration/puppetlabs/services/jruby/tasks_test.clj
This verifies that the 'files' key includes all files including the task file, implementation files if provided, and helper files if provided in the metadata.
=> (SERVER-2283) Update task-details to include required task files

src/clj/puppetlabs/services/master/master_core.clj, test/integration/puppetlabs/services/jruby/tasks_test.clj
The puppet plugins mount is not module specific so we need to exclude
the module name when using the plugins mount.
=> (SERVER-2313) Don't include module name in plugins path

acceptance/suites/tests/certificate_authority/split_external_cas.rb
This commit removes a check from the external CA test that is no longer
valid due to poor messaging from Puppet. We ultimately want to update
the message to report the way the test expects now, so we are just
commenting out the assertion for now.
=> (maint) Comment out assertion failing due to messaging changes

.gitattributes, azure-pipelines.yml, docker/.rspec, docker/Gemfile, docker/ci/build.ps1, docker/puppetserver-standalone/Dockerfile, docker/puppetserver-standalone/healthcheck.sh
This enables building Docker images / containers in the Azure Devops Pipelines. Uses a custom agent in the `Default` agent pool that has Docker with LCOW supported installed / enabled, Ruby 2.5 and hadolint installed - all required for this build. It also has Go and Node.js installed, which are currently not required.
Currently requires https://github.com/puppetlabs/puppet_docker_tools/pull/26 (currently installing as a gem from that git ref) and has cherry-picked over test fixes in #1794 
Once those are merged, this can be rebased, edited to remove the cherry-picked commit and the git ref to the puppet_docker_tools PR, and merged.
=> (maint) Build Container in Azure Pipelines

documentation/config_file_ca.markdown, documentation/index.markdown, documentation/services_master_puppetserver.markdown
The `ca.conf` file was initially deprecated in Server 2.2, but that deprecation's scope was later limited to only certificate status authorization settings being supplanted by settings in Server's `auth.conf` file.
Some, but not all, of the documented deprecation notices didn't fully reflect this narrowed scope. Furthermore, new settings added in Server 6.0 are intended for `ca.conf`, so notices that suggest the entire file is deprecated are confusingly conflicting.
Remove the overly broad deprecation notices, and modify the heading of the "Status settings" section (which describes only deprecated settings) in the `ca.conf` doc.
=> (docs)(DOC-3750) Remove broad ca.conf deprecation notes

documentation/config_file_ca.markdown, ezbake/config/conf.d/ca.conf, resources/ext/config/conf.d/puppetserver.conf
This commit adds a ca.conf to the files ezbake installs alongside
puppetserver. It should be used for the new CA-related settings we added
in Server 6.
=> (SERVER-2327) Ship a default ca.conf

ezbake/config/conf.d/auth.conf, src/clj/puppetlabs/puppetserver/certificate_authority.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
This cherry-picks three commits from 6.0.x responsible for adding authentication for the CA CLI to the master cert out of the box:
1) Update to auth.conf to respect the extension
2) Addition of the extension OID to Puppetserver's list of recognized OIDs
3) Addition of the extension to the master cert during CA bootstrapping
=> (SERVER-2323) Backport CLI auth extension to 5.3.x

docker/ci/build.ps1
- Use the git describe as we're doing in Bash scripts to pull a version
from the repository when building / testing Docker containers
=> (maint) Add Docker build version support

src/clj/puppetlabs/services/ca/certificate_authority_core.clj, src/clj/puppetlabs/services/ca/certificate_authority_service.clj, test/integration/puppetlabs/services/legacy_routes/legacy_routes_test.clj, test/integration/puppetlabs/services/master/master_service_test.clj
This commit registers the CA service with the StatusService. It does not
register the DisabledCAService, so if that is enabled instead of the
regular CA service, no CA info will be available from the status
endpoint.
=> (SERVER-2350) Register the CA service with the status service

documentation/puppet_conf_setting_diffs.markdown, documentation/services_master_puppetserver.markdown
This commit removes or deprecates rack master, passenger and Ruby master in the docs.
=> (SERVER-2352) Remove mention of old features in the docs

project.clj
This contains an update to Jetty which fixes a security vulnerability.
=> (TK-472) Update clj-parent to 1.7.17

docker/ci/build
It's complicated trying to make sure `--no-latest` is set in the correct branches and nothing gets weird on mergeups. This adds the `IS_LATEST` environment variable that defaults to false and can be set to true for the one branch we need it set on in the build job.
=> (maint) Update 'latest' tag logic for Docker

docker/puppetserver-standalone/Dockerfile
This allows HEALTHCHECK routine to work with any container hostname.
=> Update health check script to use any hostname

documentation/release_notes.markdown
This commit adds the release notes for Puppet Server 6.0.2. Merge 23rd October.
=> (DOCS) Add puppetserver 6.0.2 release notes

docker/puppetserver-standalone/Dockerfile
Used double quotes on --resolve line
=> Correct quotation in healthcheck script

documentation/puppet-api/v3/environment_classes.markdown
This commit corrects the `environment_classes` endpoint page re. removed `resource_type`.
=> (DOC-3825) Update `environment_classes` endpoint page

documentation/config_file_puppetserver.markdown
This commit updates the compile-mode documentation to reflect SERVER-2130.
=> (DOCUMENT-936) Update compile-mode documentation

docker/Makefile
We should use `git fetch --unshallow` instead of `git pull --unshallow`
so we aren't merging. We should also use recursively expanded variables
for variables relating to versions so that they are set following the
execution of the 'prep' command.
=> (maint) Fixups for version determination in CI

project.clj
This commit bumps to the latest ezbake version. This version adds a Gemfile to
the resulting package build and makes use of the packaging gem, rather than
cloning the packaging repo.
=> (RE-11577) Bump to ezbake 1.1.17

documentation/index.markdown
I found that this link to the simple status endpoint was missing from the index and the nav bar while reviewing a PuppetDB PR, puppetlabs/puppetdb#2723.
=> (docs) Add link to simple status API page

.travis.yml
Conflicts:
- .travis.yml
- ruby/puppet
Took acceptance/submodule updates from 6, travis docker updates from
5.3.
=> (maint) Merge branch '5.3.x' into '6.0.x'

documentation/install_from_packages.markdown
This commit adds CentOS as a supported platform, based on DOC-3180.
=> (DOC-3180) Add CentOS as a supported platform

project.clj
This contains an update to Jetty to stop reporting the server version in
headers.
=> (TK-473) Update clj-parent to 1.7.18

project.clj
This also contains an update to clj-parent for TK-473.
=> Merge 5.3.x -> 6.0.x

.gitattributes, docker/puppetserver-standalone/Dockerfile, docker/puppetserver-standalone/docker-entrypoint.d/10-set-permissions.sh, docker/puppetserver-standalone/docker-entrypoint.d/20-use-templates-initially.sh, docker/puppetserver-standalone/docker-entrypoint.d/30-update-puppetdb-conf.sh, docker/puppetserver-standalone/docker-entrypoint.d/40-set-certname.sh, docker/puppetserver-standalone/docker-entrypoint.d/50-setup-autosign.sh, docker/puppetserver-standalone/docker-entrypoint.d/60-set-dns-alt-names.sh, docker/puppetserver-standalone/docker-entrypoint.sh
The entrypoint script was getting big and hard to extend. This change
splits the entrypoint script into individual scripts in docker-entrypoint.d
and reduces docker-entrypoint.sh to running scripts from that directory.
=> (maint) Change docker-entrypoint.sh to source from a directory

documentation/puppet_server_metrics.markdown
This commit updates the Puppet Server Metrics doc based on DOCUMENT-951 and DOCUMENT-950.
=> [skip ci] (DOCUMENT-951) + (DOCUMENT-950) Update Puppet Server Metrics doc 

docker/puppetserver-standalone/Dockerfile, docker/puppetserver-standalone/docker-entrypoint.d/35-update-puppetserver-conf.sh, docker/puppetserver-standalone/puppetserver.conf
This adds env variables `PUPPETSERVER_MAX_ACTIVE_INSTANCES` and
`PUPPETSERVER_MAX_REQUESTS_PER_INSTANCE` to allow `max-active-instances`
and `max-requests-per-instance` to be configured in
/etc/puppetlabs/puppetserver/conf.d/puppetserver.conf.
=> (CPR-650) Make puppetserver.conf more configurable

documentation/services_master_puppetserver.markdown
This commit removes mention of the classic Puppet Master application in the 6.0 docs, since it has been removed.
=> [skip ci] Update Puppet Server introduction

acceptance/config/beaker/options.rb, documentation/release_notes.markdown
This commit adds the release notes for Puppet Server 6.1.0. Merge 18th December.
=> (DOCS) Add puppetserver 6.1.0 release notes

Rakefile, project.clj
This commit updates clj-parent to 1.7.19, which pulls in
jackson-databind 2.9.8, fixing several security issues.
=> (SERVER-2418) Update clj-parent to 1.7.19

dev/dev_tools.clj
As part of removing the developer dashboard, we removed the need to
depend on lein as a dev dependency. It was removed from project.clj at
that time, but not from dev_tools.clj, meaning that the repl can no
longer be started on the 5.3.x series. In the 6.x series, this dep was
removed as part of the move to figwheel-sidecar. This commit removes it
from dev_tools.clj in the older branch.
=> (maint) Remove leftover lein dependency

Rakefile, documentation/known_issues.markdown, project.clj
This updates clj-parent to 2.5.0 for the jackson-databind CVE update.
=> Mergeup and clj-parent bump

project.clj
This downgrades dynapath to 0.2.5, fixing server reloads.
=> (SERVER-2421) Update clj-parent to 2.6.0

documentation/http_api_index.markdown
Some CA docs were removed from the Puppet docs repo, and you have updated versions in Puppet Server, so I'm changing the relevant URLs. This should affect any version 6.0 or later.
=> (docs) updating some URLS for >6.0 docs changes

documentation/release_notes.markdown
This commit adds the release notes for Puppet Server 6.2.0.
=> (DOCS) Add Puppet Server 6.2.0 release notes

project.clj
This brings in a new BouncyCastle, fixing a security vulnerability.
=> (SERVER-2431) Update clj-parent to 1.7.21

documentation/config_file_puppetserver.markdown
The documentation for the jruby profiling output file setting is incorrect. The current documentation shows profiling-output-file while the actual setting name is profiler-output-file. (https://github.com/puppetlabs/jruby-utils/blob/d8a8f9be9499f78356f5874d41b16cbeb65cc758/src/clj/puppetlabs/services/jruby_pool_manager/jruby_core.clj#L167)
=> (Docs) profiler-output-file setting incorrectly documented

acceptance/suites/pre_suite/foss/95_install_pdb.rb
Reverts puppetlabs/puppetserver#1952
The modules causing the dependency cycle have been updated and the problem is fixed.
=> Revert "(PDB-4232) Pin apt module to 6.2.1 when installing puppetDB"

project.clj
This commit bumps the ezbake version to 1.9.6, which adds support for el 8.
=> (RE-12077) Bump to ezbake 1.9.6

project.clj
This reverts commit 38fa24729e6006e33690c6e1feea00aa610567a1.
Tests started to fail after this bump, so reverting until we sort it out.
=> Revert "(RE-12077) Bump to ezbake 1.9.6"

docker/Makefile
Allow the Docker image namespace "puppet" (i.e. puppet/puppetserver) to
be configurable, which makes it easier for local development of the
image.
We don't want to push these images to DockerHub ever, so we don't honor
the namespace override in the `make publish` target.
=> (MAINT) Configurable image name

spec/puppet-server-lib/puppet/jvm/execution_spec.rb
This broke if `python` was python 3 due to syntax changes, but there's
no reason to require another language runtime to test this anyway.
=> (maint) Don't use python in test

ezbake/config/conf.d/auth.conf
Previously, the v4 endpoints were undeclared, so by default deny all.
However for documentation, testing, and later management purposes it is
valuable to have the two endpoint calling schemes spelled out in the
default auth.conf.
=> (maint) Update auth.conf for v4 catalog endpoints

documentation/config_file_auth.markdown
This commit removes EOL documentation and links to more detailed examples.
=> (DOC-3947) Update auth.conf docs

project.clj
This commit bumps the ezbake version to 1.9.7, which includes support for el 8.
=> (RE-12077) Bump to ezbake 1.9.7

src/clj/puppetlabs/services/master/master_core.clj, src/ruby/puppetserver-lib/puppet/server/compiler.rb, src/ruby/puppetserver-lib/puppet/server/log_collector.rb, src/ruby/puppetserver-lib/puppet/server/master.rb
This commit adds code to wrap the catalog compilation that captures any
logging emitted during the compilation and returns it along with the
catalog. Normally, this logging would just go into the main puppetserver
log, and would be interleaved with any other compilations going on,
making it very hard to tell where the messages were coming from. This
way, the logs are tied to the catalog whose compilation produced them.
Note that this means that the logs will NOT also go to Puppet Server's
normal log destination.
=> (SERVER-2475) Return logs from compilation with response

resources/ext/build-scripts/mri-gem-list.txt, src/clj/puppetlabs/puppetserver/certificate_authority.clj
This commit updates the list of required CA files to no longer include
the infra_serials file. This file is always updated (or created) when
puppetserver starts and the infra CRL feature is enabled, so it is
unnecessary to require it to be present beforehand. This requirement was
unnecessarily causing issues with upgrade workflows.
=> (SERVER-2478) Do not require `infra_serials` file on startup

acceptance/suites/pre_suite/foss/70_install_puppet.rb
Our image of RHEL 8 does not appear to have nss installed by default
this will conditionally install or upgrade depending on platform.
---
I haven't checked whether or not nss is necessary. The pre-suite still fails locally for me after the currently failing check because libfacter isn't available for JRuby.
Will check if nss is necessary and if the libfacter problem is specifically a RHEL8 problem
=> (maint) Install nss on RHEL 8

src/clj/puppetlabs/services/master/master_core.clj, src/ruby/puppetserver-lib/puppet/server/compiler.rb
Before this PR, the schema had a `job_id` that was propagated through to be used at compile time. However, all the code indicates that the proper name should be `code_id`,  and is furthermore determined by the `current-code-id-fn`.
This PR removes that `job_id` from the schema and plumbs the code_id function through to the v4 catalog endpoint.
=> (SERVER-2479) Plumb code_id through to the v4 catalog endpoint

spec/puppet-server-lib/puppet/jvm/compiler_spec.rb, src/clj/puppetlabs/services/master/master_core.clj, src/ruby/puppetserver-lib/puppet/server/compiler.rb
In order to use the classifier (or other terminus such as an ENC) we need
to use the indirector to retrieve the node. Whether to use the requested
environment is controlled by a new parameter in the request:
```json
{"options": {"prefer_requested_environment": <boolean>}}
```
=> (SERVER-2468) Use node indirection in v4/catalog

spec/puppet-server-lib/puppet/jvm/compiler_spec.rb, src/clj/puppetlabs/services/master/master_core.clj, src/ruby/puppetserver-lib/puppet/server/compiler.rb
This commit passes the `job_id` from the v4 catalog request along to
PuppetDB to be saved alongside the catalog.
=> (SERVER-2497) Save job_id along with catalog

acceptance/lib/helper.rb
This commit updates the list of supported PDB platforms to explicitly
exclude RHEL 8, because the puppetdb module is not currently supported
on that platform. This should be undone once RHEL 8 support is added to
the module.
=> (maint) Disable PDB on RHEL 8

acceptance/suites/tests/code_commands/code_scripts.rb
Several times as we've added new supported platforms, the state of their
default Python installation (python3 only, none) has caused problems for
our code script test, which was using Python relatively superfluously to
validate and pretty-print JSON. This commit removes that use of Python,
leaving it to the Ruby JSON parse tool to handle errors. This means we
no longer have any straggling dependencies on Python in these tests.
=> (SERVER-2501) Remove use of python from acceptance tests

src/clj/puppetlabs/services/legacy_routes/legacy_routes_service.clj, src/clj/puppetlabs/services/master/master_core.clj, src/clj/puppetlabs/services/master/master_service.clj, test/integration/puppetlabs/services/master/master_service_test.clj, test/unit/puppetlabs/services/master/master_core_test.clj
Creates the queue-limit middleware in MasterService then passes it through core methods until we get to v4-catalog-handler where we wrap the v4 catalog handler in similar JRuby related middleware. Updates tests and legacy-routes since they reach into master-core.
=> (SERVER-2477) Wrap v4 catalog endpoint with jruby queue limit

acceptance/suites/tests/catalog/v4_catalog.rb, src/clj/puppetlabs/services/master/master_core.clj, src/ruby/puppetserver-lib/puppet/server/compiler.rb, test/unit/puppetlabs/services/master/master_core_test.clj
Previously we were not requiring the caller of the v4 catalog endpoint
to provide an environment, assuming that the caller would know when it
was needed and supply the environment in those cases.
This led to the need to create defaults, either a specific environment
like "production" or Puppet's ":current_environment" within its context.
Neither of these are good defaults as default environments could be set
by users to some value besides production and
Puppet.lookup(:current_environment) has undefined, non-thread safe
semantics.
The simplest and most backwards compatible behavior is to always require
and environment from the endpoint caller.
This may be loosened in the future if we can define more concrete
workflows that may break backwards compatibility.
=> (maint) Require environment in v4 catalog endpoint

documentation/puppet-api/v4/catalog.markdown
We recently updated the request format for the v4 catalog endpoint to
make the environment key required. This commit updates the docs to
reflect that.
=> (maint) Document required `environment` field

azure-pipelines.yml, docker/ci/build.ps1, docker/puppetserver-standalone/.rspec, docker/puppetserver/.rspec, docker/spec/puppetserver_spec.rb, docker/spec/spec_helper.rb
- Emit more debug output in Azure / Docker builds
- Add some extra code to fail fast if network or containers can't be created for tests
- Change %x to a new helper command based on popen that emits stderr / captures stdout / returns error code
- Only read Azure metadata uri when in Azure VM
=> (maint) Update to Docker builds for Azure

documentation/release_notes.markdown
This commit adds the release notes for Puppet Server 5.3.8.
=> (DOCS) Add Puppet Server 5.3.8 release notes

documentation/release_notes.markdown
This commit adds the release notes for Puppet Server 6.3.0
=> (DOCS) Add Puppet Server 6.3.0 release notes

Rakefile, spec/puppet-server-lib/puppet/jvm/compiler_spec.rb, spec/puppet-server-lib/puppet/jvm/puppet_config_spec.rb, spec/spec_helper.rb
This adds our own spec_helper file and moves us to using rspec
expectations instead of mocha.
=> (maint) Use rspec expectations instead of mocha

project.clj
We inadvertently made this version of puppetserver require a version of
rbac-client that was not publicly available.
=> (maint) Use publicly available version of rbac-client

docker/puppetserver-standalone/docker-entrypoint.d/90-consul.sh
This check is super lightweight, so we should run it every second to
avoid unnecessary latency with consul knowing what services/hosts are
available
=> (maint) If consul is enabled, run the http healthcheck every second

acceptance/suites/tests/code_commands/code_scripts.rb
The Code command scripts test uses the puppetlabs/git module to set up a
FOSS code manager like environment. This module is deprecated and does
not support any of our currently supported versions of Debian. It does
however support RHEL variants that we will continue to support for the
long term.
Unfortunately, there is no clear cut replacement for the
functionality of the puppetlabs/git module and would require two
different modules to replace. At this point it is much more productive
to use the existing test setup on RedHat 7 for several more years before
surveying how we want to move off of puppetlabs/git.
=> (maint) Do not run code_commands test on Debian

documentation/restarting.markdown
This commit adds a note to address a user feedback question re. the `systemctl restart puppet command`.
=> (DOC-3964) Add note re. `systemctl restart puppet`

acceptance/suites/tests/authorization/default_rules.rb
The deafult rule for the report endpoint in PE was recently updated.
This test now verifies both versions of the rule.
=> (maint) Update auth.conf test for new PE report rule

docker/puppetserver/Dockerfile
If storeconfigs are configured in the 'main' section in puppet.conf, the
run will always use cached facts. This commits move those to the
'master' section so agent runs do not used cached facts.
=> (CPR-676) Move storeconfigs settings to the 'master' config section

docker/puppetserver-standalone/docker-entrypoint.sh
Supercedes #2007 
- In rare situations running chmod and the script directly afterwards
causes a 'Text file busy' error
- See moby/moby#13594 for details
- Similar change made to PDB at
https://github.com/puppetlabs/puppetdb/pull/2887
=> (maint) Fix 'Text file busy' error in Dockerfile 

documentation/compatibility_with_puppet_agent.markdown, documentation/config_file_auth_migration.markdown, documentation/config_file_puppetserver.markdown, documentation/configuration.markdown, documentation/dev_debugging.markdown, documentation/dev_running_from_source.markdown, documentation/http_api_index.markdown, documentation/http_certificate_revocation_list.md, documentation/puppet-api/v3/task_detail.json, documentation/puppet-api/v3/task_detail.markdown, documentation/puppet_conf_setting_diffs.markdown, documentation/puppet_server_metrics.markdown, documentation/puppet_server_metrics_performance.markdown, documentation/services_master_puppetserver.markdown, documentation/ssl_server_certificate_change_and_virtual_ips.markdown, documentation/subcommands.markdown, documentation/tuning_guide.markdown
Happy May, Server team! I bring you good tidings of docs pothole repair. 
This PR fixes instances of "once" and "since" in the puppetserver/documentation directory. Both of these words have several different meanings, which can make them ambiguous for non-native English speakers. I've changed many of these instances to more specific words like "because," "after," or "when." Where "since" indicates a given period of time passing ("since 1966"), I've left it alone.
=> (DOCS) clarify usage of once, since in docs

.dir-locals.el
CIDER, the interactive Clojure development environment, by default injects a
dependency on nREPL. Due to the dependency on nREPL 0.2.13 in project.clj and
`:pedantic :abort` this means that starting CIDER fails with a default config.
This tiny PR adds a `.dir-locals.el` which overrides the
`cider-inject-dependencies-at-jack-in` and sets it to `nil`.
=> Override Emacs CIDER nREPL dependency injection

docker/puppetserver-standalone/healthcheck.sh
Rather than using `puppet config print` to determine hostname and cert
locations, we hard-code directory paths and figure out the certname
based on what certificate we find on the filesystem.
This has some significant performance improvements over the previous
healthcheck.
Tested on a macbook, with old script:
$ time ./healthcheck.sh
real    0m2.405s
user    0m2.130s
sys     0m0.160s
tested on the same macbook, with new script:
$ time ./healthcheck.sh
real    0m0.092s
user    0m0.030s
sys     0m0.000s
=> (maint) Update puppetserver healthcheck to not use `puppet config print`

docker/docker-compose.yml
This moves to using `hostname` and `domainname` separately rather than
the having the domain included in the hostname. This is needed to work
in k8s.
=> (maint) Update docker-compose to contain fixes from pdb

.gitmodules, dev-resources/puppetlabs/services/master/environment_transports_int_test/puppet.conf, dev/puppetserver.conf, documentation/puppet-api/v3/environment_transports.json, documentation/puppet-api/v3/environment_transports.markdown, src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj, src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj, src/clj/puppetlabs/services/master/master_core.clj, src/clj/puppetlabs/services/protocols/jruby_puppet.clj, src/java/com/puppetlabs/puppetserver/JRubyPuppet.java, src/ruby/puppetserver-lib/puppet/server/master.rb, test/integration/puppetlabs/services/master/environment_classes_int_test.clj, test/integration/puppetlabs/services/master/environment_transports_int_test.clj, test/unit/puppetlabs/services/master/master_core_test.clj
This depends on https://github.com/puppetlabs/puppetserver/pull/2065 see https://github.com/justinstoller/puppetserver/compare/server2471-3...justinstoller:server2532 for a realistic diff.
I need to update the tests at a minimum. Though I'd love to go through and rename all our caching, but I'm not sure if that's just a nice to have, that could potentially do later.
=> (SERVER-2532) Enable caching for transports

acceptance/suites/pre_suite/foss/80_configure_puppet.rb
Cherry-pick of `c8de13c5`; required conflict resolution
Previous commit message:
---
Previously, we did not specify the server setting in the puppet.conf but
used `--server <server>` in any invocation that required it. The
`puppetserver ca` cli does not have a `--server` flag like puppet does
(it expects you to have your agent configured to actually talk to your
master correctly). Consequently we need to have the server value set in
our puppet.conf (the default of "puppet" is used by our internal Ops
infra). Previously, the puppetserver ca tool used a default server value
of `certname` rather than `puppet` so it didn't require this.
=> (maint) Specify `server` setting puppet.conf

resources/ext/cli/gem.erb, resources/ext/cli/irb.erb, resources/ext/cli/ruby.erb
On OpenJDK 8 the security.egd and securerandom.sourcefile parameters,
if set, should have a protocol attached their path. When using
`-Djava.security.debug=provider` one can see this error with the
previous value:
```
puppetserver[24654]: provider: Failed to create seed generator with /dev/urandom: java.net.MalformedURLException: no protocol: /dev/urandom
```
With this change service start up time (measure with just
`while true; do time systemctl restart puppetserver; done`)
goes from 27 seconds on redhat 7 to 20 seconds and from 23 seconds on
debian 8 to 18 seconds.
For gem install with the same loop but `puppetserver gem install r10k`
times go on redhat 7 from 20s to 14s.
I should note that removing this line completely also has the same
effect. It appears that in OpenJDK 8 and above …
=> (maint) Use protocol in egd java parameter

project.clj
This moves us from 1.9.7 to 2.0.4. The impetus is to pick up a change
that properly specifies the source of randomness when we start our
services. It will also be needed to pick up fips building in later
branches when this is merged up. The "breaking" changes from 1.x to 2.x
seem to be in build internals:
"Remove legacy-build action that used the removed artifacts. Packages
can only be built using FPM."
Which I don't think we care about. Molly says there's no reason we
shouldn't be on 2.x by now.
=> (maint) Bump EZBake to 2.0.4 for egd source change

acceptance/lib/puppetserver/acceptance/compat_utils.rb, acceptance/suites/compat_tests/020_backwards_compat/binary_file_test.rb, acceptance/suites/compat_tests/020_backwards_compat/source_file_test.rb, acceptance/suites/externalCA_tests/020-external-ca/010_setup_remote_ca.rb, acceptance/suites/externalCA_tests/020-external-ca/020_retrieve_new_cert.rb, acceptance/suites/externalCA_tests/020-external-ca/030_revoke_agents.rb, acceptance/suites/pre_suite/foss/80_configure_puppet.rb, acceptance/suites/tests/00_smoke/master_starts_if_agent_run_before_ssl_files_inited.rb, acceptance/suites/tests/00_smoke/puppetdb_integration.rb, acceptance/suites/tests/00_smoke/run_with_jruby9k.rb, acceptance/suites/tests/authorization/x509_auth.rb
This lays down a puppet.conf that contains a `server` setting in `main` for all nodes, not just the master.
It then removes the usage of `--server` from all tests and helpers that we can be sure are used in tests (there are pre-suites and helpers that are used in setup that continue to specify `--server`).
This also refactors the x509 auth test to use `with_puppet_running_on` vs HUPing the server.
=> (maint) Remove `--server` usage from tests

project.clj, src/clj/puppetlabs/puppetserver/certificate_authority.clj, test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
Use the ca key to detect the correct certificate to use from a
certificate bundle on the ca, and the ca cert to detect the correct crl
from a crl bundle.
=> (SERVER-2465) Allow ca certs and crl bundles to be in any order

.travis.yml
Trusty is going EOL and travis is migrating.
=> (maint) Update travis to use xenial image

project.clj
With the current repository setup in `project.clj`, `:repositories` and
`:deploy-repositories` are set to point to internal-to-puppet
infrastructure. While builds still succeed with these settings on
external networks, there is a noticible slowdown while waiting for
network timeouts.
This commit also adds an `internal` profile that can be used for builds
running on Puppet's internal network to access local repos/mirrors. To
use this new profile, run `lein with-profile ezbake,internal ezbake
build` in instances where you are currently running `lein with-profile
ezbake ezbake build`.
=> (maint) Don't override leiningen's default repositories by default

acceptance/suites/pre_suite/upgrade/10_install_puppet.rb
When moving to our archives the puppet-agent 1.x series (which contains
Puppet 4.x) had its zypper repo list corrupted. The invalid repo list
contains an extra "=" in it. See
https://tickets.puppetlabs.com/browse/RE-12490 for more info.
This works around it by using sed to remove the extraneous "="s.
=> (maint) sed zypper list when installing puppet-agent 1.x

src/clj/puppetlabs/services/jruby/jruby_metrics_core.clj, test/integration/puppetlabs/services/jruby/jruby_metrics_service_test.clj, test/integration/puppetlabs/services/master/master_service_test.clj
The changeset in this PR enhances the JRuby Metrics Service with the ability to time JRuby use per-borrow reason. Prior to these changes, the service only kept a single global borrow timer. This timer could show when JRuby performance was slowing down, but could not reveal whether the slowdown was coming from a specific use such as catalog requests, report uploads or file serving.
=> (SERVER-1975) Time JRuby use per-borrow reason

resources/ext/config/request-logging.xml, src/clj/puppetlabs/services/jruby/jruby_metrics_core.clj
This changeset updates the jruby-metrics implementation to store the
elapsed borrow time in the Logback mapped diagnostic context. The
default request log pattern is also updated to include the stored
borrow time in the puppet server access log using the mechanisms
added to trapperkeeper-webserver-jetty9 in TK-470.
Ref. puppetlabs/trapperkeeper-webserver-jetty9#192
The `Content-Length` header added to the `pe-puppetserver` access log in puppetlabs/pe-puppetserver#308 is also ported over.
=> (SERVER-2198) Add JRuby borrow time to the access log

documentation/puppet-api/v3/compile.markdown, spec/puppet-server-lib/puppet/jvm/ast_compiler_spec.rb, src/ruby/puppetserver-lib/puppet/server/ast_compiler.rb, src/ruby/puppetserver-lib/puppet/server/compiler.rb, src/ruby/puppetserver-lib/puppet/server/master.rb
This adds the Ruby logic to compile catalogs from snippets of Puppet AST. It is built on https://github.com/puppetlabs/puppetserver/pull/2069 (logging refactor) and https://github.com/puppetlabs/puppetserver/pull/2069 (Clojure endpoint exposure).
See https://github.com/puppetlabs/bolt/blob/master/lib/bolt/catalog.rb#L63-L90 for the bolt version of this functionality.
=> (SERVER-2540) Compile AST snippets

docker/puppetserver-standalone/Dockerfile, docker/puppetserver-standalone/README.md, docker/puppetserver-standalone/docker-entrypoint.d/80-ca.sh, docker/puppetserver/README.md
Add a specific ENV variable to the docker image that controls whether
the CA accepts or rejects SSL certs with subject alt names.
=> (MAINT) Add CA_ALLOW_SUBJECT_ALT_NAMES toggle

.travis.yml, project.clj
The commit b8e8ade that removes the hook may be a bad idea, or at least need a cjc change, I'm not sure.
I'm also not sure if the profile twiddling is better than the top level nrepl dependency or not.
I'd like to wait until I can get a lein-parent release of 0.3.7 to fix some warnings. See https://github.com/achin/lein-parent/pull/20 .
I didn't update the versions of voom, but I also don't _think_ it's used, but couldn't find the CI configs to confirm one way or the other.
=> (maint) Clean up project.clj

Gemfile, acceptance/scripts/generic/testrun.sh, acceptance/suites/pre_suite/foss/95_install_pdb.rb, acceptance/suites/tests/00_smoke/puppetdb_integration.rb
Tests that involve installing puppet modules will not work in FIPS mode. This restriction also precludes installing PuppetDB. This commit skips tests that rely on modules or PDB being installed.
=> (SERVER-2555) Make test suite run in FIPS mode

dev/install-test-gems.sh
Jenkins uses the `LEIN` env var to control the version of lein to use in
its jobs. This commit updates our script to install gems for testing to
respect this var.
=> (maint) Make test gem install respect LEIN env var

.dockerignore, .gitattributes, .gitignore, .travis.yml, azure-pipelines.yml, docker/Makefile, docker/ci/build.ps1, docker/puppetserver-standalone/Dockerfile
The docker image build has been updated to start with an ezbake
local-build so that we're running puppetserver 'from source' in the
containers.
=> Build puppetserver snapshot packages for use in docker images

resources/ext/cli/gem.erb, resources/ext/cli/irb.erb, resources/ext/cli/ruby.erb
The performance of urandom vs the defaults anecdotally has been the
same. If users would like to manage the egd source explicitly they're
encouraged to do so via the JAVA_ARGS_CLI variable.
=> (SERVER-2602) Stop setting egd in subcommands

acceptance/suites/pre_suite/foss/95_install_pdb.rb, acceptance/suites/tests/00_smoke/puppetdb_integration.rb, dev/puppetserver.conf, resources/ext/config/conf.d/puppetserver.conf, src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj, src/clj/puppetlabs/services/jruby/jruby_puppet_schemas.clj, src/ruby/puppetserver-lib/puppet/server/key_recorder.rb, src/ruby/puppetserver-lib/puppet/server/master.rb
This PR introduces a new lookup_key_recorder to track hiera lookups, as well as a new setting in the jruby-puppet configuration to turn aforementioned key_recorder on or off.
=> (SERVER-2585) hiera lookup config setting

Gemfile
The jira-ruby gem used to be used for generating tickets via a rake
task, but the only tickets we autogenerate now come from a centralized
repo of tasks, so we don't need this dep anymore. This commit removes
it, following an update to it that started limiting the Ruby versions
with which it can be installed.
=> (maint) Remove jira-ruby gem

docker/puppetserver-standalone/Dockerfile
Use nightly repos for resolving the puppet-agent runtime dependency in the docker containers.
=> (maint) use nightlies for containers

dev-resources/puppetlabs/services/master/plans_int_test/puppet.conf, src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj, src/clj/puppetlabs/services/master/master_core.clj, src/clj/puppetlabs/services/protocols/jruby_puppet.clj, src/java/com/puppetlabs/puppetserver/JRubyPuppet.java, src/ruby/puppetserver-lib/puppet/server/master.rb, test/integration/puppetlabs/puppetserver/testutils.clj, test/integration/puppetlabs/services/master/plans_int_test.clj
This adds the endpoints to expose the plan information service
from Puppet as an HTTP service.
Primarily this code is copy&paste from the similar glue for tasks,
with bits removed as needed (mostly around metadata and file lists,
since currently plans have neither of those). It seemed better to
duplicate rather than try to share code paths, since task and plan
metadata formats are more likely to diverge than converge.
The test for this currently includes an assertion that plan metadata
is empty, which will be a nice reminder for us to add tests for
metadata when it becomes available :sunglasses:
=> (SERVER-2543) Add endpoints for plans list and plan metadata

dev/puppetserver.conf, src/clj/puppetlabs/puppetserver/jruby_request.clj, src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj, src/clj/puppetlabs/services/protocols/jruby_puppet.clj, src/clj/puppetlabs/services/request_handler/request_handler_core.clj, src/clj/puppetlabs/services/request_handler/request_handler_service.clj
This commit allows you to specify "jruby-puppet.multithreaded=true" to
switch into a mode where all requests requiring a jruby instance are
passed through a single JRuby, designed to be running a thread-safe
puppet implementation.
It does not address other uses of JRuby instances (like settings
loading), it does not respect `max-requests-per-instance`, and it does
not work with pool locking (the instance is never returned so a request
to lock will block forever).
=> (SERVER-2529) Allow request handling with one shared JRuby instance

docker/puppetserver-standalone/Dockerfile
- Ignore problems in the first 2 minutes for bootstrapping, then allow
an additional minute to pass before marking unhealthy
=> (maint) Update healthcheck timings to max 3 mins

acceptance/suites/pre_suite/foss/95_install_pdb.rb
Now that the changes we need for Hiera lookup data collection have been
released in PDB, this commit updates our tests to use the puppet6
release repos, which will pull in the latest released version of PDB in
that stream.
=> (maint) Use puppet6 release repos for PuppetDB

docker/puppetserver/.rspec
We already fail fast if there's an error in :before blocks, and we'd
prefer to run all tests if it gets out of the :before block, so we
actually don't want --fail-fast.
=> (MAINT) Remove --fail-fast

resources/ext/cli_defaults/cli-defaults.sh.erb, src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj, src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj, test/unit/puppetlabs/services/jruby/jruby_puppet_core_test.clj
When we moved to supporting native Facter we began optionally
adding the facter.jar in clojure at runtime if it was available.
This is because Java only allows a native library to be loaded once per
JVM and attempting to load the library from different classloaders will
cause an error.
This approach was possible because the application classloader was a
global, mutable object.
See SERVER-718 & FACT-965 for the original work and rationale.
In Java 9+, the global classloaders are no longer mutable so the
classloader that the clojure code adds the facter.jar to is never seen
by any JRuby instance. This causes starting Puppet Server with more than
one JRuby instance, or reloading Puppet Server with only one JRuby
instance, or whenever Puppet Server tries to refresh the one JRuby
instance …
=> (SERVER-2423) Add facter.jar to system classpath from cli

src/ruby/puppetserver-lib/puppet/server/puppet_config.rb
Puppet @ a1153bf3b created a method to update the default
Puppet::Context that all request threads see. We need to put in a dummy
value for the :ssl_context in the Puppet::Context during Server init to
function properly in FIPS installs.
This updates us to take advantage of that global update method, fixing a
regression in FIPS functionality.
=> (maint) Push context changes globally during Server init

src/ruby/puppetserver-lib/puppet/server/key_recorder.rb, src/ruby/puppetserver-lib/puppet/server/master.rb
It isn't recommended and few do it, but we should generally allow
running agents and masters of similar versions, as it at least makes
upgrade scenarios easier for our users and git bisects and code
promotions easier on us.
=> (maint) Allow using Puppet code prior to 0f370f0fb

documentation/admin-api/v1/jruby-pool.markdown, project.clj, src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj, src/clj/puppetlabs/services/protocols/jruby_puppet.clj, src/clj/puppetlabs/services/puppet_admin/puppet_admin_core.clj, test/integration/puppetlabs/services/puppet_admin/puppet_admin_int_test.clj
This commit adds a `jruby-pool/thread-dump` endpoint to the admin API.
This endpoint can be used to retrieve a backtrace from each JRuby
interpreter registered to the pool when `-Djruby.management.enabled=true`
has been set in JAVA_ARGS.
=> (SERVER-2193) Add thread-dump endpoint to admin API

docker/puppetserver-standalone/Dockerfile, docker/puppetserver-standalone/docker-entrypoint.d/20-use-templates-initially.sh
We've realized most of the data in
/opt/puppetlabs/server/data/puppetserver is runtime data that should be
preserved as a volume during container runs. However,
`vendored-jruby-gems` only ever contains files installed at package
build time. Ideally these will move out of the data directory, but in
the interim work around it using the existing /var/tmp + entrypoint
pattern we have.
=> (maint) Preserve vendored gems at container build time

src/ruby/puppetserver-lib/puppet/server/puppet_config.rb
This change sets Indirection object settings globally so all threads have
the same settings. It requires that the `set_global_setting` definition
is available in the Indirection class; otherwise, it defaults to the
older, non-threadsafe way of using `setting=` to define various
indirection settings.
=> (PUP-9933) Use global indirection settings to configure Puppet

acceptance/config/beaker/options.rb, documentation/install_from_packages.markdown, documentation/release_notes.markdown, documentation/services_master_puppetserver.markdown
Release notes for 6.6, and a couple of file changes. 
I removed some info from pages, so please review those carefully and let me know if I removed something I shouldn't have. 
I removed:
out-of-stream release notes
outdated info on services_master_puppetserver.markdown 
outdated info on install_from_packages.markdown
=> 6.6 release

documentation/puppet-api/v3/plan_detail.markdown, documentation/puppet-api/v3/plans.markdown
In a previous commit [1] the plan list and plan metadata endpoints
were added. This commit adds API docs for those new endpoints.
[1]: 531ce7f86aeae13317e11b7569996b74e0895620
=> (SERVER-2543) add plan api docs

documentation/release_notes.markdown
Along with the release note for 6.7, I went through and removed the 6.0.x release notes, and added them to the corresponding 6.y versions (based on dates). If you see errors, please let me know and I'll fix.
=> 6.7 release

docker/Makefile, docker/puppetserver-standalone/Dockerfile, docker/spec/puppetserver_spec.rb
This is partly about making puppetserver / pe-puppetserver containers similar, but more about configuring a more reasonable healthcheck in addition to:
- Need a bundle update to be able to pull the pupperware spec_helper
(this primarily impacts local dev)
- Latest spec helpers include a new wait_on_stack_healthy that is
automatically called by docker_compose_up
Any explicit calls to wait on specific services are no longer
necessary
- Follow similar patterns set by other suites like pe-puppetserver
for the sake of consistency
- It's no longer necessary to follow a check for the docker-compose
binary
- Under LCOW, this container sometimes doesn't start in a 240s
initial time window.
Increase the initial failing healthcheck period to 4m from 2m and
increase the retries so that the container …
=> (maint) Update Docker healthcheck

azure-pipelines.yml, docker/puppetserver-standalone/Dockerfile
- Set reasonable upper bounds for various stages in Azure to abort
jobs quickly when Docker misbehaves
- Based on timings of trhe open source stack under LCOW, this container
typically starts in about 200s. Give the healthcheck an additional
100s buffer, allowing it to take up to 5m to be healthy, rather than 6m
=> (maint) Update healthcheck timeouts

project.clj
This update includes changes to Jetty cipher suites, an update of
jackson-xml to fix some CVEs, and an update for tk-filesystem-watcher to
improve error handling.
This commit also adds tk-filesystem-watcher as an explicit dependency,
rather than relying on its coming in transitively through tk-jetty9.
=> (maint) Update clj-parent to 4.2.6

project.clj
This updates jackson-databind to a more secure version, and
tk-fs-watcher to a version with better error handling.
=> (maint) Update clj-parent to 3.1.2

documentation/release_notes.markdown
This commit documents the removal of the developer dashboard in the release notes for Server 5.3.7. https://tickets.puppetlabs.com/browse/DOC-4223
=> (DOC-4223) Document removal of the Puppet Server developer dashboard

project.clj, src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj, src/clj/puppetlabs/services/jruby/jruby_puppet_schemas.clj, src/ruby/puppetserver-lib/puppet/server/puppet_config.rb, test/unit/puppetlabs/services/jruby/jruby_puppet_core_test.clj, test/unit/puppetlabs/services/jruby/jruby_puppet_testutils.clj
This change forces the puppet configuration to turn i18n off when in a
multithreaded jruby environment.
=> (SERVER-2630) Turn off puppet i18n when using multithreaded jruby

project.clj
This update downgrades JRuby to 9.2.8.0 to avoid a bug in 9.2.9.0.
=> (SERVER-2674) Update clj-parent to 4.2.8

src/clj/puppetlabs/services/ca/certificate_authority_core.clj, test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj
This change adds in the additional optional key `cert_ttl` for the
`certificate_status` endpoint that will override the `ca-ttl` CA
setting.
=> (PE-27515) Allow sign requests to specify ttl

documentation/release_notes.markdown
This note was accidentally removed from the 6.x docs. This commit adds
it back.
=> (DOC-4171) Add known issue about Ruby's process spawning

resources/ext/build-scripts/mri-gem-list-no-dependencies.txt
This update adds the ability to specify a `--ttl` flag with `sign` and
`generate` actions, which controls the TTL of the cert being created.
=> (SERVER-2678) Update CA CLI gem to 1.5.0

.github/workflows/docker.yml, docker/Makefile, docker/distelli-manifest.yml
Pipelines is EOL Jan 31, so we need to migrate to something else. This
adds a github action to lint, build, test, and publish containers on
pushes to the master branch.
Pipelines auto-builds have been disabled and necessary secrets have been
added to the puppetserver github repo.
=> (maint) Migrate container builds from pipelines to GitHub Actions

dev/puppetserver.conf, ext/thread_test/puppetserver.conf, project.clj, src/clj/puppetlabs/puppetserver/jruby_request.clj, src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj, src/clj/puppetlabs/services/protocols/jruby_puppet.clj, src/clj/puppetlabs/services/request_handler/request_handler_core.clj, src/clj/puppetlabs/services/request_handler/request_handler_service.clj, test/unit/puppetlabs/services/jruby/jruby_puppet_testutils.clj, test/unit/puppetlabs/services/master/master_core_test.clj, test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj
This reverts the interim implementation of the `multithreaded` mode, replacing it with the new JRuby reference pool.
=> (SERVER-2684) Take up new jruby-utils

docker/puppetserver-base/Dockerfile, docker/puppetserver/Dockerfile, docker/puppetserver/release.Dockerfile
- Reduce Dockerfile build steps
- Improve ability to cache build steps
- Make sure resulting images have all metadata correctly (including `build_date` and `vcs_ref`) 
- Ensure all constituent `Dockerfile` source files are copied into image (base Dockerfile and derivatives)
=> (maint) Improve Dockerfile organization

.travis.yml
- Segregate into:
before_install - for setting up tools like compose
before_script - for linting / building
script - for testing
- This allows for better timings of these individual sequences in
the Travis UI (for comparison with other build strategies later)
=> (maint) Restructure Travis container scripts

project.clj, src/clj/puppetlabs/services/puppet_admin/puppet_admin_core.clj
This includes the work for the `flush-timeout` setting in the JRuby ref pool.
=> (SERVER-2685) Bump jruby-utils to 3.0.1

project.clj, src/clj/puppetlabs/puppetserver/jruby_request.clj, test/integration/puppetlabs/services/jruby/jruby_metrics_service_test.clj
This patchset contains two improvements for the Server-side behavior of the `max-queued-requests` setting:
- 503 responses with `Retry-After` are not sent to HTTP clients that do not set a `X-Puppet-Version` header with `5.3.1` or newer. Puppet agents older than this version, or non-puppet agents won't understand what to do with the `Retry-After` header.
- A `Connection: close` header is added to any 503 response that includes `Retry-After`. This will cause Puppet agents to close their TCP connection to the server before sleeping for the amount of time specified by `RetryAfter`.
=> (SERVER-2405,SERVER-2696) Improve max-queued-requests behavior

documentation/install_from_packages.markdown
Conflicts were resolved by maintaining the state of the current branch, except
for the documentation changes for installing from packages.
=> Merge 5.3.x -> 6.3.x

documentation/install_from_packages.markdown
Conflicts were resolved by maintaining the state of the current branch, except
for the documentation changes for installing from packages.
=> Merge 6.3.x -> master

project.clj
This commit updates some ambiguous type specifications that were causing
problems on Java 11.
=> (maint) Update clj-parent to 4.2.11

.travis.yml, ext/travisci/test.sh, project.clj, src/clj/puppetlabs/services/master/master_core.clj, test/integration/puppetlabs/puppetserver/bootstrap_testutils.clj, test/integration/puppetlabs/services/jruby/jruby_metrics_service_test.clj, test/integration/puppetlabs/services/jruby/jruby_puppet_pool_int_test.clj, test/integration/puppetlabs/services/jruby/puppet_environments_int_test.clj, test/integration/puppetlabs/services/jruby/tasks_test.clj, test/unit/puppetlabs/services/jruby/jruby_puppet_testutils.clj
This allows the puppetserver clojure tests to be run in multithreaded mode when the `MULTITHREADED` environment variable is set to `true`. Setting this var will update the test configs to toggle the `multithreaded` setting. The tests should then be run with `lein test :multithreaded` to ensure correct filtering, since some tests require different implementations between the two modes.
=> (SERVER-2680) Parameterize Clojure tests for multithreaded mode

test/integration/puppetlabs/services/jruby/puppet_environments_int_test.clj
This commit adds a comment to the `environment-flush-integration-test`
explaining why it doesn't make sense to run this test (or a test like it) in
multithreaded mode.
=> (SERVER-2721) Explain single-threaded-only test

project.clj
This commit updates the default test filter to exclude tests that are
tagged with `:multithreaded-only`, since those tests require the
`MULTITHREAED` env var to be set in order to work correctly.
=> (maint) Exclude :multithreaded-only tests by default

documentation/release_notes.markdown
Combined the release notes for both SERVER-2678 and PE-27489 to make one release note that is (I hope) a little clearer. If this looks good to you, I can make the same change in the other relevant branches.
=> improve release note for TTL setting

dev-resources/puppetlabs/general_puppet/general_puppet_int_test/custom_trusted_oid_mapping.yaml, src/ruby/puppetserver-lib/puppet/server/certificate.rb, test/integration/puppetlabs/general_puppet/general_puppet_int_test.clj
PUP-6258 introduced the new oid ppAuthCertExt, but this new OID was
never added to the custom_extensions method. This commit adds the
missing OID and ensures that it can be accessed
=> (SERVER-2722) Add ppAuthCertExt to custom_extensions

docker/puppetserver/Dockerfile, docker/puppetserver/release.Dockerfile
For multi-stage builds, setting `ARG`s before the `FROM` makes their
scope global, but you still need to have an `ARG foo` line in each build
step to use the global `ARG foo`.
For single-stage builds, it doesn't make sense to define `ARG`s before
the `FROM` except for `ARG`s used in the `FROM`, since global scope
doesn't really help with only one stage.
=> (maint) Scoping for Docker ARGs is not intuitive

spec/puppet-server-lib/puppet/jvm/compiler_spec.rb, src/ruby/puppetserver-lib/puppet/server/compiler.rb
Set pe_serverversion in set_server_facts as per the same in puppet.
Document the other set_server_facts in puppet,
to reduce the chance of them being out of sync.
=> (SERVER-2724) set pe_serverversion in set_server_facts

src/ruby/puppetserver-lib/puppet/server/compiler.rb
This fact was added to the `server_facts` hash in puppet as part of PUP-5109,
so this commit ensures parity.
=> (SERVER-2724) Add missing `ipaddress6` fact to v4 catalog endpoint

project.clj
This update includes a tk-jetty update fixing an ambiguous type
inference when running with Java 11.
=> (SERVER-2734) Update clj-parent to 4.3.2

ext/thread_test/environments/funky/manifests/init.pp, ext/thread_test/environments/funky/modules/threader/lib/puppet/functions/threader/futurist.rb, ext/thread_test/environments/production/manifests/init.pp, ext/thread_test/environments/production/modules/threader/lib/puppet/functions/threader/futurist.rb, ext/thread_test/test.rb, spec/puppet-server-lib/puppet/jvm/certificate_spec.rb, spec/puppet-server-lib/puppet/jvm/logging_spec.rb, spec/puppet-server-lib/puppet/jvm/master_spec.rb, spec/puppet-server-lib/puppet/jvm/puppet_config_spec.rb, spec/puppet-server-lib/puppet/jvm/settings_spec.rb, src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj, src/ruby/puppetserver-lib/puppet/server/master.rb, src/ruby/puppetserver-lib/puppet/server/puppet_config.rb, src/ruby/puppetserver-lib/puppet/server/settings.rb
This implementation of a Puppetserver puppet settings class wraps
the original Puppet::Settings and generates new Puppet::Settings
as necessary per compilation. If, over the course of a compilation,
the settings are modified, there will be a new ThreadLocal settings
object that will be used for the duration of that compilation.
Those modified settings will not persist after the request has
been handled.
=> (SERVER-2726) Implement thread aware Puppetserver settings

acceptance/lib/helper.rb
When first initializing ssl for an agent, there are sporadic issues
with the autosigning; the output in the puppet logs indicate that
the autosigning didn't work, and the cert is still not signed.
This change tries one more time after 3 seconds; hopefully, allowing
for more time will give the server the time it needs to sign the
certificate.
=> (SERVER-2677) Make initial puppet run more resilient to CI Load

spec/puppet-server-lib/puppet/jvm/http_client_spec.rb, src/ruby/puppetserver-lib/puppet/server/http_client.rb
By moving the credential code handling from `post()` to `create_common_request_options()` the HttpClient will handle HTTP basic auth on `get()` as well.
Any code that already uses `HttpClient` (such as Hiera lookup functions) and manually sets Authorization as a workaround, would start to fail. To handle this, the header values are compared and an exception is only raised when the values differ.
=> SERVER-2597: Set HTTP basic auth on GET in HttpClient

acceptance/scripts/generic/testrun.sh
This commit updates our test scripts to use beaker subcomands, so we can
take advantage of some setup that occurs in the beaker helpers when
using `beaker provision`.
=> (RE-13304) Switch to using beaker subcommands

src/clj/puppetlabs/puppetserver/certificate_authority.clj
In Puppet-as-a-Service use cases it is common for individual nodes to be
owned by various different tenant, or customer, teams. None of the
registered ppRegCertExt OIDs we currently provide cleanly allow generic
specification of an owner in this context.
Provide a new OID, pp_owner, which generically fits this use case.
=> (PUP-10364) Add pp_owner ppRegCertExt OID

.github/workflows/docker.yml, docker/Makefile
In our pipelines configuration, we always want to try to make a release build so that we don't have to kick that off manually. But we also only want to build and publish a release build if it doesn't already exists.
This adds some safeguards so we don't try to build the release build yet if it hasn't been published and updated in dujour, and also so that we only build and publish the release build if we haven't already pushed that tag.
Blocked on #2188 
TODO
=> (maint) Only build a release build if it makes sense

Rakefile, acceptance/suites/tests/010-puppetserver-cli/subcommand/gem.rb
This is a workaround to get our pipelines unblocked. Ultimately we would
like to revert this and have the test still pass.
=> (SERVER-2763) Pass no-document flag when installing gems

project.clj
This update fixes a `sprintf` buffer bug.
=> (SERVER-2660) Update jruby to 9.2.11.1

project.clj
This version of clj-parent was published to clojars, while the previous
version was an interal-only release.
=> (maint) Update clj-parent to 1.7.34

project.clj
This update brings in the new jruby-utils version, so this commit also
removes the jruby-utils pin.
=> (SERVER-2660) Update to clj-parent 4.4.1

.github/workflows/docker.yml
Skipped release build without failing the job at https://github.com/puppetlabs/puppetserver/runs/550391873?check_suite_focus=true
=> (maint) Remove default `set -e ` for gh actions shell

src/clj/puppetlabs/puppetserver/certificate_authority.clj, test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj, test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj
This adds a new field to the GET response for the
`certificate_status` endpoint, listing the authorization extensions
present on the cert or CSR being queried. This will be used to help
inform users of potentially risky extensions, so they can make an
informed decision about whether or not to sign a certificate.
=> (SERVER-2718) Return authoriziation extensions with cert status response

resources/ext/build-scripts/mri-gem-list-no-dependencies.txt
This update will display a certificate or CSR's authorization extensions
when they are available from the API (Puppet Server 6.10.0+).
=> (SERVER-2591) Update CA CLI gem to 1.7.0

.travis.yml
We no longer maintain a PE stream that ships FIPS with Java 8 and we
don't believe the multithreaded work should vary based on Java 8 vs 11.
Consequently, we believe we can improve our velocity by removing those
two cells.
=> (maint) Remove unnecessary travis cells

documentation/http_certificate_status.md
Changing `puppet cert' to 'puppetserver ca'. @Magisus Could you please verify this is correct here? Thanks!
=> DOC-3749 Remove mention of puppet cert

documentation/release_notes.markdown
This commit contains a known issue for Puppet Server 6.10.0, as part of an emergency PE release.
=> (DOCS) Release notes for Puppet Server 6.10.0

azure-pipelines.yml, docker/docker-compose.yml, docker/puppetserver-base/docker-entrypoint.d/20-use-templates-initially.sh, docker/spec/puppetserver_spec.rb
- Remove having to add .test to the end of container names in compose
due to DNS resolution bugs in LCOW
- Remove any LCOW file system copy workarounds given WSL2 does
not have these problems
=> (maint) Remove LCOW support / convert to WSL2

acceptance/suites/pre_suite/puppet5_compat/70_install_puppet.rb
We recently removed some of the older versions of the puppet5 stream
from our internal repos, so this commit updates us to the latest of that
stream to test against.
=> (maint) Update Puppet Agent version for 5.x compat job

project.clj, src/clj/puppetlabs/puppetserver/certificate_authority.clj
When writing files always use the atomic-write function from kitchensink which
ensures the file is either fully written or not at all by writing out a temp
file and moving it into place.
=> (SERVER-2565) Write files atomically in CA

project.clj
This update downgrades JRuby to 9.2.8.0 to avoid a potential bug that
causes StackOverflow errors in 9.2.11.1.
=> (SERVER-2793) Update clj-parent to 4.4.4

docker/puppetserver/docker-entrypoint.d/80-ca.sh
- As part of a refactoring made in #2327 / 8c305fe470, in scenarios
where dns_alt_names were not already set in the main section of
puppet.conf, the dns_alt_names value would be set to
,$DNS_ALT_NAMES
when it instead should have been set to
$DNS_ALT_NAMES
- Similarly, when a value was used in a docker-compose file like:
DNS_ALT_NAMES=puppet,${DNS_ALT_NAMES:-}
When the environment variable is not set, the value `puppet,` is
set in the conf file
- These bugs resulted in values like `DNS:, DNS:puppet, DNS:puppet`
being generated via `puppetserver ca setup` which would immediately
crash container startup:
/opt/puppetlabs/puppet/lib/ruby/2.5.0/openssl/x509.rb:20:in `create_ext': subjectAltName = DNS:, DNS:puppet, DNS:puppet: invalid extension string (OpenSSL::X509::ExtensionError)
- This makes …
=> (maint) Fix issue setting container DNS_ALT_NAMES

documentation/puppet-api/v3/compile.markdown, spec/puppet-server-lib/puppet/jvm/ast_compiler_spec.rb, src/clj/puppetlabs/services/jruby/jruby_puppet_schemas.clj, src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj, src/clj/puppetlabs/services/legacy_routes/legacy_routes_service.clj, src/clj/puppetlabs/services/master/master_core.clj, src/clj/puppetlabs/services/master/master_service.clj, src/clj/puppetlabs/services/protocols/jruby_puppet.clj, src/java/com/puppetlabs/puppetserver/JRubyPuppet.java, src/ruby/puppetserver-lib/puppet/server/ast_compiler.rb, src/ruby/puppetserver-lib/puppet/server/master.rb, test/unit/puppetlabs/services/master/master_core_test.clj
Previously when the compile endpoint was asked to compile AST with references to Bolt objects the compile would fail. This commit updates the compiler to accept serialized pcore and to deserialize it for compilation. This adds the requirement of some Bolt library code (and some supporting gems [addressable, public_suffix]) as well as the boltlib module. Part of making the serialized types perform as expected the compiler now creates specialized bolt inventory to back operations on bolt Target options. This work depends on two new additions to the `jruby-puppet` configuration section for pe-puppetserver. The first is appending the path to the bolt library code in the `ruby-load-path` array. The second is a new setting called `boltlib-path` which is an array pointing to the path of any bolt …
=> (PE-28877, PE-28941) Add option to compile-ast endpoint to load bolt types

project.clj
This version rolls JRuby forward again to 9.2.11.1. We are going to
experiment with increasing the JVM stack size to 2MB, which is the
size recommended by JRuby.
=> (SERVER-2793) Update clj-parent to 4.4.5

.gitmodules, spec/puppet-server-lib/puppet/jvm/compiler_spec.rb
We have been rewriting Facter from C++ back into Ruby, so puppetserver
can finally take up a new Facter version for testing and repl workflows.
This commit updates our facter submodule to point at the new version.
=> (SERVER-2727) Use Facter NG as our facter submodule

.gitmodules, spec/puppet-server-lib/puppet/jvm/compiler_spec.rb
Reverts puppetlabs/puppetserver#2283
Puppet is going to pin back to Facter < 4 for the time being, while they sort out some spec failures. This means that we won't be able to install the Facter 4 gem when running our specs, so this need to be reverted for the time being. We will continue to use Facter 2 until Puppet's issues are resolved and they unpin.
=> Revert "(SERVER-2727) Use Facter NG as our facter submodule"

project.clj
This commit bumps clj-parent to 4.5.0, which includes bumps to jetty and
trapperkeeper-metrics in preparation for the LTS.
=> (SERVER-2799) Bump clj-parent to 4.5.0

project.clj
This version deprecates the v1 version of the metrics endpoint.
=> (TK-486) Update clj-parent to 1.7.35

.gitmodules, spec/puppet-server-lib/puppet/jvm/compiler_spec.rb
This reverts the previous revert now that puppet is fixed, and updates the Facter 4 submodule to latest.
=> (SERVER-2727) Use Facter 4

project.clj
This commit bumps clj-parent to 4.5.1, which includes i18n 0.9.0.
=> (maint) Bump clj-parent to 4.5.1

project.clj
This commit bumps i18n to 0.9.0, to match the version specified in clj-parent.
According to a comment in the pe-puppetdb-extensions repo (which I've copied
here), we need to specify this separately and it must match the version in
clj-parent.
=> (maint) Bump i18n to 0.9.0

src/ruby/puppetserver-lib/puppet/server/puppet_config.rb
The underlying method here had a parameter added so our check was too
specific. Update it so it's slightly better and we aren't accidentally
pushing settings globally all the time.
=> (maint) Update parameter check in settings

project.clj
This commit adds a flag to not use invoke-dynamic for yields in JRuby,
since that mode may be causing StackOverflows.
=> (SERVER-2793) Update clj-parent to 4.5.2

documentation/config_file_webserver.markdown
Based on the following customer ticket: https://tickets.puppetlabs.com/browse/DOCUMENT-1114.
I wasn't sure whether the equals sign in `access-log-config = /etc/puppetlabs/puppetserver/request-logging.xml` should also be replaced with a colon?
=> (Docs) Incorrect webserver.conf client-auth example

documentation/config_file_puppetserver.markdown
This commit removes a warning against using the `max-queued-requests`
setting with a node population that includes significant numbers of
agents running a version older than 5.3.1. The fixes for SERVER-2405,
and SERVER-2696 shipped in Puppet Server 5.3.11 and 6.9.0 make this
warning obsolete as Puppet Server now checks the agent version headers
and skips enforcement of the limit if the agent is too old or the
header is missing.
=> (maint) Remove max-queued-requests warning note

project.clj
This commit updates clj-parent to 1.7.36, which updates postgresql to address a
security issue in pgjdbc driver. This issue does not affect puppetserver, but
updating for consistency with puppetdb.
=> (maint) Bump to clj-parent 1.7.36

resources/ext/build-scripts/mri-gem-list-no-dependencies.txt
This version updates the Facter version requirement to allow Facter 4.
=> (maint) Update CA CLI gem to 1.8.0

project.clj
This commit updates clj-parent to 4.5.4, which updates trapperkeeper-metrics to
1.3.1. This includes support for trapperkeeper-authorization.
=> (TK-489) Bump to clj-parent 4.5.4

documentation/install_from_packages.markdown
Do not merge yet (first iteration of changes).
I've made a few updates to start addressing the following feedback:
- The instructions jump around a lot - linking elsewhere on the same page - it really just needs a good prereq section
- The doc links to Enabling package repositories - that page should just list the available packages for each OS and the correct `wget` instead of making the user search for them (a nice touch would be adding the command for each OS to view their current OS build)
- There is an `apt-get` command, so perhaps the issue is that the commands are not clearly separated by platform. Separating the docs in this way would make them more user-friendly, especially for newer users who may not already be familiar with the command-line.
If anyone has other thoughts on how …
=> (Docs) Reorganise server installing instructions

src/clj/puppetlabs/services/ca/certificate_authority_core.clj, src/clj/puppetlabs/services/ca/certificate_authority_service.clj, test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj
This commit fixes a misplaced parenthesis that made it impossible to
delete CSRs via the API. It also cleans up some erroneous whitespace.
=> (SERVER-2795) Fix CSR deletion and cleanup whitespace

src/clj/puppetlabs/services/ca/certificate_authority_core.clj, test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj
This is a cherry-pick from master, see https://github.com/puppetlabs/puppetserver/pull/2372.
I skipped the whitespace commit because there were too many conflicts.
=> (SERVER-2795) Fix CSR DELETE API

ezbake/config/conf.d/auth.conf, src/clj/puppetlabs/puppetserver/certificate_authority.clj, src/clj/puppetlabs/services/ca/certificate_authority_core.clj, test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
This commit adds a `puppet-ca/v1/ca-expirations` endpoint that returns the expiration date of each CA cert and CRL in their respective bundles, keyed by common name. For the certs, this is the "not-after" date, while for CRLs it is the "next-update" date.
Interested in feedback on the format of the response and the name of the endpoint, as well as the usual things.
=> (SERVER-2551) Make CA cert and CRL expirations available via API

documentation/_puppetserver_nav.html
Here's a first swing at revising the sidebar nav for Puppet Server. We think it's less confusing if Puppet Server goes back to having its own sidebar, where the context is more clearly "you are in the Puppet Server docs now!"
I moved some things, removed others, and added others. There are some questions on DOC-4463, and a few revision notes for context. I'll ping you there as well.
=> REVIEW: DOC-4463 sidebar nav revision

Rakefile, ext/build_defaults.yaml, project.clj
This PR updates:
* `build_defaults.yaml` to point to the right build and nightly repos
* Rakefile to ensure that the puppet and puppet-agent versions point to the right branches
* project version to 7.0.0
=> (SERVER-2848) Branch twiddling

src/clj/puppetlabs/puppetserver/certificate_authority.clj, src/clj/puppetlabs/services/ca/certificate_authority_core.clj, test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj
This commit updates the `certificate_statuses` API endpoint to accept query
params for filtering by a given 'state'. For example, this can be used to
identify all agents with unsigned (i.e. requested) certs.
=> (SERVER-2233) Add query params for filtering certificate statuses

acceptance/suites/puppet5_tests/puppet5_version_test.rb
The Puppet 5 compat test was asserting that the version installed on the
master be 6, but it should be 7.
=> (SERVER-2848) Update major version in compat test

Rakefile
Previously, the puppet-agent branch for Platform 7 was called "next",
but it was recently renamed to "main". This commit updates our tracking
branch to point to `main`.
=> (maint) Update puppet-agent branch to `main`

.gitmodules
Previously, the Facter 4 code lived in the facter-ng repo. Now that it
has moved to the main facter repo, this commit updates our submodule pin
to point there, to the 4.x branch.
=> (maint) Update facter submodule to point at facter#4.x

documentation/config_file_auth.markdown
This commit adds a note to the docs that OID short names cannot be used
in auth.conf extension-based rules when the CA is disabled.
=> (SERVER-1689) Document short name auth.conf caveat

.gitmodules
`net/http` uses `openssl` which is not FIPS compliant on jRuby. We can use the same mechanism that is used for missing gems to detect this case and log an error message, but continue to provide the facts we can resolve.
=> (FACT-2742) Exclude net/https when running on jruby FIPS

acceptance/lib/helper.rb
When puppet is trying to manage the puppetserver service and starts
it, the shell command seemed to return very early, 1.37 seconds for
redhat 8 as opposed to ~18 for other platforms.. Beaker does a
check to http://localhost:8140 after the command, but it is only
ostensibly successful; this change extends the timeout to 20 seconds
to see if this allows the pre-suite step to complete successfully.
If this is successful, we should probably look into why redhat 8 is
completing the service start command so quickly.
=> (SERVER-2677) Extend sleep for unsigned certs

src/clj/puppetlabs/services/master/master_core.clj, src/ruby/puppetserver-lib/puppet/server/ast_compiler.rb
This commit updates the compile_ast endpoint to support loading plan variables from an ordered list. Deserialization requires ordered hashes. Hash order is lost when moving from ruby -> clojure -> json so the ordered data is preserved in a list and then an ordered hash is created.
=> (PE-29443) Preserve hash order for plan variables

resources/ext/ezbake.conf
This commit updates the packaging requirement for what puppet-agent
version must be installed alongside the server to 6.16.0, which is the
vesrion that shipped with the last PE LTS release. Notably, this version
contains all the necessary changes for multithreaded support, which
should allow us to remove some speical-casing eventually.
=> (maint) Update required agent version to 6.16.0

acceptance/suites/tests/authorization/default_rules.rb, ezbake/config/conf.d/auth.conf
The `/puppet/v3/status` endpoint and associated indirection were
recently removed. This commit removes the associated tk-auth rule and
test for the endpoint.
=> (PUP-10386) Remove tk-auth rule for puppet status endpoint

documentation/http_api_index.markdown, test/integration/puppetlabs/general_puppet/general_puppet_int_test.clj
Remove test and docs for the `environment` REST API. The `environments` API is
unchanged.
=> (maint) Prepare for catalog environment REST API removal

acceptance/suites/tests/authorization/fixtures/extensions_test_auth.conf, acceptance/suites/tests/certificate_authority/fixtures/auth.conf, dev-resources/puppetlabs/puppetserver/auth_conf_test/auth.conf, src/clj/puppetlabs/services/master/master_core.clj, test/unit/puppetlabs/services/master/master_core_test.clj
I missed removing the `/puppet/v3/environment` route in https://github.com/puppetlabs/puppetserver/pull/2411. While I was there, I updated `/puppet/v3/status` and removed it from some test fixtures.
=> (maint) Remove environment and status leftovers

acceptance/suites/tests/authorization/default_rules.rb
This commit removes the teardown step to set `use-legacy-auth-conf` back to
true. We no longer use the legacy auth, but this setting was bleeding into other
tests. This caused test failures because legacy auth doesn't have a way to
restrict access based on cert extensions.
=> (maint) Don't set `use-legacy-auth-conf` to true

test/integration/puppetlabs/services/jruby/request_handler_test.clj
Puppet recently removed support for using md5 hashes with
file-bucket. This updates our tests accordingly.
=> (maint) Fix tests to avoid disallowed md5 hash

Rakefile
This commit adds a new rake task that can be used to update the Facter
submodule commit based on the last passing version published by the
puppet-agent Jenkins pipeline.
It introduces a new variable to track which branch to pull the Facter
SHA from, because while the 6.x agent is still using Facter 3, in our
submodule we use Facter 4, because we need it to be a Ruby lib rather
than C++.
This also renames some tasks to be more descriptive of the new state, so
any automation around these tasks will need to be updated accordingly.
=> (SERVER-2809) Add rake task for updating facter submodule

src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj
The upgrade to Rubygems 3 broken some of JRuby's globbing code. They
fixed the issue around `uri:classloader`, but not issues with the
`classpath` protocol, which we were using to load our Ruby code inside
puppetserver. However, it appears we can switch to using
`uri:classloader` instead, so this PR changes our loadpath addition to
use that protocol. This means that globbing against our loadpath (e.g.
when installing gem documentation) now works.
=> (SERVER-2763) Use `uri:classloader` to avoid globbing issue

acceptance/lib/puppetserver/acceptance/compat_utils.rb, acceptance/suites/compat_tests/020_backwards_compat/binary_file_test.rb, acceptance/suites/compat_tests/020_backwards_compat/source_file_test.rb
Puppet default digest algorithm was changed to sha256
https://github.com/puppetlabs/puppet/pull/8315
This commit updates the compatibilty test to
specify the checksum explicitly as `sha256`
=> (maint) Update puppet 5 compatibilty tests

src/clj/puppetlabs/services/master/master_service.clj, test/integration/puppetlabs/services/legacy_routes/legacy_routes_test.clj, test/integration/puppetlabs/services/master/master_service_test.clj
This commit adds `/status/v1/simple/server` endpoint
similar to `/status/v1/simple/master`
It also updates the `/status/v1/services` endpoint
with a new field `server` containing the same
information as `master`.
LE: this might do more than i thought.
=> (PUP-10673) add simple server endpoint

src/clj/puppetlabs/puppetserver/certificate_authority.clj
Previously, when a cert was revoked the certname was not logged. This
caused problems keeping track of what certnames were revoked. Prior to
the bulk API existing, customers had been largely able to review
revocation activity based on puppetserver-access.log. This new logging
effectively restores prior log functionality.
=> (PE-30068) Log certnames that are revoked

src/ruby/puppetserver-lib/puppet/server/config.rb, src/ruby/puppetserver-lib/puppet/server/http_response.rb
We want to defer to Puppet's shim implementation for the HTTP client
class registered with the HTTP pool. This shim will adapt calls made to
the old-style HTTP client API to the new form, which will then get
passed to our client impl, which is registered as
`Puppet.runtime[:http]`.
=> (maint) Stop registering server HttpClient class

src/ruby/puppetserver-lib/puppet/server/puppet_config.rb
This commit switches the default facter terminus from yaml to json,
which has more robust parsing support and better number handling.
=> (PUP-10656) Use json fact terminus by default

spec/puppet-server-lib/puppet/jvm/http_client_spec.rb, src/ruby/puppetserver-lib/puppet/server/http_client.rb
In order to be consistent with Puppet's API, we need the errors raised
by our HTTP client implementation to match what Puppet raises.
=> (maint) Inherit from Puppet's HTTP error class for HTTPClientError

resources/ext/build-scripts/mri-gem-list-no-dependencies.txt
This commit bumps the puppetserver-ca gem to 2.0.0, which includes the new
cadir location.
=> (SERVER-2895) Bump puppetserver-ca to 2.0.0

src/clj/puppetlabs/puppetserver/certificate_authority.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
Previously, was curious about why we never used the cadir setting before. I haven't found anything conclusive but I'm thinking that it was just expedient the last time it came up and prior to that we only cared about what was actually set since each setting we get that is nested inside the cadir is also independently configurable...
------------------
With Puppet 7 we want to move the cadir outside of the ssldir however we
want to symlink back to the old cadir to ease the transition. This
provide existing documentation and code to largely just work for new
users, preventing them from being able to accidentally delete their
cadir.
This commit looks at the last portion of the cadir to determine if it is
the the new default or something else while also allowing us to
substitute out the …
=> (SERVER-2760) Symlink new to old cadir on bootstrap

ext/travisci/test.sh
We recently had several issues with running Puppet Server's specs
locally all relating to keeping cached data around longer than
necessary.
This adds that information to our travis script, ensuring the builds in
travis and locally work similarly.
=> (maint) Update travis script to remove caches

project.clj
This commit updates our JRuby 9k version to 9.1.17.0, which contains a
fix for a memory leak in FilenoUtil.
=> (SERVER-2925) Update JRuby 9k to 9.1.17.0

project.clj
This picks up an updated release of jruby-deps that correctly makes its
project.clj available top-level, to enable ezbake's dependency
resolution for additional uberjars.
=> (SERVER-2925) Use correct build of JRuby 9.1.17.0

spec/puppet-server-lib/puppet/jvm/ast_compiler_spec.rb, src/clj/puppetlabs/services/master/master_core.clj, src/ruby/puppetserver-lib/puppet/server/ast_compiler.rb
Target vars do not need to maintain hash order. This commit updates the compile_ast endpoint to remove the complexity in keeping target vars ordered.
=> (PE-30410) Do not preserve hash order for target vars

resources/ext/build-scripts/mri-gem-list-no-dependencies.txt
This commit bumps puppetserver-ca to 1.9.1, which includes support for the
`server` section of `puppet.conf` and ensures that the symlink we create when
migrating the CA dir has the same ownership as the actual CA dir.
=> (SERVER-2917) Bump puppetserver-ca gem to 1.9.1

documentation/config_file_auth.markdown
This fixes some broken links in older versions of the docs that
deal with Puppet 3 agent compatibility. In some cases this means
linking to the docs archive for docs that no longer exist in their
original form on the website.
=> (Docs) Fix broken links to Puppet 3 and 4

.github/workflows/docker.yml
I think the differences in the workflow between 6.x (the default branch)
and main (the branch we build from) was the source of the issues.
I was able to confirm on my fork that this change allowed builds to happen on push to main.
=> (CPR-768) Update github workflow to build on pushes to 'main' branch

acceptance/suites/tests/code_commands/code_scripts.rb
Newer versions of r10k pull new versions of CRI which does not work on
the older versions of Ruby that we still must support in Server 5.x.
-----
Validated this works locally on 5.x:
```
Test Suite: tests @ 2021-01-12 16:12:42 -0800                                                           
- Host Configuration Summary -                                                                          
- Test Case Summary for suite 'tests' -                                                         
Total Suite Time: 910.51 seconds                                                                       
Average Test Time: 60.70 seconds                                                                        
Attempted: 15 …
```
=> (maint) Pin r10k to latest 2.x

acceptance/suites/tests/code_commands/code_scripts.rb
We want to pin r10k to a version that still supports Ruby < 2.5 on the
5.x branch, but allow 6.x to float. This reverts the pin to r10k in our
acceptance tests for Puppetserver 6+.
=> (maint) Unpin r10k

resources/ext/build-scripts/jruby-gem-list.txt, test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj
- Includes feature from 1.2.7 to load environment variables into lists
like:
FOO.1
FOO.2
See https://github.com/puppetlabs/ruby-hocon/pull/117
=> (maint) Bump jruby hocon to 1.3.1

dev-resources/puppetlabs/services/legacy_routes/legacy_routes_test/confdir/puppet.conf, dev-resources/puppetlabs/services/master/master_service_test/confdir/puppet.conf, src/ruby/puppetserver-lib/puppet/server/puppet_config.rb
This commit updates the settings section we load from `master` to
`server` to avoid deprecation warnings. Puppet will make sure both
sections are always loaded, but specifying `server` instead of `master`
avoids the warning.
=> (maint) Switch to using `server` instead of `master` puppet.conf section

dev-resources/puppetlabs/services/legacy_routes/legacy_routes_test/codedir/environments/production/modules/foo/manifests/bar.pp, dev-resources/puppetlabs/services/legacy_routes/legacy_routes_test/codedir/environments/production/modules/foo/manifests/baz.pp, dev-resources/puppetlabs/services/legacy_routes/legacy_routes_test/codedir/environments/production/modules/foo/manifests/init.pp, dev-resources/puppetlabs/services/legacy_routes/legacy_routes_test/codedir/environments/production/modules/foo/manifests/params.pp, dev-resources/puppetlabs/services/legacy_routes/legacy_routes_test/confdir/puppet.conf, dev-resources/puppetlabs/services/legacy_routes/legacy_routes_test/enc.sh, dev-resources/puppetlabs/services/legacy_routes/legacy_routes_test/puppet.conf
We deleted the tests that use these a while back as part of removing the
feature for Platform 7.
=> (maint) Remove leftover test fixtures for legacy routes test

src/ruby/puppetserver-lib/puppet/server/master.rb
Puppet returns binary data for some endpoints as a string encoded with
Ruby's ASCII-8BIT encoding. This encoding is unique to ruby and is
essentially meant to be treated as raw bytes. As of version 1.6.0,
ring-servlet attempts to encode the response body when it's a string
using the charset in the header, falling back to UTF-8. When we
encounter this encoding now we will convert it to a java byte array and
ring won't attempt to encode it.
=> (SERVER-2948) Treat ASCII-8BIT body as bytes

project.clj
One of the libraries we use in testing, cemerick/url, is unmaintained
and archived. It has not been updated to pull in a non-vulnerable
version of protobuf, so this commit overrides that dependency to pull in
the fixed version.
Ultimately we should probably try to stop using cemerick/url. When that
happens, we can remove this pin as well.
=> (PE-30976) Pin protobuf test dep to 3.4.0

project.clj
This update contains a new GPG key.
=> (maint) Update ezbake to 2.2.2

src/clj/puppetlabs/puppetserver/certificate_authority.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
Previously, the error messages issued when auth extensions or SANs were
disallowed referenced the `puppetserver.conf` file. But these settings
live in the `ca.conf` file in both PE and FOSS now. This commit updates
the messages to refer to that file instead.
=> (SERVER-2321) Refer to ca.conf in allow-* CA error messages

src/clj/puppetlabs/services/config/puppet_server_config_core.clj, test/unit/puppetlabs/services/config/puppet_server_config_core_test.clj
This commit changes the default CRL path supplied to Jetty from the CA's
to the local server's copy. This latter path, in the ssldir rather than
the CA, is present even if the CA service is disabled, because the
puppet agent will write the CRL it fetches to that location, while the
CA's copy is not always available.
This mirrors what we configure in PE, and makes setting up compilers in
FOSS easier.
=> (SERVER-2558) Use puppet's copy of CRL as jetty CRL

src/clj/puppetlabs/services/master/master_core.clj, src/ruby/puppetserver-lib/puppet/server/compiler.rb, test/unit/puppetlabs/services/master/master_core_test.clj
Previously, the v4 catalong endpoint had these issues with environment
handling:
1. Would not use the environment in the body of the request for code_id
generation.
2. Did not validate environment names.
The issue was needed for feature parity with Puppet while the
first issue caused spurious warnings to be issued.
=> (SERVER-2965) Better environment handling for v4 catalogs

acceptance/suites/pre_suite/foss/85_configure_sut.rb
Beaker has had a built-in option to configure `/etc/hosts` to redirect
update.puppetlabs.com to localhost for a long time, and it is enabled by
default. This commit removes our duplication of this configuration.
=> (SERVER-1061) Remove pre-suite step to redirect dujour ping

src/ruby/puppetserver-lib/puppet/server/auth_config.rb, src/ruby/puppetserver-lib/puppet/server/master.rb, src/ruby/puppetserver-lib/puppet/server/puppet_config.rb
This work was to update Puppet Server to ensure all the modern
non-harmful terminology APIs were being used. However, some terminology
in Puppet around routing was missed in the 7.0 release. This changes as
much terminology as possible while commenting as to why the rest hasn't
changed.
=> (SERVER-2870) Update Puppet APIs that use master

dev/puppetserver.conf, ext/thread_test/puppetserver.conf, resources/ext/config/conf.d/puppetserver.conf, src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj, src/clj/puppetlabs/services/jruby/jruby_puppet_schemas.clj, test/integration/puppetlabs/puppetserver/bootstrap_int_test.clj, test/integration/puppetlabs/puppetserver/bootstrap_testutils.clj, test/integration/puppetlabs/puppetserver/testutils.clj, test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj, test/integration/puppetlabs/services/jruby/class_info_test.clj, test/integration/puppetlabs/services/jruby/jruby_puppet_pool_int_test.clj, test/integration/puppetlabs/services/jruby/module_info_test.clj, test/integration/puppetlabs/services/jruby/request_handler_test.clj, test/integration/puppetlabs/services/jruby/tasks_test.clj, test/integration/puppetlabs/services/master/master_service_test.clj, test/unit/puppetlabs/services/ca/certificate_authority_disabled_test.clj, test/unit/puppetlabs/services/config/puppet_server_config_core_test.clj, test/unit/puppetlabs/services/config/puppet_server_config_service_test.clj, test/unit/puppetlabs/services/jruby/jruby_puppet_core_test.clj, test/unit/puppetlabs/services/jruby/jruby_puppet_testutils.clj
This creates new server-* variants of the existing master-* config
names (master-conf-dir, master-code-dir, etc). When resolving values
we will prefer the new setting, the old setting, then the default.
This updates the default config files shipped with Puppet Server to use
the new setting names. It also updates the variable names containing the
default values in code. This updates the tests to use the new names,
changes the name of the variables that hold their test values, and in
select cases changes the names of the test directories from `master` to
`server` (only for the autogenerated test directiories, not the
fixtures).
=> (SERVER-2867) Make server-* configs preferred to master-* variants

src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj, test/unit/puppetlabs/services/jruby/jruby_puppet_core_test.clj
When we moved to prefering server-* config variants we did not set
master-* variants if the server-* variants were set first. This will
cause a regression in those who programmatically use our config.
This should only cause issues for those who load puppetserver as a
library, which may only be pe-puppetserver-extensions.
This patch resolves server-* variants as usual and then sets the
master-* variants to the equivalent server-* values.
=> (maint) Make server-* configs available at master-*

project.clj
We pulled in this dependency when we though we were going to use
multijson/jrjackson for JSON parsing. When that wound up not being
feasible, we gave up on that effort, but left this dependency in. This
commit removes it.
=> (SERVER-2941) Remove unused jackson-afterburner dep

ext/thread_test/environments/funky/manifests/init.pp, ext/thread_test/environments/funky/modules/threader/lib/puppet/functions/threader/color.rb, ext/thread_test/environments/funky/modules/threader/lib/puppet/functions/threader/futurist.rb, ext/thread_test/environments/production/manifests/init.pp, ext/thread_test/environments/production/modules/threader/lib/puppet/functions/threader/color.rb, ext/thread_test/environments/production/modules/threader/lib/puppet/functions/threader/futurist.rb, ext/thread_test/environments/production/modules/threader/lib/puppet/functions/threader/other_func.rb, ext/thread_test/parallel_test.rb
This commit puts the original thread test script into a `parallel_test`
script, and creates a new test script that just makes a single catalog
request. The former is good for testing races, while the latter is
better for inspecting an individual compile.
It also updates the fixtures to no longer use the `future_features`
setting, which has been removed.
=> (maint) Add single catalog compile script

resources/ext/build-scripts/mri-gem-list-no-dependencies.txt
This update ensures that ca-client certs will also be signed with the CN
as a SAN.
=> (maint) Update CA CLI gem to 1.9.3

resources/ext/build-scripts/mri-gem-list-no-dependencies.txt
This update ensures that ca-client certs will also be signed with the CN
as a SAN.
=> (maint) Update CA CLI gem to 2.0.2

.github/workflows/docker.yml, .travis.yml, docker/Makefile, docker/puppetserver/Dockerfile, docker/puppetserver/docker-entrypoint.sh
- Bump docker-compose to 1.28.6 (necessary for moving away from deprecated -no-ansi flag)
- Pull hadolint from gchr.io to avoid rate-limiting on Docker Hub
- Set +x on entrypoints at build time to be a better non-root citizen in k8s (more non-root work required on this container)
- Add note about why the entrypoint should always use `/bin/bash` and not `/bin/sh`
- Prune containers on the builder to prevent disk related build /publish failures
=> (maint) Docker consistency updates

.travis.yml
Turns out it's much better to keep buildkit enabled if possible rather than trying to disable as is done in #2514. Hopefully a simple upgrade is the better solution.
- This repo requires Docker buildkit to build containers in CI, which
enables skipping optional stages in multi-stage builds (which skips
building packages when not creating edge containers). Standard
`docker build` does not support this, nor does it handle setting ARG
valeus across stages as this Dockerfile needs.
- Travis has been failing frequently with an error like:
failed to solve with frontend dockerfile.v0: failed to build LLB:
failed commit on ref "layer-sha256:XXX":
unexpected commit size 0, expected 162: failed precondition
This appears to be related to the version of Docker / Buildkit in
use in Travis as this …
=> (maint) Upgrade TravisCI docker version

docker/Makefile, docker/puppetserver/Dockerfile, docker/puppetserver/docker-entrypoint.d/90-log-config.sh, docker/puppetserver/healthcheck.sh
- With cert preloading added to test suites, there is a server.crt
present alongside puppet.pem. This entrypoint script errors and
prevents the container from starting and the healthcheck fails
because of the existence of server.crt, so update the filter to be
more sensible
This fix is not visible to this test suite as this suite will
always generate certificates - but it will be visible elsewhere in
suites like puppetdb, pupperware, etc
- Log the certname as well
- Allow `DOCKER_BUILDKIT` to be overridden (even though we need buildkit)
- Refactors container healthcheck to be similar to PE variant
- curl --no-progress-meter cleans up livenessprobe logs
- Readiness probes in Kubernetes that use exec ignore timeout and
require the command itself to enforce a timeout. Use `curl --max-time` …
=> (maint) Filter scanned certs in container startup

resources/ext/build-scripts/mri-gem-list-no-dependencies.txt
This commit bumps the puppetserver-ca gem to 1.9.4, which includes appropriate
settings detection for migrated CA directories.
=> (SERVER-2993) Bump puppetserver-ca to 1.9.4

resources/ext/build-scripts/mri-gem-list-no-dependencies.txt
This update contains some harmful terminology removals.
=> (SERVER-2932) Update CA CLI gem to 1.9.5

resources/ext/build-scripts/mri-gem-list-no-dependencies.txt
This update contains removal of harmful terminology.
=> (SERVER-2932) Update CA CLI gem to 2.1.0

test/integration/puppetlabs/puppetserver/auth_conf_test.clj, test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj, test/integration/puppetlabs/services/legacy_routes/legacy_routes_test.clj
As of version 4.5.8 of the apache httpclient, URLs with a double slash
in them are processed differently. Our tests were accidentally adding an
extra slash between the server and the URL path, which ran afoul of
this. This commit updates some callers of the test helper to stop adding
an additional slash.
=> (SERVER-3014) Stop putting double slashes in test urls

src/clj/puppetlabs/services/master/master_core.clj, test/integration/puppetlabs/services/master/environment_classes_int_test.clj
Prior to this patch, if a request to the environment_classes endpoint contained
an If-None-Match header with an etag in it, but the cache had been evicted we
would compute the class info. If that class info's checksum matched the given etag
we would return a 304 but not cache the checksum. Because the cache was not
updated, subsequent requests that included an etag would still trigger class info
computation.
With this patch we will now cache the computed etag, allowing subsequent
requests that include the correct If-None-Match header to skip class info
computation.
=> (SERVER-3015) Cache etag if cache was previously evicted

src/clj/puppetlabs/puppetserver/certificate_authority.clj, src/clj/puppetlabs/services/ca/certificate_authority_core.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj, test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj
This commit ensures that the new PUT endpoint for the
`certificate_revocation_list` API also updates the infra CRL.
=> (SERVER-2550) Update infra CRL via API

project.clj
java.version on some platforms differs from what Puppetserver's project file tries to parse.
java.specification.version is however guaranteed to match the expected format.
On Debian openjdk-17-jre-headless's "java -XshowSettings:properties -version" is:
```
file.encoding = UTF-8
file.separator = /
java.class.path =
java.class.version = 61.0
java.home = /usr/lib/jvm/java-17-openjdk-amd64
java.io.tmpdir = /tmp
java.library.path = /usr/java/packages/lib
/usr/lib/x86_64-linux-gnu/jni
/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu
/usr/lib/jni
/lib
/usr/lib
java.runtime.name = OpenJDK Runtime Environment
java.runtime.version = 17-ea+24-Debian-1
java.specification.name = Java Platform API Specification
java.specification.vendor = Oracle Corporation
java.specification.version = 17
java.vendor = …
```
=> Use java.specification.version for version check

project.clj, test/integration/puppetlabs/services/jruby/jruby_metrics_service_test.clj
This commit replaces the `com.cemerick/url` dependency with `lambdaisland/uri`.
The former is unmaintained and has been archived upstream, so it no longer
receives security updates. Even though this dependency was only used for testing
purposes, our security scanner would still flag vulnerable transitive
dependencies that were included in the unmaintained `url` lib. This moves us to
a maintained lib, which should allow us to get clean security scans.
=> (SERVER-2841) Replace cemerick.url with lambdaisland.uri

ezbake/config/conf.d/auth.conf
Prior to this change, all PUT requests to the `certificate_revocation_list`
endpoint would get denied, since the request path wouldn't exactly match the
string in the auth rule. Using type `regex` ensures that we can access this
endpoint appropriately.
=> (SERVER-3033) Fix auth rule for CRL update endpoint

dev-resources/java.security.jdk11-fips, dev-resources/java.security.jdk8-fips
There is an issue with the latest bc-fips version involving circular
provider loading, that can be fixed by using the full class name for the
BCJSSE FIPS provider, rather than relying on an alias. This commit
updates our java-security file for Java 11 to use the full name.
It also updates the key manager factory algorithm following a
recommendation from the BC maintainers.
=> (PE-32070) Update Java 11 security file for new BCFIPS

dev-resources/java.security.jdk11-fips, dev-resources/java.security.jdk8-fips
The PKIX factory is correct for non-FIPS BC, but in FIPS mode we want to
use BCFKS.
=> (PE-32070) Use BCFKS key factory in FIPS mode

docker/puppetserver/Dockerfile, docker/ruby-docker-copy-patch.rb
There's a particularly gnarly bug in Linux kernels 5.6 to 5.10 that
can result in 0 byte files being written when copying files inside
containers in a specific workflow as described in:
docker/for-linux#1015
This impacts the packaging gem used by ezbake when it renders ERB
templates, resulting in 0 byte files critical to the execution of
the build process.
Using a different filesystem (like tmpfs) for /tmp as a workaround
didn't seem to work.
Since there is no way to explicitly control the kernel version in
environments like Travis, the best approach is to monkey-patch the
_Entry class in Ruby that supports FileUtils.cp, such that a no-op
mode change is performed on the source and destination files before
and after being written to prevent the 0 byte files from being
written. In local OSX …
=> (RE-14082) Monkey-patch docker ezbake build Ruby

src/clj/puppetlabs/puppetserver/certificate_authority.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
Previously, when `allow-subject-alt-names` was set to false, we rejected
any and all SANs on CSRs. However, now that we are adding the CSR's
subject as an alt name when generating CSRs, per RFC 2818, we need to
make an exception, so as to not block all internally generated CSRs.
This affects, for example, the `puppetserver ca generate` command. This
commit updates the validation function to allow a single alt name
matching the CSR's subject, even when `allow-subject-alt-names` is
false.
=> (SERVER-3032) Always allow SAN that matches CSR subject

resources/ext/build-scripts/mri-gem-list-no-dependencies.txt
This Gem bump contains added feature and improvement made to the puppetserver-ca CLI.  The CLI tool can now provide the user the option to choose the format of the output when executing the command 'list' to be either in text or JSON.  Furthermore, the user can execute commands in verbose mode by adding the '--verbose' flag to the existing command.
=> (SERVER-3038) Update Gem version

resources/ext/build-scripts/mri-gem-list-no-dependencies.txt
This GEM bump contains the bug fixes and changes made to Puppetserver's CA CLI prune action.
Bug fixes:
- Correctly update the CRL number instead of updating the CRL protocol number.
Changes:
- Make sure that the CRL does not get update if there was no duplicated cert to prune.
- Output to the user the amount of duplicated certs pruned once the action is complete.
=> (SERVER-2740) Update GEM version to 1.11.1

project.clj, resources/ext/build-scripts/mri-gem-list-no-dependencies.txt
This GEM bump contains the bug fixes and changes made to Puppetserver's CA CLI prune action.
Bug fixes:
- Correctly update the CRL number instead of updating the CRL protocol number.
Changes:
- Make sure that the CRL does not get update if there was no duplicated cert to prune.
- Output to the user the amount of duplicated certs pruned once the action is complete.
=> (SERVER-2740) Update GEM version to 2.3.1

src/clj/puppetlabs/puppetserver/certificate_authority.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
This commit include changes made to the function 'revoke-existing-certs' that will now check the list of serials to be added to the revoked lists for possible duplicate entries.
=> (SERVER-2509) Prevent duplicate entries in Puppet's CA CRL

spec/puppet-server-lib/puppet/jvm/ast_compiler_spec.rb, src/clj/puppetlabs/services/master/master_core.clj, src/ruby/puppetserver-lib/puppet/server/ast_compiler.rb, test/unit/puppetlabs/services/master/master_core_test.clj
This commit adds logic to the compile endpoint to support compiling AST for a
bolt project rather than an environment. Mostly project compiles are the same
as environment compiles (after all, we are still just compiling puppet code)
with a few important differences:
* We pass some additional data about the project to the compile operation
(this is mostly data about the project name and where it's located on disk)
* The context of project compiles requires us to use `in_tmp_environment`
instead of `in_environment` so that we can 1. ensure that we are not loading
things from environment.conf and 2. that we can control the entirety of the
modulepath for the compile (projects do not make use of
basemodulepath/vendormodulepath and we need to ensure we have only exactly
the modulepath passed in …
=> (PE-32484) Update ast_compiler to work for projects

project.clj
This commit bumps the version of ezbake to include updated jenkins urls.
=> (maint) Bump to ezbake 2.2.4

docker/puppetserver/puppetserver.conf
For some testing it is desireable for puppetserver to serve some project content from some pre-defined project content. By setting a bolt-projects dir we can enable puppetserver to serve project content assuming it is in a proper structure even if it is not actually managed with code manager/file sync.
=> (maint) Provide a reasonable default for bolt-projects dir

dev-resources/puppetlabs/services/master/master_core_test/bolt_projects/local_23/modules/helpers/scripts/yogurt.sh, src/clj/puppetlabs/services/master/file_serving.clj, src/clj/puppetlabs/services/master/master_core.clj, test/integration/puppetlabs/general_puppet/general_puppet_int_test.clj, test/unit/puppetlabs/services/master/file_serving_test.clj, test/unit/puppetlabs/services/master/master_core_test.clj
This adds a new default mount "scripts" which loads files from the
scripts directory of the specified module. The mount can be used by the
file_content and file_metadata APIs (or any other API that specifies a
mount) to load file metadata and content for scripts from modules.
Requires puppetlabs/puppet#8711
=> (SERVER-3058) Add "scripts" mount as a default mount

ext/travisci/suppression.xml, resources/ext/build-scripts/mri-gem-list-no-dependencies.txt
This GEM bump contains:
- Update to the output message for `puppetserver-ca revoke` to be more reassuring to users
- Update `puppetserver-ca list` to use the new certificate_status endpoint for better performance
when querying for CSRs only.
=> (maint) Update pupppetserver-ca GEM version to 1.11.2

ext/travisci/suppression.xml
This commit includes the suppression message for the false positive detected with core.cache-0.7.1.jar since the previous commit that was merged did not include a clear note.
=> (SERVER-3063) Update supression notes for scan failure

ext/travisci/suppression.xml, resources/ext/build-scripts/mri-gem-list-no-dependencies.txt
This GEM bump contains:
- Update to the output message for `puppetserver-ca revoke` to be more reassuring to users
- Update `puppetserver-ca list` to use the new certificate_status endpoint for better performance
when querying for CSRs only.
=> (maint) Update puppetserver-ca GEM version to 2.3.2

resources/ext/build-scripts/mri-gem-list-no-dependencies.txt
What this GEM bump contains:
- Update to the `prune` action so that it only prune a single Puppet's CRL.
- Update logging information of the `prune` action to log the total number of certificates in Puppet's CRL.
- Fix a bug when not checking `:query` parameters to be `nil` when create a URL.
=> (maint) Update puppetserver-ca GEM version to 1.11.3

resources/ext/build-scripts/mri-gem-list-no-dependencies.txt
This GEM bump contains:
- Update to the `prune` action so that it only prune a single Puppet's CRL.
- Update logging information of the `prune` action to log the total number of
certificates in Puppet's CRL.
- Fix a bug when not checking `:query` parameters to be `nil` when create a URL,
causing an error.
=> (main) Update puppetserver-ca GEM version to 2.3.3

project.clj
We have landed support for TLS 1.3, so this commit bumps the snapshot version
so that we can do a Y release with this feature.
=> (maint) Bump snapshot version to prep for 7.4.0 release

resources/ext/build-scripts/mri-gem-list-no-dependencies.txt
This commit bumps the puppetserver-ca gem to 1.11.5, which includes a `--force`
flag to be used with `puppetserver ca generate --ca-client` when we can't
determine if the puppetserver service is running or not.
=> (SERVER-2842) Bump puppetserver-ca to 1.11.5

acceptance/config/beaker/options.rb
This commit updates our pins for puppet and puppet-agent to the release
candidates for the upcoming 7.11.0 release, in order to get validation
started before those have officially promoted.
=> (maint) Update to latest puppet/puppet-agent pins

spec/puppet-server-lib/puppet/jvm/compiler_spec.rb, src/ruby/puppetserver-lib/puppet/server/compiler.rb
Previously, the v4 catalog endpoint would only fetch facts (as opposed
to requiring them in the request) if the PuppetDB facts terminus was
configured. This caused issues for people wanting to use extensions of
the PDB terminus, like satellite, because the endpoint would error
claiming that PDB wasn't configured.
This commit removes the restriction on the fact retrieval logic. Now, if
facts are not supplied in the request body, puppetserver will attempt to
fetch them from whatever facts terminus is configured, whether that is
yaml/json (default), PuppetDB, or some custom terminus. So long as the
terminus implements `find`, this will succeed.
=> (SERVER-3050) Allow retrieving facts from any terminus

acceptance/scripts/generic/testrun.sh, src/ruby/puppetserver-lib/puppet/server/compiler.rb
When we stopped explicitly querying the PuppetDB terminus for facts, we
inadventently started using the yaml cache terminus instead of PuppetDB,
even when PuppetDB was configured. However, trusted facts are not stored
in the yaml cache, and the primary use case for this endpoint requires
stored trusted facts to be retrieved from the system. So this commit
updates the fact retrieval to bypass the cache terminus for facts, going
instead directly to the primary terminus.
When PuppetDB is configured, this means we will query PDB for facts,
rather than the default yaml cache, and therefore retrieve its stored
trusted facts.
=> (SERVER-3050) Bypass the fact cache in the v4 catalog endpoint

acceptance/suites/pre_suite/foss/10_update_ca_certs.rb
Recently a major root certificate expired and had to be replaced. This
caused postgres to fail to install, on platforms where we install PDB.
This commit adds a step to our presuite that fetches new CA certificates,
to ensure that next time a cert is rotated, we will fetch it automatically.
=> (maint) Update ca-certificates

acceptance/lib/helper.rb, acceptance/suites/pre_suite/foss/10_update_ca_certs.rb
The recent root certificate expiration has made it difficult to install
postgres on EL6. RedHat did not issue an update of the `ca-certificates`
package for this EOL platform, so avoiding the expired cert is much more
complicated. Since we will soon be dropping support for EL6, we decided
to instead stop testing the PDB integration on this platform. This
commit removes it from the list of PDB master platforms. If a good
workaround is found, we can put this back.
=> (maint) Stop testing with PuppetDB on EL6 for now

dev/puppetserver.conf, resources/ext/build-scripts/dropsonde-gem.txt, resources/ext/build-scripts/install-vendored-gems.sh, resources/ext/config/conf.d/puppetserver.conf, src/clj/puppetlabs/services/analytics/analytics_service.clj, src/clj/puppetlabs/services/analytics/dropsonde.clj
This installs the Dropsonde gem into an isolated directory during package 
install. This gem is meant to be run via MRI Ruby from the CLI, and uses
its own self-contained dependencies, not gems installed with either 
puppetserver or puppet-agent.
It also a new scheduled job to the analytics service, to submit
module metrics to dujour via dropsonde. This submission is managed by
the same service as the existing analytics submission, but is configured
separately and runs weekly instead of daily.
Submission is disabled by default. When enabled, metrics will be
collected and submitted when the server starts, and weekly thereafter.
A failed dropsonde invocation will log an error but otherwise cause no
issues.
=> (SERVER-3079) Run Dropsonde weekly

resources/ext/build-scripts/dropsonde-gem.txt, src/clj/puppetlabs/services/analytics/dropsonde.clj
In Puppet Server 7 we renamed several settings from `master-*` to
`server-*`. This commit updates our reading of these settings to use the
existing default resolution logic, which check both values before
falling back to the hard-coded default.
=> (SERVER-3079) Use updated terminology for puppet settings

resources/ext/cli/dropsonde.erb
This allows users to invoke Dropsonde as `puppetserver dropsonde` and
access the local functionality such as generating reports for their own
usage or to validate what data will be submitted.
=> (SERVER-3079) add Dropsonde wrapper script

project.clj
This update brings in support for building Debian 11 Bullseye packages.
=> (SERVER-3137) Update ezbake to 2.3.0

src/clj/puppetlabs/puppetserver/certificate_authority.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
There are two fixes in this PR:
Firstly, for consistency, the auto CA generation code in puppetserver now creates its self-signed CA cert with a `keyid` authority key identifier. This is consistent with what the newer (recommended) chained CA generation code in the CLI tool does.
Secondly, it removes the subject alt names from the self-signed cert, since they're unnecessary, and the fact that its common name is not a valid DNS name caused issues with LibreSSL.
=> (SERVER-3114) Fix authority key ID and alt names of self-signed CA cert

resources/ext/build-scripts/dropsonde-gem.txt
This commit updates dropsonde to 0.0.7, which includes a stable url for the
telemetry endpoint (updates.puppet.com).
=> (SERVER-3166) Bump dropsonde to 0.0.7

docker/puppetserver/docker-entrypoint.d/30-set-permissions.sh
The container is created with the puppet user owning these directories
and if a user causes the UID of the puppet user to change than they will
not be readable.
This forces those directories to be owned by the puppet user regardless
of UID on start up.
h/t to jay7x who originally proposed this.
=> (maint) Ensure needed container directories are owned by puppet

dev/puppetserver.conf, docker/puppetserver/puppetserver.conf, ext/thread_test/puppetserver.conf, resources/ext/config/conf.d/puppetserver.conf, test/unit/puppetlabs/puppetserver/ruby/http_client_test.clj
This commit removes the HTTP client tests for TLS 1.0 and TLS 1.1. These
protocols are no longer considered secure and, as such, have been disabled in
certain operating systems, including Debian 10 (buster), which is what the
jenkins workers now use. Previously, these tests were failing since the jenkins
workers were recently upgraded.
=> (maint) Stop testing TLS 1.0 and 1.1

docker/puppetserver/README.md
IMO, the easiest way to get started with puppetserver is using docker. I wasn't familiar with what would be required from to have a puppetserver that could survive across a container restart, so I had to look at some other sources. 
This just a little note that would help a person trying to get started with puppetserver by using the docker deployment. Please feel free to change any thing or reject it - this is just an idea that would have helped me get started slightly easier.
=> (docs) Just a little note about server persistence across restarts

src/clj/puppetlabs/puppetserver/certificate_authority.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
With the release of jvm-ssl-utils 3.4.0, the authority key identifer
can be copied from an existing certificate and used when signing
CSRs, instead of always computing a type 1 key from the CA's public
key. This commit changes puppetserver to use the CA's certificate
during signing so that puppetserver signs CSRs with the existing CA's
subject key id as the authority key id for agent requests. This will
allow puppetserver to use externally created CA certificates that
use a type 2 key.
=> (SERVER-2662) Use existing cacert's subject key id when signing

acceptance/suites/tests/code_commands/code_scripts.rb
This commit updates the ntp module that we use in acceptance tests to version
9.1.0. This test started failing when we added support for sles-15-x86_64
because ntp 4.1.0 does not support that platform. 9.1.0 is the latest version
of the ntp module and includes support for a more up-to-date set of operating
systems.
=> (maint) Update ntp module to 9.1.0

resources/ext/config/conf.d/puppetserver.conf, src/clj/puppetlabs/services/analytics/analytics_service.clj
This changes dropsonde to be opt-out by default if the configuration value is
not specified per this announcement:
https://puppet.com/blog/the-next-step-in-puppet-content-telemetry/
=> (SERVER-3170) make dropsonde opt-out by default

project.clj
Support for fixed UIDs/GIDs was added to ezbake way back in
EZ-128 (puppetlabs/ezbake#512)
This commit uses this feature to use the reserved UID of 52 when the
`puppet` user is created when the puppetserver RPM is first installed.
=> (SERVER-1381) Create puppet user with uid/gid 52

src/ruby/puppetserver-lib/puppet/server/master.rb, src/ruby/puppetserver-lib/puppet/server/network/http/handler.rb
JRuby deprecated `java_kind_of?` many years ago and finally removed it
in 9.3. This commit switches to the general replacement `kind_of?` in
preparation for upgrade to JRuby 9.3.
=> (SERVER-3133) Remove deprecated JRuby function

acceptance/suites/tests/code_commands/code_scripts.rb
Following CVE-2022-24765 (see
https://github.blog/2022-04-12-git-security-vulnerability-announced/)
git will no longer trust repositories owned by another user without
being explicitly allowed. This fix is in Git 2.35.2.
The code_scripts.rb test has the git user own a test repositiory so
it may be served by a local git server. Once the repository is owned
by the git user the root user may not commit to it.
This commit marks the shared local repository as safe as soon as its
ownership is given to the git user.
=> (maint) Update acceptance test for git CVE-2022-24765

src/clj/puppetlabs/services/master/master_core.clj, test/unit/puppetlabs/services/master/master_core_test.clj
Previously, the URLs generated for certain task files were incorrect and
led to those tasks not being runnable. Task files can be loaded from the
`tasks`, `scripts`, `files` or `lib` directory of a module. If the
module itself had any of those names, the URL generated was incorrect.
The trouble was that we were trying to determine the module and
subdirectory of the file purely based on its absolute path on disk,
without knowing the modulepath or the module name. Without that
information, it's impossible to accurately interpret the file path in
all cases.
We now use the additional "file name" field which has the information we
need in a much easier to parse form. Specifically, the file name is
supplied in one of two forms:
* the basename for a task implementation file, in which case we …
=> (PE-33240) Properly serve task files from a module called "tasks"

.gitattributes, jenkins/mergeup.sh
This commit adds a script that can be used as a merge driver for project.clj
and for the beaker options file. It will resolve common conflicts around version
bumps, but any unfamiliar conflicts will need manual intervention. This script
was copied from pe-puppet-server-extensions and modified slightly to handle the
beaker options file. Previously, puppetserver mergeup conflicts were handled by
a custom merge driver created as part of the `puppetserver-mergeup.sh` script in
ci-job-configs, but this did not handle conflicts in project.clj. This strategy
will allow us to resolve fewer conflicts by hand and will allow us to simplify
the mergeup script in jenkins.
=> (maint) Add custom merge driver script

acceptance/suites/tests/https/client_may_use_external_cert_chains.rb
PE includes puppetdb as a report processor and, in some cases when
running this test, may still be configuring itself. To manage this we
include puppetdb as a report processor if we a PE install as well as
allow `puppet agent -t` to return `2`.
=> (maint) Respect PE in external cert test

project.clj
The next puppetserver 6.x release includes some new features (already shipped in
puppetserver 7.8.0), so this prepares us for a Y release.
=> (maint) Bump version to 6.20.0-SNAPSHOT

test/unit/puppetlabs/puppetserver/ruby/http_client_test.clj
This commit ensures that the test http client uses the appropriate cipher suites
when testing TLSv1.3. Previously, this test would fail with
`javax.net.ssl.SSLHandshakeException: Received fatal alert: protocol_version` on
newer Java 8 versions.
=> (maint) Specify cipher suites when testing TLS 1.3

project.clj
This causes automatic mergeups to fail, since it thinks that conflict markers
were not cleaned up appropriately.
=> (maint) Remove trailing whitespace

src/clj/puppetlabs/services/master/master_core.clj, test/integration/puppetlabs/services/jruby/tasks_test.clj, test/integration/puppetlabs/services/master/tasks_int_test.clj, test/unit/puppetlabs/services/master/master_core_test.clj
Updates the master_core service to return "private" and "description"
keys from tasks when hitting the /v3/tasks API. Depends on
https://github.com/puppetlabs/puppet/pull/8921
=> (PUP-11540) Update all-tasks-response! to read private/description

acceptance/suites/tests/https/client_may_use_external_cert_chains.rb
This should hopefully unblock pe-puppetserver CI.
=> (maint) Skip external cert chain test on FIPS

acceptance/suites/tests/https/client_may_use_external_cert_chains.rb
The previous comment was not accurate - we use the agent's Ruby, so we should
have access to OpenSSL.
=> (maint) Update explanation for skipping external cert chain test on FIPS

Gemfile
v5.x of the public_suffix gem no longer supports ruby 2.5 which
causes installation failures during the bundle install. This commit
pins public_suffix to v4.0.7, which is compatible. Note this is not
needed for main branch which is running jruby 9.3.x (compatible with
Ruby 2.6.x).
=> (maint) fix packaging gem installation

.travis.yml, Gemfile, ext/travisci/install-java.sh, project.clj, resources/ext/build-scripts/dropsonde-gem.txt
Resolved options in favor of main, brought along the dropsonde bump
Conflicts:
- resources/ext/build-scripts/dropsonde-gem.txt
=> (maint) Merge '6.x' into 'main'

Rakefile
We previously pinned bundler to a version of 1.x because when 2.x was released it required a Ruby version compatible with 2.3 or greater but we were stuck support JRuby 1.7.
Those constraints are long gone and we need newer bundler versions to better handle dependency restrictions, particularly based on Ruby versions.
=> (PE-34508) Unpin bundler in Rakefile

project.clj
We provide our own versions of these libraries and it's best to only have one of each on the classpath.
=> (SERVER-3219) Exclude JRuby stdlib dependencies from uberjar

locales/eo.po, locales/puppetserver.pot, src/clj/puppetlabs/puppetserver/certificate_authority.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj, test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj
Updating certificate authority validation regexp to restrict hostname format. Originally our regex validation was simply checking that the hostname did not contain non ascii characters. As this allowed invalid hostnames and the potential for command injection, we have now updated the regex to reduce the allowed characters as well as follow  a hostname or domain format.
=> (PE-34096) Certificate authority regexp

project.clj
In a previous commit we began passing flags to the JVM that allows JRuby to access protected members of the Java IO subsystem, as is currently required by JRuby 9.3.8. However, this flag does not exist in (at least) Java 8 and so we must conditionally include these flags based on Java versions.
The conditional code is based on the existing conditional JVM flags passed in FIPS mode.
=> (maint) Conditionally open Java IO only for Java 17

src/clj/puppetlabs/services/request_handler/request_handler_core.clj, src/ruby/puppetserver-lib/puppet/server/network/http/handler.rb, test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj
This removes the use of slurp in the clojure code to instead present the input stream to ruby to process. While ruby will still read the string when the body is requested, this change will prevent the clj layer from having a referenced string during the lifetime of the request. This should help reduce memory overhead.
=> (PE-33991) remove use of slurp to reduce memory footprint

docker/puppetserver/Dockerfile
Currently docker build fail with the following error:
```#12 41.61 ERROR:  Error installing fpm:
#12 41.61 	The last version of public_suffix (< 6.0, >= 2.0.2) to support your Ruby & RubyGems was 4.0.7. Try installing it with `gem install public_suffix -v 4.0.7` and then running the current command again
```
This PR fix this by forcing the public_suffix ruby gem to 4.0.7
=> fix docker build by forcing older version of public_suffix

.travis.yml
This commit adds a note to the Travis CI config to make clear that we do not officially support the s390x architecture.
=> (maint) Add note that we don't officially support s390x

test/integration/puppetlabs/services/jruby/tasks_test.clj
Previously we tested our task data integration using invalid fixtures and with PUP-11683 these fixtures will no longer be returned.
=> (PUP-11683) Remove invalid fixtures

project.clj
Now that this pin is in clj-parent it is causing leiningen to fail to resolve dependencies.
=> (maint) Use clj-parent snakeyaml version

Rakefile
Bunlder released a Christmas surprise in 2.4 which required Ruby 3.0.1 or greater. Later 2.4.x releases relaxed that to >= 2.6 but regardless the 2.3.x series of Bundler is the last to support Ruby < 2.6.
So for the 6.x series we need to pin Bundler to less than 2.4.
=> (maint) Pin bundler to '< 2.4' for the 6.x branch

src/clj/puppetlabs/services/master/master_service.clj, test/unit/puppetlabs/services/master/master_core_test.clj
This commit updates the master service to log a warning when:
1. An incompatable/unknown java version is used to run puppetserver
2. java version 8,9, or 10 is used and will be deprecated
=> (SERVER-2782) Issue deprecation warning for java 8

src/ruby/puppetserver-lib/puppet/server/master.rb
The Puppet::Server::Master#terminate code was updated to support JRuby 9.4 and only JRuby 9.4. And in FOSS we only allow users to use the vendored JRuby, but in PE we allow users to swap out JRuby jars. We are also delaying upgrading JRuby to 9.4 in PE for the time being, so it is advantageous to support multiple JRuby versions in this code now.
The thread leakages that necessitated the old shutdown code was supposedly fixed in JRuby 9.3.8 (we currently use JRuby 9.3.9) but the old private code we handled was removed in 9.4.0.
JRuby users will experience the thread leakages we saw in 9.4 _if_ they update the timeout stdlib module. If they do not update our new code will fail. This change will resolve the thread leakage if using the new timeout module.
=> (maint) Allow using JRuby 9.3

project.clj, src/ruby/puppetserver-lib/puppet/server/master.rb
(maint) Update to JRuby 9.4.2
---
(maint) Remove unneeded Timeout module workaround
In JRuby 9.4.0 & 9.4.1 there was an issue when shutting down threads,
if JRuby encountered an adopted thread it would stop its thread shutdown
procedure and any abandoned threads would be leaked.
This was particularly problematic because the Timeout module does not
attempt to shutdown its watcher thread and Puppet Server adopts a Jetty
thread as part of processing incoming requests, so we would consistently
leak Timeout threads when flushing a JRuby.
To work around this issue while we tested our JRuby upgrade we manually
killed the Timeout watcher thread. This was not a vialable solution to
ship with, but allowed us to see how much work the move to a Ruby 3
compatible interpreter would be.
With JRuby 9.4.2 …
=> (maint) Bump jruby

src/clj/puppetlabs/puppetserver/certificate_authority.clj, test/integration/puppetlabs/puppetserver/bootstrap_int_test.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj, test/unit/puppetlabs/services/ca/ca_testutils.clj
As part of atomic-file work (https://github.com/puppetlabs/clj-kitchensink/commit/dffc88be0d5af0b126475bd925901999c67a1571) routines to convert strings to Path objects, get and set permissions were added to the clj-kitchensink project. There are similiar routines in the CA space. This removes those routines in favor of the routines in the kitchensink project.  Tests are updated as appropriate.
=> (maint) remove redundant file permissions checks

resources/ext/build-scripts/mri-gem-list-no-dependencies.txt
Upgrade puppetserver-ca gem to 2.5.0 with a new 'delete' command to delete signed certificates from disk and additional options to existing 'prune' command.
Delete command has following options:
--expired - Delete expired signed certificates
--revoked - Delete certs that are already revoked
--all - Delete all signed certs on disk
Prune command will now has three options:
--remove-duplicates - Remove duplicates(default)
--remove-expired - Remove expired entries from CRL
--remove-entries - Remove given entries(serialnumbers or certnames)
from CRL
=> PE-34952 PE-34951 Use puppetserver-ca gem with updated prune and delete

src/clj/puppetlabs/puppetserver/certificate_authority.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
In the CA host validation code a complex regular expression was being used that involved looping, and in some circumstances would create performance issues.
This replaces the complex regular expression with a series of simple steps to validate the subject against specific criteria.
Additionally, info level logging was added to help diagnose issues with particular host requests being rejected.
An issue was found in the clj-i18n logging routine where multiple arguments are not handled correctly, and substitution is not being done. A defect has been raised about that issue, and as a stop-gap the logging and error messages for the ca-signing that use multiple arguments were altered to not use the i18n routines.
=> (PE-35786) improve performance and reliability of subject validation

src/clj/puppetlabs/puppetserver/certificate_authority.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
This updates the validation to allow trailing dots, and the subjects to start with an underscore, and have segments that start or end in underscores.
Tests are updated to reflect the updated behaviors.
=> (PE-35786) allow trailing dot in subject validation

project.clj, src/clj/puppetlabs/puppetserver/certificate_authority.clj, src/clj/puppetlabs/services/ca/certificate_authority_core.clj, src/clj/puppetlabs/services/ca/certificate_authority_service.clj, src/clj/puppetlabs/services/legacy_routes/legacy_routes_service.clj, test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj, test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj
Added an optional dependency for the ActivityReportingService, as well as new functionality for attempting to extract CA signee data from requests to sign and revoke certificates. With preference for RBAC user details, but will fall back to the name linked to the certificate used to sign, and defaulting to the “CA” signee if no other information is available. When a certificate event occurs, log messages will now include information on who signed the certificate. Additionally, if the activity service is available, the information will be submitted there as well.
Added tests checking updated log messages and also mocked activity service to check logged activities.
Manually tested signing, plus revoking individual and multiple.
=> (PE-35325) Update Puppet Server to include the requester's info

project.clj
We previously tagged 7.10.0 in preparation for the Platform 7.24 release, however a late breaking issue was discovered that needed to be addressed. Consequently, we burned the 7.10.0 tag and will ship 7.11.0 to include a fix for cert regex matching that could be nonterminating.
=> (maint) Update version towards 7.11.0

src/clj/puppetlabs/puppetserver/certificate_authority.clj
In a previous commit https://github.com/puppetlabs/puppetserver/commit/a029e7762c07d1d47947edcef6485e5fcd59c2c2 some new strings were added to improve supportability.  While bench testing those issues, it was observed that some strings were not expanded correctly with multiple arguments. The issue turned out to be an escape issue with a single quote.  This resolves that issue, and replaces the use of `format` from that previous commit with the more appropriate i18n translation functions.
=> (maint) fix i18n issues

ext/build_defaults.yaml
There has been confusion for a few major releases about what this file does. Apparently it controls where the `packaging` gem ships the packages publicly. The setting in `project.clj`
controls where ezbake puts the packages after it builds them (internally).
This was not updated so puppetserver 8 was shipped to puppet7.
This should be rectified, and the repo setting should be controlled in a single place, but for now this will ship puppetserver 8.y.z to the proper public destination.
=> (maint) Update build_defaults.yaml to puppet8

src/clj/puppetlabs/puppetserver/certificate_authority.clj, src/clj/puppetlabs/puppetserver/common.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj, test/unit/puppetlabs/services/ca/ca_testutils.clj
In preparation for future changes coming to the CA endpoints, this adds explicit read/write locking to the management of the serial file.
This also adds the ability for the serial lock acquisition to timeout preventing potential locking issues. The default timeout is 5 seconds.
The locks are added to the ca-settings, and schemas updated as appropriate.
=> (PE-35637) add explicit read/write locking to serial file use

src/clj/puppetlabs/puppetserver/certificate_authority.clj
In previous work, the signature of read-infra-nodes was changed to pass in a reader. The intent was to remove the reader from the funciton so that the reader lifetime could be properly maintained. This updates the code to not create the redundant reader.
=> (PE-3288) remove redundant reader

src/clj/puppetlabs/puppetserver/certificate_authority.clj, src/clj/puppetlabs/services/ca/certificate_authority_core.clj, test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj, test/unit/puppetlabs/services/ca/ca_testutils.clj, test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj
This updates the ca-settings to have two new locks, one for the crl, and one for the infra-crl along with appropriate timeouts for each.  The locks are used in the routines that read and write the crl files to ensure they are only read when they aren't being written. 
Tests are updated as appropriate.  See individual commits comments for more details.
=> (PE-35638) make crl file manipulation routines thread safe

src/clj/puppetlabs/puppetserver/certificate_authority.clj, src/clj/puppetlabs/puppetserver/common.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj, test/unit/puppetlabs/services/ca/ca_testutils.clj
This adds a ReentrantLock that is used to protect multiple threads from writing to the inventory file at the same time.  This is important because the inventory update routine now has to read in the contents prior to appending a new entry. If two separate threads are updating the file at the same time, there is the possiblity that one of the entries would be lost.
Tests were updated as needed.
=> (PE-35641) promote inventory content safety

project.clj
We want to go back to using the jruby from clj-parent in the main branch. This commit updates the puppetserver project to use the version contained in clj-parent.
=> (PE-35007) Stop overriding jruby from clj-parent

src/clj/puppetlabs/puppetserver/certificate_authority.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
This adds a new function `cert-authority-id-match-ca-subject-id?` that validates that for a given cert and a ca-cert, that the cert was issued by the ca-cert.
Tests were added to demonstrate the behavior.
=> (PE-35706) add certificate validity function

src/clj/puppetlabs/puppetserver/certificate_authority.clj, src/clj/puppetlabs/services/ca/certificate_authority_core.clj, src/clj/puppetlabs/services/ca/certificate_authority_service.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
In the first commit:
This simplifies the mechanism for activity reporting to centralize the message creation and reporting into a separate function that can be called with the subjects and type of reporting without having to pass the request around. It simplifies the testing required, and creates reuse.
In the second commit:
Given an existing certificate, which is assumed to be from the
same issuer (caller to validate), generate a new signed cert
with the same extensions, and a new expiration period determined
by the auto-renewal-cert-ttl time.
Note that the issuer and subject identifier extensions need to be
regenerated for signing to occur properly.
Tests are added to demonstrate the behavior of the function.
=> (PE-35709) add in renew-certificate function

dev/puppetserver.conf, ezbake/config/conf.d/ca.conf, src/clj/puppetlabs/puppetserver/certificate_authority.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj, test/unit/puppetlabs/services/ca/ca_testutils.clj, test/unit/puppetlabs/services/config/puppet_server_config_service_test.clj
Add three new parameters to certificate-authority. allow-auto-renewal - to toggle auto renewal of certs. auto-renewal-cert-ttl - determines the lifetime of cert. ca-ttl - default expiration time. If ca-ttl is set in certificate-authority, it will override the ca-ttl value in puppet conf.
=> PE-35698 Add new certificate-authority parameters

.github/workflows/pr-testing.yaml
This enables running the clojure tests via github actions on the matrix of versions of java, multithreaded support, and with fips.
=> (maint) enable pr testing through github actions

.github/workflows/pr-testing.yaml
This updates the ruby version in the github PR action to use ruby 3.1 instead
of ruby 2.7.  The older version of ruby was causing test failures with log lines
being repeated multiple times.
=> (maint) update ruby version in github action to 3.1 

src/clj/puppetlabs/puppetserver/certificate_authority.clj, src/clj/puppetlabs/services/ca/certificate_authority_core.clj, test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj, test/unit/puppetlabs/services/ca/ca_testutils.clj
This commit updates the handle-cert-renewal function to extract certificates present in the request. Certificates can be included either as a ssl-client-cert property in the request, or as an x-client-cert field in the request header.
Imports for certificate-authority-core and certificate-authority-int-test were alphabetized as well.
=> (PE-35705) extract certificate from renewal request

test/integration/puppetlabs/puppetserver/auth_conf_test.clj, test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj, test/integration/puppetlabs/services/jruby/jruby_puppet_pool_int_test.clj, test/integration/puppetlabs/services/master/environment_classes_int_test.clj, test/integration/puppetlabs/services/master/environment_transports_int_test.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj, test/unit/puppetlabs/services/config/puppet_server_config_core_test.clj, test/unit/puppetlabs/services/config/puppet_server_config_service_test.clj, test/unit/puppetlabs/services/master/master_core_test.clj
The single-threaded and multi-threaded versions of `admin-api-flush-jruby-pool-test` were named nearly the same
thing, which was confusing. This changes the naming to make them different, and forces the multithreaded
test to specify the multithreaded flag to guarantee the test runs in multithreaded mode regardless of the environment variable setting.
=> (maint) differentiate test names

src/clj/puppetlabs/puppetserver/certificate_authority.clj, src/clj/puppetlabs/services/ca/certificate_authority_core.clj, test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj
This modifies the `/v1/certificate/<hostname>` endpoint to honor the if-modified-since header to prevent sending content if the file hasn't been modified since the date specified. This will reduce the amount of traffic from the CA, and reduce the amount of handling needed on the client.
=> (PE-36083) add if-modified-since handling for get-certificate endpoint

src/clj/puppetlabs/services/ca/certificate_authority_core.clj, test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj
This commit uses the the certificate validation function from a previous commit [1] to check that the certificate supplied in the renew request was signed by the CA.
[1]: e42cfa1e26cb3224bc1f831267d6d7ff4195cf6d
=> (PE-35707) validate certificate supplied in renew request

src/clj/puppetlabs/puppetserver/certificate_authority.clj, src/clj/puppetlabs/services/ca/certificate_authority_core.clj, test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj
This commit uses the renew-certificate! function added in a previous commit [1] to sign a new certificate and return the new cert to the agent when a qualified request is made to the certificate_renewal endpoint.
[1]: a29054e19641ae1852615ee4cd89434939dff665
=> (PE-35710) renew certificates when requested

ezbake/config/conf.d/auth.conf
This adds a configuration block that allows authenticated clients to access the certificate renewal endpoint.
=> (PE-36178) Add config block for certificate renewal endpoint

src/clj/puppetlabs/puppetserver/certificate_authority.clj, src/clj/puppetlabs/services/ca/certificate_authority_core.clj, test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
This adds the concept of the CA determining if a given agent CSR can support renewal or not. As a stop-gap, this introspects the x-puppet-version header to check the version of the agent. If it is present, and >= 8.2.0, then it is assumed that the agent supports the feature. Also as a stop-gap, a file is written alongside of the csr to indicate that the agent supports the feature. Future work will be to use this file to choose a short ttl (assuming renewal is enabled), and clean up the temporary file as appropriate.
Additional follow-on work will include leveraging attributes/extensions present in the CSR instead of the version to indicate that the agent supports renewal.
Also as part of this work, the puppet function `versioncmp` was ported into clojure and included. Similar tests to …
=> (PE-36202) add indication that agent supports certificate renewal

project.clj
This updates ezbake to 2.4.2 to allow ubuntu to be a build target for puppetserver.
=> (SERVER-3289) add ubuntu 22.04 as build target

src/clj/puppetlabs/puppetserver/certificate_authority.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
This removes the version compare function that was added as a stop-gap until the kitchensink version was available.  Now that it is, this removes the function, the utility routines and the tests from this repo.
=> (maint) use version compare function from kitchensink

project.clj, src/clj/puppetlabs/puppetserver/certificate_authority.clj, src/clj/puppetlabs/puppetserver/common.clj, src/clj/puppetlabs/services/master/file_serving.clj
This removes the use of clj-yaml for yaml parsing because internally it uses snakeyaml 1.33. Instead, snakeyaml 2.0 is used directly and a routine for mapping from java structures to clojure structures is added.
=> (PE-36386) remove use of clj-yaml in favor of snakeyaml 2.0

dev/puppetserver.conf, src/clj/puppetlabs/puppetserver/certificate_authority.clj, test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj, test/unit/puppetlabs/services/ca/ca_testutils.clj, test/unit/puppetlabs/services/config/puppet_server_config_service_test.clj
This alters the default initial ttl for agents with auto-renewal capability to 90 days from 60 days, and changes the period of validity on renewal from 60 days to 90 days.
=> (PE-32607) change default auto-renewal ttl to 90 days

test/integration/puppetlabs/general_puppet/general_puppet_int_test.clj
With the change in https://tickets.puppetlabs.com/browse/PUP-9964 the oid that was used in the custom-trusted-oid-mapping is no longer unnamed in puppet. This updates the test to reflect the new puppet behavior.
See: https://github.com/puppetlabs/puppet/pull/9080/commits/38f24392ff01a7e0e9f390d89b46d9ff6c4257a6
=> (maint) fix naming of pp_cli_auth

src/clj/puppetlabs/puppetserver/certificate_authority.clj, test/integration/puppetlabs/general_puppet/general_puppet_int_test.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
This adds a new function to puppetserver that extracts attributes from CSRs, which will be needed to determine if an agent is capable of auto-renewal or not, rather than the current method of looking at the agent version.
This adds tests to demonstrate the behavior
=> (PE-36456) add a routine to extract attributes from a CSR

src/clj/puppetlabs/puppetserver/certificate_authority.clj, src/clj/puppetlabs/services/ca/certificate_authority_core.clj, test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
This changes the mechanism used to determine if an agent should have the shorter "auto-renewal" ttl for Certificate Signing Requests, or if it should use the default ca-ttl.
The agent will include an attribute that indicates with a "true" value that it supports auto-renewal. If the attribute is missing, or is a "false" value, the indication is that it does not support auto-renewal.
Tests are updated as needed to demonstrate the new behaviors.
The code related to creating, interrogating and deleting the indicator file have been removed.
=> (PE-36457) use attribute in csr for auto-reneal indication

project.clj, src/clj/puppetlabs/puppetserver/certificate_authority.clj, src/clj/puppetlabs/services/master/file_serving.clj
This removes the use of clj-yaml, and replaces it with a use of snake-yaml as implemented in trapperkeeper. This is to help resolve https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-1471
which can't be fully resolved due to a dependency on snakeyaml 1.3.3 by jRuby
=> (PE-36479) remove use of clj-yaml

project.clj
This updates ezbake to 2.5.2, which brings in support for el9 builds, and addresses an issue on the el platforms where tzdata-java was missing from some dependencies because of changes in the openjdk.
=> (PE-36185) update ezbake

src/clj/puppetlabs/puppetserver/certificate_authority.clj, test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
Prior to this commit, non-default auto-renew-cert-ttl settings were ignored due to a parameter naming issue. This commit corrects the naming and adds a test for non-default setting values.
=> (PE-36566) fix auto-renew-cert-ttl

src/clj/puppetlabs/services/ca/certificate_authority_core.clj, test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj
Previously, when a `DELETE` request was  sent to `puppet-ca/v1/certificate_status/<nodename>` a `204` response was sent with a malformed content-type header. This commit removes the header.
=> (PE-36076) Remove content type from certificate reject

project.clj
contains a fix for el9 package builds for Puppet Platform 8
=> (maint) Update ezbake to 2.5.3

acceptance/suites/pre_suite/foss/70_install_puppet.rb
Adds `install_package` exception for el-9. Flipped logic since it's a little more clear.
=> (maint) Add nss install exception for el-9

acceptance/suites/pre_suite/foss/70_install_puppet.rb, src/clj/puppetlabs/services/ca/certificate_authority_core.clj, test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj
* 7.x:
(maint) update submodule versions and agent pin
(maint) Add nss install exception for el-9
(maint) Update ezbake to 2.5.3
(maint) update submodule versions and agent pin
(maint) update submodule versions and agent pin
Set clj-parent=5.5.0
(maint) update submodule versions and agent pin
([PE-36076](https://tickets.puppetlabs.com/browse/PE-36076)) Remove content type from certificate reject
(maint) update submodule versions and agent pin
(maint) update submodule versions and agent pin
(maint) update submodule versions and agent pin
(maint) update submodule versions and agent pin
(maint) update submodule versions and agent pin
=> (maint) merge 7.x to main

ezbake/config/logback.xml
Adding temporary debug logging to try to find more out about this failure: 
https://jenkins-platform.delivery.puppetlabs.net/job/platform_puppetserver_integration-system_no-conditional_smoke-7.x/LAYOUT=redhat9-64mdca,LDAP_TYPE=default,label=k8s-beaker/101/console
=> (revert later) Add temporarily debug logging

project.clj
This removes the pinned version of ssl-utils from puppetserver as the main branch is now using a newer clj-parent that contains the pinned version. The previous branch that was merged in pinned the version to avoid an infinite recursion bug.
=> (maint) remove ssl-utils pin

src/clj/puppetlabs/puppetserver/certificate_authority.clj, src/clj/puppetlabs/services/ca/certificate_authority_service.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj, test/unit/puppetlabs/services/ca/ca_testutils.clj
Please see individual commit comments.
=> (PE-36952) ensure infra-serial is up to date

src/clj/puppetlabs/puppetserver/certificate_authority.clj, src/clj/puppetlabs/services/analytics/analytics_service.clj, src/clj/puppetlabs/services/ca/certificate_authority_service.clj, src/clj/puppetlabs/services/master/master_service.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
In the first commit:
This alters the analytics service to explicitly stop the jobs it is running when shutting down. It also adds some simple logging to the startup / shutdown process.
Additionally, an unused dependency in the `master_service` was removed.
In the second commit:
This adds a new behavior where once a day, puppetserver will check to
see if the crls for both the main crl, and if enabled the infra-crl
are nearing expiration.  If one is, the list of expired serial numbers
is collected from the inventory file, and used to prune the CRL list.
The CRL is then regenerated with the (potentially) smaller set of serials.
If the CRLs are not nearing expiration, nothing is done.
Tests are added to demonstrate the CRL behaviors added.
Resolves #2789
=> (PE-36269) ensure CRLs are regenerated when nearing expiration

dev/bootstrap.cfg, dev/dev_tools.clj, ext/thread_test/bootstrap.cfg, ezbake/system-config/services.d/bootstrap.cfg, project.clj, test/integration/puppetlabs/services/master/environment_classes_int_test.clj, test/integration/puppetlabs/services/master/environment_transports_int_test.clj, test/unit/puppetlabs/puppetserver/ruby/http_client_test.clj, test/unit/puppetlabs/services/jruby/jruby_puppet_testutils.clj, test/unit/puppetlabs/services/puppet_profiler/puppet_profiler_service_test.clj, test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj
This commit updates the dependencies and service declarations for trapperkeeper-webserver to the jetty 10 version.
=> (PE-35512) update deps and bootstrap to tkw-j10

project.clj
metrics 2.0.0 is needed for the dev/test space as well as the default dependencies, so this pins the version to that.
=> (maint) pin metrics in test space

project.clj
Per https://codeberg.org/leiningen/leiningen/src/branch/main/doc/PROFILES.md#user-content-composite-profiles best practice is to not mix vector and map dependencies in profiles, so this modifies the existing project to use exclusively one or the other for profiles.
=> (maint) update dependencies to use vectors and maps exclusively

src/clj/puppetlabs/puppetserver/certificate_authority.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
This adds a new function that given a set of csr names, the CA settings and a function to report activity will attempt to sign all the csrs that are valid.  The function returns a map that contains the names of the csrs that were signed, and those that weren't signed.
The function validates alt-names, authorization-extensions, and signatures.
Locking is done across the group to prevent lock contention.  In local testing, it took ~5 seconds to process ~500 records, of which 100 were valid.
=> (PE-37347) add bulk signing function

ezbake/config/conf.d/auth.conf
This adds the /v1/sign and the /v1/sign/all endpoints to the auth.conf so that they will use the authentication gating for `pp_cli_auth`.
=> (PE-37350) ensure bulk signing endpoints enforce authentication gates

src/clj/puppetlabs/puppetserver/certificate_authority.clj, src/clj/puppetlabs/services/ca/certificate_authority_core.clj, test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
See individual commit comments.
=> (PE-37348) connect bulk signing behavior to endpoint

src/clj/puppetlabs/puppetserver/certificate_authority.clj, src/clj/puppetlabs/puppetserver/common.clj, src/clj/puppetlabs/services/ca/certificate_authority_core.clj, test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
This adds the CA "sign/all" endpoint that signs any CSRs that are found in the directory, and comply with the rules for CSR signing.
It leverages the `sign-multiple-certificate-signing-requests!` which has heavy testing in itself, so a basic smoke test is provided.
=> (PE-34953) add sign/all endpoint

acceptance/suites/pre_suite/foss/80_configure_puppet.rb
It was discovered that the dropsonde service was running during acceptance tests, and due to the nature of the tests (many reloads in rapid succession, and lack of outward connectivity), the ruby processes could cause excessive memory use. This disables the service during acceptance tests, as we don't need to test it specifically there.
=> (maint) disable dropsonde during acceptance tests

acceptance/suites/pre_suite/foss/95_install_pdb.rb
Postgres 11 is deprecated, use postgres 14 for acceptance test setup when installing puppetdb via puppetlabs-puppetdb module.
=> (maint) Use postgres 14 for acceptance tests in puppetdb

acceptance/suites/pre_suite/foss/95_install_pdb.rb
This allows us to take up latest puppetlabs/postgresql module with gpg key updates.
=> (PE-37477) Temporarily use puppetlabs-puppetdb branch for testing

acceptance/suites/tests/code_commands/code_scripts.rb
Ruby 2.7 does not consider ruby version when resolving gem deps. Pin back faraday to avoid dependency resolution conflict.
=> (maint) Pin faraday for ruby 2.7 compatability

acceptance/suites/tests/code_commands/code_scripts.rb
This reverts commit 9168ec0babd91db185e436dedb75ac2edf5f9853.
This commit was auto merged up from 7.x. It is not needed for the main branche because this branch is puppet 8 / ruby 3 based.
=> Revert "(maint) Pin faraday for ruby 2.7 compatability"

project.clj
The behavior of using nested maps in a vector of dependencies in `lein` has unexpected behaviors. The most predictable results come from declaring alternative profiles and using those in the vector declarations to allow multiple profiles to be used. For example, on the left of this is the result of `lein deps :tree` before this change was made, and the right is after the change is made.  Note that the `test` scope is correctly applied to everything now.
```
1c1
<  [beckon "0.1.1"]
---
>  [beckon "0.1.1" :scope "test"]
12c12
<  [lambdaisland/uri "1.4.70"]
---
>  [lambdaisland/uri "1.4.70" :scope "test"]
23c23
<  [org.bouncycastle/bcpkix-jdk18on "1.74"]
---
>  [org.bouncycastle/bcpkix-jdk18on "1.74" :scope "test"]
29c29
<  [org.clojure/tools.namespace "0.2.11"]
---
> …
```
=> (maint) change profile definitions to avoid maps in vectors

project.clj
As part of a recent change in clojars, it is necessary for the license to be part of the exported pom file. Puppetserver has been under the apache-2 license for ~12 years, so this isn't anything new. This adds the declaration to the project.clj so that leiningen will correctly add the license to the exported pom file.
=> (maint) add license to project.clj

src/clj/puppetlabs/puppetserver/certificate_authority.clj
This adjusts the logging of failures during bulk cert signing to error
so they end up in the standard log. Additionally, this adds info level
logging of the subject name for a newly signed cert which is done
on the old endpoint.
=> (PE-37635) adjust logging of error to error level, add info logging 

src/clj/puppetlabs/puppetserver/certificate_authority.clj, test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj
Prior to this change, if the sign-all behavior was invoked for the CA service, an exception would be thrown because the function returns a result that wasn't expected. This adds a test that demonstrates the failure, and adds a fix to get the test to pass.
=> (PE-37634) ensure sign-all with empty list succeeds

acceptance/suites/tests/code_commands/code_scripts.rb
By default when Puppet creates a user the password is recorded as having a sentinel value of an exclamation mark. This special value prevents users from logging in via password - though the root user can still `su` to it locally - and by default SSHD will not allow access to these "locked" accounts.
Most of our acceptance VMs specially configure SSHD to allow access to these "locked" accounts, but not our newer Almalinux VMs.
By giving the git user an explicit password we can connect via SSH to the git user, regardless of the SSHD configuration on the VM. The star ("*") used for the git user's password is also a special sentinel value which prevents logging into the user via password, but will not be considered "locked" by SSHD.
For reference see: …
=> (maint) Improve code scripts test

src/clj/puppetlabs/puppetserver/jruby_request.clj
Prior to this change, a failure in schema checks would provide minimal useful context in the logs around what the schema error was. This adds specific handling for schema failures to log them more verbosely as well as forming a json error payload that contains the schema failures.
Prior to this change, the default handler for jetty was generating a generic error page with the schema failure.  Given that the consumers of this endpoint are not often webbrowsers, this form of content was deemed less useful than a json response with the details.
=> (PE-37145) ensure schema failures are verbosely logged

project.clj
The metrics version being included in the `ezbake->dependencies` was
pulling in a older version of metrics. The version of metrics is now
managed at the clj-parent level, so this removes the pin.
=> (maint) remove metrics dependency in self-referential inclusion

project.clj
HEAD of main has gone through all testing required for release, but this needs to be updated to release the agreed to 8.5.0 rather than 8.4.1.
=> (SERVER-3339) Prepare for 8.5.0 release

src/clj/puppetlabs/puppetserver/certificate_authority.clj, src/clj/puppetlabs/puppetserver/common.clj, test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
This adds tracking to the csr requests to report what csrs are submitted. This will be used for overall host activity tracking.
White box tests are added to demonstrate the behavior.
=> (PE-37584) add action tracking for csr signing requests

src/clj/puppetlabs/puppetserver/certificate_authority.clj, test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
This adds action tracking to the certificate signing behaviors for both the "single sign" behavior and "bulk signing".  Renewals are intentionally ignored.
Tests are added to demonstrate the behaviors.
=> (PE-37585) add action tracking to certificate signing behaviors

src/clj/puppetlabs/puppetserver/certificate_authority.clj, src/clj/puppetlabs/services/ca/certificate_authority_core.clj, test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
This adds action tracking to the certificate revocation routine.
The list of names comes in from input. The routine will throw
and exception if the certnames aren't found in the inventory
file or on disk, so it is reasonable to report removal in
any regard. This could mean that a host that is already removed
will be reported removed again, but this isn't a big issue.
Tests were added to demonstrate the behaviors.
=> (PE-37586) add revocation action tracking to revocation routine 

src/clj/puppetlabs/services/master/master_core.clj, src/clj/puppetlabs/services/request_handler/request_handler_core.clj, test/integration/puppetlabs/services/master/master_service_test.clj
This adds catalog compilation action recording for the v3 and v4 endpoints through the `common/record-action` function.
A test was added to demonstrate the behavior of the v3 endpoint.  There are no existing integration tests for the v4 endpoint, and adding them was beyond the scope of this work.
=> (PE-37184) record catalog compilation actions for hosts

acceptance/suites/tests/certificate_authority/fixtures/certdir/391489c4.0, acceptance/suites/tests/certificate_authority/fixtures/certdir/391489c4.r0, acceptance/suites/tests/certificate_authority/fixtures/certdir/39f49c14.0, acceptance/suites/tests/certificate_authority/fixtures/certdir/39f49c14.r0, acceptance/suites/tests/certificate_authority/fixtures/certdir/4fe5e8ad.0, acceptance/suites/tests/certificate_authority/fixtures/certdir/4fe5e8ad.r0
These symlinks were most likely mistakenly added as part of 3d275466ac20bf991f6a129dd5ef4e261811c00a, and serve no purpose that I could find.
They were flagged by Debian's [Lintian](https://wiki.debian.org/Lintian) tool in the distro's own [puppetserver](https://tracker.debian.org/pkg/puppetserver) package.
=> (maint) drop absolute symlinks pointing to tmpdirs

resources/ext/cli_defaults/cli-defaults.sh.erb
Facter 4 was introduced in Puppet 7, so the facter.jar from Facter 3 is no longer needed.
=> Remove facter.jar from classpath

src/clj/puppetlabs/services/ca/certificate_authority_core.clj, test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj
The inventory is managed in several ways in the CA, including an inventory file, which records certificates, expiration periods and serial numbers. In the case where we want to get the actual certificate status, we don't want to use the inventory file. The liberator `exists` method was checking in both the filesystem and the inventory file for the certificate in question for a `GET` request.  This alters that behavior to only check the file system under those circumstances.
A test is added to demonstrate the behavior.
Resolves https://github.com/puppetlabs/puppetserver/issues/2851
=> (issue) only issue GET requests for concrete files

spec/fixtures/puppet-server-lib/puppet/jvm/execution_spec/echo_cwd.sh, spec/puppet-server-lib/puppet/jvm/execution_spec.rb, src/ruby/puppetserver-lib/puppet/server/execution.rb
If a `cwd` option is passed in Puppet::Util::Execution.execute, then pass it through to ShellUtils.executeCommand.
=> (SERVER-3051) Pass cwd through to ShellUtils

project.clj
Updated ezbake (via PR https://github.com/puppetlabs/ezbake/pull/629) build version from 2.5.5 to [2.6.2](https://repo.clojars.org/puppetlabs/lein-ezbake/2.6.2/), as this newer version includes the support for debian-12-x86_64.
This will be used to build puppetserver for debian-12-x86_64
=> (SERVER-3379): Updated ezbake build version to support debian-12-x86_64 build for puppetserver

src/ruby/puppetserver-lib/puppet/server/master.rb, test/integration/puppetlabs/services/master/master_service_test.clj
Previously, when using the compileCatalog method of
Puppet::Server::Master compilation would fail to serialize rich data.
This occurred because during serialization we introspect the
Puppet.context for the rich_data value (the setting itself defaults to
true & and strict now defaults to error, throwing an error when we
encounter an object that requires rich_data to serialize).
Normal catalog compilation works because the value of rich_data in the
Puppet.context is overridden by the caller of the serialization code for
indirected routes, using whatever is set in the environment and if unset
in the environment then falling back to the actually rich_data setting.
In the compileCatalog method however we do not use the indirected routes
for serialization, instead calling `to_data_hash` on the …
=> (PE-38948) Respect rich_data in compileCatalog

Gemfile, project.clj
Updated ezbake build version to support debian-12-x86_64 build for puppetserver in 7.x
=> (SERVER-3390): Updated ezbake build version to support debian-12-x86_64 build for puppetserver in 7.x

src/clj/puppetlabs/services/jruby/jruby_metrics_core.clj, src/java/com/puppetlabs/puppetserver/MetricsPuppetProfiler.java
We have triggered a nasty performance regression in the JVM with some of our Regex usage in the MetricsPuppetProfiler. Regardless of the performance regression, our Regex usage is unnecessary and unneedlessly expensive.
=> (PE-38408) Remove expensive Regexes from puppet profiler Java impl

project.clj
This reverts commit c24578da0e8567a36d0cca9bfe9cd5071a91093c.
This particular change will get a merge up commit from a [PR #2879](https://github.com/puppetlabs/puppetserver/pull/2879) for 7.x branch. Therefore I am reverting this in main.
This will fix https://jenkins-platform.delivery.puppetlabs.net/view/puppetserver/view/all/job/platform_puppetserver_puppetserver-mergeup_7.x/148/console pipeline
=> Revert "(SERVER-3379): Updated ezbake build version to support debian-12-x86_64 build for puppetserver"

project.clj
This reverts commit 76fbf1d61d2922f89364dae428356f4fae5e3843.
Yesterday, due to some confusion, I mistakenly thought that the changes related to the ezbake build version hadn't been merged from the 7.x branch, so I created a [PR #2889](https://github.com/puppetlabs/puppetserver/pull/2889) to revert the change, which was unnecessary.
I’d like to correct my mistake this time by reapplying the change.
=> Reapply "(SERVER-3379): Updated ezbake build version to support debian-12-x86_64 build for puppetserver"

resources/ext/cli/prune.erb
This adds a puppetserver subcommand to help garbage-collect old reports.
The default TTL is the same as the one used for PuppetDB (14d), where this garbage collection is done automatically.
=> (maint) Add puppetserver prune subcommand

dev-resources/regen_certs.rb, test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
In less than one year, the test CA certificates shipped as part of the testsuite will be expire.
This PR improves the `dev-resources/regen_certs.rb` script, so that it:
- Installs the regenerated certificates in the correct directories instead of the current working directory
- Regenerates test CA certificates in addition to HTTP certificates
In addition, it make a small adjustment to a CA unit test to remove hard-coded expiry dates
This change will also help with reproducibility testing where the date/time environment is made to vary.
=> (maint) Regenerate test CA certificates
