- documentation/configuration.markdown
- documentation/ssl_server_certificate_change_and_virtual_ips.markdown
This is linked with https://github.com/puppetlabs/puppet-docs/pull/423.
> DOC-1466 part 2/2

- README.md
- documentation/gems.markdown
- documentation/subcommands.markdown
@KevinCorcoran @jbondpdx Here's the subcommand docs plucked from master
> (SERVER-253) Documentation for subcommands

- documentation/subcommands.markdown
Edited the new subcommand page for Puppet Server.
> DOC-1488: Edit subcommand.markdown

- documentation/ssl_server_certificate_change_and_virtual_ips.markdown
Light edits to the ssl_server_certificate_change_and_virtual_ips page.
> Server 101 docs

- test/unit/puppetlabs/puppetserver/ruby/http_client_test.clj
Because the HTTP client library we are using is asynchronous, there
is a race condition that happens when an SSL handshake fails; you
may get a "connection closed" exception from Jetty before you get
the "SSLHandshakeException" that would eventually be thrown by
the HTTP client library.
When writing tests that involve intentional SSL failures, the
tests need to be tolerant of the different types of exceptions that
can occur.  This commit changes some tests that were not working
that way to be a bit more tolerant of the different possible
exception types, while still trying to be as specific as possible
and validate that the exception actually represents the
expected SSL failure.
> (MAINT) be more tolerant of ssl exceptions in tests

- Gemfile
- Gemfile.lock
- spec/puppet-server-lib/puppet/jvm/master_spec.rb
This is needed to maintain acceptance test parity with the new version
of MRI Puppet.
> (MAINT) Bump Ruby puppet version

- ezbake/config/bootstrap.cfg
- ezbake/config/conf.d/global.conf
- ezbake/config/conf.d/web-routes.conf
- ezbake/config/conf.d/webserver.conf
- ezbake/config/logback.xml
- project.clj
- resources/ext/ezbake.conf
This commit should bring the stable branch up to the newest EZBake-as-a-plugin.
> (SERVER-363) EZBake 0.2.3 support

- Gemfile
- Gemfile.lock
- project.clj
- resources/ext/ezbake.conf
This commit takes the changes that Nate made in the stable
branch for SERVER-363 (to add lein ezbake support to the
stable branch) and merges them up to the master branch.
> (MAINT) Merge SERVER-363 changes from stable to master

- documentation/puppet_conf_setting_diffs.markdown
- src/clj/puppetlabs/puppetserver/certificate_authority.clj
- src/clj/puppetlabs/services/config/puppet_server_config_core.clj
- test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
- test/unit/puppetlabs/services/config/puppet_server_config_core_test.clj
There is a fairly length description of this work in the ticket, but each commit has a brief explanation of what went on there.
> (SERVER-345) Fixup usages of cacert / localcacert in master

- documentation/known_issues.markdown
- documentation/release_notes.markdown
- documentation/tuning_guide.markdown
1.0.8 release notes and minor tuning guide edits.
> DOCS-465 release notes for Puppet Server 1.0.8

- .travis.yml
> (QENG-2034) Reduce hipchat noise associated with other branches.

- project.clj
This commit bumps the version to the 2.0.0 identifier.
> (SERVER-484) Update version to 2.0.0

- documentation/release_notes.markdown
This commit provides release notes for Puppet Server 2.0. Since the docs
toolchain is tracking the master branch for 2.0, and the stable branch
for 1.x, I just went ahead and replaced the 1.x release notes
altogether: They'll still be available in the /1/ version on
docs.puppetlabs.com.
> Release notes for Puppet Server 2.0.

- documentation/services_master_puppetserver.markdown
Changed "PE 3.7" to "PE 3.7 and later" on services_master_puppetserver page.
> Updating PE version info as relates to Puppet Server.

- documentation/index.markdown
- documentation/services_master_puppetserver.markdown
Added Tuning Guide links to index and services_master_puppetserver pages.
> SERVER-560: add Tuning Guide links to pages

- dev/user_repl.clj
- documentation/admin-api/v1/environment-cache.markdown
- src/clj/puppetlabs/puppetserver/ring/middleware/params.clj
- src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj
- src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj
- src/clj/puppetlabs/services/jruby/puppet_environments.clj
- src/clj/puppetlabs/services/protocols/jruby_puppet.clj
- src/clj/puppetlabs/services/puppet_admin/puppet_admin_core.clj
- test/integration/puppetlabs/services/jruby/puppet_environments_int_test.clj
- test/unit/puppetlabs/services/jruby/puppet_environments_test.clj
@cprice404 asked me to make any small changes required to #556 in the interest of getting it merged ASAP. I've simply corrected the version number in the docs.
> (SERVER-324) #556 + a docs fix

- acceptance/scripts/generic/testrun-full.sh
- acceptance/scripts/test-full-puppet3compat.sh
@nwolfe here ya go, I removed the "noprovision" scripts since they actually depend on additional post-suite behavior.
> (MAINT) Add simple beaker test run scripts.

- acceptance/README.md
- acceptance/lib/helper.rb
- acceptance/scripts/generic/testrun-full.sh
- acceptance/scripts/test-full-puppet3compat.sh
- acceptance/suites/puppet3_tests/020_backwards_compat/external_fact_output_test.rb
- spec/puppet-server-lib/puppet/jvm/master_spec.rb
Corresponding ci-job-config PR: https://github.com/puppetlabs/ci-job-configs/pull/283
> (MAINT) Upgrade puppet dependencies

- README_BRANCHING.md
- dev/user_repl.clj
- documentation/admin-api/v1/environment-cache.markdown
- documentation/configuration.markdown
- src/clj/puppetlabs/puppetserver/ring/middleware/params.clj
- src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj
- src/clj/puppetlabs/services/jruby/jruby_puppet_internal.clj
- src/clj/puppetlabs/services/jruby/jruby_puppet_schemas.clj
- src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj
- src/clj/puppetlabs/services/jruby/puppet_environments.clj
- src/clj/puppetlabs/services/protocols/jruby_puppet.clj
- src/clj/puppetlabs/services/puppet_admin/puppet_admin_core.clj
- test/integration/puppetlabs/services/jruby/jruby_puppet_internal_test.clj
- test/integration/puppetlabs/services/jruby/puppet_environments_int_test.clj
- test/unit/puppetlabs/services/jruby/puppet_environments_test.clj
* stable:
(docs) Minor revision of max-requests-per-instance description
(SERVER-659) Restore broken http client timeout settings
(SERVER-325) Add docs for max-requests-per-instance
(SERVER-657) Bump lein-ezbake dependency to 0.2.10
(MAINT) Updates to README_BRANCHING.md for 1.1/2.1 releases
(maint) Correct release number in docs
(SERVER-324) Add support for flushing a single environment
> (MAINT) Merge stable to master (2015-05-22)

- documentation/release_notes.markdown
based on initial notes from @dankreek. I left some as-is and filled in a few other descriptions.
> (docs) release notes for server 2.1.

- documentation/release_notes.markdown
- Remove old version number from title
- Remove unused link references
> (docs) Minor fixes in release notes

- documentation/puppetserver_vs_passenger.markdown
- documentation/release_notes.markdown
- project.clj
- src/clj/puppetlabs/services/ca/certificate_authority_core.clj
- src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj
- test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj
- test/unit/puppetlabs/services/jruby/jruby_puppet_core_test.clj
Ugh...  More conflicts than I'd like.  I really wish I started SERVER-297 on
the stable branch rather than the master so we didn't have to cherry-pick back
then merge it right back up.
> (maint) Merge up stable into master

- documentation/configuration.markdown
- documentation/release_notes.markdown
This should be merged once we have the go/no-go meeting, since merging it will post these notes to the docs website.
> 2.1.1 release notes

- documentation/release_notes.markdown
This includes all the changes from Jeff's original PR, plus some minor wording changes. We can merge it once we have the go/no-go meeting, since merging it will post the release notes to the docs site.
> 1.1.1 release notes

- .gitmodules
- dev/puppet-server.conf.sample
- documentation/configuration.markdown
- test/integration/puppetlabs/services/jruby/jruby_pool_int_test.clj
- test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
- test/unit/puppetlabs/services/ca/ca_testutils.clj
- test/unit/puppetlabs/services/jruby/jruby_puppet_core_test.clj
- test/unit/puppetlabs/services/jruby/jruby_testutils.clj
@cprice404's #638 didn't look quite right to me, so I had a quick crack at it myself.
> Merge stable into master

- acceptance/suites/tests/010-puppetserver-cli/subcommand/gem.rb
This will allow us to cleanup the Beaker command line a bit
> (MAINT) Add require statements to main helper

- acceptance/lib/helper.rb
> (maint) Bump puppet version to address acceptance failures

- project.clj
- src/clj/puppetlabs/services/config/puppet_server_config_core.clj
- src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj
- src/clj/puppetlabs/services/jruby/jruby_puppet_internal.clj
- src/clj/puppetlabs/services/jruby/jruby_puppet_schemas.clj
- src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj
- src/clj/puppetlabs/services/protocols/jruby_puppet.clj
- src/clj/puppetlabs/services/request_handler/request_handler_core.clj
- test/integration/puppetlabs/services/jruby/jruby_pool_int_test.clj
- test/integration/puppetlabs/services/jruby/puppet_environments_int_test.clj
- test/unit/puppetlabs/services/ca/certificate_authority_disabled_test.clj
- test/unit/puppetlabs/services/jruby/jruby_pool_test.clj
- test/unit/puppetlabs/services/jruby/jruby_puppet_agents_test.clj
- test/unit/puppetlabs/services/jruby/jruby_puppet_service_test.clj
- test/unit/puppetlabs/services/jruby/jruby_testutils.clj
- test/unit/puppetlabs/services/master/master_service_test.clj
- test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj
FWIW I believe this is the last change to the OSS code that I will need for metrics stuff, and also the last patch I intended for 1.x at all, so I think maybe we can consider that branch to be in maintenance mode as soon as this gets merged all the way up.
> (MAINT) merge 1.x to stable, 2015-08-18

- Gemfile
untested, so I'll keep an eye on CI as discussed...
> updates Gemfile to push us to beaker 2.24.0

- acceptance/suites/tests/authorization/default_rules.rb
Replace usages of '(hostname -f)' with the Beaker variable 'master'
since the former doesn't always return the FQDN on all platforms.
> (MAINT) Fix default_rules acceptance test

- documentation/compatibility_with_puppet_agent.markdown
- documentation/configuration.markdown
This commit includes the following documentation changes:
1) Adds a section to the `configuration.markdown` file, comparing some
legacy Puppet auth.conf settings to corresponding
trapperkeeper-authorization auth.conf settings.
2) Adds some distinctions related to the use of
trapperkeeper-authorization to the
`compatibility_with_puppet_agent.markdown` doc.
> (SERVER-812) Added auth.conf compatibility documentation

- documentation/release_notes.markdown
Quick fix for these; needs a followup.
> Fix 112 release notes.

- documentation/compatibility_with_puppet_agent.markdown
- documentation/config_file_auth.md
- documentation/config_file_ca.md
- documentation/config_file_global.md
- documentation/config_file_master.md
- documentation/config_file_puppetserver.md
- documentation/config_file_web-routes.md
- documentation/config_file_webserver.md
- documentation/configuration.markdown
This PR implements the developmental edits by @kayayarai. These edits should be prose-focused, not technical.
> edit of tk-auth changes to server docs

- acceptance/suites/tests/010-puppetserver-cli/subcommand/foreground.rb
- src/clj/puppetlabs/services/jruby/jruby_puppet_agents.clj
- src/java/com/puppetlabs/puppetserver/pool/JRubyPool.java
- src/java/com/puppetlabs/puppetserver/pool/LockablePool.java
- test/unit/puppetlabs/services/jruby/jruby_pool_test.clj
@camlow325 I was already working on this before I saw your last comments on the HTTP client nil patch, so I just went ahead and finished it.  I'll do another merge from 2.1.x to stable to include that after it's fixed/merged.
> (MAINT) merge up 2.1.x 2015 11 17

- documentation/install_from_packages.markdown
- documentation/release_notes.markdown
> (docs) Note puppet-agent 1.3.0 requirement.

- acceptance/suites/tests/010-puppetserver-cli/subcommand/gem.rb
so that we stop failing every time nokogiri is updated on stickler
> (MAINT) pin nokogiri version

- project.clj
We should wait to merge this until the 1.1.3 tests have passed.
> (MAINT) Bump to 1.1.4-SNAPSHOT for dev

- Gemfile
Reverts puppetlabs/puppet-server#809
> Revert "(MAINT) updates beaker pin in gemfile.  Removes HTTPParty"

- acceptance/suites/tests/010-puppetserver-cli/subcommand/gem.rb
There were no merge conflicts to resolve.
> Merge 2.1.x into stable

- Gemfile
- acceptance/README.md
- acceptance/scripts/external_ca/test_preserve_hosts.sh
- acceptance/scripts/generic/testrun.sh
Reverts puppetlabs/puppet-server#833
> Revert "(QENG-3181) Use beaker-hostgenerator instead of sqa-utils."

- Gemfile
- acceptance/README.md
- acceptance/scripts/external_ca/test_preserve_hosts.sh
- acceptance/scripts/generic/testrun.sh
Reverts puppetlabs/puppet-server#837
> (QENG-3181) Use beaker-hostgenerator instead of sqa-utils

- project.clj
- src/clj/puppetlabs/services/ca/certificate_authority_core.clj
This is blocked on a `comidi` release.
> (FOR REVIEW) (MAINT) update to clojure 1.7

- project.clj
This reverts commit 3ef68e0ecec1675b84e2707eb981252d672bd7b9.
> Revert "(MAINT) Exclude org.clojure from lein-ezbake"

- acceptance/suites/tests/00_smoke/puppetdb_integration.rb
The puppetdb integration test can assume that PuppetDB is already
installed and configured when testing PE.
> (SERVER-1089) Skip PuppetDB installation in PE

- test/unit/puppetlabs/services/config/puppet_server_config_service_test.clj
This commit adds some (gross) logic to the puppet-server-config-test
to eliminate a race condition that was allowing JRuby pool initialization
to happen on a background thread after the test finished executing.
The long-term fix is described in SERVER-1087.
> (SERVER-1090) Fix race condition in puppet-server-config-test

- test/unit/puppetlabs/services/jruby/jruby_testutils.clj
This commit just has a minor refactor to our JRuby test utilities
that is useful in downstream projects like pe-puppet-server-extensions
and pe-aio.
> (SERVER-1072) Add `with-puppet-conf-files` test utility

- dev-resources/puppetlabs/general_puppet/general_puppet_int_test/puppet.conf
- test/integration/puppetlabs/general_puppet/general_puppet_int_test.clj
This PR includes 2 commits to address feedback from PR #849 .
> (SERVER-885) Style fixups for #849

- test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj
This commit bumps up the maximum amount of time that the
`test-jruby-pool-not-full-during-code-id-generation` test will wait for
a catalog request to complete from 5 seconds to 10 seconds.  This test
frequently failed for me locally when run in isolation from the command
line because the first catalog request takes right around 5 seconds,
although subsequent ones were much faster (~100 milliseconds).
> (MAINT) Bump jruby-pool-code-id test timeout

- test/integration/puppetlabs/services/jruby/jruby_pool_int_test.clj
This commit uses a `with-test-logging` wrapper to suppress the
ERROR messages that appear in console output when running the
test-503 jruby pool int tests.
> (MAINT) Suppress ERROR messages from jruby-pool-int test output

- src/clj/puppetlabs/services/versioned_code_service/versioned_code_core.clj
- test/unit/puppetlabs/services/versioned_code_service/versioned_code_core_test.clj
Follow up PR to add semicolons to the allowed list of characters in a code-id
> (SERVER-1109) Add semicolon to allowed characters

- dev/user_repl.clj
- project.clj
- src/clj/puppetlabs/puppetserver/certificate_authority.clj
- src/clj/puppetlabs/services/jruby/jruby_puppet_internal.clj
- test/integration/puppetlabs/general_puppet/general_puppet_int_test.clj
- test/integration/puppetlabs/puppetserver/error_handling_int_test.clj
- test/integration/puppetlabs/services/jruby/jruby_pool_int_test.clj
- test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
- test/unit/puppetlabs/puppetserver/shell_utils_test.clj
- test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj
- test/unit/puppetlabs/services/jruby/jruby_interpreter_test.clj
- test/unit/puppetlabs/services/jruby/jruby_puppet_core_test.clj
- test/unit/puppetlabs/services/jruby/jruby_puppet_service_test.clj
- test/unit/puppetlabs/services/jruby/jruby_testutils.clj
- test/unit/puppetlabs/services/master/master_service_test.clj
- test/unit/puppetlabs/services/versioned_code_service/versioned_code_core_test.clj
- test/unit/puppetlabs/services/versioned_code_service/versioned_code_service_test.clj
This commit upgrades us to a new version of TK that includes
HUP support.  The internal API for TK's app-context changed
slightly so a few tests and the repl utils needed to be cleaned
up accordingly.
> (SERVER-1127) Upgrade to TK version w/HUP support

- acceptance/suites/tests/code_commands/code_scripts.rb
fixed up teardown
removed unneeded comments at the end.
> (SERVER-1118)Validate code id command

- project.clj
This comit bumps ther version of EZBake
due to a new release
> (maint) Bump EZBake version

- acceptance/README.md
This commit adds a section to the acceptance test docs describing how run
acceptance tests against local changes
> (MAINT) Update acceptance test docs

- src/clj/puppetlabs/services/master/master_core.clj
- src/clj/puppetlabs/services/master/master_service.clj
Extract the creation of the ruby request handler and the
clojure request wrapper, as well as their use in the creation of
the root-routes handler, into a separate function,
construct-root-routes-handler.
> (MAINT) Add construct-root-routes-handler fn

- acceptance/lib/helper.rb
- dev-resources/puppetlabs/services/jruby/jruby_pool_int_test/logback-test-restart-comes-back.xml
- dev/puppet-server.conf.sample
- spec/puppet-server-lib/puppet/jvm/master_spec.rb
- src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj
- src/clj/puppetlabs/services/legacy_routes/legacy_routes_service.clj
- src/clj/puppetlabs/services/master/master_core.clj
- src/clj/puppetlabs/services/master/master_service.clj
- test/integration/puppetlabs/puppetserver/testutils.clj
- test/integration/puppetlabs/services/jruby/class_info_test.clj
- test/integration/puppetlabs/services/jruby/jruby_pool_int_test.clj
- test/integration/puppetlabs/services/master/environment_classes_int_test.clj
- test/unit/puppetlabs/services/master/master_core_test.clj
@camlow325 This PR merges-down `master` into `stable` to pick up your recent changes of the Puppet submodule and such.
> Mergedown master again

- documentation/index.markdown
- documentation/restarting.markdown
@gguillotte here's a rough cut at this stuff.
If you're good with these as 'pre-docs' then we can merge this and I'll assign the ticket back to you so that you can get them into a state you're happy with?
> (SERVER-1084) pre-docs for initial HUP support

- documentation/config_file_puppetserver.md
- documentation/puppet-api/v3/static_file_content.md
> (doc) Add static_file_content API and config docs.

- test/integration/puppetlabs/services/jruby/jruby_pool_int_test.clj
This commit adds stack traces for all running threads to the assertion
message which is displayed when a jruby-pool-int-test encounters a time
out.
> (SERVER-1148) Dump thread traces when a jruby-pool-int-test times out

- documentation/puppet-api/v3/static_file_content.md
Based on commit 1938ce4 by @camlow325 on the environment_classes PR.
> (doc) Note auth details for static_file_content endpoint

- documentation/_puppetserver_nav.html
- documentation/config_file_logbackxml.md
- documentation/configuration.markdown
This was done in parallel to PR #874 and should be better integrated with its work. I'm making this PR for preliminary review.
> (docs) Basic Logback docs

- documentation/_puppetserver_nav.html
- documentation/restarting.markdown
Edits to the SIGHUP predocs by @cprice404. Resolves SERVER-1084 and SERVER-1192.
> (doc) Edit SIGHUP predocs.

- acceptance/lib/helper.rb
@joshcooper @nathanielksmith @camlow325
> (maint) Bump puppet submodule to stable latest

- documentation/puppet-api/v3/environment_classes.md
Reformats and reorganizes the new `environment_classes` API pre-docs.
- Breaks the list of differences with the resource type API into a section with subsections.
- Adjusts language for clarity and style for consistency.
- Adds links to other documentation.
CC @camlow325
> (doc) Revise the environment_classes API pre-docs.

- project.clj
Waiting on puppet agent package pipeline to finish.
> [DNM] (SERVER-1165) Bump version to 2.3.0

- documentation/restarting.markdown
Apply edits suggested by @kayayarai.
> (doc) Apply developmental edits to the HUP doc.

- documentation/install_from_packages.markdown
- documentation/release_notes.markdown
Updates and provides more context for notes on Puppet Server's dependency on Puppet Agent.
> (doc) (DOCUMENT-522) Improve Puppet Agent dependency notes.

- project.clj
This commit bumps the version to 2.3.1 for release
> (SERVER-1220) Bump from snapshot for 2.3.1 release

- project.clj
Bump the version after 2.3.1 release
> (MAINT) Bump to 2.3.2-stable-SNAPSHOT

- documentation/release_notes.markdown
- Adds a release notes section for Server 2.3.1.
- Adds bug fix and known issue release notes for SERVER-1215.
> (doc) Add 2.3.1 release notes.

- documentation/puppet-api/v3/environment_classes.md
> (doc) Apply developmental edits by @kayayarai to environment classes API.

- acceptance/lib/helper.rb
- spec/puppet-server-lib/puppet/jvm/master_spec.rb
Bump to puppet-agent 1.4.1 and puppet 4.4.1.
> (maint) Bump to puppet agent 1.4.1

- documentation/config_file_puppetserver.md
- documentation/puppet-api/v3/static_file_content.md
> (doc) Apply developmental edits by @kayayarai to static catalog docs.

- acceptance/README.md
Significant surgery to move sections around, followed by a thousand smaller cuts to tweak language, style, etcetera.
> (MAINT) Update README.md for easier consumption

- src/clj/puppetlabs/puppetserver/certificate_authority.clj
Previously, an error was logged if the configured CSR Attributes
file path or the configured Custom Trusted OID Mappings file
path failed an fs/file? check. However, Puppet has a default
value for both of these settings, meaning the error would be
logged on startup unless the user specifically adds those
configuration files.
This removes the logging of that error.
This is what we were originally doing with the `csr-attributes-file`, and I realized why when I added these changes to pe-p-s-e and and it started spewing errors about not loading these files.
> (MAINT) Remove csr attrs and oid error logging

- acceptance/lib/helper.rb
This is a copy pasta from pe-p-s-e, because we want to be able to use the method from inside puppet-server as well as from inside pe-p-s-e.  I've tested that having the method present in both puppet-server and pe-p-s-e did not break file-sync tests.
> (MAINT)Adds the https_request method from pe-p-s-e

- acceptance/README.md
Add a few missing `bundle exec` invocations. Thanks @melissa
> (MAINT) Use bundle exec consistently

- documentation/config_file_auth.md
Once more, with ~~feeling~~ a master branch target per @KevinCorcoran.
CC @nathanielksmith, this is the same as PR #1015.
> (SERVER-1252) Document new tk-auth allow/deny options

- acceptance/lib/helper.rb
Bumps agent to
http://builds.delivery.puppetlabs.net/puppet-agent/9c3d884f367a505e5a01224d16d572e079b574fe
> (MAINT) bumps agent sha

- documentation/config_file_puppetserver.markdown
> (doc) Fix order of content in puppetserver.conf doc

- acceptance/lib/helper.rb
This is a continued effort from PR #1046.  @kurtwall made some comments, and I made some minor updates to those comments.
> (SERVER-1303) Adds method that merges TK Auth rules into existing config

- documentation/dev_trace_func.markdown
... in example output within the "Tracing Code Events" doc.
> (doc) Remove hyphen from puppetserver-release.jar

- resources/ext/config/request-logging.xml
only conflict was the ezbake version in the project.clj.
> (MAINT) merge up from 1.x to stable, 2016 05 09

- documentation/install_from_packages.markdown
Resolves DOC-2714. CC @melissa
> (doc) Add list of packaged platforms.

- documentation/index.markdown
- Add static file content API endpoint doc.
- Add new auth and logging docs.
- Convert headings to sentence case per recent changes to company style.
- Structure introduction and usage docs into sections.
- Add note pointing to PE's docs.
> (doc) Update index.

- test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj
> (maint) Update certificate-status-test content-type assertion to check for charset

- README.md
-   Add more links to documentation.
-   Note `puppet-agent` dependency, and Ruby 2.1 dependency for Puppet 4.
-   Note `trapperkeeper`.
-   Update copyright year and company name.
> (maint) Update and edit repo README.

- acceptance/config/beaker/jenkins/ubuntu-1604-x86_64-mdca-a.cfg
- acceptance/config/beaker/jenkins/ubuntu-1604-x86_64-mdca.cfg
- acceptance/lib/helper.rb
* Update acceptance test helper to say ubuntu 16.04 uses systemd
* Add beaker configs for ubuntu 16.04 (don't think they are used in jenkins, but they are useful for running tests locally)
> (maint) Fix acceptance tests for xenial

- documentation/puppet-api/v3/environment_classes.markdown
> (doc) Fix and update links in environment_classes doc

- README.md
- documentation/index.markdown
- documentation/install_from_packages.markdown
Only conflicts were in the README, and I kept mostly the stuff in stable since @gguillotte had recently done some fixes there.
> (maint) merge up stable to master

- acceptance/lib/helper.rb
like @camlow325 said in the first place
> (MAINT) changes the hup helper to use pgrep -f 

- acceptance/lib/helper.rb
- project.clj
- resources/ext/ezbake.conf
to what are included in puppet-agent 1.5.0, and bump PUPPET_BUILD_VERSION in the acceptance helper to match.
Also change the puppetserver version from 2.4.0-master to 2.4.0-stable.
> (SERVER-1334) Bump puppet and hiera versions

- project.clj
Blocked on https://github.com/puppetlabs/puppetserver/pull/1095.
> [DO NOT MERGE] (SERVER-1336) Bump version to 2.4.1-SNAPSHOT for post release development

- Gemfile
> (SERVER-1354) Updates beaker and host gen pins

- ezbake/system-config/services.d/bootstrap.cfg
This commit adds the jruby-pool-manager-service to the ezbake bootstrap file
> (SERVER-1163) Add pool manager service to bootstrap

- acceptance/lib/helper.rb
This adds a 30s sleep to the hup helper.
> (MAINT) Add 30s sleep to hup

- project.clj
DO NOT MERGE UNTIL COORDINATING IN HIPCHAT!
This commit is based on #1166 and needs to come in *after*
* #1166 has been merged
* #1166 has gone through CI
* We've validated that the final packages/artifacts for 2.5.0 are in the appropriate places
> (FOR REVIEW) (SERVER-1426) update version for next dev cycle

- Gemfile
2.49.0 has a nice fix for JSON output that I'd like to use.
> (MAINT) Update beaker pin

- documentation/index.markdown
- documentation/puppet-api/v3/environment_classes.markdown
- documentation/status-api/v1/services.markdown
This commit provides some pre-docs for the status endpoint.
> (SERVER-1505) Pre docs for the status endpoint

- acceptance/lib/helper.rb
This commit updates the https_request test helper to include an options
hash, which initially can be used to change the read timeout for https
requests from the default of 60.
> (maint) Update https_request test helper to include options

- documentation/_puppetserver_nav.html
- documentation/bootstrap_upgrade_notes.markdown
- documentation/config_file_logbackxml.markdown
- documentation/config_file_puppetserver.markdown
- documentation/config_logging_advanced.markdown
- documentation/external_ca_configuration.markdown
- documentation/install_from_packages.markdown
- documentation/puppetserver_vs_passenger.markdown
- documentation/release_notes.markdown
- documentation/services_master_puppetserver.markdown
-   Add 2.6.0 release notes.
-   Update Logback references.
> (docs) Server 2.6.0 notes and updates

- test/integration/puppetlabs/puppetserver/testutils.clj
pe-puppet-server-extensions has some updates to our test helper
functions that mean duplicated code between the two repos. This commit
moves over some of the changes to the catalog related functions so that
they can be removed from pe-pse.
> (SERVER-709) Port test functions from pe-pse

- Gemfile
@haus I don't need your custom tmpdir change in `stable` / `master`, do I?
> (MAINT) merge from 1.x to stable 2016-10-03

- project.clj
- resources/ext/ezbake.conf
Also removes the pre-start actions since ezbake takes care of the rundir for us
> (MAINT) Update ezbake to 1.1.2

- Gemfile
> Add location_for method to Gemfile.

- Gemfile
> Merge 0.1.x up into stable branch.

- Rakefile
This commit adds some rake tasks that make it easier to run smoke tests on a specific package version, or to do an ezbake build and then run smoke tests against that.
> (MAINT) Bake'n'beak

- documentation/puppet-api/v3/environment_classes.markdown
- documentation/restarting.markdown
This commit includes some documentation updates related to the service
reload feature.
> (SERVER-1582) Add some service reload docs

- resources/ext/cli/gem.erb
> (MAINT) merge down from master

- project.clj
Everything contained in this branch at this point has passed CI. Latest good build is [here](https://jenkins-master-prod-1.delivery.puppetlabs.net/job/platform_puppetserver_integration-system_no-conditional_smoke-stable/66/)
> (SERVER-1675) Bump version to 2.7.2 for release

- src/clj/puppetlabs/puppetserver/cli/subcommand.clj
Previously, if some kinds of errors were thrown during the processing of
a CLI subcommand, e.g., a Prismatic schema error when parsing content
from the puppetserver.conf file, the resulting error displayed on the
command line had no indication of what the real error was.
This commit adds some extra error handling to the `run` function in the
CLI subcommand which, for cases like the schema error, allows the
original upstream exception passed through to the CLI output.  This
would allow the user to see more specific information about the root
cause behind the error.
> (SERVER-1690) Improve CLI subcommand error handling

- test/integration/puppetlabs/puppetserver/testutils.clj
Change the puppetserver testutils to allow the sources of the temporary
puppet conf files set up by with-puppet-conf-files to be java.net.URLs
in addition to strings or java.io.Files, and to copy the sources to the
destination files by wrapping the sources in an input stream, which
works even when the source is a URL that points to a classpath resource
contained in a jar.
Together, these changes allow the conf file sources passed to
with-puppet-conf-files to be classpath resources distributed in a jar,
instead of requiring them to be files.
> (PE-19130) Allow puppet conf file to be resources.

- project.clj
This commit upgrades the i18n plugin version from 0.4.3 to 0.5.1.
> (SERVER-1712) Upgrade to i18n 0.5.1

- documentation/dev_running_from_source.markdown
This commit adds some docs on running a source based PuppetDB instance
with a source based Puppet Server instances. I also added some
clarification around invoking the Puppet Agent that I found helpful
when setting up a dev environment.
> (MAINT) Add PuppetDB info to the running from source docs

- acceptance/suites/puppet3_tests/010_hello_world/testtest.rb
> (maint) Test puppet 3 compat against Puppet 4/5

- acceptance/suites/tests/metrics/collect_default_metrics.rb
Previously, the collect_default_metrics test would, via the grafanadash
module, try to setup a graphite webserver on port 80.  When run in the
PE Puppet Server Extensions pipeline, this test would fail because
Apache would be unable to listen on port 80 since the PE console already
would have claimed the port.
This commit changes the test to have the graphite web server hosted on
port 50000 in order to avoid the conflict with the PE console.
> (SERVER-1788) Use different graphite port in collect_default_metrics

- test/unit/puppetlabs/services/puppet_profiler/puppet_profiler_core_test.clj
This commit reworks the test-profiler-via-ruby test to call .terminate()
when finished using the ScriptingContainer that it creates.  The test
also calls `create-scripting-container` instead of
`empty-scripting-container` to create the container, ensuring that more
of the common initialization logic from jruby-utils is utilized.
> (MAINT) Cleanup scripting container in test-profiler-via-ruby test

- documentation/config_file_metrics.markdown
- documentation/index.markdown
- documentation/puppet_server_metrics.markdown
- documentation/sample-puppetserver-metrics-dashboard.json
-   Pull and revise PE metrics docs for open source metrics.
-   Add Grafana dashboard JSON.
-   Document `metrics.conf`.
> (SERVER-1830) Add metrics docs.

- acceptance/suites/upgrade_tests/10_upgrade.rb
We need to have the latest version of the puppet agent installed on all
agent systems to ensure that the systems under test are the same version
as the tests being run.
> (maint) Upgrade puppet agents for upgrade acceptance testing

- Rakefile
- acceptance/lib/helper.rb
* merge-up from 5.0.x
* update pin from `5.0.x` to `master`
> (server-1870) add ci job for automatically bumping puppet submodule commit

- acceptance/suites/tests/00_smoke/puppetdb_integration.rb
* 5.0.x:
(maint) Switch java version on Debian 8 upgrade tests
(SERVER-1894) install `apt-transport-https` on Debian for PDB
(maint) update puppet submodule version and pins
>     Merge branch '5.0.x'

- Rakefile
- spec/puppet-server-lib/puppet/jvm/master_spec.rb
removed the conflicts arising in the submodule and acceptance puppet pins.
> (maint) Merge remote-tracking branch 'upstream/5.0.x'

- acceptance/config/beaker/options.rb
Reverts puppetlabs/puppetserver#1488
> Revert "(maint) Manually bump puppet SHA and version"

- acceptance/config/beaker/options.rb
* picks up new puppet version that fixes issue regarding inaccessible method in
i18n setup for modules
> (SERVER-1912) update pup submodule to fix missing method

- project.clj
Move the version up to the next snapshot version
> (MAINT) bump version to next snapshot

- project.clj
Reverts puppetlabs/puppetserver#1509
> Revert "(RE-8994) Update to ezbake 1.6.0"

- documentation/puppet_conf_setting_diffs.markdown
> (DOCUMENT-729) Note static_catalogs setting behavior.

- Rakefile
The puppet-agent pipeline writes a JSON file with only the data about
passing SHAs when it finishes. Since that data is no longer exposed as
params as part of Jenkins' built-in API, we should read that file
instead.
> (maint) Get puppet and PA versions from written file, not Jenkins API

- Rakefile
- dev-resources/puppetlabs/services/master/tasks_int_test/echo
- dev-resources/puppetlabs/services/master/tasks_int_test/hello_world
- dev-resources/puppetlabs/services/master/tasks_int_test/warn_echo_and_error
- locales/puppetserver.pot
- project.clj
- src/clj/puppetlabs/services/legacy_routes/legacy_routes_service.clj
- src/clj/puppetlabs/services/master/master_core.clj
- src/clj/puppetlabs/services/master/master_service.clj
- test/integration/puppetlabs/general_puppet/general_puppet_int_test.clj
- test/integration/puppetlabs/services/jruby/tasks_test.clj
- test/integration/puppetlabs/services/master/tasks_int_test.clj
- test/unit/puppetlabs/services/master/master_core_test.clj
> Merge 5.1.x at e48e4050 into master

- documentation/release_notes.markdown
Package metadata and filenames changed with Server 5.1.3. Note this in the release notes for Server 5.1.3.
> (DOC-3372)(CPR-429) Note packaging change.

- project.clj
This brings the git history of our upcoming release into our main development branches and prepares for our next release.
> (maint) Merge up release branch and prepare for add'l 5.1.x development

- acceptance/lib/helper.rb
This reverts commit 32e8328a918e5fd2f85be823d377eddd4c66a532.
> Revert "(SERVER-1972) Support Debian 9 in test setup"

- project.clj
Both resolve to the same location but this one is more accurate. @haus I believe this is the appropriate jargon
> (maint) Make artifactory url gooder

- Gemfile
- Rakefile
- acceptance/scripts/external_ca/retest.sh
- acceptance/scripts/external_ca/test_preserve_hosts.sh
- acceptance/scripts/generic/testrun.sh
We don't believe a url redirect will work so I get to manually change all of the urls.
> (maint) Replace stickler with artifactory

- .travis.yml
- ext/travisci/test.sh
To reduce maintenance costs and ensure that all new branches are tested, here I remove the branches from the .travis.yml file.
> (maint) Remove branches from travis

- spec/puppet-server-lib/puppet/jvm/puppet_config_spec.rb
- src/ruby/puppetserver-lib/puppet/server/logger.rb
- src/ruby/puppetserver-lib/puppet/server/puppet_config.rb
* origin/2.6.x:
(SERVER-1922) Defer settting Puppet log level
(SERVER-1922) Set puppet log level from logback
> (maint) Merge 2.6.x into 2.x

- project.clj
This brings in the commits for the 5.1.5 and retargets development for the 5.1.x branch towards 5.1.6.
> (SERVER-2086) Finalize 5.1.5 release branch work

- project.clj
- resources/ext/build-scripts/gem-list.txt
- resources/ext/config/conf.d/puppetserver.conf
This adds the JrJackson gem and the new gem directory from puppet-agent.
> (SERVER-2098) (SERVER-2133) Multijson and agent shared gem dir

- project.clj
Built successfully at builds.delivery.puppetlabs.net/puppetserver/5.1.6.SNAPSHOT.2018.03.09T1056
> (RE-10172) Update to ezbake 1.8.1

- acceptance/suites/tests/00_smoke/puppetdb_integration.rb
This commit updates the PuppetDB integration test to make it more robust
and easier to diagnose:
- The test now handles dataset timestamps that return as `null`.
- The test retries the query for updated data up to three times. This
mitigates failures due to race conditions by giving PuppetDB extra
time to process commands into the database.
- An informative message is printed upon failure that lists which datasets
were missing or not updated along with which logs to check for failures.
> (SERVER-2129) Improve failure message for PuppetDB test

- acceptance/suites/tests/00_smoke/puppetdb_integration.rb
This commit makes some modifications to the PuppetDB integration test
in order to reduce transient failures:
- Time prior to the Puppet Agent run is measured by executing the `date`
command on the master node instead of Ruby's Time.now in the Beaker test.
This cancels out clock drift between the node driving the test and the node
where the test is executing.
- The timestamp taken from `date` is included in the error message so
that it can be compared against log files.
- A one second sleep is added before retrying the test query. This gives
PuppetDB some time to catch up on command processing.
Ref. commit 361b880
> (SERVER-2129) Improve timing of PuppetDB test

- documentation/release_notes.markdown
> (DOC-3532) Add Server 5.3.1 release notes.

- documentation/release_notes.markdown
This assumes SERVER-2237 lands in time for release.
> Add release notes for Server 5.3.4

- Gemfile
- Rakefile
- ext/build_defaults.yaml
also, use Artifactory as gem source
> (RE-10177) Use packaging as a gem

- Gemfile
- Rakefile
- ext/build_defaults.yaml
This reverts commit ee0f3a4ed1461b210fc36ab13ad0183cde6a435b, reversing
changes made to 5074a078e49edebd26436c4608c9b2b1e7875fcd.
Accidentally targeted the wrong branch.
> Revert "Merge branch '2.6.x' into 5.1.x"

- Gemfile
- Rakefile
- ext/build_defaults.yaml
Conflicts:
- Gemfile
- Rakefile
- ext/build_defaults.yaml
I think these resolved these correctly. It'd be nice to get @mwaggett to check it out though.
> (maint) Merge branch '2.x' into '5.1.x'

- Rakefile
- acceptance/lib/helper.rb
- acceptance/scripts/generic/testrun.sh
- spec/puppet-server-lib/puppet/jvm/master_spec.rb
> (maint) Exclude packaging when running JRuby specs

- Rakefile
- acceptance/lib/helper.rb
- acceptance/scripts/generic/testrun.sh
This also updates ezbake to the latest version.
> Merge 2.6.x -> 2.x

- dev/puppetserver.conf
- resources/ext/config/conf.d/puppetserver.conf
- src/clj/puppetlabs/puppetserver/certificate_authority.clj
- test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
- test/unit/puppetlabs/services/ca/ca_testutils.clj
- test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj
> (SERVER-2278) Add allow-subject-alt-names setting to puppetserver.conf

- docker/ci/build
This updates the build script to build containers in the correct
namespace for publishing to dockerhub.
> (CPR-600) Auto-publish to dockerhub

- docker/ci/build
- docker/puppetserver-standalone/spec/dockerfile_spec.rb
- docker/puppetserver/spec/dockerfile_spec.rb
depends on https://github.com/puppetlabs/puppet_docker_tools/pull/26
> (maint) unravel docker-api gem from spec tests

- docker/ci/build
- docker/puppetserver-standalone/spec/dockerfile_spec.rb
- docker/puppetserver/spec/dockerfile_spec.rb
Required to pickup Docker build testing changes from #1794
> Mergeup 5.3.x to 6.0.x

- documentation/release_notes.markdown
> Revise release note.

- Rakefile
This is a cherry pick of 952326810a8f961d3e0e0c09ba89bc0bb8f99ee4
> (maint) Add back package:bootstrap and package:implode for compatibility

- documentation/install_from_packages.markdown
Packages exist: https://apt.puppet.com/pool/stretch/puppet6/p/puppetserver/
> (docs) Add Stretch to server install doc.

- project.clj
- resources/ext/build-scripts/mri-gem-list.txt
This also updates the clj-parent version to 2.3.2
> Merge 5.3.x -> 6.0.x

- documentation/install_from_packages.markdown
This commit updates the instructions for setting up the Puppet CA in
Puppet 6.
> (SERVER-2347) Fix package installation docs

- documentation/configuration.markdown
> (SERVER-2353) Remove another ca.conf deprecation note

- ext/build_defaults.yaml
Conflicts were resolved by taking the changes from 5.1.x.
> Merge 5.1.x -> 5.3.x

- Gemfile
- acceptance/lib/helper.rb
- acceptance/scripts/generic/testrun.sh
- acceptance/suites/pre_suite/foss/70_install_puppet.rb
Update to beaker 4 and beaker-puppet 1, along with some minor updates to the pre-suites to fix Windows installs.
> (SERVER-2374) Update to beaker 4

- documentation/http_certificate.md
- documentation/http_certificate_request.md
- documentation/http_certificate_revocation_list.md
- documentation/http_certificate_status.md
per ticket: https://tickets.puppetlabs.com/browse/SERVER-2333
> Files moved from puppet-docs repo.

- documentation/tuning_guide.markdown
This commit adds information on ReservedCodeCache to the main docs.
> (DOC-3822) Add information on ReservedCodeCache

- acceptance/suites/tests/authorization/default_rules.rb
- dev/dev_tools.clj
- ezbake/config/conf.d/auth.conf
```
Conflicts:
- dev/dev_tools.clj
```
> (maint) Merge '5.3.x' into '6.0.x'

- acceptance/suites/tests/authorization/default_rules.rb
- dev/dev_tools.clj
- ezbake/config/conf.d/auth.conf
> (maint) Merge '6.0.x' into 'master'

- resources/ext/build-scripts/mri-gem-list.txt
> (maint) Merge branch '5.3.x' into '6.0.x'

- azure-pipelines.yml
- Ensures .gitattributes apply properly when changes are made
> (maint) Clean source repo on Azure checkout

- src/clj/puppetlabs/puppetserver/certificate_authority.clj
- test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
- test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj
Also, remove extra comma in the sentence.
> (maint) String resources should not end with ","

- documentation/dev_running_from_source.markdown
Add details and solutions to the problems I encountered while trying to set up a Puppetserver development envionment
> Add development environment gotchas and solutions

- azure-pipelines.yml
- docker/ci/build.ps1
Cleanup performed these actions... 
```
Pruning Containers
Total reclaimed space: 0B
Found puppet/puppetserver images:
6.0.3 24f02d3d1018 2019-02-09 00:09:58 +0000 GMT
6.2.0 05561b505e92 2019-02-08 23:40:53 +0000 GMT
6.1.0 6e2f14d72eb3 2019-01-18 17:26:21 +0000 GMT
6.0.2 abe0bf55ea46 2019-01-11 17:43:15 +0000 GMT
Filtering removal candidates...
Removing Old puppet/puppetserver Image 6.1.0 (6e2f14d72eb3) Created On 01/18/2019 17:26:21
Untagged: puppet/puppetserver:6.1.0
Deleted: sha256:6e2f14d72eb33c07fb1a43fbdf7ba6d47f76b4d9979998c92fb37aca98196bbd
Deleted: sha256:217bec8878b501b6a11099e931aa1724a17c178bd46ae9c264090cb45bb81842
Deleted: sha256:ed0ff3e9f2f8d279aec3aa4e8a719f8ae00d7a1b3f95e165b15c72b986b08537
Deleted: sha256:a098c072280acd9d69485eab808219fd81f5870720cbe1d18a218ed61d56e472 …
```
> (maint) Cleanup Azure container leftovers smarter

- documentation/release_notes.markdown
> (docs) correction to release date 5.5.7

- documentation/release_notes.markdown
correction to the release date
> (docs) date fix on 6.0.3 rel notes

- src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj
- src/clj/puppetlabs/services/master/master_core.clj
- src/clj/puppetlabs/services/protocols/jruby_puppet.clj
- src/java/com/puppetlabs/puppetserver/JRubyPuppet.java
- src/ruby/puppetserver-lib/puppet/server/master.rb
- test/unit/puppetlabs/services/master/master_core_test.clj
> Add new catalog endpoint

- src/clj/puppetlabs/puppetserver/certificate_authority.clj
- test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj
Currently fails a few tests.
See https://tickets.puppetlabs.com/browse/SERVER-2370
> Add details to certificate status endpoint

- docker/ci/build.ps1
For consistency with our other near-copies of this file.
> (MAINT) Update container test for PE versions

- spec/puppet-server-lib/puppet/jvm/compiler_spec.rb
- src/clj/puppetlabs/services/master/master_core.clj
- src/ruby/puppetserver-lib/puppet/server/compiler.rb
- test/unit/puppetlabs/services/master/master_core_test.clj
This is built on builds.d.pl.net as 6.2.2.SNAPSHOT.2019.03.01T1538
> (SERVER-2457) save compile artifacts

- acceptance/suites/tests/catalog/v4_catalog.rb
To enable storeconfigs for catalogs we need to set it manually in the
puppet.conf, however we only want to do this if PDB is installed.
> (SERVER-2462) Don't force storeconfigs

- docker/Makefile
- docker/puppetserver-standalone/README.md
- docker/puppetserver/README.md
Contents copied from existing documentation on DockerHub and new
"Configuration" section added.
Update the documentation when we update the images on DockerHub.
> (MAINT) Add container README

- project.clj
Update in preparation for the 6.3.0 release.
> (maint) Update version to 6.3.0-SNAPSHOT

- documentation/configuration.markdown
https://tickets.puppetlabs.com/browse/DOCUMENT-852
> (DOCUMENT-852) Clarify which puppet.conf sections puppetserver uses

- acceptance/suites/pre_suite/upgrade/10_install_puppet.rb
Previously we depended on a beaker-puppet helper to install the PC1 repo
packages. With those packages moving to our new archives this helper no
longer works for installing PC1.
This inlines the relevant old helper bits hardcoded to the new archive url.
> (maint) Inline PC1 repo installation

- documentation/puppet-api/v3/compile.markdown
- src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj
- src/clj/puppetlabs/services/master/master_core.clj
- src/clj/puppetlabs/services/protocols/jruby_puppet.clj
- src/java/com/puppetlabs/puppetserver/JRubyPuppet.java
- src/ruby/puppetserver-lib/puppet/server/master.rb
- test/unit/puppetlabs/services/master/master_core_test.clj
I think this, minus cleaning up commit messages is ready to do. Hopefully this works with what you're working on @Magisus.
> (SERVER-2541) compile endpoint - clojure work

- acceptance/suites/pre_suite/upgrade/10_install_puppet.rb
Uses code from 0b26a8639 to finish work started (and described more
fully in) a116edeb8.
> (maint) Extend `server` config changes to upgrades

- acceptance/suites/pre_suite/puppet5_compat/80_configure_puppet.rb
See 9a25e2580054f3b2cd9111bd7b281ab5e7b1916e for more info/links.
> (maint) Extend server settings in puppet.conf to compat tests

- project.clj
Reverts puppetlabs/puppetserver#2101
> Revert "(maint) Don't override leiningen's default repositories by default"

- acceptance/suites/pre_suite/upgrade/10_install_puppet.rb
> (SERVER-2586) Merge branch '6.0.x' into '6.3.x'

- acceptance/suites/pre_suite/upgrade/10_install_puppet.rb
>  (SERVER-2571) Merge branch '6.3.x' into 'master'

- documentation/release_notes.markdown
6.5 release notes. OK to merge today. After merge, please let me know the SHA for the publishing pipeline. Thank you!
> (docs) Server 6.5 release notes

- .travis.yml
- Rakefile
- dev/install-test-gems.sh
- project.clj
This had conflicts around the project.clj refactors, @justinstoller can you double check those changes please?
> Merge 6.0.x -> 6.3.x

- docker/puppetserver-standalone/Dockerfile
Hoping that maybe 18.04 will be less prone to dns issues than 16.04.
> (maint) Move to ubuntu 18.04

- src/clj/puppetlabs/services/ca/certificate_authority_core.clj
Note that this is just a trivial mitigation -- it does not prevent
corruption that might result from a server crash while writing, nor
does it prevent simultaneous crl read operations from seeing partial
updates.
To fix those, we might rework the code to make the updates to a temp
file while holding the lock, and then use Files/move to ATOMIC_MOVE
the update into place.
> (SERVER-115) Avoid potential corruption by serializing crl writes

- src/ruby/puppetserver-lib/puppet/server/master.rb
https://github.com/puppetlabs/puppet-resource_api/pull/187 implemented a dedicated function in the Resource API to load and return all transport schemas. Use it here now.
> (FM-8553) use the dedicated rsapi function

- src/clj/puppetlabs/services/ca/certificate_authority_core.clj
There was a conflict, which I resolved and tested the ca integration test that I thought best tested the change. However, I've left travis to run the full suite.
Original commit message:
Note that this is just a trivial mitigation -- it does not prevent
corruption that might result from a server crash while writing, nor
does it prevent simultaneous crl read operations from seeing partial
updates.
To fix those, we might rework the code to make the updates to a temp
file while holding the lock, and then use Files/move to ATOMIC_MOVE
the update into place.
> (SERVER-2641) Backport SERVER-115

- documentation/release_notes.markdown
one lonely missing space messing up the bullet formatting
> fix formatting typo

- locales/puppetserver.pot
- src/clj/puppetlabs/services/ca/certificate_authority_core.clj
- test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj
Important conflict in `src/clj/puppetlabs/services/ca/certificate_authority_core.clj`.
> Merge 5.3.x -> 6.3.x

- ext/thread_test/Gemfile
- ext/thread_test/bootstrap.cfg
- ext/thread_test/environments/funky/manifests/init.pp
- ext/thread_test/environments/funky/modules/threader/hiera.yaml
- ext/thread_test/environments/funky/modules/threader/lib/puppet/functions/threader/doit.rb
- ext/thread_test/environments/funky/modules/threader/lib/puppet/parser/functions/oldschool.rb
- ext/thread_test/environments/funky/modules/threader/metadata.json
- ext/thread_test/environments/production/manifests/init.pp
- ext/thread_test/environments/production/modules/threader/hiera.yaml
- ext/thread_test/environments/production/modules/threader/lib/puppet/functions/threader/doit.rb
- ext/thread_test/environments/production/modules/threader/lib/puppet/parser/functions/oldschool.rb
- ext/thread_test/environments/production/modules/threader/metadata.json
- ext/thread_test/puppetserver.conf
- ext/thread_test/test.rb
- project.clj
Run with `lein thread-test` and then run ext/thread_test/test.rb. See
the file for setting iterations and number of processes. Individual
processes will stop on the first error and cause the main process to
exit 1 if there is a failure.
> (SERVER-2526) Add basic testing for thread safety

- test/integration/puppetlabs/services/puppet_admin/puppet_admin_int_test.clj
The tests for the (deprecated) whitelist access control for the admin
API were previously testing each of the various endpoints under
`puppet-admin-api`, even though the whitelist applies the same to each
of them. Moreover, two of the endpoints (to get thread dumps and flush
the JRuby pool) also do not behave correctly with mock JRubies.
Since the whitelist tests only need to show that the endpoint returns a
success code instead of 'access denied', this commit updates them to
only test one of the endpoints, the one that behaves correctly when
JRubies are mocked, as a representative case for testing the whitelist.
The other two endpoints are tested for their functionality elsewhere.
> (maint) Remove test cases that have bad behavior with mock JRubies

- documentation/install_from_packages.markdown
Based on user feedback: https://tickets.puppetlabs.com/browse/DOC-4395
> (DOC-4395) Clean up installing from packages docs

- documentation/restarting.markdown
Based on the following docs feedback:
https://tickets.puppetlabs.com/browse/DOC-4397
> (DOC-4397) Add step on how to reload PE

- documentation/http_certificate_status.md
- documentation/release_notes.markdown
plus change to http cert status page
> 6.3.3 release notes

- test/integration/puppetlabs/services/jruby/jruby_metrics_service_test.clj
> (SERVER-2681) Enable metrics tests in multithreaded mode

- test/integration/puppetlabs/services/jruby/jruby_puppet_pool_int_test.clj
This commit adds an `admin-api-flush-jruby-ref-pool-test` that copies from the
existing flush API test for the instance pool. The new test assumes a single
JRuby instance and checks that the (overall) borrow count has gone down in
order to determine the flush has completed. Otherwise the tests are identical.
> (SERVER-2721) Add flush API test for multithreaded mode

- documentation/release_notes.markdown
This commit adds a new feature note for the Server 6.9.0 release.
> (docs) Server 6.9.0 release notes

- documentation/release_notes.markdown
This commit adds one resolved feature release note.
> (DOCS) Server 5.3.11 release notes

- documentation/release_notes.markdown
This commit adds one resolved feature release note.
> (DOCS) Server 6.9.1 release notes

- .gitignore
- acceptance/scripts/generic/testrun.sh
This updates the various modes to take advantage of beaker subcommands.
> (maint) Cleanup testrun script

- dev-setup
- dev/install-test-gems.sh
- project.clj
- resources/ext/build-scripts/install-vendored-gems.sh
This update also bumps JRuby to 9.2.11.0.
> (SERVER-2758) Update jruby-utils to 3.1.0

- documentation/intermediate_ca.md
@Magisus Let me know if the description of the diagrams is accurate and whether you would like to add / change anything else. Thanks!
> (DOC-4476) Add CA diagrams

- documentation/scaling_puppet_server.markdown
I expect this will need some adjusting, so please review and I can fix whatever mistakes I've made here. I've made the following changes, broken into three commits for easy removal if needed.
1. I added the information about "pointing the puppet.conf to the CA master." I am not actually sure what that practically means! My best guess was that it was the same as the agents, setting `ca_server` to the CA hostname, so I cribbed from that.
2. I added the feedback about the missing SSL settings in webconf. I did not provide values for those because I didn't know if the ticket had actual values or example values that would vary for users.
3. I updated "compile master" to compiler throughout. Please let me know if there's a case where I've changed the meaning of the sentence and the master (MoM) …
> REVIEW: (DOCUMENT-1016) Scaling compiler edits

- .travis.yml
> (maint) Properly fail Travis make lint, buld, test

- documentation/intermediate_ca.md
Requested in DOC-4521 (https://tickets.puppetlabs.com/browse/DOC-4521).
> (DOCS) Add SERVER-2535 limitation

- documentation/intermediate_ca.md
Fixed the formatting issues on steps 7 and 8 per ticket DOC-4634 https://tickets.puppetlabs.com/projects/DOC/issues/DOC-4634.
> updating intermediate_ca formatting

- documentation/puppet-api/v3/environment_classes.markdown
Fixed a broken link per https://tickets.puppetlabs.com/browse/DOC-3892
> Environment classes.markdown

- acceptance/lib/helper.rb
Prior to this change, the pre-suite would nuke the ssl dir while
puppetserver was running; this would crash the puppetserver,
and systemd would then restart the service. This results in a race
condition with the beaker method #with_puppet_running_on. If the
restart from the crash completes after #with_puppet_running_on ensures
that the service is stopped, then puppetserver never picks up the new
puppet.conf file. I think...
If this ends up solving the transients, the other SERVER-2677 commits
should be reverted.
> (SERVER-2677) Safely remove ssl dir

- documentation/http_certificate.md
- documentation/http_certificate_request.md
- documentation/http_certificate_revocation_list.md
- documentation/http_certificate_status.md
do not merge until puppetserver 6.13.0 is released
> (SERVER-2233) Add `state` param to Certificate Status API docs

- src/clj/puppetlabs/puppetserver/certificate_authority.clj
This commit backports the work done in
ea74310747eeb7684033c7b130a617ee7d7b5596 and
6522a7957bcdfebb4371a62a8b2a203f1c0883e5 to ensure that all CA files are
written atomically.
> (SERVER-2863) Write CA files atomically

- acceptance/suites/tests/authorization/x509_auth.rb
This commit updates the test that verifies whether extensions can be
used to prevent acces via tk-auth to use the correct assertions. The
master cert does not have the extension and so cannot use the catalog
endpoint, which requires it.
> (maint) Test for 403 on locked down catalog endpoint

- src/clj/puppetlabs/services/master/master_core.clj
- test/unit/puppetlabs/services/master/master_core_test.clj
> (SERVER-2875) Add .modules to default module path for new style bolt projects

- project.clj
Conflicts:
acceptance/config/beaker/options.rb
project.clj
ruby/puppet
Conflicts were resolved by maintaining the state of the current branch.
> Merge 6.x -> main

- dev-resources/puppetlabs/services/master/master_core_test/bolt_projects/local_23/facts.d/something
- dev-resources/puppetlabs/services/master/master_core_test/bolt_projects/local_23/lib/puppet/comment.rb
- dev-resources/puppetlabs/services/master/master_core_test/bolt_projects/local_23/modules/helpers/lib/puppet/monkey_patch.rb
- dev-resources/puppetlabs/services/master/master_core_test/bolt_projects/local_23/modules/unhelpers/facts.d/unhelpful
- dev-resources/puppetlabs/services/master/master_core_test/bolt_projects/local_23/modules/unhelpers/lib/puppet/comment.rb
- dev-resources/puppetlabs/services/master/master_core_test/bolt_projects/local_23/modules/unhelpers/lib/puppet/monkey_patch.rb
- src/clj/puppetlabs/services/master/file_serving.clj
- src/clj/puppetlabs/services/master/master_core.clj
- test/integration/puppetlabs/services/master/master_service_test.clj
- test/unit/puppetlabs/services/master/file_serving_test.clj
- test/unit/puppetlabs/services/master/master_core_test.clj
Add support for retrieving file metadata and content for plugins (lib and facts.d) for bolt projects.
> (SERVER-2876) Support pluginsync for bolt projects

- src/clj/puppetlabs/services/master/file_serving.clj
- test/integration/puppetlabs/services/master/master_service_test.clj
Note, the first commit isn't needed and I'm not sure it is an improvement. Happy to hear folks' thoughts on it.
> (SERVER-2914) Change query param from `project` to `versioned_project`

- spec/puppet-server-lib/puppet/jvm/ast_compiler_spec.rb
- src/clj/puppetlabs/services/master/master_core.clj
- src/ruby/puppetserver-lib/puppet/server/ast_compiler.rb
This takes advantage of the recently merged Puppet 7 PR (https://github.com/puppetlabs/puppet/pull/8412)
Signed-off-by: Enis Inan <enis.inan@puppet.com>
> (PE-30410) Shadow fact/variable collisions in the PAL for plans

- resources/ext/build-scripts/mri-gem-list-no-dependencies.txt
- src/clj/puppetlabs/puppetserver/certificate_authority.clj
> (SERVER-2917) Ensure old cadir symlink has same perms as actual cadir

- project.clj
Conflicts:
- resources/ext/build-scripts/mri-gem-list-no-dependencies.txt
> (maint) Merge branch '6.x' into 'main'

- dev-resources/puppetlabs/services/master/master_core_test/bolt_projects/override_builtin_content/bolt-project.yaml
- dev-resources/puppetlabs/services/master/master_core_test/bolt_projects/override_builtin_content/modules/bic_module_one/files/marco.sh
- dev-resources/puppetlabs/services/master/master_core_test/bolt_projects/override_builtin_content/modules/bic_module_one/lib/puppet/monkey_patch.rb
- dev-resources/puppetlabs/services/master/master_core_test/bolt_projects/override_builtin_content/modules/bic_module_one/tasks/init.json
- dev-resources/puppetlabs/services/master/master_core_test/bolt_projects/override_builtin_content/modules/bic_module_one/tasks/init.sh
- dev-resources/puppetlabs/services/master/master_core_test/builtin_bolt_content/bic_module_one/files/marco.sh
- dev-resources/puppetlabs/services/master/master_core_test/builtin_bolt_content/bic_module_one/lib/puppet/monkey_patch.rb
- dev-resources/puppetlabs/services/master/master_core_test/builtin_bolt_content/bic_module_one/tasks/init.json
- dev-resources/puppetlabs/services/master/master_core_test/builtin_bolt_content/bic_module_one/tasks/init.sh
- dev-resources/puppetlabs/services/master/master_core_test/builtin_bolt_content/bic_module_two/files/marco.sh
- dev-resources/puppetlabs/services/master/master_core_test/builtin_bolt_content/bic_module_two/lib/puppet/monkey_patch.rb
- dev-resources/puppetlabs/services/master/master_core_test/builtin_bolt_content/bic_module_two/tasks/init.json
- dev-resources/puppetlabs/services/master/master_core_test/builtin_bolt_content/bic_module_two/tasks/init.sh
- src/clj/puppetlabs/services/legacy_routes/legacy_routes_service.clj
- src/clj/puppetlabs/services/master/file_serving.clj
- src/clj/puppetlabs/services/master/master_core.clj
- src/clj/puppetlabs/services/master/master_service.clj
- test/integration/puppetlabs/services/master/master_service_test.clj
- test/unit/puppetlabs/services/master/file_serving_test.clj
- test/unit/puppetlabs/services/master/master_core_test.clj
Signed-off-by: Enis Inan <enis.inan@puppet.com>
> (PE-30860) Update puppetserver to use the builtin-content-dir setting

- .travis.yml
- ext/travisci/suppression.xml
- project.clj
This commit adds the `lein-nvd` security scanner and adds a vulnerability check
to the set of checks that Travis runs on each PR.
> (SERVER-3021) Add `lein-nvd` security scanner

- resources/ext/build-scripts/mri-gem-list-no-dependencies.txt
Going from version 1.9.5 to 1.10.0
> (SERVER-3038) Update to new gem version

- project.clj
I know you said I could just push directly, but PRs make me feel better 😅 
I'll just merge it myself if no one gets to it before me.
> (maint) Bump to 6.17.0-SNAPSHOT to prep for Y release

- project.clj
This update fixed some reflection issues, for a mild performance
improvement.
> (maint) Update i18n plugin to 0.9.2

- src/clj/puppetlabs/puppetserver/certificate_authority.clj
- src/clj/puppetlabs/services/ca/certificate_authority_core.clj
- test/integration/puppetlabs/puppetserver/error_handling_int_test.clj
- test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
Improving the speed of querying for CSR statuses by dividing up the process.
> (SERVER-3020) Improve certificate_status endpoint speed when querying CSR

- .travis.yml
> (maint) Run travis tests on focal

- resources/ext/build-scripts/mri-gem-list-no-dependencies.txt
Conflicts:
- .travis.yml
Take content from main
> (maint) Merge up 7.x

- src/clj/puppetlabs/puppetserver/certificate_authority.clj
In a code inspection it was noted that the reader used in in the `read-infra-nodes` funciton in the certificate-authority would leak an open reader after the sequence was evaluated. This alters the function signature to pass in the reader, and allow the caller to manage the lifetime of the reader as appropriate.
> (SERVER-3288) ensure reader is closed with use of read-infra-nodes

- src/clj/puppetlabs/puppetserver/certificate_authority.clj
- test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj
Prior to this change, it was possible that a partial inventory write, or changes to the inventory file could occur to cause corruption.
This uses the atomic-write behavior to ensure that only whole inventory files will be present in the location where they are expected. The new behavior uses the kitchen-sink atomic-write with a streaming function to allow the current content to be streamed to a new file, the new entry appended, and once that is done, moved to replace the old file in an atomic way.
A test was added to demonstrate the correct handling of large inventory file content.
> (PE-35640) ensure inventory append operations are crash-safe

- src/clj/puppetlabs/puppetserver/certificate_authority.clj
- test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
Adds duration string parsing function, I made it robust, able to take in invalid strings, but perhaps it should reject conversion entirely if there are any invalid strings?
> (PE-35699) Create duration string parsing function

- src/clj/puppetlabs/services/ca/certificate_authority_core.clj
- test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj
This commit adds a stubbed endpoint for ca/v1/certificate_renewal that uses the allow-auto-renewal configuration added in a prior commit [1] to return either:
- a 501 Not Implemented response when true
- a 404 Not Found response when false
[1]: b52fdde85967b3a5244fa7456ca353ffb688b277
> (PE-35703) add auto-renewal endpoint

- src/clj/puppetlabs/puppetserver/certificate_authority.clj
- test/unit/puppetlabs/services/config/puppet_server_config_service_test.clj
Set the default values for allow-auto-renewal and auto-renewal-cert-ttl correctly if no values are given in the config
> PE-35698 Set the default values correctly

- src/clj/puppetlabs/puppetserver/certificate_authority.clj
- src/clj/puppetlabs/services/ca/certificate_authority_core.clj
- test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj
Conflicts:
- src/clj/puppetlabs/puppetserver/certificate_authority.clj
- src/clj/puppetlabs/services/ca/certificate_authority_core.clj
> (maint) Merge 'origin/7.x' into 'origin/main'

- src/clj/puppetlabs/puppetserver/certificate_authority.clj
- test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj
This moves all the CSR deletion requests to a singular function for handling the CSR deletion, which centralizes logging and provides a bottleneck for all CSR removal behaviors.
Since all calls to the "autosign" routine were always followed by calls to remove the CSR, the delete routine was moved into the autosign routine.
In the updated delete routine, a new behavior is added to look for and remove the indicator file if it is present.  The delete routine needed to be moved up in the file because it is now used by some earlier functions.
Tests are updated to reflect the new behavior and ensure the file is properly deleted.
> (PE-36204) ensure indicator file is deleted

- src/clj/puppetlabs/services/ca/certificate_authority_core.clj
- test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj
This adds a new authenticated path for certificate renewal in the case that there is puppet managed proxy between the agent and the CA.
In that case, the proxy will inject the x-client-cert header into the request. This will be allowed if the requester is listed in the infra-nodes inventory list. Otherwise the request is denied.
> (PE-36768) add authenticated route for proxied requests

- acceptance/suites/pre_suite/foss/95_install_pdb.rb
Ubuntu 18 went EOL in May 2023, so it no longer has official pgdg repos for its packages. Setup the archive repo so tests can continue to be run
> (PE-37178) bionic tests - install pg from archive

- src/clj/puppetlabs/services/master/master_core.clj
- src/clj/puppetlabs/services/request_handler/request_handler_core.clj
- test/integration/puppetlabs/puppetserver/error_handling_int_test.clj
This ensures that even if a catalog compilation "fails" the action is correctly tracked as being in use. This happens when there are issues with the catalog compilation itself, and the agent may still apply a cached catalog.
> (PE-37184) ensure all catalog compilations are tracked

- src/clj/puppetlabs/services/master/master_core.clj
- test/unit/puppetlabs/services/master/master_core_test.clj
> (maint) Support systems with more than 2TB of RAM

- acceptance/suites/puppet4_tests/puppet4_version_test.rb
- acceptance/suites/puppet5_tests/puppet5_version_test.rb
> (maint) Update Compat tests for Beaker update

- acceptance/suites/tests/code_commands/code_scripts.rb
There is some change for Redhat 9's SSH set up that are causing this acceptance test to now fail. I thought originally it was a peculiarity of git shipped on Redhat 9 and an issue with the safe.directory setting. After wasting half a day on it and finally root causing the true issue, just moving to use a file protocol is the simplest fix. This test is looking at the code_scripts extension points, the way the git repo is configured is not important to the test.
> (maint) Fix code_scripts acceptance test

- spec/puppet-server-lib/puppet/jvm/compiler_spec.rb
- src/ruby/puppetserver-lib/puppet/server/compiler.rb
All of those are available at least since Facter 3.
-----
This is just https://github.com/puppetlabs/puppetserver/pull/2878 but with a fixed up spec.
> compiler.rb: Switch to modern facts
