acceptance/suites/tests/010-puppetserver-cli/subcommand/gem.rb

* Change list of installed gems to reduce complexity of install. Beaker changes
too often to use it here without specifying a concrete version, which in turn
would require more complex handing of this list of gems throughout the rest of
the test.
* Clears the list of rubygems sources before adding the internal mirror to
ensure that gem installation problems are not masked by network failures.

(MAINT) Fix intermittent gem install failures.

---

project.clj

We just upgraded to JRuby 1.7.17, but then they released JRuby 1.7.18 the
next day.  Since we haven't kicked off long-running memory testing yet,
it seemed like we should go ahead and bump to the latest.  I believe it
contains some additional fixes related to the 'crypt' method, among
other things.

(MAINT) Upgrade to jruby 1.7.18

---

Gemfile
Gemfile.lock

Without this patch the `pl:tickets` rake task fails because the jira-ruby
dependency is missing.  This patch addresses the problem by adding jira-ruby to
the project Gemfile.  The dependency will be available following `bundle
install`.
The library is in the development group to allow the dependency to be filtered
using `bundle install --without development`.
This patch also moves rake out of the test group because the rake dependency is
always required when running rake tasks for development and testing.

(SERVER-247) Add jira-ruby to Gemfile

---

dev-resources/puppetlabs/services/jruby/request_handler_test/puppet.conf
spec/puppet-server-lib/puppet/jvm/handler_spec.rb
src/clj/puppetlabs/services/master/master_core.clj
src/clj/puppetlabs/services/request_handler/request_handler_core.clj
src/ruby/puppet-server-lib/puppet/server/network/http/handler.rb
test/integration/puppetlabs/services/jruby/request_handler_test.clj
test/unit/puppetlabs/services/master/master_core_test.clj
test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj

In the previous commit, the body for any HTTP requests made to the
Puppet master service with a Content-Type of <none> or
"application/octet-stream" was inappropriately decoded into a UTF-8
string.
With the changes in this commit, the body for any HTTP requests made to
the Puppet master service with a Content-Type of <none> or
"application/octet-stream" is now passed through as raw bytes to the
JRuby request layer, where it is converted into an ASCII-8BIT Ruby
String.
Puppet agent requests to the "file_bucket_file" endpoint include a
Content-Type of "text/plain".  While these requests should technically,
per the HTTP spec, be transformed to ISO-8859-1 or US-ASCII instead of
UTF-8, the actual payload is intended to be treated as "binary".  This
commit treats requests to the …

(SERVER-269) Passthrough binary payload properly for master requests

---

dev-resources/puppetlabs/services/master/master_service_test/conf/puppet.conf
documentation/puppet_conf_setting_diffs.markdown
src/clj/puppetlabs/puppetserver/certificate_authority.clj
src/clj/puppetlabs/services/ca/certificate_authority_disabled_service.clj
src/clj/puppetlabs/services/ca/certificate_authority_service.clj
src/clj/puppetlabs/services/config/puppet_server_config_core.clj
src/clj/puppetlabs/services/master/master_service.clj
src/clj/puppetlabs/services/protocols/ca.clj
test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
test/unit/puppetlabs/services/ca/ca_testutils.clj
test/unit/puppetlabs/services/config/puppet_server_config_core_test.clj
test/unit/puppetlabs/services/master/master_service_test.clj

This commit changes the master to, at each startup, copy the file
pointed at by the Puppet `cacrl` setting, if it exists, over to the
file pointed at by the Puppet `hostcrl` setting.
This commit also changes the `override-webserver-setting!` logic to
use the file at the `hostcrl` setting rather than the one at the `cacrl`
setting to determine which file the webserver uses to validate
certificates for connecting clients.  This was done based on the fact
that a "standalone" master -- one hosted without a corresponding active
CA in the same container -- would have used the `hostcrl` setting under
the Ruby master.  With the logic in place to copy the `cacrl` to the
`hostcrl` when a real CA is in place, the latest CRL, when the master
and CA are running in the same container, should now be in …

(SERVER-85) Sync CA CRL to Host CRL at startup

---

project.clj

This should fix the `lein uberjar` command to produce a working Puppet
Server uberjar that includes the Jetty dependency, without interfering
with the ezbake packaging process.

(SERVER-220) Include Jetty dependency in uberjar

---

resources/ext/cli/gem.erb
resources/ext/cli/irb.erb
resources/ext/cli/ruby.erb

Make the cli .erb files more robust by adding quotes around the
JAVA_BIN and CONFIG environment variables.
This implements the changes suggested by @jeffmccune in https://github.com/puppetlabs/pe-puppet-server-extensions/pull/162. I thought this belonged in stable since it's a minor change and since it's going into 3.7.2, it might as well go into 1.0.1 as well.

(MAINT) Make cli .erb files more robust

---

acceptance/suites/tests/010-puppetserver-cli/subcommand/gem.rb
acceptance/suites/tests/010-puppetserver-cli/subcommand/irb.rb
acceptance/suites/tests/010-puppetserver-cli/subcommand/ruby.rb

Without this patch there are no acceptance level tests for the ruby and irb
subcommands as they relate to the `gem` subcommand.  This is a problem because
we need to ensure these commands behave as expected, particularly when the
`gem` subcommand is used to install third party libraries.
This patch addresses the problem by installing the `hiera-eyaml` gem and then
checking that the `ruby` and `irb` subcommand can `require 'eyaml'`.
This patch also adds basic testing of the behavior of GEM_HOME and FOO_DEBUG
with regard to the irb and ruby subcommands in addition to ensuring `require
'puppet'` works in both subcommands.

(SERVER-252) Add acceptance tests for irb and ruby subcommands

---

acceptance/suites/tests/010-puppetserver-cli/subcommand/irb.rb
acceptance/suites/tests/010-puppetserver-cli/subcommand/ruby.rb

Without this patch the tests are failing because of bad logic in the tests
themselves.  This patch addresses the problem by correcting the logic in the
tests, specifically /BAD/ was matching in the irb tests because irb echos input
to standard output.  /^BAD$/ will not match the echoed input.  The ruby test
was failing because string interpolation was happening in the beaker process
when it was intended to be passed through beaker to the ruby subcommand being
tested.  This patch addresses the problem by avoiding string interpolation
entirely and using concatenation instead.

(SERVER-252) Fix bad irb and ruby subcommand tests

---

acceptance/suites/tests/010-puppetserver-cli/subcommand/irb.rb

Same issues as before, string interpolation was happening in beaker when it
should be passed through.  Switched from #{} to concatenation with +.

(SERVER-252) Fix bad irb acceptance test... again.

---

documentation/configuration.markdown
documentation/release_notes.markdown

You don't have to restart anymore for logback.xml changes. This file now says so.

DOCS: configuration.markdown, restart not needed for logback change

---

Rakefile
dev/puppet-server.conf.sample
dev/user_repl.clj
src/clj/puppetlabs/services/ca/certificate_authority_core.clj
src/clj/puppetlabs/services/master/master_core.clj
src/ruby/puppet-server-lib/puppet/server/master.rb
src/ruby/puppet-server-lib/puppet/server/puppet_config.rb
test/integration/puppetlabs/puppetserver/error_handling_int_test.clj
test/integration/puppetlabs/services/jruby/puppet_environments_int_test.clj
test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj
test/unit/puppetlabs/services/master/master_core_test.clj
test/unit/puppetlabs/services/master/master_service_test.clj

For Puppet 4 the master's routes have changed. The environment is a query
param, there is a version string (v3) for all routes, and there is a url
prefix. This makes the necessary updates to Puppet Server to work with
these changes.
The CA routes have been split out completely from the master routes.
They are now at a different prefix and version than the master routes in
Puppet's code. This means that in Puppet Server they can have their own
prefix (by default `/puppet-ca`) - they no longer need to be mounted at `/`.
In addition, the environment has been moved from the first part of the path to
a query parameter. The environment is never used in the CA routes, so this
query parameter is now ignored completely.
This also adds a check that the prefix specified in Puppet's code through
the …

(SERVER-149) Update Puppet Server for Puppet 4 url changes

---

project.clj
spec/puppet-server-lib/puppet/jvm/certificate_spec.rb
src/clj/puppetlabs/puppetserver/certificate_authority.clj
src/clj/puppetlabs/puppetserver/ringutils.clj
src/clj/puppetlabs/services/ca/certificate_authority_core.clj
src/clj/puppetlabs/services/request_handler/request_handler_core.clj
src/ruby/puppet-server-lib/puppet/server/certificate.rb
src/ruby/puppet-server-lib/puppet/server/config.rb
test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
test/unit/puppetlabs/puppetserver/ringutils_test.clj
test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj
test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj

* Updated dependencies to reflect renaming puppetlabs/certificate-authority project to puppetlabs/ssl-utils
* Changed references to old jvm-ca project to jvm-ssl-utils in clojure/ruby files

(SERVER-101) Changed jvm-ca references to jvm-ssl-utils

---

src/ruby/puppet-server-lib/puppet/server/puppet_config.rb

Eliminate the `reset_environment_context` and
`configure-indirector-routes` methods, which were copied directly
from Puppet, in favor of the new methods in
Puppet::ApplicationSupport.
Both the clojure and ruby tests passed. I tried running the acceptance tests but was unable to do so on my machine due to a known issue with beaker and zsh.

(SERVER-155) Eliminate duplicated code

---

src/ruby/puppet-server-lib/puppet/server/master.rb

Prior to this commit, there was an old require that referenced a library
from puppet that no longer exists. This caused puppet-server to fail on
startup. This commit fixes that by removing the require reference.

(maint) Remove unused require from puppet-server-lib

---

dev-resources/java.security
documentation/configuration.markdown
project.clj

Without this patch the unit tests fail on JVM versions more recent than
1.7.0_u75 because SSLv3 is disabled at the JRE layer by default.  This is a
problem because the end user may explicitly configure the JRE to allow SSLv3
algorithms, even though we disable them by default at the application layer,
and we need to test the behavior of the system in this scenario.  This patch
addresses the problem by allowing all SSLv3 algorithms by overriding the
java.security jdk.tls.disabledAlgorithms property.

(SERVER-332) Allow all TLS algorithms in the dev lein profile

---

dev/puppet-server.conf.sample
dev/user_repl.clj
ezbake/config/conf.d/web-routes.conf

The webrouting config for the master service was changed for SERVER-300 to
have :master-routes and :invalid-in-puppet-4. This commit updates the
webrouting config for packaging and the repl so that everything will work
properly.

(maint) Update webrouting configs for master service

---

acceptance/lib/helper.rb
acceptance/suites/pre_suite/foss/20_install_released_puppet.rb
acceptance/suites/pre_suite/foss/70_install_puppet.rb
resources/ext/ezbake.conf

Previously, the puppet package created the puppet user and group. However, the
puppet agent does not require this user, since it runs as root. The puppet
user is only required for the master. The puppet-agent AIO packages will not
be creating the puppet user or group, so the puppetserver packages must now do
this and must also set proper permissions on certain directories. This commit
adds the necessary steps to the postinstall.
It also removes the `puppet_apply_as_puppet_user` method from the acceptance
helpers, which 1) is no longer required, and 2) since the puppet user is not
created before installing the puppetserver package, we couldn't complete this
step.

(maint) Update packaging & acceptance tests to create puppet user

---

src/clj/puppetlabs/services/master/master_core.clj
src/ruby/puppet-server-lib/puppet/server/master.rb
test/unit/puppetlabs/services/master/master_core_test.clj

Add the /environments route to the v3 routes, as it previously
existed in the v2 routes.

(SERVER-326) Add /v3/environments route

---

src/clj/puppetlabs/services/master/master_core.clj
src/clj/puppetlabs/services/master/master_service.clj

Generate the 404 upgrade message once instead of on every request
handled, since the information displayed should not change and
grabbing the Puppet Version from JRuby is an expensive operation.

(SERVER-334) Generate upgrade message once

---

spec/puppet-server-lib/puppet/jvm/master_spec.rb
test/integration/puppetlabs/services/jruby/request_handler_test.clj

This submodule update pulls in the changes made for PUP-3812, which change the
content-type and accept headers that the file buck endpoint respects. This
commit updates the jruby integration test to work with these changes.

(maint) Update puppet submodule & fix tests

---

project.clj
resources/ext/ezbake.conf

Without this patch the dependency on the JVM packages are expressed in the
project specific ezbake configuration.  This is a problem because it duplicates
the same dependency expressed statically in the [ezbake package
specifications][requires].  The duplication is confusing and more difficult to
coordinate and maintain over time.
The principle for dependencies is that those required to satisfy the behavior
of ezbake itself, or the system level service management scripts, should be
expressed statically in ezbake since those dependencies will apply to all
projects using ezbake and the resulting scripts.  Application level
dependencies should be specified in the project specific ezbake.conf file such
that individual applications are not interdependent on common dependencies.
[requires]: …

(SERVER-338) Use lein-ezbake 0.1.2 to resolve netstat issue

---

src/clj/puppetlabs/services/jruby/jruby_puppet_agents.clj
src/java/com/puppetlabs/puppetserver/JRubyPuppet.java
src/ruby/puppet-server-lib/puppet/server/config.rb
src/ruby/puppet-server-lib/puppet/server/http_client.rb
src/ruby/puppet-server-lib/puppet/server/master.rb
test/unit/puppetlabs/puppetserver/ruby/http_client_test.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_agents_test.clj
test/unit/puppetlabs/services/jruby/jruby_testutils.clj

Add in a new `terminate` method to the master that closes the HTTP client and call it before terminating the JRuby scripting container.
I'm definitely looking for some feedback on this one. In particular, I'm not sure about testing. I was having trouble figuring out how to test this. I did add a test to ensure that the master termination function works as intended, but wasn't sure how to write a test to ensure a client is closed before we destroy its scripting container, so any feedback or suggestions on that front are very much appreciated.

(SERVER-206) Close client on scripting container termination

---

spec/puppet-server-lib/puppet/jvm/puppet_config_spec.rb
src/ruby/puppet-server-lib/puppet/server/puppet_config.rb

Recently, Puppet was changed to allow the log level to be configured via
settings.  This broke the way in which we were previously initializing
it.  This commit fixes that initialization and adds a ruby spec test to
ensure that logging is initialized correctly.
In addition to the spec test, I also manually verified this change - [here's the log output](https://gist.githubusercontent.com/KevinCorcoran/4b1338a6e0ab1edd3c81/raw/5cc253523ae6ab8bac73c9c9dfcd1f892e4de29f/gistfile1.txt) of starting Puppet Server and doing a no-op agent run against it previously, and [here's the logging](https://gist.githubusercontent.com/KevinCorcoran/704169f20c06efaf86de/raw/e19594eb81ec943f9828b7262c2eaf8f8e993b9a/gistfile1.txt) for the same process but including this patch.

(SERVER-354) fix initialization of Puppet logging

---

acceptance/lib/helper.rb

Without this patch the puppet-server acceptance tests are failing due to an out
of date dependency on the AIO puppet-agent 0.2.1.  This patch addresses the
problem by updating the dependency from version 0.2.1 to version
49f7b1b967e44020587ab087f87e2f5e3ff2b1f6, which is packaged and published at
http://builds.puppetlabs.lan/puppet-agent/49f7b1b967e44020587ab087f87e2f5e3ff2b1f6/
This new version of puppet-agent has updated configuration paths as
described in [PUP-3632](https://tickets.puppetlabs.com/browse/PUP-3632)

(SERVER-339) Depend on puppet-agent AIO dev version

---

project.clj
spec/puppet-server-lib/puppet/jvm/certificate_spec.rb
src/clj/puppetlabs/puppetserver/certificate_authority.clj
src/clj/puppetlabs/puppetserver/ringutils.clj
src/clj/puppetlabs/services/ca/certificate_authority_core.clj
src/clj/puppetlabs/services/request_handler/request_handler_core.clj
src/ruby/puppet-server-lib/puppet/server/certificate.rb
src/ruby/puppet-server-lib/puppet/server/config.rb
test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
test/unit/puppetlabs/puppetserver/ringutils_test.clj
test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj
test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj

Cherry-picked Joe's commit to update from the old certificate-authority lib to the new ssl-utils lib.
Conflicts:
src/clj/puppetlabs/puppetserver/ringutils.clj

(MAINT) Cherry pick commit to migrate to ssl-utils

---

ext/travisci/test.sh
project.clj
src/clj/puppetlabs/services/master/master_core.clj
test/integration/puppetlabs/services/jruby/request_handler_test.clj
test/unit/puppetlabs/services/master/master_core_test.clj

Delete a terrible hack which munged the Content-Type header of incoming
/file_bucket_file requests to always be 'application/octet-stream'.
Historically, the agent has sent a value of 'text/plain' for this
header, but that is fixed as of PUP-3812.
I think that the primary risk of a regression here would be to accidentally break handling of non-UTF8 data (as we originally did in SERVER-269) - however, that should be sufficiently covered by the integration test in `puppetlabs.services.jruby.request-handler-test/file-bucket-test`.  So, I think this is good on test coverage.

(SERVER-294) delete Content-Type hack

---

ezbake/config/logback.xml

This commit re-adds the logappender ref to the logback.xml file, which
was somehow lost during a rebase or merge. With this change, the
foreground subcommand should now produce output.

(SERVER-356) Fix foreground output

---

dev/puppet-server.conf.sample
dev/request-logging-dev.xml
ezbake/config/conf.d/webserver.conf
resources/ext/config/request-logging.xml

This commit adds a new Apache-style puppetserver-access.log file to
capture HTTP traffic.

(SERVER-319) Apache-style request logging

---

documentation/configuration.markdown
src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj
src/clj/puppetlabs/services/protocols/jruby_puppet.clj

This commit simply increases the timeout to 1200000 ms (20 minutes).

(SERVER-389) Increase JRuby pool default-borrow-timeout

---

project.clj

The unit tests can still be run independently via `lein test :unit`.

(maint) make 'lein test' include integration tests

---

acceptance/lib/helper.rb
acceptance/suites/pre_suite/foss/80_configure_puppet.rb
dev/puppet-server.conf.sample
dev/user_repl.clj
documentation/configuration.markdown
documentation/services_master_puppetserver.markdown
resources/ext/config/conf.d/puppetserver.conf
src/clj/puppetlabs/puppetserver/certificate_authority.clj
src/clj/puppetlabs/puppetserver/cli/irb.clj
src/clj/puppetlabs/puppetserver/cli/ruby.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj
test/unit/puppetlabs/services/config/puppet_server_config_service_test.clj
test/unit/puppetlabs/services/jruby/jruby_testutils.clj

This commit moves the :ruby-load-path setting out of the os-settings
section and into the jruby-puppet section. The os-settings section is no
longer necessary, so it was removed altogether.

(SERVER-331) Fold os-settings back into jruby-puppet

---

spec/puppet-server-lib/puppet/jvm/puppet_config_spec.rb
src/ruby/puppet-server-lib/puppet/server/puppet_config.rb

Without this patch puppet server defers to puppet on the value of the
always_cache_features setting.  This is a problem because it does not
make sense for features to be reloaded frequently on the puppet server,
this behavior is only useful for puppet agent processes that need to
update the set of installed features mid-run.
This patch addresses the problem by explicitly setting
Puppet[:always_cache_features] to true in Puppet::Server::PuppetConfig.
This approach is employed to keep all of the static jruby-puppet related
settings in one place, internal to the JRuby contexts.  This approach is
employed in order to avoid expanding the surface area between Clojure
and JRuby.

(SERVER-410) Always cache features in puppet server

---

dev-resources/puppetlabs/services/jruby/jruby_interpreter_test/puppet.conf
dev/puppet-server.conf.sample
dev/user_repl.clj
documentation/configuration.markdown
documentation/dev_running_from_source.markdown
project.clj
resources/ext/config/conf.d/puppetserver.conf
src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj
test/integration/puppetlabs/puppetserver/bootstrap_int_test.clj
test/integration/puppetlabs/puppetserver/bootstrap_testutils.clj
test/unit/puppetlabs/services/ca/certificate_authority_disabled_test.clj
test/unit/puppetlabs/services/jruby/jruby_interpreter_test.clj
test/unit/puppetlabs/services/jruby/jruby_testutils.clj

This commit adds plumbing for codedir, rundir, logdir in the same way we
were plumbing confdir and vardir through to JRuby.
This commit also bumps up the ruby Puppet submodule.
----
:+1: Unit tests pass
:+1: Can run the Server from source
:-1: Server is broken in packages, but not sure it's due to these changes, still investigating
**UPDATE**: Broken due to bindir and ssldir issues that are expected and not related to this PR

(SERVER-409) Plumb directories into jruby

---

Gemfile

Without this patch puppetserver is using an older version of beaker that does
not have all of the AIO path updates as of this point in time.  This patch
updates beaker to version 7d0cccf which is the exact version Puppet is using in
their master branch as per PUP-4056.

(SERVER-435) Pin beaker to 7d0cccf

---

documentation/install_from_packages.markdown

The docs site MD parser thought we were trying to italicise, for some reason.

(docs) Fix glitchy link and list item spacing in install page

---

project.clj
resources/ext/ezbake.conf

Create an empty `/var/run/puppet` directory before starting up puppet server

(SERVER-404) Create empty /var/run/puppet directory

---

acceptance/suites/pre_suite/foss/71_smoke_test_puppetserver.rb

Without this patch the acceptance tests in the master branch are passing with
all green, successful, positive results.  This is a problem because those
results are misleading, immediately out of the package puppetserver fails to
start due to permission errors.
The problem is masked by the use of `puppet` in beaker shortly after installing
the puppetserver package.  The use of `puppet resource`, `puppet apply` or
`puppet agent` as root has the side-effect of changing ownership and
permissions of /var/run/puppetlabs, /var/log/puppetlabs, and
/etc/puppetlabs/puppet, all of which have the follow-on effect of allowing the
puppetserver service to start because the puppet user it runs as is then able
to create the directories it needs.
This patch addresses the problem by trying to start the …

(maint) Check service start right out of the package

---

project.clj
resources/ext/ezbake.conf

Without this patch the puppetserver puppet rundir does not exist, which is a
problem because the parent directory of rundir is owned by root and
puppetserver runs as puppet which is unable to create the rundir.  This
prevents the service from starting up out of the package.
This patch addresses the problem by creating the rundir directory in a manner
owned by the same account puppetserver runs as.  This eliminates the need for
puppetserver to create the directory and allows puppetserver to create files in
the rundir directory.
NOTE: This does not cover the case of `puppetserver foreground` which will
still fail if executed before the service is started using the service
management framework.

(SERVER-414) Manage rundir during service startup

---

project.clj

This commit moves the lein-voom plugin to a new :voom profile instead of
a top-level project plugin. The plugin causes several warnings any time
lein is invoked and this is pretty noisy.

(MAINT) Move lein-voom plugin into profile

---

documentation/configuration.markdown
src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj
src/clj/puppetlabs/services/protocols/jruby_puppet.clj
test/unit/puppetlabs/services/ca/certificate_authority_disabled_test.clj
test/unit/puppetlabs/services/config/puppet_server_config_service_test.clj
test/unit/puppetlabs/services/jruby/jruby_pool_test.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_agents_test.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_service_test.clj
test/unit/puppetlabs/services/jruby/jruby_testutils.clj
test/unit/puppetlabs/services/master/master_service_test.clj

This PR cherry-picks the following three commits from master:
f72c912b3b636dca0a2bf87fbffa574b422d0a4e
14c498ec2beb71786cc8b6791feb4cdde44d7c2d
8ef238393fa8e632412f3668ca18e4121b43fd6e
This should effectively back-port the jruby borrow timeout work to the stable branch.

(SERVER-408) backport jruby borrow timeouts

---

dev/puppet-server.conf.sample
documentation/configuration.markdown
resources/ext/config/conf.d/puppetserver.conf
src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj
test/unit/puppetlabs/services/jruby/jruby_pool_test.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_core_test.clj

There was a glaring flaw in the way that we had previously been
calculating a default value for the number of JRuby instances.
The formula was 'num-cpus + 2', which meant that on a really large
server with e.g. 32 cores, you'd get 34 JRuby instances.  That
many JRuby instances will require a very large heap size, but we
default to a 2G heap size, so users were hitting OutOfMemory errors.
This commit changes the formula.  We now use 'num-cpus - 1', with
a minimum value of 1 and a maximum value of 4.  We also log a
warning message if the user hasn't provided an explicit value for
this setting, and suggest that they do so.

(SERVER-448) Reduce the default value for # JRubies

---

acceptance/lib/helper.rb

Without this patch we are not using a puppet-agent version in CI that contains the package provides improvements in RE-4141.  This is a problem because we need to run puppetserver through CI in combination with a puppet-agent that includes the RE-4141 improvements.
This patch addresses the problem by updating to puppet-agent build [890a4a2](http://builds.puppetlabs.lan/puppet-agent/890a4a29148a3ae2997cb1cf2cefd329e6badf3d/)
which includes these changes.
This commit also updates the submodule to the same commit of puppet included in the puppet-agent builds, which is the 4.0.0-rc1 tag in puppet.
See: [puppet.json](https://github.com/puppetlabs/puppet-agent/blob/890a4a29148a3ae2997cb1cf2cefd329e6badf3d/configs/components/puppet.json)

(SERVER-415) Update PUPPET_BUILD_VERSION for RE-4141

---

acceptance/lib/helper.rb

This reverts commit b6fee071fb46a10e9c570218fa4f48ac98809f8d.
This is being reverted because version identifiers are the worst thing
ever and quite possibly the most difficult problem in computer science.
lein test :only puppetlabs.services.config.puppet-server-config-service-test/config-service-functions
FAIL in (config-service-functions) (puppet_server_config_service_test.clj:57)
Basic puppet-server config service function usage The config service has puppet's version available.
expected: (valid-semver-number? (get-in-config service [:puppet-server :puppet-version]))
actual: (not (valid-semver-number? "4.0.0-rc1"))

Revert "(SERVER-415) Update PUPPET_BUILD_VERSION for RE-4141"

---

project.clj
test/unit/puppetlabs/services/config/puppet_server_config_service_test.clj

Without this patch the unit tests are not properly parsing semantic version
strings according to the specification.  This is a problem for RC versions of
dependencies with versions such as "4.0.0-rc1"  This patch addresses the
problem by using a third party library written by our very own Deepak designed
to parse and manipulate semantic version data.

(SERVER-450) Add proper semver parsing to unit tests

---

dev/puppet-server.conf.sample
ezbake/config/conf.d/global.conf
src/clj/puppetlabs/services/master/master_core.clj
src/clj/puppetlabs/services/master/master_service.clj

Fix an issue wherein the group-id "puppetlabs" was not being used,
which caused getting the version string for puppet-server to fail.
Make dujour configuration optional. Remove dujour configuration
from the default config file.

(MAINT) Fix dujour issues

---

acceptance/lib/helper.rb
spec/puppet-server-lib/puppet/jvm/master_spec.rb

This reverts commit f8c7e2fc47ed52477493a37c9bdb49f556889fb0.
Now that we have the unit tests fixed up with improved semver checking behavior
we can re-update to a PUPPET_BUILD_VERSION that works with RE-4141 and Puppet
4.0.0-rc1

Revert Revert (SERVER-415) Update PUPPET_BUILD_VERSION for RE-4141

---

project.clj
spec/puppet-server-lib/puppet/jvm/certificate_spec.rb
src/clj/puppetlabs/puppetserver/certificate_authority.clj
src/clj/puppetlabs/puppetserver/ringutils.clj
src/clj/puppetlabs/services/ca/certificate_authority_core.clj
src/clj/puppetlabs/services/request_handler/request_handler_core.clj
src/ruby/puppet-server-lib/puppet/server/certificate.rb
src/ruby/puppet-server-lib/puppet/server/config.rb
test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
test/unit/puppetlabs/puppetserver/ringutils_test.clj
test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj
test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj

This commit upgrades the jvm-certificate-authority dependency
to jvm-ssl-utils. Most/all changes are just renames.

(SERVER-437) Upgrade to jvm-ssl-utils 0.8.0

---

project.clj

If this commit passes through CI then this change in will be tagged as
2.0.0-rc2
Note: It's not yet clear to me if this commit itself, or the merge commit that
brings it in should be tagged.  I'm thinking the merge commit, but I could see
us using the commit if there are specific tooling or processing that assumes
the version bump itself is the commit that is to be tagged.

(SERVER-438) Update version to 2.0.0-rc2

---

project.clj
test/unit/puppetlabs/services/config/puppet_server_config_service_test.clj

Without this patch the config service test uses an exception hander to figure
out if a semver identifier is valid or not.  This is a problem because the
semver function may not have raised the exception being handled.  This patch
addresses the problem by updating the clj-semver library to 0.3.0 which
implements a semver check function that returns boolean true or false.

(SERVER-454) Remove exception handler in config service test

---

Gemfile

The Gemfile on puppet-server's master branch has 'jira-ruby' as a
development gem.  This commit adds that gem for the stable branch as
well.
This commit also makes 'rake' a development and test gem and sources a
Gemfile local if one is defined for the user.  These changes were done
just to replicate the behavior we now have on the master branch.

(MAINT) Restore jira-ruby gem dependency

---

project.clj

This commit bumps puppet-server's lein-ezbake plugin dependency to
0.2.6.

(MAINT) Bump lein-ezbake plugin dependency to 0.2.6

---

project.clj

This commit bumps the tk-jetty9 dependency to 1.3.0.

(SERVER-513) Bump tk-jetty9 dependency to 1.3.0

---

Gemfile
acceptance/config/nodes/redhat7-64m-windows2008r2-64a.yaml
acceptance/suites/pre_suite/foss/10_install_release_repos.rb
acceptance/suites/pre_suite/foss/30_install_dev_repos.rb
acceptance/suites/pre_suite/foss/70_install_puppet.rb
acceptance/suites/tests/00_smoke/testtest.rb

Without this set of patches windows agents error out in the pre-suite.  This is
a problem because we need to test windows2008r2-64a against redhat7 and
ubuntu1404.
These patches install the AIO agent onto windows hosts.  It's unclear if the
full acceptance suite passes, but I'd like to get this up for review.

(SERVER-499) Get smoke tests passing for windows agents

---

project.clj

Without this patch puppetserver depends on ezbake 0.3.0 which is a
problem because that version of ezbake does not build working packages
for debian flavor platforms.  This patch addresses the problem by
updating to ezbake 0.3.1 which includes support for AIO with debian7,
ubuntu1404, and ubuntu1204

(maint) Update to ezbake 0.3.1

---

acceptance/suites/pre_suite/foss/10_install_release_repos.rb

Without this patch the confinement added in 2f8d33c is a problem because it
changed behavior to install the release repository only on windows, but the
desired behavior is to avoid this step on windows.
This patch addresses the problem by inverting the confinement.

(SERVER-499) Fix inverted confinement for 10_install_release_repos

---

project.clj
src/clj/puppetlabs/services/version/version_check_core.clj
test/unit/puppetlabs/services/version/version_check_core_test.clj

This commit removes the hyphen from "puppet-server" in the project.clj
defproject.  This is needed in order to preserve backward compatibility
with dujour checkins of Puppet Server, which used "puppetserver" as the
artifact-id.

(SERVER-518) Update group-id and artifact-id for version checks

---

project.clj
src/clj/puppetlabs/services/master/master_service.clj

This commit removes the hyphen from "puppet-server" in the project.clj
defproject. This is needed in order to preserve backward compatibility
with dujour checkins of Puppet Server, which used "puppetserver" as the
artifact-id.

(SERVER-520) Remove hyphen from puppet-server in project.clj

---

spec/puppet-server-lib/puppet/jvm/http_client_spec.rb
src/ruby/puppet-server-lib/puppet/server/http_client.rb
test/unit/puppetlabs/puppetserver/ruby/http_client_test.clj

This commit changes the HTTP client so it catches underlying Java
exceptions and raises them as a Ruby Puppet::Server::HttpClientError
instead.
This change allows consumers of the HTTP client to catch errors using
only MRI Ruby and not require the use of JRuby.

(SERVER-517) Raise Ruby errors from HTTP client

---

documentation/configuration.markdown

This commit adds documentation for the new HTTP access log.

(SERVER-319) Document HTTP access log

---

project.clj

This commit bumps the puppetserver version in the project.clj file to
1.0.8 for release.

(MAINT) Bump version to 1.0.8 for release

---

project.clj

This commit bumps the puppetserver version in the project.clj file to
1.0.9-SNAPSHOT for the next release.

(MAINT) Bump version to 1.0.9-SNAPSHOT for next release

---

documentation/configuration.markdown

One little line, causing the doc to render wrong.

DOCS: fixed broken bullet list in configuration.markdown

---

acceptance/lib/helper.rb

Previously we were requiring 'beaker/dsl/ezbake_utils' directly, with a
reorganization of the beaker code projects should simply require
'beaker/dsl/install_utils' and all other dsl installation helpers
(including ezbake helpers) will get installed.

(maint) Update acceptance helper for new beaker layout -- WAIT TO MERGE

---

project.clj

For the 2.0.0 release of puppetserver, it will be shipped to a repo
named PC1 alongside the new agent. This commit adds the repo-target
option to the ezbake config to ensure that it is shipped to the correct
repo.

[Do not merge] (SERVER-506) Set repo-target to PC1 for 2.0 release

---

src/clj/puppetlabs/puppetserver/cli/irb.clj
src/clj/puppetlabs/puppetserver/cli/ruby.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_agents.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_internal.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_schemas.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj
test/integration/puppetlabs/puppetserver/bootstrap_int_test.clj
test/integration/puppetlabs/services/jruby/jruby_pool_int_test.clj
test/integration/puppetlabs/services/jruby/puppet_environments_int_test.clj
test/unit/puppetlabs/puppetserver/ruby/http_client_test.clj
test/unit/puppetlabs/services/config/puppet_server_config_service_test.clj
test/unit/puppetlabs/services/jruby/jruby_interpreter_test.clj
test/unit/puppetlabs/services/jruby/jruby_pool_test.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_agents_test.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_service_test.clj
test/unit/puppetlabs/services/jruby/jruby_testutils.clj

This PR is a pre-cursor to the real implementation details for SERVER-325.  The goal of that ticket is to introduce a new setting that allows users to configure JRuby instances to be flushed after being used for a certain number of requests.
There was a lot of code clean-up / reorganization necessary in order to make it possible to implement that functionality.  The main issue was that there were some circular dependencies between some of the namespaces that make up the JRuby pool functionality, and we needed to break those namespaces up into smaller units in order to be able to wire everything together without circular dependencies.
The commits related to that code reorganization are very susceptible to merge conflicts if any other work is being done related to the JRuby scripting …

(SERVER-325) reorganize code for max requests

---

src/clj/puppetlabs/services/jruby/jruby_puppet_schemas.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_service_test.clj
test/unit/puppetlabs/services/jruby/jruby_testutils.clj

Many (most?) of the configuration maps that were being used
in the jruby-puppet-service-tests were invalid, but this wasn't
surfacing in the test runs because of the way the mock
JRuby instances were being created.  This commit improves
the validation of the input to the mock fixture, and fixes all
of the test configurations.

(SERVER-535) Fix several bugs in j-p-service-test

---

README_BRANCHING.md

Without this patch we don't have a documented plan for how to handle changes
destined for 2.1.x in our current world where 1.1 and 2.0 have not yet been
released.  This is a problem because we need to start active development on 2.1
before 1.1 and 2.0 are released, but we only have stable and master for 1.1 and
2.0 respectively.
This patch addresses the problem by establishing a plan of action that
introduces the 2.1.x branch and how we're going to handle it as a deviation
from our normal workflow with stable and master.

(SERVER-533) Update branching document for 2.1

---

acceptance/lib/helper.rb

Without this patch puppetserver 2.0.0 is testing against a development build of
puppet agent.  This patch addresses the problem by moving the pin from a
development build to the real deal 1.0.0 version of the puppet-agent packages.

(SERVER-480) Test against puppet-agent 1.0.0

---

Gemfile

Without this patch puppetserver is pinned to a specific GIT sha of beaker.
This is a problem because using a Git checkout has the side effect of transient
false positive failures as described in QENG-2138.  This patch addresses the
problem by updating the dependency expression to so-called pessimistic
dependency that pins beaker to released versions installed via rubygems, not
git, in the 2.9.x series.

(maint) Pessimistically pin to beaker 2.9.0

---

src/clj/puppetlabs/puppetserver/certificate_authority.clj
src/clj/puppetlabs/services/config/puppet_server_config_core.clj
test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
test/unit/puppetlabs/services/ca/ca_testutils.clj

Caution: this is a PR hacked at vey high speed during the Ghent Puppet Contributor Summit after several conference days, so it might have many issues :)
This new feature makes the puppet-server respect the puppet.conf keylength parameter when creating new certificates.
Unlike what suggested in the original ticket, there's no specific error message about invalid keylength as the jvm current error message looked sufficient. 
Please review and feel free to comment!
Brice

(SERVER-157) use the keylength settings from puppet.conf

---

project.clj

This commit bumps the puppet-server lein-ezbake dependency to 0.3.3,
needed to avoid Fedora 19 being used as a build target since that's now
been removed for our packaging jobs.

(MAINT) Bump lein-ezbake dependency to 0.3.3

---

project.clj

This commit bumps the puppet-server lein-ezbake dependency to 0.2.7,
needed to avoid Fedora 19 being used as a build target since that's now
been removed for our packaging jobs.

(MAINT) Bump lein-ezbake dependency to 0.2.7

---

src/clj/puppetlabs/puppetserver/certificate_authority.clj
src/clj/puppetlabs/services/config/puppet_server_config_core.clj
test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
test/unit/puppetlabs/services/ca/ca_testutils.clj

If none are provided, it will resort to the default puppet
value.
Note that if the keylength is not correct (too small or
too high) the underlying java security code will throw
an InvalidParameterSecurity message about RSA key size,
but not a puppet specific message.
Signed-off-by: Brice Figureau <brice-puppet@daysofwonder.com>
Conflicts:
test/unit/puppetlabs/puppetserver/certificate_authority_test.clj

(SERVER-157) Use the keylength setting from puppet.conf

---

README_BRANCHING.md

Without this patch the branching document is out of date because we've released
2.0.0 and master is now taking over responsibility for 2.1.x.
Conflicts:
README_BRANCHING.md

(SERVER-555) Update branching strategy document post 2.0.0

---

documentation/puppetserver_vs_passenger.markdown

Since a user spent some significant time tracking down this problem,
it seems worth preventing future frustration.

(docs) Add mention of missing /status endpoint

---

acceptance/lib/helper.rb

Without this patch the smoke tests are failing in the 2.1.x branch, presumably
because the pinned version of the puppet-agent dependency has been pruned from
the builds server.  This patch addresses the problem by pinning to 1.0.0 which
is a released version and should not be pruned.

(maint) Pin 2.1.x against puppet-agent 1.0.0

---

project.clj

This commit bumps the puppet-server lein-ezbake dependency to 0.2.9.
The primary change the new release has that Puppet Server is interested
in is quiet debug output by default during package installation.

(SERVER-541) Bump lein-ezbake dependency to 0.2.9

---

project.clj

This commit bumps the puppet-server lein-ezbake dependency to 0.3.4.
The primary change the new release has that Puppet Server is interested
in is quiet debug output by default during package installation.

(SERVER-541) Bump lein-ezbake dependency to 0.3.4

---

acceptance/README.md
acceptance/README_LOCAL_VM.md
acceptance/config/beaker/jenkins/redhat7-64m-64a.cfg
acceptance/suites/pre_suite/puppet3_compat/00_setup_environment.rb
acceptance/suites/pre_suite/puppet3_compat/10_install_release_repos.rb
acceptance/suites/pre_suite/puppet3_compat/30_install_dev_repos.rb
acceptance/suites/pre_suite/puppet3_compat/70_install_puppet.rb
acceptance/suites/pre_suite/puppet3_compat/README.markdown
acceptance/suites/puppet3_tests/010_hello_world/testtest.rb
acceptance/suites/puppet3_tests/README.markdown
dev/scripts/server545_puppet3_compatibility.sh

Without this patch there is no location to add acceptance tests that exercise
Puppet 3.x agents against Puppet Server 2.0.  This patch addresses the problem
by creating a new suite that maps to a new Jenkins job.  The pre_suite for this
new job will install Puppet 3.x legacy agents specified by the
PUPPET_LEGACY_VERSION environment variable.

(SERVER-545) Add ability to test Puppet 3.x agents

---

acceptance/suites/puppet3_tests/010_hello_world/testtest.rb

Without this patch the post suite is failing in the new CI job created
as part of QENG-2227.  The post suite fails trying to copy the server
logs because the server has never started.  This patch addresses the
problem by doing a single agent run against the server, which was the
original behavior of the basic testtest file.

(SERVER-545) Fix CI failure in post_suite log copy

---

project.clj
src/clj/puppetlabs/puppetserver/ring/middleware/params.clj
src/clj/puppetlabs/services/request_handler/request_handler_core.clj
test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj

Due to some conflicting opinions about how request bodies should be processed between the Ruby Puppet code and ring's 'params' middleware, our current code has the unfortunate behavior of reading the body of the HTTP request into memory twice for any requests that are routed into the JRuby layer.
We can prevent this by duplicating a few functions from the ring middleware library in our own code base, which isn't awesome, but seems preferable to the unnecessary extra memory usage (which can be a pretty big chunk of RAM for requests like catalog/report).

(SERVER-544) stop duplicating request body for jruby

---

README_BRANCHING.md

This commit contains some updates to the README_BRANCHING.md document
related to our change in strategy to do 2.1 development from the 2.1.x
branch and unfreeze the master branch for periodic mergeups from the
stable and 2.1.x branches.

(MAINT) Updates to README_BRANCHING.md related to 2.1 release

---

src/clj/puppetlabs/services/jruby/jruby_puppet_schemas.clj

This commit removes a reference to the old default value of
`num cpus + 2` for the `max-active-instances` setting.

(MAINT) Fix docstring re: num cpus

---

documentation/tuning_guide.markdown

This commit updates the tuning guide doc to be more explicit
about the default values for `max-active-instances`, including
an explicit description of the behavior in 2.0.0.

(MAINT) Update tuning guide to be explicit about 2.0 defaults

---

project.clj
src/clj/puppetlabs/puppetserver/certificate_authority.clj
src/clj/puppetlabs/services/ca/certificate_authority_core.clj
src/clj/puppetlabs/services/ca/certificate_authority_service.clj
src/clj/puppetlabs/services/master/master_core.clj
src/clj/puppetlabs/services/master/master_service.clj
src/clj/puppetlabs/services/puppet_admin/puppet_admin_core.clj
test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj
test/unit/puppetlabs/services/master/master_core_test.clj

This PR ports our web routing library over from compojure to comidi.  This will allow us to introspect our web routes for things like metrics, middleware, documentation, etc. in the future.

(PE-8645) use comidi for routes

---

src/clj/puppetlabs/puppetserver/cli/irb.clj
src/clj/puppetlabs/puppetserver/cli/ruby.clj

The alias was changed in the namespace declaration but a couple usages
were missed.

(MAINT) Fix missed usages of renamed namespace

---

src/clj/puppetlabs/services/master/master_core.clj
test/unit/puppetlabs/services/master/master_core_test.clj

This commit re-enables the legacy Puppet Ruby status endpoint.  It
simply whitelists the endpoint in Puppet Server code so that the request
can be passed through to Ruby Puppet code.

(SERVER-564) Re-enable legacy Puppet status endpoint

---

project.clj

This commit adds "master" to the puppetserver project's name in
project.clj - resulting in 2.1.0-master-SNAPSHOT instead of
2.1.0-SNAPSHOT.  The motivation for this change is that it appears
that with race conditions around the CI packaging jobs that
packages being built for the 2.1.x branch, also currently using the
name 2.1.0-SNAPSHOT, end up being built with some artifacts from one
branch and some from another when the jobs are built around the same
time on the same machine.  The inclusion of a branch name in the version
should allow for these to be unique per branch without forcing us to
commit to what the real next version needs to be for either branch.

(MAINT) Add master to version string

---

acceptance/suites/tests/010-puppetserver-cli/subcommand/foreground.rb
acceptance/suites/tests/010-puppetserver-cli/subcommand/gem.rb

@camlow325 Moving this over to stable from master ([old PR](https://github.com/puppetlabs/puppet-server/pull/520))

Server 390 acceptance test for foreground command

---

acceptance/suites/pre_suite/puppet3_compat/70_install_puppet.rb

As recommended by the Beaker developers.

(QENG-2385) Use install_puppet to install puppet.

---

project.clj

This commit adds "2.1.x" to the puppetserver project's name in
project.clj - resulting in 2.1.0-2.1.x-SNAPSHOT instead of
2.1.0-SNAPSHOT. The motivation for this change is that it appears
that with race conditions around the CI packaging jobs that
packages being built for the master branch, also currently using the
name 2.1.0-SNAPSHOT, end up being built with some artifacts from one
branch and some from another when the jobs are built around the same
time on the same machine. The inclusion of a branch name in the version
should allow for these to be unique per branch without forcing us to
commit to what the real next version needs to be for either branch.

(MAINT) Add 2.1.x to version string

---

spec/puppet-server-lib/puppet/jvm/http_client_spec.rb
src/ruby/puppet-server-lib/puppet/server/http_client.rb

This commit corrects a problem with the initialization of HTTP client
options which had been introduced by SERVER-530, the merge-up of
changes from 1.0.8 into the 2.1.x branch.  The merge-up had caused
HTTP requests to try to call the `setConnectTimeoutMilliseconds` and
`setIdleTimeoutMilliseconds` methods on the `RequestOptions` class.
`RequestOptions` does not support those methods; they can only
be configured at the client and not a per-request level.  To adjust
for this, this PR moves the invocation of the timeout methods to the
client level via `ClientOptions`.

(SERVER-614) Initialize timeouts from ClientOptions

---

acceptance/lib/puppetserver/acceptance/compat_utils.rb
acceptance/suites/pre_suite/puppet3_compat/70_install_puppet.rb
acceptance/suites/pre_suite/puppet3_compat/71_install_simmons_module.rb
acceptance/suites/pre_suite/puppet3_compat/72_disable_authconf.rb
acceptance/suites/pre_suite/puppet3_compat/80_configure_agents.rb
acceptance/suites/puppet3_tests/020_backwards_compat/binary_file_test.rb
acceptance/suites/puppet3_tests/020_backwards_compat/content_file_test.rb
acceptance/suites/puppet3_tests/020_backwards_compat/custom_fact_output_test.rb
acceptance/suites/puppet3_tests/020_backwards_compat/external_fact_output_test.rb
acceptance/suites/puppet3_tests/020_backwards_compat/mount_point_binary_file_test.rb
acceptance/suites/puppet3_tests/020_backwards_compat/mount_point_source_file_test.rb
acceptance/suites/puppet3_tests/020_backwards_compat/recursive_directory_test.rb
acceptance/suites/puppet3_tests/020_backwards_compat/source_file_test.rb
dev/scripts/server545_puppet3_compatibility.sh

This commit adds a suite of acceptance tests using the nwolfe-simmons
module to exercise various parts of the master/server HTTP API.
----
module: https://github.com/nwolfe/puppet-simmons/tree/0.3.1

(SERVER-545) 3x->4x compatibility acceptance tests

---

acceptance/suites/tests/010-puppetserver-cli/subcommand/foreground.rb

The `timeout` command isn't available on RH5, so skip it

(SERVER-653) Skip foreground test on RHEL5

---

src/clj/puppetlabs/puppetserver/cli/gem.clj
src/clj/puppetlabs/puppetserver/cli/irb.clj
src/clj/puppetlabs/puppetserver/cli/ruby.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_internal.clj
test/unit/puppetlabs/services/jruby/jruby_interpreter_test.clj

This commit has changes which allow Puppet Server to boot without
JRuby's jopenssl trying to load its own Bouncy Castle jar.
Prior to JRuby 1.7.20, we set the JARS_NO_REQUIRE environment variable
onto the ScriptingContainer in order to instruct JRuby's
jar-dependencies to not try to load the Bouncy Castle jar - which we
intentionally exclude from the Puppet Server uberjar so that
'jvm-ssl-utils' can pull in its own version.
In JRuby 1.7.20's jopenssl, jar-dependencies was not being required
implicitly and so the JARS_NO_REQUIRE variable was ignored.  This
led Puppet Server to fail to boot because the Bouncy Castle jar
could not be loaded.
This commit has Puppet Server do an explicit require of
jar-dependencies so that the JARS_NO_REQUIRE variable can be honored
properly again.  It also …

(SERVER-655) Fix Bouncy Castle jar load failure

---

acceptance/lib/puppetserver/acceptance/compat_utils.rb
acceptance/suites/pre_suite/puppet3_compat/71_install_simmons_module.rb
acceptance/suites/puppet3_tests/020_backwards_compat/binary_file_test.rb
acceptance/suites/puppet3_tests/020_backwards_compat/content_file_test.rb
acceptance/suites/puppet3_tests/020_backwards_compat/custom_fact_output_test.rb
acceptance/suites/puppet3_tests/020_backwards_compat/external_fact_output_test.rb
acceptance/suites/puppet3_tests/020_backwards_compat/mount_point_binary_file_test.rb
acceptance/suites/puppet3_tests/020_backwards_compat/mount_point_source_file_test.rb
acceptance/suites/puppet3_tests/020_backwards_compat/recursive_directory_test.rb
acceptance/suites/puppet3_tests/020_backwards_compat/source_file_test.rb

This commit includes some changes to the Puppet 3.x acceptance tests to
support testing in a Windows environment.  These include:
1) Dynamically determine the temp directory to store synced simmons
module content into.
2) Replace use of openssl with md5sum for performing md5 sums of files
on the agent node.  md5sum is available on Windows nodes via cygwin.
3) Unskip external_fact_output_test for Windows since it is viable for
Windows agents.

(SERVER-652) Changes to acceptance tests to support Windows

---

src/clj/puppetlabs/puppetserver/cli/irb.clj
src/clj/puppetlabs/puppetserver/cli/ruby.clj

This commit adds onto the changes made in the first PR for SERVER-655.
In the first PR, the ruby subcommand was still errantly trying to load
the JRuby Bouncy Castle jar when a require was passed via a "-r" flag on
the command line.  The same behavior was not occurring for the irb
subcommand, though.  The difference was that the irb subcommand already
had logic to front load the Ruby load path with the list of libraries
that JRuby uses for loading its intenal libs.  One of those paths is the
path to jar-dependencies.  This commit addresses that and syncs up the
irb and ruby subcommands to basically have the same logic.

(SERVER-655) Fix Bouncy Castle cli command failure

---

src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_core_test.clj

Without this patch puppetserver fails to start with with an uncaught exception
when these three settings are not defined.  This is a problem because these
settings are strictly necessary because they are defined in the underlying
puppet implementation.  This patch addresses the problem by settings the values
to nil which will cause puppetserver to consult puppet for the values.
The exception this fixes looks like:
clojure.lang.ExceptionInfo: Output of initialize-config does not match schema:
{:master-code-dir missing-required-key,
:master-log-dir missing-required-key,
:ruby-load-path missing-required-key,
:master-run-dir missing-required-key}
at puppetlabs.services.jruby.jruby_puppet_core$eval14631$initialize_config__14632.invoke (jruby_puppet_core.clj:84)
...

(SERVER-647) Make master-{code,run,log}-dir settings optional

---

src/clj/puppetlabs/services/legacy_routes/legacy_routes_service.clj

Without this patch the legacy-routes-service specifies a dependency on the
master-service and the ca-service.  This is a problem because the
master-service is not implemented in Puppet Enterprise, instead the
pe-master-service is implemented.  This patch addresses the problem by removing
the dependency on the master service which will allow the legacy-service to
operate in PE.
The dependency is no longer necessary because the catch-all 404 handler has
been removed from the master-service which allows either service to handle
request before handing them to the other service.

(maint) Remove legacy-service dependency on Master and CA for PE

---

project.clj

This commit bumps the lein-ezbake dependency to version 0.3.6.  This is
needed in order to allow Puppet Server packaging to include an updated
version of the foreground command which allows the HOME environment
variable to be set for the puppet user when the foreground subcommand is
executed.  Without this change, attempts to execute the foreground
subcommand on Ubuntu via sudo would fail because an inappropriate value
for the HOME environment variable was being used.

(SERVER-657) Bump lein-ezbake dependency to 0.3.6

---

acceptance/lib/puppetserver/acceptance/compat_utils.rb
acceptance/suites/puppet3_tests/020_backwards_compat/binary_file_test.rb
acceptance/suites/puppet3_tests/020_backwards_compat/content_file_test.rb
acceptance/suites/puppet3_tests/020_backwards_compat/custom_fact_output_test.rb
acceptance/suites/puppet3_tests/020_backwards_compat/external_fact_output_test.rb
acceptance/suites/puppet3_tests/020_backwards_compat/mount_point_binary_file_test.rb
acceptance/suites/puppet3_tests/020_backwards_compat/mount_point_source_file_test.rb
acceptance/suites/puppet3_tests/020_backwards_compat/recursive_directory_test.rb
acceptance/suites/puppet3_tests/020_backwards_compat/source_file_test.rb

This changes the tests to iterate over all agents instead of just the
legacy one, which means the 4.x agent on the master will now be tested
against the 4.x master the same way as the 3.x agents.

(SERVER-649) Additionally test 4x->4x in compatibility tests

---

README_BRANCHING.md

This commit contains some updates to the text in the
`README_BRANCHING.md` document related to the upcoming 1.1 and 2.2
releases.

(MAINT) Updates to README_BRANCHING.md for 1.1/2.1 releases

---

project.clj

This commit bumps the lein-ezbake dependency to version 0.2.10.  This is
needed in order to allow Puppet Server packaging to include an updated
version of the foreground command which allows the HOME environment
variable to be set for the puppet user when the foreground subcommand is
executed.  Without this change, attempts to execute the foreground
subcommand on Ubuntu could result in an inappropriate value for the
HOME environment variable being used.

(SERVER-657) Bump lein-ezbake dependency to 0.2.10

---

src/clj/puppetlabs/services/jruby/jruby_puppet_internal.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_schemas.clj
test/integration/puppetlabs/services/jruby/jruby_puppet_internal_test.clj

This commit restores the ability for connect and idle timeout settings
configured for Puppet Server to be honored for HTTP client requests.
The code to support these settings had previously been inadvertently
removed as part of some refactor work for SERVER-325.

(SERVER-659) Restore broken http client timeout settings

---

Gemfile

This commit bumps the beaker dependency to 2.12.0.

(MAINT) Bump beaker dependency to 2.12.0

---

acceptance/suites/pre_suite/foss/30_install_dev_repos.rb
acceptance/suites/pre_suite/puppet3_compat/30_install_dev_repos.rb

This commit configures options explicitly for the
'30_install_dev_repos.rb' for package installs.  This was done
specifically to configure the use of the 'PC1' repo since this is
required for use with AIO testing.  The need for this change was
introduced by the beaker refactoring done for BKR-184 which removed PC1
from the default list of repos that beaker checks during installation.

(MAINT) Add install options to 'install_dev_repos'

---

documentation/compatibility_with_puppet_agent.markdown
documentation/index.markdown
documentation/release_notes.markdown

Without this patch the documentation directory the Docs team frequently looks
at doesn't have an information about the Puppet 3 URL compatibility feature we
added to Puppet Server 2.1.
This patch adds those documents, focusing on these things:
* The actual structure of the URL
* How `auth.conf` works with Puppet 3 agents
* An example of a customized auth.conf
This patch also adds information about changes in 2.1, specifically the
`max-requests` feature added as SERVER-325.

(SERVER-625) Add Puppet 3 URL compatibility notes

---

src/clj/puppetlabs/services/legacy_routes/legacy_routes_service.clj
src/clj/puppetlabs/services/master/master_core.clj
src/clj/puppetlabs/services/master/master_service.clj
test/integration/puppetlabs/services/legacy_routes/legacy_routes_test.clj

This commit changes the logic in the legacy-routes-service to get the
route of the master-service via the service protocol name rather than by
a hard-coded service name.  This allows for the legacy-routes-service to
pull the route from whatever service implementing the MasterService
protocol happens to be in the service stack, i.e., master-service for
OSS or pe-master-service for PE.

(SERVER-683) Dynamically get master service for legacy route service

---

dev/request-logging-dev.xml
ezbake/config/logback.xml
resources/ext/config/request-logging.xml

This commit restores the 'scan=true' attribute to the configuration
element in the logback and request-logging-dev xml files.  This had been
added previously as part of SERVER-275 but errantly lost in the
transition from ezbake to the lein-ezbake plugin between the Puppet
Server 1.0.2 and 1.0.8 releases.

(SERVER-682) Restore 'scan=true' to logback xml files

---

Rakefile

This commit pins the version of bundler that is used when executing spec
tests to 1.9.9.  Starting with version 1.10.0 of bundler, the .gemspec
file from core Ruby Puppet is automatically validated at 'bundle install'
startup.  The rubygems version in JRuby, 2.4.6, is not the same as the
rubygems version in the core Puppet repo's .gemspec file, 1.8.24.  This
causes validation to fail and, therefore, for the "bundle install" to
fail.  Pinning to bundler version 1.9.9 allows validation to be
bypassed for now.  See SERVER-697 for follow-up on long-term solution.

(MAINT) Pin bundler version to 1.9.9

---

.gitmodules

This commit temporarily changes Puppet Server to point at a branch of
the core Puppet repo which is based on the Puppet 4.1.0 tag but with a
couple of changes to the acceptance tests which would otherwise cause
failures when the tests are run.  This should only be latest on the
master branch for a very short period of time, hopefully until the fixes
for the acceptance tests land in the core Puppet repo.
Changes on the acceptance test branch are:
* Cherry-picked fix for PUP-4652 for the
`4420_pluginfacts_should_be_resolvable_on_agent.rb` test.
* Skipped broken `environment_scenario` tests documented in PUP-4659.

(MAINT) Update Puppet submodule tests for 4.1.0 acceptance test fixes

---

documentation/install_from_packages.markdown

As someone not super familir to Debian file defaults, had to do a bit of searching to find out how to set puppetserver memory on Ubuntu! :smile:
I did it as a bulletpoint list for if this is at a different location on other OS's and can be easily added in the future

(docs) Adds Debian specific config location

---

src/clj/puppetlabs/services/config/puppet_server_config_core.clj

Not actually needed in Puppet Server, but will be needed for file sync.

Add $codedir to the list of settings read from Puppet

---

acceptance/lib/helper.rb
acceptance/suites/tests/00_smoke/validate-excluded-bc-jars.rb

JARS_NO_REQUIRE is an environment variable which, if set to `true`, will prevent
the loading of embedded jars using the `require_jar' method of the
`jar-dependencies` gem.
This is required to ensure that jruby-openssel, which is loaded by the JRuby
Kernel whenever ruby code requires 'openssl', does not attempt to load embedded
bouncy castle jars onto the classpath. The effect is to ensure that
jruby-openssl uses the bouncycastle included as a requirement of
jvm-certificate-authority rather than the version included with JRuby, as well
as preventing jvm-ceritificate-authority from using JRuby's bouncycastle.
This commit also adds an integration smoke test to ensure that the jar is
actually excluded by listing the contents of the jar then using the
`assert_no_match` minitest method to …

(SERVER-701) Cherry-pick jar exclusion acceptance test

---

src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_core_test.clj

Add hardcoded defaults for the :master-_-dir settings so that
the behavior of puppetserver will be in line with our
docs when these settings are absent.

(SERVER-692) Add defaults to master dir settings

---

documentation/puppetserver_vs_passenger.markdown

This reverts commit 76b6881970a409f0eb798857114eaf30e1242b63, because we added
the /status endpoint back in Puppet Server 1.1 and 2.1.
This should also be merged up into master.

Revert "(docs) Add mention of missing /status endpoint"

---

acceptance/suites/tests/010-puppetserver-cli/subcommand/SERVER-297_common_behavior.rb
acceptance/suites/tests/010-puppetserver-cli/subcommand/gem.rb
src/clj/puppetlabs/puppetserver/cli/gem.clj
src/clj/puppetlabs/puppetserver/cli/irb.clj
src/clj/puppetlabs/puppetserver/cli/ruby.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_internal.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_schemas.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_core_test.clj

Without this patch the manner in which environment variables are handled in the
JRuby portions of puppet-server vary across the use cases of the `puppetserver
{gem,irb,ruby}` command line utilities in addition to the service itself.  This
is a problem because the behaviors have not kept in sync with one another over
time so there has been divergence at times, e.g. `puppetserver gem env`
currently fails because PATH is unset in that scenario but set in others, e.g.
the production service.
This patch addresses the problem by consolidating all of the environment
handling behavior into a single authoritative method.  The behavior itself
remains unchanged, GEM_HOME is set based on the config file value, PATH and
HOME are the only variables allowed to flow through to JRuby unmodified, all
other …

(SERVER-297) Consolidate JRuby environment handling

---

acceptance/suites/tests/010-puppetserver-cli/subcommand/irb.rb
acceptance/suites/tests/010-puppetserver-cli/subcommand/ruby.rb

The smoke tests are failing checking that FOO_DEBUG is being preserved for the
irb and ruby subcommands.  This is a problem because the behavior has been
consolidated around the behavior of the production scripting container which is
to filter out variables like FOO_DEBUG.  This patch addresses the problem by
changing the test to assert the desired behavior.

(maint) Fix failing FOO_DEBUG irb and ruby CLI tests

---

acceptance/suites/tests/010-puppetserver-cli/subcommand/SERVER-297_common_behavior.rb

(maint) Fix failing smoke test on irb -e
Fixes this error:
IRB::UnrecognizedSwitch: Unrecognized switch: -e
irb reads from STDIN, it doesn't have a -e flag like the ruby command does.
(maint) Fix failing smoke test on undefined var output
Fixes:
#<NameError: undefined local variable or method `output'

(SERVER-297) Fix failing smoke tests on irb -e and output undefined var

---

src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_core_test.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_service_test.clj

This commit adds some logic which searches for a file named 'facter.jar'
in the ruby load path and, if found, adds the file to the system
classloader's classpath.  This is needed for compatibility with Facter
3+.  The jar needs to be in the system classloader's classpath in order
for Facter's backing native shared library to only be loaded once by a
classloader, avoiding an error which would otherwise occur if attempts
were made to load the library into more than 1 JRuby container instance
classloader.

(SERVER-718) Load facter jar into system classloader classpath

---

src/clj/puppetlabs/services/ca/certificate_authority_core.clj
test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj

This commit changes the validation for the 'certificate_status' endpoint
to allow for the request's content-type to include a "charset"
parameter.  Previously, the presence of a "charset" parameter in the
content-type would cause the content-type to fail validation with an
HTTP 415 (unsupported media type) error.

(SERVER-646) Allow charset for certificate_status content-type

---

src/clj/puppetlabs/services/ca/certificate_authority_core.clj
test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj

This commit wraps plain text error responses to CA requests with a
Content-Type of "text/plain" for 'error' cases in which liberator does
not automatically set the Content-Type.  Previously, these error cases
would have resulted in a Content-Type of ";charset=UTF-8" being
delivered in the response.  Some clients would subsequently fail to be
able to parse the error response correctly.

(SERVER-723) Return good Content-Type for CA errors

---

acceptance/suites/tests/010-puppetserver-cli/subcommand/SERVER-297_common_behavior.rb
acceptance/suites/tests/010-puppetserver-cli/subcommand/gem.rb
acceptance/suites/tests/010-puppetserver-cli/subcommand/irb.rb
acceptance/suites/tests/010-puppetserver-cli/subcommand/ruby.rb
project.clj
src/clj/puppetlabs/puppetserver/cli/gem.clj
src/clj/puppetlabs/puppetserver/cli/irb.clj
src/clj/puppetlabs/puppetserver/cli/ruby.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_internal.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_schemas.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_core_test.clj

Without this patch the manner in which environment variables are handled
in the JRuby portions of puppet-server vary across the use cases of the
`puppetserver {gem,irb,ruby}` command line utilities in addition to the
service itself.  This is a problem because the behaviors have not kept
in sync with one another over time so there has been divergence at
times, e.g. `puppetserver gem env` currently fails because PATH is unset
in that scenario but set in others, e.g. the production service.
This patch addresses the problem by consolidating all of the environment
handling behavior into a single authoritative method.  The behavior
itself remains unchanged, GEM_HOME is set based on the config file
value, PATH and HOME are the only variables allowed to flow through to
JRuby unmodified, all other …

(SERVER-721) Consolidate JRuby environment handling

---

project.clj

This commit bumps Puppet Server's JRuby dependency to 1.7.20.1 in order
to mitigate RubyGems CVE-2015-4020.

(SERVER-761) Bump JRuby dependency to version 1.7.20.1

---

.gitmodules
Rakefile

This commit contains a couple of changes:
1) Switch the ruby/puppet submodule back from a commit on
camlow325/puppet to one on puppetlabs/puppet.  The prior submodule
was used temporarily because of broken tests being skipped per
PUP-4659.  The PUP ticket has been fixed now, though, so these
tests should be runnable again.
2) Unpin bundler version 1.9.9.  This was done previously because
1.10.0 would fail because of a rubygems version mismatch between the
Puppet .gemspec requirement and JRuby rubygems version.  The Puppet
.gemspec rubygems requirement is no longer present with this new
Puppet submodule and, therefore, the bundler pin should no longer be
needed.

(MAINT) Switch puppet submodule to core Puppet and remove bundler pin

---

.gitmodules

This commit is a follow-on to the commit from PR #609, e1abff.  In that
commit, the Puppet submodule had been pointed from the camlow325/puppet
fork back to puppetlabs/puppet under the assumption that the underlying
test fixes would be good for Puppet Server acceptance testing to use.
Unfortunately, this is not yet the case because of the following issues:
1) Puppet Server acceptance for the master branch currently uses
puppet-agent 1.1.0 (puppet core 4.1.0).  Tests created/modified for the
following tickets were done post-puppet core 4.1.0 - PUP-2638 and
PUP-4538.
2) The new 'calling_all_functions' test is not currently working for the
agent configuration that Puppet Server uses - see PUP-4749.
This commit reverts back to the camlow325/puppet fork temporarily but
with the fixes for the …

(MAINT) cherry-pick PUP-4659 test fixes

---

src/clj/puppetlabs/services/legacy_routes/legacy_routes_core.clj
src/clj/puppetlabs/services/legacy_routes/legacy_routes_service.clj
test/integration/puppetlabs/puppetserver/bootstrap_testutils.clj
test/integration/puppetlabs/services/legacy_routes/legacy_routes_test.clj
test/unit/puppetlabs/services/legacy_routes/legacy_routes_core_test.clj

Previously all CA routes were forwarded directly the core CA functions,
even if the disabled CA service was enabled. This commit removes the
legacy CA forwarding when the disabled CA service is enabled.

(SERVER-759) Do not forward disabled CA routes

---

.gitmodules
acceptance/lib/helper.rb

This commit bumps the puppet-agent version dependency and puppet
submodule forward to a version which is closer to what is
planned for release in puppet-agent 1.2.0.  This is being done to get
some early feedback on potential conflicts between the forthcoming
puppet-agent release and latest puppetserver master branch code.

(MAINT) Bump puppet-agent dep and puppet module - 2015-06-18

---

spec/puppet-server-lib/puppet/jvm/master_spec.rb

This commit bumps the expected Puppet version in the `master_spec.rb`
Ruby spec test up to 4.2.0, in order to line up with the new version of
the Puppet submodule which is being used as of PR #619 being merged.

(MAINT) Bump expected Puppet version to 4.2.0 in spec test

---

project.clj

Updates since 0.3.6:
* Fixes for service account handling on package
and source based installations
* Update default startup timeout to 180 seconds
* Remove EL-5 as a build target
* Add support for systemd tmpfiles.d configs
* On package upgrade, update service account information (home dir,
group membership, etc) if necessary
* Packaging: Fix varlibdir to use real_name for PE (so its
app_data/lib/puppetdb, not app_data/lib/pe-puppetdb)
* Packaging: In Debian, ignore service stops for services that are already
stopped during upgrade.
* Packaging: In Debian, add a prerm section to stop services gracefully on a
failed upgrade.
* Packaging: Fixed lots of inconsistencies between PE and FOSS, now we are
closer then ever.
* Packaging: Users were being created using the old FOSS based homedirs. …

Update ezbake to 0.3.11

---

documentation/_puppetserver_nav.html

In the docs.puppetlabs.com website, we use a central config file to assign an
HTML fragment as the navigation sidebar for a group of pages.
It used to be that we had to store these fragments in one specific directory,
but we recently revised our tools so we could load an HTML fragment from any
content directory.
This makes it possible to maintain the navigation TOC right alongside the
content that it governs. The PuppetDB team have been doing this for a few months
now, and it makes it much easier to add or delete a page.
Once this PR is merged, there will be two new tasks for maintaining these docs:
* If you add a page, add it to the TOC. Its URL should be an absolute path from
the root of the docs site, and should use a {{server_version}} placeholder
to represent the version number.
* …

(docs) Store navigation sidebar alongside Puppet Server docs content

---

test/integration/puppetlabs/services/jruby/jruby_pool_int_test.clj

This commit adds a couple of more JRuby pool flush tests:
1) Make multiple JRuby flush requests back-to-back and ensure that
nothing obviously *bad* happens.
2) Ensure that a file handle open from Ruby code run in a
`ScriptingContainer` is not automatically invalidated when a
pool flush is requested.

(SERVER-251) Add a couple of more jruby flush tests

---

documentation/configuration.markdown
documentation/puppet_conf_setting_diffs.markdown
resources/ext/config/conf.d/puppetserver.conf

Improve the documentation around the consequences of changing the master-dir settings in `puppetserver.conf`.

(SERVER-719) Improve documentation around master-dir settings

---

project.clj

Fixes for correctly handling service restarts for package
upgrades on Debian and Ubuntu.
Fixes for upgrading the service account on package upgrade

(packaging) Update ezbake to 0.3.13

---

dev/puppet-server.conf.sample

Without this change, the dev sample config file cannot be used without
modification - if they are, the server will crash during startup with an
error: "Permission denied - /var/log/puppetlabs"
This error was introduced by f7627a78aa25e647501c22dac4f6d318c6874137

(maint) Fix dev sample config file

---

test/integration/puppetlabs/services/jruby/jruby_pool_int_test.clj

This commit modifies some of the work previously committed for
SERVER-251, mostly due to concerns about the length of execution time
added to the suite.
1) The `admin-api-multiple-flush-jruby-pool-test` was eliminated.  The
value of the test was already a bit dubious due to some of the variable
timing in the execution of the test and limited ability to validate the
system's behavior with concurrent flush requests.  More importantly, the
test appeared to add 5 minutes or so to the overall execution time for
the test suite - increasing from 6 minutes or so to 11 minutes or so.
This commit removes the test completely.
2) The `hold-instance-while-pool-flush-in-progress-test` was modified to
just try to initialize 2 `jruby-puppet` instances instead of 4.  This
should speed the execution of the …

(SERVER-251) Tweak jruby-flush tests because of performance issues

---

.gitmodules
dev/puppet-server.conf.sample
test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
test/unit/puppetlabs/services/ca/ca_testutils.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_core_test.clj
test/unit/puppetlabs/services/jruby/jruby_testutils.clj

I chose version 1.3.4 as that was the version in the latest PE 3.8.1.  We can bump this up to newer versions for master branch, etc., as we do the merge-up from here.

(SERVER-781) Add hiera as submodule

---

acceptance/lib/helper.rb

This commit bumps the Ruby Puppet submodule up to version 4.2.0.

(SERVER-789) Bump puppet submodule to 4.2.0

---

documentation/configuration.markdown

This commit includes some updates to the documentation to qualify
which endpoints are supported by the `allow-header-cert-info` setting
in the `master.conf` section.

(SERVER-765) Qualify endpoints supported by `allow-header-cert-info`

---

src/clj/puppetlabs/services/request_handler/request_handler_core.clj

This change doesn't have any value for this project on its own, but it
is necessary for downstream consumers (like PE) which will consume this
code directly.

(maint) Refactor handle-request for reuse

---

acceptance/lib/helper.rb
spec/puppet-server-lib/puppet/jvm/master_spec.rb

Without this patch the tests are mixing and matching the version of Puppet
being installed.  For example, the legacy puppet agent tests are installing
3.8.1 while the unit and integration tests run with a Puppet 3.7 version from
the submodule.
This patch addresses the problem by updating the behavior of the tests to use
the same version, 3.8.1.

(maint) Update submodule and tests to Puppet 3.8.1

---

documentation/configuration.markdown

This commit updates the endpoint links that the `allow-header-cert-info`
docs reference.  The links should now point to locations which are valid
for Puppet Server 2.x / Puppet 4.x.

(SERVER-765) Updated endpoint links for `allow-header-cert-info` docs

---

src/clj/puppetlabs/services/request_handler/request_handler_core.clj
src/clj/puppetlabs/services/request_handler/request_handler_service.clj
test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj

This commit modifies the `request-handler` service to use more
of a ring-middleware style of composing functions for building
up the final request handler function.  This should make it easier
to share code / extend the service in subsequent development.

(SERVER-811) port request handler service to middleware-style

---

src/clj/puppetlabs/services/request_handler/request_handler_core.clj
src/clj/puppetlabs/services/request_handler/request_handler_service.clj
test/integration/puppetlabs/puppetserver/error_handling_int_test.clj
test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj

Merge conflicts:
* a couple places where we're testing against the Puppet or puppet-agent version number (obviously, different across branches)
* `puppetlabs.puppetserver.error-handling-int-test/test-HTTP-500` had to be updated to no longer refer to the `handle-request` function which was deleted in #645.  This test does not exist on stable.

Merge stable into master

---

.travis.yml

The `sudo: false` flag indicated to Travis-CI that the tests should be
run in a container instead of VM. This should hopefully allow for faster
test results.

(SERVER-808) Enable containerized test running

---

acceptance/README.md
acceptance/README_LOCAL_VM.md
acceptance/lib/helper.rb
acceptance/suites/pre_suite/foss/70_install_puppet.rb

We've been asked to stop using puppetlabs.lan addresses, so I've swapped
them for the preferred names/URIS.

(maint) Stop using .lan addresses

---

acceptance/lib/helper.rb
project.clj
src/java/com/puppetlabs/puppetserver/JRubyPuppet.java
src/ruby/puppet-server-lib/puppet/server/http_client.rb
src/ruby/puppet-server-lib/puppet/server/master.rb
test/integration/puppetlabs/services/jruby/class_info_test.clj

This commit adds two new methods to the JRubyPuppet interface -
`getClassInfoForEnvironment` and `getClassInfoForAllEnvironments` - to
the JRubyPuppet interface.  A corresponding implementation of those in
the `Puppet::Server::Master` Ruby class uses the
`Puppet::InfoService::ClassInformationService` to get class information
for available manifests in environments.

(SERVER-815) Add getClassInfo methods to JRubyPuppet interface

---

src/clj/puppetlabs/puppetserver/certificate_authority.clj

The latter is deprecated in favor of the former; we should no longer see
deprecation warnings during `lein test` for this.

(MAINT) Prefer clj-time/seconds over clj-time/secs

---

acceptance/lib/helper.rb

Previously, puppet-server stable tests were running against a build of
puppet-agent that was from the per-commit pipeline. This meant that it was not
available on all platforms we run puppet-server stable acceptance tests against.
The first commit in this PR bumps the puppet build version to a puppet-agent package version in
nightlies, which is built for all the platforms.
PUP-4824 had some incorrectly written tests that caused errors for our CI.
These have now been fixed in puppet stable. The second commit updates the submodule
(and therefore the acceptance tests we are running) for these fixes.
The second commit does not update the puppet agent/puppet build version in
`acceptance/lib/helper.rb` since the only changes that have been made since the
package we currently have specified …

(maint) Update puppet version to fix acceptance test failures

---

.travis.yml

Given that some of our packages now require java 8, it seems like a good idea
to add travis for it.

(maint) Add java 8 as travis target

---

project.clj
src/clj/puppetlabs/services/config/puppet_server_config_core.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_internal.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_schemas.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj
src/clj/puppetlabs/services/protocols/jruby_puppet.clj
src/clj/puppetlabs/services/request_handler/request_handler_core.clj
test/integration/puppetlabs/services/jruby/jruby_pool_int_test.clj
test/integration/puppetlabs/services/jruby/puppet_environments_int_test.clj
test/unit/puppetlabs/services/ca/certificate_authority_disabled_test.clj
test/unit/puppetlabs/services/jruby/jruby_pool_test.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_agents_test.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_service_test.clj
test/unit/puppetlabs/services/jruby/jruby_testutils.clj
test/unit/puppetlabs/services/master/master_service_test.clj
test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj

This PR introduces a function in the JRuby service protocol that allows consumers to register callback functions, to get a notification when a JRuby instance is requested, borrowed, or returned.

(SERVER-847) jruby event callbacks

---

acceptance/lib/helper.rb

This commit bumps the puppet-agent dependency for CI testing to
d5b768cd20d39a5a04da7ba88006e5dd7b788087.

(MAINT) Bump puppet-agent dep

---

dev/user_repl.clj

This commit fixes the user_repl.clj, previously broken by changes
introduced in SERVER-813.  The primary change in the commit is to rename
`pool->vec` to `registered-instances` per the name change made as part
of the work on that ticket.  The commit also includes some web-routing
and puppet-admin sections missing from the sample repl configuration.

(MAINT) Fix repl per break in SERVER-813

---

src/clj/puppetlabs/services/master/master_core.clj
test/unit/puppetlabs/services/master/master_core_test.clj

This route is used for retrieving information about an environment
catalog. This just passes through handling of the route to puppet, as
with all the similar routes.

(maint) Add handler for /environment/:environment route

---

acceptance/lib/helper.rb

The version we were pinned to has been purged from the nightly repo, so
we need to bump it up to the newest (green) build. This also bumps the
puppet submodule to match the version expected by puppet-agent.

(MAINT) Upgrade puppet-agent package

---

project.clj

This commit adds the "stable" branch name to the 2.1.2-SNAPSHOT
project.clj version in order to distinguish OSS puppet-server versions
being built from the stable branch from those being built from the
master branch.

(MAINT) Add stable branch name to 2.1.2-SNAPSHOT version string

---

project.clj

This commit adds the "master" branch name to the 2.1.2-SNAPSHOT
project.clj version in order to distinguish OSS puppet-server versions
being built from the master branch from those being built from the
stable branch.

(MAINT) Add master branch name to 2.1.2-SNAPSHOT version string

---

documentation/puppetserver_vs_passenger.markdown

Previously we didn't have a message to users describing the different
Ruby runtime versions between Puppet Server and the Agent.
This commit adds a section to the Apache/Passenger->Puppet Server
doc describing the Ruby compatibility requirements for code that
runs on the server vs agent.

(PUP-4536) Add docs comment about module code compatibility

---

dev/puppet-server.conf.sample
dev/user_repl.clj
ezbake/config/conf.d/auth.conf
project.clj
test/integration/puppetlabs/puppetserver/auth_conf_test.clj
test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj
test/integration/puppetlabs/services/puppet_admin/puppet_admin_int_test.clj
test/unit/puppetlabs/services/jruby/jruby_testutils.clj

This commit fills out the new auth.conf with default rules as they're
specified in the legacy Ruby auth.conf. Tests and developer resources
have also been updated to include new required fields.
Planning to do a follow-up pull request including some simple acceptance
tests for these default rules.

(SERVER-846) Default tk-authz auth.conf rules

---

dev/user.clj.sample

user.clj is a special namespace and can't reference anything
complicated or anything that requires java compilation directly.

(MAINT) fix bug in user.clj

---

src/clj/puppetlabs/services/jruby/jruby_puppet_agents.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_internal.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_schemas.clj
src/java/com/puppetlabs/puppetserver/pool/JRubyPool.java
src/java/com/puppetlabs/puppetserver/pool/LockablePool.java
test/integration/puppetlabs/services/jruby/class_info_test.clj
test/integration/puppetlabs/services/jruby/jruby_puppet_internal_test.clj
test/unit/puppetlabs/puppetserver/lockable_pool_test.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_agents_test.clj
test/unit/puppetlabs/services/jruby/jruby_testutils.clj

Rename RegisteredLinkedBlockingDeque to JRubyPool and move the locking logic relating to atomic code deploys into this data structure, so that we have one encapsulated datastructure managing the JRuby pool.
Add tests for our required behavior of this encapsulated data structure.
I have tried to separate out the commits so that adding/moving of files is in a separate commit from modifying those commits and is hopefully easier to understand.

(SERVER-860) Introduce ReentrantReadWriteLock into JRubyPool data structure

---

src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj
test/integration/puppetlabs/services/jruby/jruby_locking_test.clj
test/unit/puppetlabs/services/jruby/jruby_testutils.clj

Add `with-lock` macro to JRuby service, which can be used by other services to
acquiring a lock on the JRubyPool, execute the body, then release the lock.
Add tests that `with-lock` actually does lock the write lock from the
JRubyPool, and add basic tests that `borrow-instance` and `return-instance`
affect the lock in the ways we expect. Add a `get-lock` helper function to get
access to the lock for tests.

(PE-11857) Add with-lock macro to JRuby Service

---

ezbake/config/conf.d/auth.conf

The default "deny all" rule needs to come at the very end and not the
end of the Puppet Labs range, otherwise the entire "user space" range
would be rejected.

(MAINT) Re-order default "deny all" rule

---

src/clj/puppetlabs/services/request_handler/request_handler_core.clj
test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj

Prior to this commit, the JRuby request handler code would
filter out any :params that had been added to the ring request
map by other middleware.  We now have concrete use cases for
this capability, so this commit loosens the restrictions and
allows other middlewares to add to :params, and have those
params still be visible to JRuby.

(SERVER-914) Allow middleware params in jruby requests

---

dev/puppet-server.conf.sample
documentation/configuration.markdown
documentation/external_ssl_termination.markdown
project.clj
src/clj/puppetlabs/services/ca/certificate_authority_service.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj
src/clj/puppetlabs/services/puppet_admin/puppet_admin_service.clj
src/clj/puppetlabs/services/request_handler/request_handler_core.clj
src/clj/puppetlabs/services/request_handler/request_handler_service.clj
test/integration/puppetlabs/puppetserver/auth_conf_test.clj
test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj

This commit changes the Ruby request handler to read client
authentication info from trapperkeeper-authorization when tk-authz is
enabled via the `use-legacy-auth-conf: false` setting.  Support for the
pre-existing method of getting this info - via X-Client headers or an
SSL certificate, depending upon how the `master.allow-header-cert-info`
setting is configured - is preserved in the case that no information can
be derived from tk-authz.  tk-authz is presumed to provide client
authentication info via an `authorization` map within the Ring request
map.

(SERVER-763) Read client auth info from tk-authz when configured

---

spec/puppet-server-lib/puppet/jvm/master_spec.rb

This commit bumps the Puppet submodule up to 91097ad in order to pick up
some recent Puppet acceptance test changes, including the ctime/mtime
fix to the `source_attribute.rb` test for PUP-5272.

(MAINT) Bump puppet submodule to 91097ad

---

src/clj/puppetlabs/services/config/puppet_server_config_service.clj
test/unit/puppetlabs/services/config/puppet_server_config_service_test.clj

Previously, Puppet Server explicitly checked the contents of the
`:webserver` key in determining whether or not it needed to
override webserver settings with those from ruby puppet, meaning
that the settings would always be overridden if a multi-webserver
style configuration is used.
This commit modifies Puppet Server to use the contents of the
configuration at `[:webserver :puppet-server]`, or `:webserver` if
`[:webserver :puppet-server]` does not exist so as to support
multi-webserver configs.

(SERVER-964) Support multi-webserver config

---

acceptance/config/beaker/options.rb
acceptance/suites/tests/authorization/default_rules.rb

This commits moves the name of the config file to options.rb so we can
set it to the PE-specific name in pe-puppet-server-extensions.

(MAINT) Extract puppet server config file name

---

documentation/configuration.markdown
project.clj
src/clj/puppetlabs/puppetserver/ringutils.clj
src/clj/puppetlabs/services/ca/certificate_authority_service.clj
src/clj/puppetlabs/services/puppet_admin/puppet_admin_service.clj
test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj
test/integration/puppetlabs/services/puppet_admin/puppet_admin_int_test.clj
test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj

This commit changes the 'puppet-admin' and 'certificate-status'
endpoints to use trapperkeeper-authorization instead of the client
whitelists for authorization when the whitelist is present in
configuration but empty.
This commit also has a couple of somewhat unrelated changes:
1) Adds an explicit ring-core 1.4.0 conflict resolution dependency to
the project.clj.  comidi 0.1.1 pulls in ring-core 1.3.2, which
conflicts with the ring-core version that
trapperkeeper-authorization pulls in, 1.4.0.
2) Allows the `X509Certificate` for an `ssl-client-cert` to be optional
in a Ring request map.  This is needed because Ring will populate
this key with 'nil' when no SSL client certificate was provided for
the request.  Found this after adding a test for calling
'puppet-admin' with …

(SERVER-915) Enable trapperkeeper-authorization for empty whitelists

---

documentation/configuration.markdown
documentation/deprecated_features.markdown
documentation/index.markdown

This commit adds a deprecated features document to Puppet Server.  The
only features (settings) covered in the doc are those related to the
deprecated of legacy authorization systems in favor of
`trapperkeeper-authorization`'s "auth.conf".

(SERVER-849) Add deprecated features doc to Puppet Server

---

acceptance/lib/helper.rb

This commit deletes the `upgrade_package` method from the helper.rb file.
With it present, the call to `rm -f` that it made for EL-7 systems was
failing because it wasn't handling directories to be removed instead of
files.  By removing this, the test helpers should now be able to use the
beaker-provided `upgrade_package` function instead.

(MAINT) Delete `upgrade_package` method from helper.rb

---

acceptance/lib/helper.rb
src/ruby/puppet-server-lib/puppet/server/auth_config.rb
src/ruby/puppet-server-lib/puppet/server/auth_config_loader.rb
src/ruby/puppet-server-lib/puppet/server/config.rb

This commit registers a dummy AuthConfigLoader with core Ruby Puppet
when Puppet Server is configured with a `use-legacy-auth-conf` of
`false`.  This is done to avoid having the auth.conf be parsed (and
corresponding messages logged) by core Ruby Puppet.

(SERVER-972) Register dummy AuthConfigLoader when not using legacy auth

---

documentation/dev_running_from_source.markdown

The environments dir must be created in the target/master-code-dir to not get the plugin error.
The path for puppet/facter should take priority over other facter/puppets in `$PATH`
Facter PATH was missing /bin

Fix dev instructions

---

documentation/release_notes.markdown

Add Puppet Server 2.1.2 release notes and make some style and formatting edits to older notes. @camlow325

(doc) Add Puppet Server 2.1.2 release notes.

---

documentation/release_notes.markdown

Add Puppet Server 1.1.2 release notes.

(doc) Add 1.1.2 release notes.

---

acceptance/suites/tests/authorization/default_rules.rb
ezbake/config/conf.d/auth.conf

This commit changes the default auth.conf to allow unauthenticated
requests to the /puppet/v3/status endpoint. This same change will be
made to the auth.conf in pe-puppetserver.

(MAINT) Allow unauthenticated requests to /status

---

src/clj/puppetlabs/services/master/master_core.clj
test/unit/puppetlabs/services/master/master_core_test.clj

This commit removes the facts and facts_search endpoints from the master
service routing layer.  These endpoints are no longer supported as of
Puppet 4 and so are no longer necessary to route through from Puppet
Server.

(MAINT) Remove facts and facts_search endpoints from routing

---

acceptance/lib/helper.rb

This commit bumps the puppet submodule to 4.2.3 and puppet-agent
acceptance test dependency to 1.2.7.

(MAINT) Bump puppet deps for 4.2.3 / agent 1.2.7

---

Gemfile

This commit bumps the Gemfile sqa-utils version up to 0.13.3.  This is
needed to pick up support for Ubuntu 15.04 and other newer platforms for
genconfig2.

(MAINT) Bump sqa-utils version to 0.13.3

---

documentation/release_notes.markdown

This commit removes an unused reference to trapperkeeper-authorization
from the release_notes.markdown.

(MAINT) Removed unused trapperkeeper-authorization doc reference

---

src/ruby/puppet-server-lib/puppet/server/auth_config.rb
src/ruby/puppet-server-lib/puppet/server/auth_config_loader.rb

To avoid excessive logging, this commit moves the log statement into the
object constructor and then caches the object from the AuthConfigLoader
class. The log statement is also lowered from INFO level to DEBUG.

(MAINT) Cache AuthConfig to reduce logging

---

acceptance/lib/helper.rb
spec/puppet-server-lib/puppet/jvm/master_spec.rb

This commit bumps the Ruby Puppet submodule up in order to pick up a
Puppet acceptance test "fix" which skips execution of the handle_upstart
test case when running on later systemd-based Ubuntus.

(MAINT) Bump Puppet submodule for upstart vivid test fix

---

acceptance/suites/tests/010-puppetserver-cli/subcommand/foreground.rb

This commit removes an assertion that the "Finished shutdown sequence"
message appears in the output of the puppetserver foreground test.  This
message has been seen to sometimes not appear when puppetserver is shut
down - because an OS may kill the process early if puppetserver's
shutdown hook takes too long to run.  For the OSes where this is
problematic - apparently RedHat-based ones but maybe not Debian-based
ones? - there doesn't appear to be any way to prolong the wait time
when running via "timeout" or pressing CTRL-C in the foreground.

(MAINT) Remove 'finish' assertion from the foreground acceptance test

---

acceptance/lib/helper.rb

This commit bumps the Puppet submodule up to version 28a10df and
corresponding puppet-agent dependency up to d5a07cfe7.

(MAINT) Bump puppet submodule to 28a10df

---

acceptance/suites/tests/010-puppetserver-cli/subcommand/foreground.rb

This commit contains two changes to the foreground acceptance test:
- Bump the run timeout up from 60s to 180s to account for occasional
long startup times.
- Replace validation for appearance of 'finish shutdown' message
with validation for 'beginning shutdown' message to account for cases
where prolonged shutdown logic may lead to the process being
terminated prematurely following SIGINT from the foreground.

(MAINT) Bump foreground test timeout and remove finish check

---

project.clj

Utopic has reached EOL and we no longer build packages for it, yet our
version of ezbake was old enough that it still attempted to build
packages for it and would fail.
This commit bumps us up to a newer version of lein-ezbake which will
allow for local ezbake builds to work properly. Jenkins CI isn't failing
because we override the platforms in ci-job-configs and thus don't rely
on the default platforms defined in lein-ezbake.

(MAINT) Upgrade lein-ezbake

---

documentation/config_file_auth.md

The `auth.conf` docs are missing the `allow-header-cert-info` setting migrated from the now-deprecated `master.conf` in 2.2. Note this change.
Also, emphasize the nature of `auth.conf` changes and the scenarios where we use the new `auth.conf` location and format.

(docs) Further emphasize auth.conf changes

---

src/clj/puppetlabs/services/jruby/jruby_puppet_agents.clj
src/java/com/puppetlabs/puppetserver/RegisteredLinkedBlockingDeque.java
test/unit/puppetlabs/services/jruby/jruby_pool_test.clj
test/unit/puppetlabs/services/jruby/jruby_testutils.clj

Prior to this commit, when a JRuby instance was added to the pool,
it was also added to the list of "registered" instances for the pool
so that we could find an authoritative list of all of the instances
even when some were out on loan.
However, we did not have the corresponding logic to *unregister*
instances from this list when an instance was flushed via
max-requests-per-instance.  This resulted in a reference being
kept to the flushed instances even after they were flushed,
meaning that we could not reclaim all of the memory during
garbage collection.  This caused memory to leak over time.
This commit adds code to unregister instances when they are
flushed, so that we do not retain the extra reference to the
flushed instances, and we are able to garbage collect them
and free up the …

(SERVER-1006) Unregister jruby instances on flush

---

project.clj

This commit bumps the version in the project.clj for puppet-server up to
2.1.3-SNAPSHOT.

(MAINT) Bump project.clj version to 2.1.3-SNAPSHOT

---

src/ruby/puppet-server-lib/puppet/server/http_client.rb

This commit nulls out the reference to the http client object
inside of the JRuby instances when we close them, just to
make 100% sure that they are eligible for garbage collection.

(MAINT) null out http client reference on close

---

acceptance/lib/helper.rb
project.clj

This commit bumps the Puppet submodule for the master branch to 2873a96
and the corresponding puppet agent package version to 2b6b9db.  This
commit also bumps the project.clj version up to a SNAPSHOT for the next
planned Puppet Server release, 2.2.0-master-SNAPSHOT.

(MAINT) Bump master Puppet submodule to 2873a96

---

acceptance/lib/helper.rb
resources/ext/ezbake.conf

This commit bumps the puppet-agent dependency to 1.3.0 and the
corresponding puppet submodule dependency to 4.3.0.

(SERVER-836) Bump puppet-agent dep to 1.3.0, puppet submodule to 4.3.0

---

resources/ext/ezbake.conf

This commit fixes a syntax problem in how the minimum puppet-agent
dependency was previously expressed for Debian - moving a paren to
the left of the version string.

(MAINT) Fix broken puppet-agent debian dependency

---

resources/ext/ezbake.conf

This commit changes the minimum puppet-agent version dependency to
1.3.0.  Previous commits had used 4.3.0.  4.3.0 is the core Puppet
version that is packaged into puppet-agent 1.3.0.

(MAINT) Change puppet-agent minimum dep version to 1.3.0

---

project.clj

This commit bumps the version in the project.clj to 2.2.0 for release.

(MAINT) Bump project.clj to puppet-server 2.2.0 for release

---

project.clj

This commit bumps the puppet-server project.clj version up to
2.2.1-SNAPSHOT.

(MAINT) Bump puppet-server project.clj to 2.2.1-SNAPSHOT

---

src/clj/puppetlabs/services/jruby/jruby_puppet_agents.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_internal.clj
src/java/com/puppetlabs/puppetserver/pool/JRubyPool.java
src/java/com/puppetlabs/puppetserver/pool/LockablePool.java
test/unit/puppetlabs/puppetserver/lockable_pool_test.clj

This commit renames the returnItem method in the JRubyPool and
LockablePool to releaseItem and adds a variant of the method which can
be used to determine whether the item should be released back into the
pool or just discarded.  For cases where an item is flushed, the item is
just discarded without going back into the pool - but with the
associated release lock for the thread being unlocked.

(SERVER-1016) Add pool releaseItem variant for unlocking item w/o return

---

test/integration/puppetlabs/services/jruby/jruby_locking_test.clj
test/unit/puppetlabs/puppetserver/lockable_pool_test.clj
test/unit/puppetlabs/services/jruby/jruby_testutils.clj

This commit fixes a typo in one of the test description strings, and
also makes the assertions in the tests a little more meaningful.

(SERVER-1016) Minor improvements to lock unit tests

---

acceptance/lib/helper.rb
acceptance/suites/pre_suite/foss/30_install_dev_repos.rb
acceptance/suites/tests/00_smoke/puppetdb_integration.rb
acceptance/suites/tests/authorization/default_rules.rb

This commit adds support for installing PuppetDB and writing tests.
Since PuppetDB packages aren't built for as many platforms as Puppet
Server we need to keep a list of supported platforms to protect the
pre-suite step and any tests against PuppetDB from breaking CI.
The PuppetDB in this commit is a relatively simple smoke test that
validates Puppet Server can communicate with PuppetDB and send it agent
information.

(MAINT) Introduce PuppetDB testing 

---

acceptance/suites/tests/010-puppetserver-cli/subcommand/gem.rb

This commit changes the gem subcommand test to pin the version for each
gem to be installed.

(MAINT) Fix gem version test pin failure

---

acceptance/suites/tests/010-puppetserver-cli/subcommand/gem.rb

This commit changes the enumeration of gems in the gem test cleanup to
use just the key name instead of the full key/value pair.  The original
approach would have used the key/value pair as an array representing the
name of the gem to uninstall, which was incorrect.

(MAINT) Change enumeration in gem test cleanup to use key as name

---

acceptance/suites/tests/00_smoke/puppetdb_integration.rb

Since the firewall is off by default and managing it will turn it on for
some/all platforms which causes subsequent tests to fail with connection
errors.

(MAINT) Disable firewall management in PuppetDB test

---

.travis.yml
acceptance/lib/helper.rb
project.clj
spec/puppet-server-lib/puppet/jvm/master_spec.rb

This updates the submodule versions as well as the packaged agent
versions to latest to ensure that we are testing and working against the
latest released puppet-agent.

(maint) Update puppet, hiera, agent versions to latest

---

Gemfile

The prior commit added an extra reference to the httparty gem in the
puppet-server Gemfile which is unnecessary.  This commit removes that
reference.

(MAINT) Remove one httparty gem reference from the Gemfile

---

project.clj

This commit adds "stable" into the puppet-server version, to
disambiguate builds done from the "stable" branch from corresponding
ones done from the "master" branch.

(MAINT) Bump project.clj version to 2.2.2-stable-SNAPSHOT

---

project.clj

The version of lein-ezbake we were on was a few releases behind and
would fail to build packages when doing a `lein with-profile ezbake
ezbake build` since utopic was removed from somewhere.
This commit just brings us up to a newer version that will no longer
attempt to build packages for utopic.

(MAINT) Upgrade ezbake to remove utopic target

---

project.clj

This commit bumps the Puppet Server version in the project.clj up to
2.2.2-master-SNAPSHOT given that we've released 2.2.1 already.

(MAINT) Bump project.clj version to 2.2.2-master-SNAPSHOT

---

documentation/config_file_auth.md

To further emphasize the new supported `trapperkeeper-authorization`
configuration file, format, and methods over the deprecated methods,
divorce them from the deprecated content, elevate them to the primary
part of the `auth.conf` documentation, lower the deprecated content, and
further emphasize the deprecation.
In the process, add more supported settings from the
`trapperkeeper-authorization` documentation to avoid having to point
users away from the Puppet Server documentation.

(docs) Revise auth.conf documentation.

---

acceptance/suites/tests/010-puppetserver-cli/subcommand/gem.rb

As you can see by the diff, the only affect of this merge is to fixup the acceptance test which installs nokogiri.  This has been failing in CI on branches without this change.

Merge 1.x into 2.1.x

---

Gemfile
acceptance/README.md
acceptance/scripts/generic/testrun.sh

Reverts puppetlabs/puppet-server#836

Revert "(QENG-3181) Use beaker-hostgenerator instead of sqa-utils."

---

Gemfile
acceptance/README.md
acceptance/scripts/generic/testrun.sh

Reverts puppetlabs/puppet-server#838

(QENG-3181) Use beaker-hostgenerator instead of sqa-utils

---

project.clj

This commit adds an explicit clojure version to our ezbake configuration.
Without this, leiningen may bring in its own version of clojure, which
can vary depending on which version of lein you are running.
Also, this commit updates us to the latest trapperkeeper for improved
logging testutils.

(MAINT) Fix ezbake clojure version conflict

---

src/clj/puppetlabs/services/protocols/versioned_code.clj

This commit merely adds a protocol for VersionedCodeService but not an
implementation. The implementation will follow in SERVER-875.
This protocol is being exercised in https://github.com/puppetlabs/pe-puppet-server-extensions/pull/506

(SERVER-874) Add protocol for VersionedCodeService

---

src/clj/puppetlabs/services/jruby/jruby_puppet_agents.clj
src/java/com/puppetlabs/puppetserver/pool/JRubyPool.java
src/java/com/puppetlabs/puppetserver/pool/LockablePool.java
test/integration/puppetlabs/services/jruby/jruby_locking_test.clj
test/integration/puppetlabs/services/jruby/puppet_environments_int_test.clj
test/unit/puppetlabs/puppetserver/lockable_pool_test.clj
test/unit/puppetlabs/services/jruby/jruby_pool_test.clj
test/unit/puppetlabs/services/jruby/jruby_testutils.clj

This PR reworks the `JRubyPool` implementation to pull in all of the
concurrent constructs around a single `ReentrantLock`, the primary benefit
being to allow the holder of a write lock to be able to borrow instances
from the pool without running the risk of a deadlock due to competing
borrows that may be occurring from other threads.  The implementation
uses three condition variables to gate borrower and locker access to the
pool, similar to how `LinkedBlockingDeque` does for managing queue takers.
Where the underlying lock construct in the `JRubyPool` class would be a
`ReentrantLock` instead of a `ReentrantReadWriteLock`, this commit also
reworks a few of the unit tests to attempt borrows from non-locking
threads as an indication that the write lock is held, as opposed to
trying to …

(SERVER-862) Enable jruby pool write locker to borrow pool instances

---

documentation/_puppetserver_nav.html

Per [`puppet-docs` PR 595](https://github.com/puppetlabs/puppet-docs/pull/595/files), update the fallback sidebar in this repo to add links to new configuration file docs.

(docs) Update fallback navigation.

---

project.clj

Instead of overriding org.clojure in ezbake profile with an explicit
version, just exclude the one dragged in by the lein-ezbake plugin.

(MAINT) Exclude org.clojure from lein-ezbake

---

documentation/config_file_puppetserver.md
src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_internal.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_schemas.clj
src/java/com/puppetlabs/puppetserver/jruby/ScriptingContainer.java
test/integration/puppetlabs/services/jruby/jruby_puppet_internal_test.clj
test/unit/puppetlabs/puppetserver/ruby/http_client_test.clj
test/unit/puppetlabs/services/jruby/jruby_interpreter_test.clj
test/unit/puppetlabs/services/jruby/jruby_pool_test.clj
test/unit/puppetlabs/services/jruby/jruby_testutils.clj

This PR is mostly cleanup, refactoring, whitespace changes.  The interesting commit is c56509d , which adds support for configuring JRuby's `CompileMode`.

(SERVER-1052) allow configurable jruby compile mode

---

src/java/com/puppetlabs/puppetserver/pool/JRubyPool.java
src/java/com/puppetlabs/puppetserver/pool/LockablePool.java
test/unit/puppetlabs/puppetserver/lockable_pool_test.clj

This commit adds an .isLocked() method to the JRubyPool, mostly for ease
of use in upstream tests for detecting whether or not the pool is
locked.

(SERVER-1091) Add .isLocked() method for JRubyPool

---

project.clj

In a recent PR, we introduced a var called `clojure-version` in
the project.clj, to coordinate our references to our clojure
dependency version.  It turns out that the name `clojure-version`
is already in use in `clojure.core`, so this var results in a
warning that we are shadowing the upstream var.
This commit changes the var name to `clj-version`, so that we
will no longer be shadowing the built-in name.

(MAINT) Rename `clojure-version` to avoid shadowing

---

project.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_agents.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_internal.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_schemas.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj
src/clj/puppetlabs/services/request_handler/request_handler_core.clj
test/integration/puppetlabs/services/jruby/jruby_pool_int_test.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_service_test.clj

With https://github.com/puppetlabs/trapperkeeper/pull/198, puppet-server may begin receiving HUP signals which will cause it to shut down and restart. Without these commits, that results in leaks of scripting containers. This PR adds a stop function to the jruby puppet service that cleans up the existing jruby pools during a shutdown. Any agents connecting during a shutdown will be given a 503 if the webserver is still up.

(SERVER-537) Cleanup jruby pools during shutdown

---

test/unit/puppetlabs/puppetserver/lockable_pool_test.clj

This commit modifies logic in the `lockable-pool-test` tests to use a
timed wait with assertions for all promises other than just ones related
to thread start synchronization.  Hopefully, this would help better
pinpoint any test failures when they occur, as opposed to just having a
test potentially hang and be aborted by a test runner without any better
information to help diagnose the problem.

(SERVER-1097) Use timed waits for lockable-pool-test promises

---

test/integration/puppetlabs/services/jruby/jruby_pool_int_test.clj

Because jenkins clients swallow HUP signals, this commit updates the HUP
test in puppet-server to call the restart-tk-apps function directly, as
the HUP would have triggered.

(SERVER-1096) Update disabled HUP test to use restart-tk-apps

---

ezbake/config/bootstrap.cfg

The previous work neglected to add the versioned-code-service to
ezbake's bootstrap.cfg, which has the unfortunate consequence of
preventing puppet-server from starting up. This commit addresses that
oversight.

(SERVER-876) Add versioned-code-service to ezbake bootstrap.cfg

---

src/clj/puppetlabs/services/master/master_core.clj
src/clj/puppetlabs/services/master/master_service.clj
test/integration/puppetlabs/puppetserver/bootstrap_testutils.clj
test/integration/puppetlabs/services/legacy_routes/legacy_routes_test.clj

Prior to this commit, the legacy routes services made some
hard-coded assumptions about the master's route configuration that
made it incompatible with the recommended webrouting configuration
style for multi-webserver configurations.  This commit adds a few
more checks to detect that case, and make the services compatible
with the multi-server configuration style.  This is necessary in
order for us to be able to run PE Puppet Server in-process with
other PE web apps.

(SERVER-1071) Make legacy routes tolerant of multi-server config

---

test/integration/puppetlabs/services/jruby/jruby_locking_test.clj
test/unit/puppetlabs/puppetserver/lockable_pool_test.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_service_test.clj

This commit includes fixes for timing-related issues in the
`pool-can-borrow-after-borrow-interrupted-during-lock` and
`pool-can-borrow-after-borrow-timed-out-during-lock` tests.  In both
cases, there previously was a race condition where a borrow on a
separate thread could succeed before a lock() call was made, causing the
lock() call to block indefinitely because the pool was indefinitely not
full.  The production code was behaving properly but the tests were
designed with the expectation that the lock would occur before the
any borrows were attempted.  Both tests were changed to wait to perform
the borrow until the lock is taken.

(SERVER-1103) Fix borrow-after-borrow lock tests

---

dev/user_repl.clj
src/clj/puppetlabs/services/master/master_core.clj
src/clj/puppetlabs/services/request_handler/request_handler_core.clj
src/clj/puppetlabs/services/versioned_code_service/versioned_code_service.clj
test/integration/puppetlabs/general_puppet/general_puppet_int_test.clj
test/integration/puppetlabs/services/jruby/puppet_environments_int_test.clj
test/unit/puppetlabs/services/master/master_core_test.clj

In a previous commit, wrap-params-for-jruby was called twice for catalog
requests. This meant that the body of the request would be consumed by
the first call (via body-for-jruby), and then the body would be gone for
the second call. This commit avoids that problem by refactoring
root-routes and the wrap-with-code-id to call wrap-params-for-jruby only
once in all routes. It also adds a test for the failing case where
catalog POST requests had no body.

(SERVER-876) Only call wrap-params-for-jruby once

---

src/clj/puppetlabs/services/legacy_routes/legacy_routes_service.clj
src/clj/puppetlabs/services/master/master_core.clj
src/clj/puppetlabs/services/master/master_service.clj
src/clj/puppetlabs/services/request_handler/request_handler_core.clj
src/clj/puppetlabs/services/request_handler/request_handler_service.clj
test/integration/puppetlabs/services/jruby/jruby_pool_int_test.clj
test/unit/puppetlabs/services/master/master_core_test.clj
test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj

This commit refactors the code which computes the code_id to only do so
while holding a JRuby instance.  This ensures that other code which may
result in the code_id changing (such as File Sync) and which requires
use of the JRubyPool's lock cannot be run in between the time when the
code_id is computed and when the catalog is compiled.

(SERVER-876) Compute code_id when holding a JRuby

---

test/integration/puppetlabs/general_puppet/general_puppet_int_test.clj
test/integration/puppetlabs/puppetserver/auth_conf_test.clj
test/integration/puppetlabs/puppetserver/bootstrap_testutils.clj
test/integration/puppetlabs/puppetserver/error_handling_int_test.clj
test/integration/puppetlabs/puppetserver/testutils.clj
test/integration/puppetlabs/services/certificate_authority/certificate_authority_int_test.clj
test/integration/puppetlabs/services/jruby/jruby_pool_int_test.clj
test/integration/puppetlabs/services/jruby/puppet_environments_int_test.clj
test/integration/puppetlabs/services/jruby/request_handler_test.clj
test/integration/puppetlabs/services/legacy_routes/legacy_routes_test.clj
test/integration/puppetlabs/services/puppet_admin/puppet_admin_int_test.clj
test/integration/puppetlabs/testutils.clj
test/unit/puppetlabs/services/ca/certificate_authority_disabled_test.clj
test/unit/puppetlabs/services/config/puppet_server_config_core_test.clj
test/unit/puppetlabs/services/jruby/jruby_interpreter_test.clj
test/unit/puppetlabs/services/jruby/jruby_testutils.clj

Several tests reuse or redefine several functions that help in
interacting with puppet catalogs, so this commit collects them in a
generic namespace for reuse. Tests that depended on the old functions
are updated to use the new ones.

(maint) Create puppetlabs.testutils namespace

---

src/clj/puppetlabs/puppetserver/shell_utils.clj
src/clj/puppetlabs/services/protocols/versioned_code.clj
src/clj/puppetlabs/services/versioned_code_service/versioned_code_core.clj
src/clj/puppetlabs/services/versioned_code_service/versioned_code_service.clj
src/java/com/puppetlabs/puppetserver/ExecutionResult.java
src/java/com/puppetlabs/puppetserver/ShellUtils.java
test/integration/puppetlabs/general_puppet/general_puppet_int_test.clj
test/unit/puppetlabs/services/versioned_code_service/versioned_code_core_test.clj
test/unit/puppetlabs/services/versioned_code_service/versioned_code_service_test.clj

This implements the open source half of get-code-content. This work is very similar to the current-code-id work with the important caveat that it switches ShellUtils's ExecutionResult to using a ByteArrayInputStream internally for stdout instead of a string.
There is some minor refactoring of the current-code-id stuff to have it share error message code with get-code-content.

(SERVER-887) Implement get-code-content

---

documentation/config_logging_advanced.md
documentation/configuration.markdown
project.clj

This PR adds a dependency on the logback logstash JSON encoder library, so that we will bundle it with our uberjar.  This allows users to opt-in to configuring their Puppet Server logs to write output in a JSON format that can be imported into logstash.
The PR also includes documentation with examples of how to configure Puppet Server's logging accordingly.
We were almost certainly going to end up with a dependency on this library in the future anyway, because it is a dependency of the structured logging library that PuppetDB is now using.

(SERVER-1069) bundle logback json encoder

---

src/ruby/puppet-server-lib/puppet/server/master.rb
test/integration/puppetlabs/services/jruby/class_info_test.clj

This commit contains two changes:
1) Update the class-info tests to expect a 'default_source' parameter to
be present in the return from a call to the
`ClassInformationService.classes_per_environment` method per expected
changes made in PUP-5713.
2) Update the code in .getClassInfoForEnvironment from "master.rb" to
ensure that the value of a candidate Puppet::Node::Environment's
"name" is coerced to a String before comparing to the supplied String
type environment argument.  Previously, the "name" was not coerced
and so was being compared as a Symbol rather than a String, leading
the comparison to always fail and for the target environment to not
be found.

(SERVER-1117) Update class-info tests per PUP-5713 changes

---

dev-resources/puppetlabs/services/request_handler/request_handler_core_test/puppet.conf
src/clj/puppetlabs/services/request_handler/request_handler_service.clj
test/integration/puppetlabs/puppetserver/testutils.clj
test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj

A previous commit moved where the current-code-id function was called
during request handling into the jruby request handler. In order to
ensure that current-code-id is always calculated with the same jruby
that is handling the request, this commit adds a test that makes a
request and inspects the state of the jruby pool while code id is being
calculated during the request.

(SERVER-876) Add test for current-code-id function

---

test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj

The VCS protocol recently was updated to include the get-code-content
function, so this commit updates a request_handler_core test that
implemented a custom VCS service to include that function in its
definition.

(SERVER-876) Update test for VersionedCodeService protocol change

---

src/clj/puppetlabs/puppetserver/shell_utils.clj
src/java/com/puppetlabs/puppetserver/ShellUtils.java
test/unit/puppetlabs/puppetserver/shell_utils_test.clj

This commit adds some extra error handling and logging around an edge case that we hit with JDK8 and commons-exec, where passing data on STDIN to a process that doesn't consume it can cause commons-exec to throw a not-very-helpful exception.  For more info see SERVER-1094 and linked tickets.

(SERVER-1094) log message about stdin jdk8 bug

---

src/clj/puppetlabs/services/master/master_service.clj
test/integration/puppetlabs/services/legacy_routes/legacy_routes_test.clj

This commit re-adds the ability to tolerate the now obsolete
`invalid-in-puppet-4` key in the webroute config for the master-service.
The work for SERVER-1071 had removed this support, causing the server to
fail to start up if it still had this key in the config.

(SERVER-1115) Tolerate invalid-in-puppet-4 key in master webroute config

---

src/clj/puppetlabs/services/master/master_core.clj
test/unit/puppetlabs/services/master/master_core_test.clj

The `not-found` handler for `/puppet` did not appear to be strictly
necessary, and since we are referencing this route tree from other
namespaces (and potentially composing it with other route trees),
getting rid of it makes the code more re-usable.

(MAINT) remove not-found handler for master service

---

src/clj/puppetlabs/services/legacy_routes/legacy_routes_service.clj
src/clj/puppetlabs/services/master/master_core.clj
src/clj/puppetlabs/services/master/master_service.clj
src/clj/puppetlabs/services/request_handler/request_handler_core.clj
src/clj/puppetlabs/services/versioned_code_service/versioned_code_service.clj
test/integration/puppetlabs/general_puppet/general_puppet_int_test.clj
test/unit/puppetlabs/services/master/master_core_test.clj
test/unit/puppetlabs/services/versioned_code_service/versioned_code_service_test.clj

Add a new /static_file_content web endpoint that exercises the
`get-code-content` service function from the VersionedCodeService.
This is based on top of https://github.com/puppetlabs/puppet-server/pull/885, which should be merged first. The relevant commit is 2bba3d2

(SERVER-880) Add static_file_content endpoint

---

test/integration/puppetlabs/puppetserver/testutils.clj

Previously these test utilities all did not have schemas applied to
them. This commit starts to change that. This introduces schemas to most
of the functions and defines a schema for puppet catalogs and resources.

(maint) Schemify puppetlabs.puppetserver.testutils

---

project.clj
src/clj/puppetlabs/puppetserver/jruby_request.clj
src/clj/puppetlabs/puppetserver/ringutils.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj
src/clj/puppetlabs/services/master/master_core.clj
src/clj/puppetlabs/services/protocols/jruby_puppet.clj
test/integration/puppetlabs/puppetserver/testutils.clj
test/integration/puppetlabs/services/master/environment_classes_int_test.clj
test/unit/puppetlabs/services/master/master_core_test.clj

This commit generates a hash value from the JSON response to an
environment_classes request and adds that hash to the HTTP response in
an Etag header.  The commit includes some work to re-sort maps in the
response body prior to JSON serialization so that the generated hash is
consistent even if the order in which keys had been inserted into the
original sub-maps may differ from one object creation to another.
Requests made by clients with an 'If-None-Match' header matching the
last 'Etag' delivered for an environment_classes request for the corresponding
environment now result in an HTTP 304 (Not Modified) response being delivered,
with an empty response body, instead of re-parsing the environment content and
delivering a response body based on the latest manifests on disk.
This PR also …

(SERVER-1111) Add Etag / If-None-Match Processing to environment_classes Endpoint

---

resources/ext/config/request-logging.xml

Prior to this commit puppetserver used a different request
logging format than puppetdb and console-services.
After this commit the request logging will be of the suggested
formatting for all trapper-keeper projects.

(PE-13485) Implement a consistent request logging format

---

acceptance/lib/helper.rb
src/clj/puppetlabs/services/master/master_core.clj
test/integration/puppetlabs/services/jruby/class_info_test.clj
test/unit/puppetlabs/services/master/master_core_test.clj

This commit contains some changes which validate / support some of
the fixes / changes done to the ClassInformationService in core Ruby
Puppet, including:
* Per PUP-5809, production code and tests updated to expect the
ClassInformationService to wrap return values for successfully parsed
classes in a `:classes` hash.
* As an optimization, removed one layer of RubyHash -> map conversion
during translation of environment_class file info to the JSON
response per the changes made in PUP-5809.
* Added a couple of tests to the class-info-test suite to validate the
removal of literal parameter values for non-JSON safe types (PUP-5744)
and values with expressions (PUP-5713).
* Bump the Puppet submodule to a81f968 and pinned puppet-agent up to
18ebd9a in order for the above PUP changes to be …

(SERVER-1126) Refactoring and tests to support PUP class_per_env changes

---

src/clj/puppetlabs/services/master/master_core.clj
test/integration/puppetlabs/general_puppet/general_puppet_int_test.clj
test/unit/puppetlabs/services/master/master_core_test.clj

This PR updates the static-file-content-endpoint to reject any
requests that would have been rejected by the file_content Puppet
endpoint. Tests are also updated to account for the new requirement. Any
files not within `modules/*/files/**` or `environments/*/modules/*/files/**`
will be rejected with a 403 error.

(SERVER-882) Restrict static_file_content endpoint

---

src/clj/puppetlabs/services/versioned_code_service/versioned_code_core.clj
src/clj/puppetlabs/services/versioned_code_service/versioned_code_service.clj
test/integration/puppetlabs/general_puppet/general_puppet_int_test.clj
test/unit/puppetlabs/services/versioned_code_service/versioned_code_service_test.clj

Previously if the versioned-code-service were partially configured, code
id would still be added to catalog requests. This commit alters that
behavior so that if only one of the two configuration settings is
present the catalog request returns a 500 error.

(SERVER-1134) Fail startup if vcs is partially configured

---

src/clj/puppetlabs/puppetserver/shell_utils.clj
test/unit/puppetlabs/puppetserver/shell_utils_test.clj

Previously if a command with arguments were passed to
shell-utils/execute-command, it would throw an error about
'/usr/bin/echo foo' command does not exist. This commit updates the
validation to throw an error if the command does not exist, but the
first part when split on a space does exist.

(SERVER-1131) Throw a better error message for commands with arguments

---

src/clj/puppetlabs/services/request_handler/request_handler_core.clj
test/integration/puppetlabs/general_puppet/general_puppet_int_test.clj

Previously, because with-code-id simply threw an exception, catalog
requests without an environment would return a 500. A bad request of 400
seems like a better match for the expected return code (as the client
controls whether or not an environment is included in the request), so
this commit updates with-code-id to throw a bad request if no
environment is present in the request.

(maint) Return 400 is no environment is in a catalog request

---

src/clj/puppetlabs/services/versioned_code_service/versioned_code_core.clj
test/integration/puppetlabs/general_puppet/general_puppet_int_test.clj
test/unit/puppetlabs/services/versioned_code_service/versioned_code_core_test.clj

Previously, if the `code-id-command` returned a non-zero exit
code, `nil` was returned for the code-id and inserted into the
catalog.
This commit modifies this behavior so that instead of returning
nil, an exception is thrown, which causes the catalog request
to fail.

(SERVER-1107) Fail on non-zero exit from code-id-command

---

acceptance/suites/tests/code_commands/code_scripts.rb

This test will cause the pe-puppet-server-extensions pipe to file until this PR is merged.

(MAINT)confine statement failed in PE; replaced with skip

---

acceptance/suites/tests/authorization/default_rules.rb
ezbake/config/conf.d/auth.conf

This PR adds an auth rule to allow authenticated access to the
static_file_content endpoint, and adds the associated acceptance test

(SERVER-1143) Auth rule for static file content

---

project.clj

This commit bumps Puppet Server's dependency on
trapperkeeper-webserver-jetty9 to 1.5.2. This is being done primarily
in order for Puppet Server to utilize some memory leak fixes related to
JMX beans in a HUP/restart scenario that were added in the latest
release.

(MAINT) Bump tk-jetty9 dep to 1.5.2

---

dev-resources/puppetlabs/puppetserver/auth_conf_test/echo
src/clj/puppetlabs/services/legacy_routes/legacy_routes_service.clj
src/clj/puppetlabs/services/master/master_core.clj
src/clj/puppetlabs/services/master/master_service.clj
test/integration/puppetlabs/general_puppet/general_puppet_int_test.clj
test/integration/puppetlabs/puppetserver/auth_conf_test.clj
test/integration/puppetlabs/puppetserver/testutils.clj
test/unit/puppetlabs/services/master/master_core_test.clj

Previously clojure routes were unauthenticated if legacy auth was
enabled because it was presumed that all routes would be handed down
into puppet for auth via auth.conf. As that is not the case, this commit
separates the jruby request handler from a new clojure request wrapper.
The jruby request handler is applied to all ruby routes, and conditional
authentication is applied to that handler. The new clojure wrapper
unconditionally applies authentication and parses the request for
params.
The legacy routes service also needed a corresponding change to account
for the changes to get-wrapped-handler and root-routes.
Additionally, this commit defines schemas for some of the existing and
all of the new functions in master-core.

(SERVER-1142) Sanely handle auth and param parsing for clojure routes

---

project.clj

The version of Joda Time used by the previous version of clj-time had
an issue on Java 8u60+ that caused it to improperly print a different
timestamp.
This commit bumps the version of clj-time, which pins to a newer
version of Joda Time, which does not have this bug on Java 8u60 and
above.

(SERVER-1007) Print Timezone format with CA correctly on Java 8u60+

---

src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj
src/clj/puppetlabs/services/master/master_core.clj
src/clj/puppetlabs/services/protocols/jruby_puppet.clj
test/integration/puppetlabs/services/master/environment_classes_int_test.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_service_test.clj
test/unit/puppetlabs/services/jruby/jruby_testutils.clj
test/unit/puppetlabs/services/master/master_core_test.clj

This commit adds a "last-updated" timestamp per environment to the
environment classes cache.  The timestamp is used by incoming
environment_classes cache requests to determine if the cache info has
changed between the time the request starts parsing for info and when
the cache is about to be updated, e.g., if a call from a separate
request to mark-environment-expired were to occur during parsing for
class info in a request.  If the timestamp has been updated during that
window, the cache is not updated with the latest parsed data, since that
data may already be stale.
This commit also adds an integration test,
class-info-updated-after-cache-flush-during-prior-request, which
performs an environment cache flush while a class info request is in
progress and validates that the following …

(SERVER-1130) Add a per-environment timestamp into the env-classes cache

---

acceptance/lib/helper.rb
spec/puppet-server-lib/puppet/jvm/master_spec.rb
test/integration/puppetlabs/puppetserver/testutils.clj
test/integration/puppetlabs/services/jruby/class_info_test.clj

This commit bumps our puppet-agent dependency for CI to 6e35df8 and our
puppet submodule dependency to 2ec5b3d.
Along with the bump, three changes to tests were necessary in order for
existing tests to continue passing:
1) Updated master_spec.rb Puppet version from 4.3.2 to 4.4.0.
2) Updated PuppetCatalog schema used for tests to tolerate existence of
the new 'catalog_format' key in the catalog response format.
3) Update class_info_tests to look for simple types for Hash and Array
instead of composite types like Hash[Scalar, Data, 0, default].  This
change was expected per the resolution of PUP-5861.

(MAINT) Bump puppet-agent to 6e35df8 and puppet submodule

---

dev-resources/puppetlabs/services/jruby/jruby_pool_int_test/logback-test-restart-comes-back.xml
test/integration/puppetlabs/services/jruby/jruby_pool_int_test.clj

This PR adds some upper bounds on the maximum number of iterations /
wait time for specific operations to complete while running the
jruby-pool-int-tests.  The bounded operations include the maximum wait
time for a new pool to be initialized, instances to be borrowed, pool
flushes to complete, and for the puppetserver service stack to be
stopped.
This commit adds some extra instrumentation to the
`test-restart-comes-back` test to hopefully help with identifying why
the test has failed when it intermittently does.

(SERVER-1148) Add timed waits and instrumentation to jruby-pool-int-tests

---

acceptance/lib/helper.rb

This commit bumps our puppet-agent dependency for CI to 112d479, latest
full OS matrix build that passed puppet-agent CI.  The prior build,
6e35df8, only included a partial OS matrix and so was not suitable for
the full OS matrix puppet-server nightly job runs.
This commit also bumps our puppet submodule dependency to 2256ed8 in
order to pick up a fix for the cached_catalog_remediate_local_drift.rb
test for ubuntu-1404.

(MAINT) Bump puppet-agent to 112d479 and puppet submodule

---

dev/puppet-server.conf.sample
src/clj/puppetlabs/services/legacy_routes/legacy_routes_service.clj
src/clj/puppetlabs/services/master/master_core.clj
src/clj/puppetlabs/services/master/master_service.clj
test/integration/puppetlabs/services/master/environment_classes_int_test.clj
test/unit/puppetlabs/services/master/master_core_test.clj

This commit adds a Trapperkeeper-level configuration setting for use in
enabling/disabling the environment class cache.  When set to "false"
(disabled), an Etag is no longer computed/returned with the payload for
a environment_classes API GET request.  When set to "true" (enabled),
the Etag will be computed and returned with the GET request payload as
was true in prior commits.

(SERVER-1185) Add enable setting for environment class cache

---

dev/puppet-server.conf.sample
src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_schemas.clj
src/clj/puppetlabs/services/master/master_service.clj
test/integration/puppetlabs/services/master/environment_classes_int_test.clj

Previously, the `environment-class-cache-enabled` setting was in a
`puppetserver` block. This was the only setting in this block. Ultimately, we
would like to separate out the `jruby-puppet` setting block to only contain
the jruby-specific settings and move many of the settings to a `puppetserver`
block. However, we are not at the point of doing that yet, and in the meantime
only having one setting in the `puppetserver` block seems confusing to explain
to users (why is this here when all the other seemingly-puppet server related
settings aren't here?). This commit moves this setting to the `jruby-puppet`
block for now.
I spoke with @loriland and she agreed that this seems easier to explain to users and the best decision for now, until we have a chance to audit our config files.

(SERVER-1185) Move environment-class-cache-enabled setting

---

acceptance/lib/helper.rb

This commit bumps the puppet-agent dependency up to 7a3dae3 and Puppet
submodule to 7fd84f34 in order to pick up a fix for the the
exported_resources.rb Puppet acceptance test, in PUP-5996.

(MAINT) Bump puppet-agent to 7a3dae3

---

src/clj/puppetlabs/services/ca/certificate_authority_core.clj
test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj

Prior to this we weren't checking that `(:desired_state json-body)` returned a non-nil value. If it had returned nil our error message formatting will cause an NPE (with `(name nil)`).
We now check for nil and return an appropriate error message and code when the parameter is missing.

(SERVER-542) Gracefully handle missing params to /certificate_status PUT

---

dev-resources/puppetlabs/services/ca/certificate_authority_core_test/autosign/ruby-autosign-executable-false

This commit changes the ruby-autosign-executable-false ruby script to
consume stdin fully before exiting.  This is needed per the changes in
SERVER-1094 which could lead to new shell utils library we use for
autosigning throwing an `IllegalStateException` on JDK 8 when stdin is
not fully consumed by the spawned process.

(SERVER-1193) Consume stdin in ruby-autosign-exe-false test script

---

acceptance/lib/helper.rb

This commit bumps Puppet Server's puppet agent dependency up to 7282f09
and corresponding Ruby Puppet submodule up to 3b36340.  These changes
enable Puppet Server CI runs to take advantage of the Ruby Puppet
acceptance test fix for puppet_lookup_cmd.rb, PUP-5997.

(MAINT) Bump puppet-agent to 7282f09

---

src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj
src/clj/puppetlabs/services/master/master_core.clj
src/clj/puppetlabs/services/protocols/jruby_puppet.clj
test/integration/puppetlabs/services/master/environment_classes_int_test.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_service_test.clj
test/unit/puppetlabs/services/master/master_core_test.clj

This PR is a replacement for #930, which was originally targeted at the
master branch.
This PR replaces the use of a timestamp for synchronization of tags
in the environment class info cache with an incrementing integer, called
the `cache-generation-id`.
This PR adds some logic behind the
`get-environment-class-info-tag-cache-generation-id!` call in the
jruby-puppet-service to update the environment class info cache with a
new entry for the environment being queried in the event that no prior
entry existed for that environment. This allows any subsequent
`mark-all-environments-expired!` calls that may be made to the service to
update the cache-generation-id in the cache for the environment and,
therefore, for the logic added in #926 to avoid updating the
cache with a stale tag to be used …

(SERVER-1183) Add entry to env class cache if not present during get

---

project.clj

This commit bumps us to tk-j9 v1.5.4, which includes a fix for
an issue that would happen if Jetty's stopTimeout was hit during
a HUP restart.  Without the fix, this will be treated as a fatal
error.  With the fix, the exception is handled and the HUP restart
can proceed.

(TK-338) Bump to tk-j9 1.5.4 to handle TimeoutException

---

dev-resources/puppetlabs/general_puppet/general_puppet_int_test/echo_foo
spec/puppet-server-lib/puppet/jvm/execution_spec.rb
src/ruby/puppet-server-lib/puppet/server/execution.rb
test/integration/puppetlabs/general_puppet/general_puppet_int_test.clj

Previously, Puppet Server failed to correctly parse more complex commands
(with lots of string escaping) passed to it by Puppet for execution.
This PR fixes that problem by updating execution.rb such that when an
array is passed it no longer concatenates that array to be a string, but
instead the first argument is passed to `ShellUtils/executeCommand` as a
string and the rest are passed as an array.

(SERVER-1160) Fix command parsing

---

src/clj/puppetlabs/puppetserver/cli/gem.clj
src/clj/puppetlabs/puppetserver/cli/irb.clj

clojure 1.7.0 included a new function named run!, which has the same
name as existing functions in the gem and irb namespaces. This produces
unsightly warnings when using the gem subcommand.
This commit adds an exclusion on the run! command from clojure to avoid
these warnings.

(SERVER-1202) Rename run! in gem and irb namespaces 

---

src/clj/puppetlabs/puppetserver/common.clj
src/clj/puppetlabs/puppetserver/jruby_request.clj
src/clj/puppetlabs/services/master/master_core.clj
src/clj/puppetlabs/services/request_handler/request_handler_core.clj
src/clj/puppetlabs/services/versioned_code_service/versioned_code_core.clj
test/integration/puppetlabs/general_puppet/general_puppet_int_test.clj
test/unit/puppetlabs/services/versioned_code_service/versioned_code_core_test.clj

This commit adds validation for inputs to the code id and code content
scripts. While ShellUtils ought to prevent any bash injection attacks,
we still deemed it wise to do validation on this sort of input.
To that end, this commit adds schemas for environment and code-id
strings and uses them at both the HTTP level and the schema level.
An old helper, `valid-code-id?`, was removed in favor of using schema.

(SERVER-1194) Validate code-id, env for external scripts

---

dev-resources/puppetlabs/services/master/environment_classes_int_test/logback-environment-classes-integration-cache-enabled-test.xml
test/integration/puppetlabs/services/master/environment_classes_int_test.clj

This PR adds some instrumentation to the
`environment-classes-integration-cache-enabled-test`, in an attempt to
get more information about why it fails when it does.
This commit adds a timeout to the initial wait that the
`class-info-updated-after-cache-flush-during-prior-request` does to see
that the getClassInfoForEnvironment method in a JRubyPuppet instance has
been invoked.  The current code waits indefinitely for that action,
which may never happen in the case that some higher-level failure has
occurred, e.g., the client fails to connect to the server, in which case
the test could hang.

(SERVER-1196) Add instrumentation to env-class-int-cache-enabled test

---

documentation/index.markdown

This commit adds a "Restarting the Server" link to the index.markdown
doc.  That link had somehow been present on the master branch but absent
from the current stable branch.

(MAINT) Add restarting the server link to index markdown doc

---

ezbake/config/conf.d/webserver.conf

This commit changes the delimiter for settings in the webserver conf
file from = signs to colons.  This is done for consistency with our
configuration elsewhere, where we should delimit these settings as JSON
would require even though HOCON allows either format.

(SERVER-532) Change = to : in webserver settings

---

spec/puppet-server-lib/puppet/jvm/execution_spec.rb
src/ruby/puppet-server-lib/puppet/server/execution.rb
test/integration/puppetlabs/general_puppet/general_puppet_int_test.clj
test/integration/puppetlabs/puppetserver/testutils.clj
test/integration/puppetlabs/services/jruby/class_info_test.clj

Previously, puppet server's execution stub assumed that if it was handed
an array, that the first element would be the command. This turns out
not to be true for all of puppet's uses of the execute method.
Specifically, config_version is often a script with arguments that is
handed as a single string in an array to Puppet::Util::Execution.execute
and then on to puppet server's execution stub.
This is a problem because something like '/bin/echo a b c' is not a valid
command. This commit addresses the problem by using the correct call to
ShellUtils in the case where there is a single element array. The
ShellUtils call will in that case correctly parse '/bin/echo a b c' into
a call to /bin/echo with a b and c as arguments.

(SERVER-1204) Update execution stub to correctly handle empty args

---

documentation/puppet-api/v3/static_file_content.md

Per @joshcooper in `puppet-docs` PR 622 and SERVER-1195, update the `static_file_content` API docs to specify the paths for files that can have inlined file resource metadata.

(docs) Update file-path glob details.

---

project.clj

The timeout has been raised in ezbake itself, and we can't think
of any great reason not to just use the default from there.

(SERVER-557) Remove ezbake timeout override

---

documentation/puppet_conf_setting_diffs.markdown
src/clj/puppetlabs/puppetserver/certificate_authority.clj
src/clj/puppetlabs/services/ca/certificate_authority_service.clj
test/unit/puppetlabs/puppetserver/certificate_authority_test.clj

Previously, if the ca_ttl setting was larger than a Java Integer
(2,147,483,647 -- representing ~68 years) the CA would fail to sign
certs.
This restricts the ca_ttl value to a value equivalent to 50 standard
years and adds validation of the ca_ttl setting to the service's init
phase, invalid ca_ttls will now fail on init, rather than when signing
certificates.
It also refactors existing deprecations warnings for various ca config
settings into core CA with our new validation function and adds tests
for the existing deprecation warnings.

(SERVER-615) Gracefully handle invalid ca_ttl settings

---

project.clj

When we introduced the dependency on logstash-logback-encoder,
we accidentally started bringing in a newer version of some
logback artifacts than those that are brought in by tk and tk-j9.
This commit temporarily makes all of the logback dependency
versions explicit in the puppet server project, so that we can
get a quick bugfix release out.
Longer term we probably want to move all of these to TK directly,
since that is the repo that really handles all of our logging
logic.

(SERVER-1215) Fix inconsistent logback versions

---

documentation/puppet-api/v3/environment_classes.md

This fixes a link to the environment cache API docs from the environment
classes endpoint docs, by using the already-defined `environment cache API`
markdown link reference.

(doc) Fix environment cache api link

---

acceptance/lib/helper.rb
dev-resources/puppetlabs/general_puppet/general_puppet_int_test/puppet.conf
src/clj/puppetlabs/puppetserver/jruby_request.clj
src/clj/puppetlabs/services/master/master_core.clj
test/integration/puppetlabs/general_puppet/general_puppet_int_test.clj
test/unit/puppetlabs/services/master/master_core_test.clj

Similar to agent catalog requests, we now add code id for the given
environment to environment catalog requests.
This extends the logic for determining the request environment to now check
both the :environment URL segment as well as the "environment" query param.
If environment is part of the URL, we favor that over a conflicting query
param.

(ORCH-1235) Add code_id to environment catalog requests

---

src/clj/puppetlabs/services/ca/certificate_authority_core.clj
test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj

Prior to this the certificate_statuses endpoint would not match calls
when the required key path segment contained anyting that wasn't an
alphanum, hyphen, underscore, or period. eg.
`puppet-ca/v1/certificate_statuses/*`
would fail to match the specification of:
`:ca-mount-endpoint/:version/certificate_statuses/:key`
even though there is no further requirements on the key path segment.
This behavior is determined by how we describe our path segment captures
to a third party library (bidi).
This patch updates our route description to allow the key path segment
to match any single path segment of one or more characters in length.

(SERVER-864) Allow special characters in certificate_statuses key

---

project.clj

This commit bumps us to the latest release of TK, which includes
explicit versioning for all of our logback artifacts to ensure
that we don't end up shipping incompatible versions of the various
logback components.  The commit also removes the previous hack
that we'd put in to temporarily fix the logback versioning issue.

(TK-344) Update to TK 1.3.1 and remove logback version hack

---

acceptance/lib/helper.rb
project.clj
spec/puppet-server-lib/puppet/jvm/master_spec.rb

Previously, puppet server packages were failing to be built because `lein
with-profile ezbake` had version conflicts and pedantic errors. This updates to a new tk-ws-j9 that removes these version conflicts.
The previous PUPPET_BUILD_VERSION was set to a puppet-agent build that was
1.3.5, which didn't work with puppet server's current requirement on
puppet-agent >= 1.4.0. This updates the PUPPET_BUILD_VERSION to the latest passing
puppet-agent version off puppet master, and the puppet submodule to the commit
that is in that puppet-agent version.

(maint) Fix pedantic errors and puppet agent version

---

acceptance/lib/helper.rb

This commit updates the PUPPET_BUILD_VERSION to the latest passing
puppet-agent version off puppet master, and the puppet submodule to the commit
that is in that puppet-agent version.
This should hopefully clear up the CI failure

(MAINT) Bump puppet-agent commit

---

Gemfile

This reverts commit 528db99d531aa2364935629d865e8cef115e5307, because BKR-650 is still a problem.

Revert "updates beaker to 2.38.1"

---

src/clj/puppetlabs/services/ca/certificate_authority_core.clj
test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj

Previously, we were falling through to the default handler of our
`web-routes` if the `certificate_statuses` endpoint did not include its
required -- but ignored -- trailing key segment.  The default handler
returns a 404.
This provides a default handler for the `certificate_statuses` endpoint
that will catch malformed URLs and return a 400 instead of a 404.
It also extracts providing a generic 400 response into a method that
is reused where appropriate.

(maint) Return 400 for incomplete URL to certificate_statuses

---

spec/puppet-server-lib/puppet/jvm/master_spec.rb
spec/puppet-server-lib/puppet/jvm/puppet_config_spec.rb
src/ruby/puppet-server-lib/puppet/server/puppet_config.rb

A performance improvement was just merged into puppet. It is guarded by
a setting called `always_retry_plugins`, which defaults to true. To take
advantage of this improvement, we should set it to false. This commit
makes that change, but checks to see if the setting is available yet by
calling into `Puppet.settings.setting`.

(PUP-5482) Toggle always_retry_plugins when available

---

documentation/admin-api/v1/environment-cache.markdown
documentation/config_file_auth.md
documentation/dev_debugging.markdown
documentation/external_ca_configuration.markdown
documentation/external_ssl_termination.markdown
documentation/gems.markdown
documentation/install_from_packages.markdown
documentation/known_issues.markdown
documentation/puppet-api/v3/static_file_content.md
documentation/puppet_conf_setting_diffs.markdown
documentation/release_notes.markdown
documentation/services_master_puppetserver.markdown
documentation/ssl_server_certificate_change_and_virtual_ips.markdown

Updates links in documentation and references to Puppet Labs.

(docs) Update Puppet branding and URLs.

---

acceptance/lib/helper.rb

This commit updates the puppet-agent version used for acceptance testing
to include the OID work that was recently merged into puppet.

(maint) Update puppet-agent version

---

src/clj/puppetlabs/puppetserver/certificate_authority.clj
src/clj/puppetlabs/services/ca/certificate_authority_core.clj
test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj

Prior to this there was no handler for the DELETE method of
certificate_request endpoint.
This adds a basic handler for deleting a pending certificate request.

(SERVER-977) DELETE handler for certificate_request endpoint

---

spec/puppet-server-lib/puppet/jvm/puppet_config_spec.rb
src/ruby/puppet-server-lib/puppet/server/puppet_config.rb

The new always_retry_plugins setting includes always_cache_features, and
setting always_cache_features now generates an unsightly deprecation
warning, so this commit removes that setting from puppet_config.

(maint) Don't set always_cache_features in puppet_config

---

acceptance/lib/helper.rb

This commit updates the puppet-agent ref to a version that passes the
puppetdb smoke tests and also updates the puppet submodule commit to
match the puppet change.

(SERVER-1258) Update puppet-agent version to greenify tests

---

dev-resources/puppetlabs/puppetserver/auth_conf_test/csr_attributes.yaml
dev-resources/puppetlabs/puppetserver/auth_conf_test/custom_trusted_oid_mapping.yaml
dev-resources/puppetlabs/puppetserver/auth_conf_test/puppet.conf
project.clj
src/clj/puppetlabs/puppetserver/certificate_authority.clj
src/clj/puppetlabs/services/ca/certificate_authority_disabled_service.clj
src/clj/puppetlabs/services/ca/certificate_authority_service.clj
src/clj/puppetlabs/services/config/puppet_server_config_core.clj
src/clj/puppetlabs/services/legacy_routes/legacy_routes_service.clj
src/clj/puppetlabs/services/master/master_service.clj
src/clj/puppetlabs/services/protocols/ca.clj
src/clj/puppetlabs/services/puppet_admin/puppet_admin_service.clj
test/integration/puppetlabs/puppetserver/auth_conf_test.clj
test/integration/puppetlabs/services/jruby/jruby_pool_int_test.clj
test/unit/puppetlabs/services/ca/certificate_authority_disabled_test.clj

Ensure the puppet OID shortname mappings and the custom
oid mappings provided in the custom oid mappings file are passed
to tk-auth.
This will require a release of tk-auth before it can be merged.

(SERVER-1245) Pass OID shortnames to tk-auth

---

test/integration/puppetlabs/services/master/environment_classes_int_test.clj

This commit adds a `trusted-oid-mapping-file` setting value that the
mock pupppetserver config service in the test uses.  This was added in
order for the newly added code which handles the trusted oid mapping
file to work without any problems - although it isn't directly related
to anything that the specific test validates.

(SERVER-1245) Add trusted oid mapping to env classes int test

---

acceptance/lib/helper.rb

This commit updates the puppet-agent ref to fix PUP-6176, which had been
causing puppetdb module failures on ubuntu-14.04.

(SERVER-1258) Update puppet-agent ref to greenify tests

---

Gemfile
acceptance/suites/pre_suite/foss/30_install_dev_repos.rb

In the recent past I attempted to update puppet-server to beaker 2.38.1.  The initial runs through CI were successful, but the nightly runs failed, because they use a larger set of test hosts, including some that do not have PuppetDB packages (fedora 21 and ubuntu 15).
Trying again.  This time, rather than relying on beakers broken confine_block (which modifies the global hosts list), I'm using a simple if statement to choose when we install PuppetDB packages.
I'll update this comment to list the layout flavors I've tested.  We shouldn't merge until I've tested on Fedora 21, Ubuntu 15, (the previously failing OSes) as well as at least one of the working ones.  Meanwhile I'd appreciate comments/review.
Tested on 
fedora21-64ma.
ubuntu1504-64ma-32a

Updates to beaker 2.38.1, and works around BKR-650

---

acceptance/suites/pre_suite/foss/30_install_dev_repos.rb
acceptance/suites/pre_suite/foss/35_install_pdb.rb

The previous PR treated puppetdb_supported_platforms as an array of strings.  It is actually an array of regexps.  See SERVER-1292

(MAINT) fixes a logic error in PR#1009

---

Gemfile

We require new versions of both these projects to support testing on
Ubuntu 16.04 Xenial

(maint) Bump Beaker and hostgenerator

---

documentation/puppetserver_vs_passenger.markdown

This commit adds some basic documentation about how logging differs
between puppetserver and passenger.

(SERVER-1257) Document loglevel differences for puppetserver vs passenger

---

acceptance/README.md
acceptance/scripts/generic/testrun.sh

Use Bash's syntax for assigning default values to variables so that values set in the environment can trump defaults set in the script. Update README to reflect these changes.

(MAINT) Assign default values expansion for all BEAKER_*

---

acceptance/lib/helper.rb

This commit bumps the puppet-agent dependency up to da1e61e and the
corresponding Ruby puppet submodule up to 57315f.

(MAINT) Bump puppet agent dep to da1e61e

---

documentation/config_file_puppetserver.markdown

- Add space between all list items for consistent rendering.
- Fix rendering issue with a blockquoted note and sublist in a list item.

(doc) Fix markdown in the puppetserver.conf doc.

---

acceptance/lib/helper.rb
spec/puppet-server-lib/puppet/jvm/master_spec.rb

This bump includes updates to the Xenial puppet-agent build that
compiles facter with JNI support.

(maint) Bump puppet version

---

acceptance/suites/tests/code_commands/code_scripts.rb

(MAINT) Corrects the assignment in the skip_test to a test.

---

acceptance/lib/helper.rb

Note that this has not been tested, and that this particular agent build failed Windows tests in the puppet agent pipeline.  I want to try it anyhow because it is a later complete build, and because we are already red.

(MAINT) moved up puppet agent pin

---

acceptance/lib/helper.rb

When we ported `https_request()` to puppetserver acceptance, we forgot to bring along a couple of helpful methods for it. This commit remedies that omission.

(MAINT) Add helper functions encode_{cert,key} to support https_request

---

src/ruby/puppet-server-lib/puppet/server/logger.rb

As of this commit in PUP:
https://github.com/puppetlabs/puppet/commit/6debe89bd935d56e2ec424900ad6f573bbf45552
It became critical that log destinations call `to_s` on the `Log` object
in order to ensure that they log all of the extra information (such as
backtraces).  Prior to this commit, the Puppet Server logback log
destination was calling `message` instead of `to_s`, so we were missing
all of the extra detailed information in our log messages.

(SERVER-1273) Add back in info that is missing from log messages

---

acceptance/suites/tests/authorization/default_rules.rb

Previously, all the checks of requests being denied were matching against the
rule. However, for TK-360 the rule name was removed from the response. This
commit updates those assertions to match against the path and method (which
are in the response) instead.

(TK-360) Fix acceptance tests testing denied response

---

acceptance/suites/tests/00_smoke/validate-excluded-bc-jars.rb
documentation/dev_trace_func.markdown
documentation/restarting.markdown
project.clj

Because of how EZBake finds the pid on Cent6 (involves a pgrep for
the jar file name), upgrades on that distro will fail if we change
the jar name without changing the ezbake logic as well.  It seems
easier to just change the jar name back for now.

(maint) add hyphen back to uberjar name

---

project.clj
src/clj/puppetlabs/puppetserver/jruby_request.clj
src/clj/puppetlabs/puppetserver/ringutils.clj
src/clj/puppetlabs/services/ca/certificate_authority_core.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj
src/clj/puppetlabs/services/master/master_core.clj
src/clj/puppetlabs/services/request_handler/request_handler_core.clj
test/unit/puppetlabs/puppetserver/ringutils_test.clj
test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj
test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj

Previously we copied and pasted (with slight changes) much of what made
up our ringutils.
As part of TK-214, the re-usable portions have moved to
puppetlabs/ring-middleware. This patch updates puppetserver to use those
common library functions and removes the outdated vendored functions.

Take up ring-middleware helpers

---

test/integration/puppetlabs/services/jruby/jruby_pool_int_test.clj

This commit bumps up the default timeout for jruby-pool-int test
borrows from 3 minutes to 5 minutes.  This compensates for sporadic
failures we've seen in Travis CI when it took more than 3 minutes for a
JRuby pool initialization to complete.

(MAINT) Bump up default borrow timeout for jruby-pool-int tests

---

Gemfile

In most test scripts, and all the CI pipelines I've looked at, we set our GEM_SOURCE to http://rubygems.delivery.puppetlabs.net.  Performing bundle operations while inadvertently having to failed EXPORT GEM_SOURCE=http://rubygems.delivery.puppetlabs.net is a constant annoyance.
Let's set the default to the thing that works.

(MAINT) updates GEM_SOURCE default

---

acceptance/lib/helper.rb
project.clj
resources/ext/ezbake.conf

This should get master acceptance tests passing again.
Also, bump puppetserver version to 2.5.0-master for post 2.4.0 development.

(maint) Merge up stable to master

---

project.clj

Do not merge until nightly (https://jenkins.puppetlabs.com/view/puppetserver/view/all/job/platform_puppetserver_integration-system_no-conditional_full-stable/ - job kicked off at 1:45am PDT May 17) has passed CI.

(SERVER-1336) Bump version to 2.4.0 for release

---

documentation/install_from_packages.markdown

-   Bump version references since 2.4 depends on agent 1.5.
-   Add Wily and Xenial.

(doc) Update install from packages doc.

---

project.clj

This commit upgrades us to the latest version of ezbake, which fixes
a bug in the bootstrap `services.d` packaging on systemd platforms.

(SERVER-1247) upgrade to ezbake 0.4.2

---

acceptance/lib/helper.rb

Now that PuppetDB and Puppet Server packages have been released for ubuntu
16.04, we can run PuppetDB tests for that platform.
Bump the PuppetDB version we test against to 4.1.0, since that is what
released Xenial support.

(SERVER-1350) Add ubuntu 16.04 to list of PuppetDB supported platforms

---

dev-resources/puppetlabs/puppetserver/certificate_authority_test/csr_attributes/csr_attributes_with_auth.yaml
src/clj/puppetlabs/puppetserver/certificate_authority.clj
test/unit/puppetlabs/puppetserver/certificate_authority_test.clj

This PR adds a new OID arc, ppAuthCertExt, and two new OIDs to that
arc: pp_authorization and pp_auth_role. These are OIDs intended for use
in extension-based tk-auth configurations.
This PR also adds a new unit test for create-csr-attrs-exts to make
sure we're translating OIDs into short names properly.
Finally, I noticed that create-csr-attrs-exts didn't have a return schema, so I added that.

(PUP-6258) Add new authorization OIDs to CA

---

acceptance/lib/helper.rb
documentation/install_from_packages.markdown
documentation/release_notes.markdown

to bring in the Xenial test helper changes for SERVER-1350 and also some docs changes.
Only conflict was in project.clj around the version number for puppetserver itself - I kept it as `2.5.0-master-SNAPSHOT`.

(maint) merge up master to stable may 25 2016

---

project.clj
src/clj/puppetlabs/puppetserver/certificate_authority.clj
src/clj/puppetlabs/puppetserver/cli/subcommand.clj
src/clj/puppetlabs/puppetserver/jruby_request.clj
src/clj/puppetlabs/services/ca/certificate_authority_core.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj
src/clj/puppetlabs/services/master/master_core.clj
src/clj/puppetlabs/services/request_handler/request_handler_core.clj
test/unit/puppetlabs/puppetserver/certificate_authority_test.clj
test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj

This moves us to use the standard exception format defined in the nogui repo. It also bumps our ring-middleware and tk-auth dependencies as they are also updated to use the new exception format.

(SERVER-1310) Use standard exception format

---

test/unit/puppetlabs/puppetserver/lockable_pool_test.clj

This commit adds some logic to the
pool-lock-supersedes-existing-borrows-test to try to wait until
.isLocked() returns true for a requested lock until the test moves on to
validating that borrow requests are held off by the lock.  Without this
change, it was more likely (although still somewhat rare) for the test
to return instances to the pool before the .lock() request was even
made, leading to borrow requests being granted immediately rather than
being held off by the lock.  Test assertions would fail as a result.

(SERVER-1375) Adds a pool lock check to pool-lock-supersedes test

---

documentation/restarting.markdown

There was a docs fix that required creating a temporary 2.3.x
branch.  This commit merges up that docs change from 2.3.x to stable.

(MAINT) Merge up 2.3.x branch to stable

---

project.clj

This commit upgrades us to kitchensink 0.3.1, which contains a fix
that gets rid of a warning that comes from a new version of clojure.tools.cli.
In older versions of kitchensink we were using a feature of
clojure.tools.cli called `:flag`, which is now deprecated.
This code path was exercised by `puppetserver gem`, which meant that
every time a user interacted with that command (explicitly or via
the puppet module that manages puppetserver gems), the deprecation
warning would be logged.
I've manually tested (via `lein gem`) that upgrading to the newer
kitchensink makes the warning go away.

(SERVER-1378) fix warning from "gem list"

---

documentation/restarting.markdown
project.clj

This merges up from stable, mostly for the purposes of getting the kitchensink upgrade, which fixes SERVER-1378.

(SERVER-1378) Merge up stable to master, 2016-06-08

---

spec/puppet-server-lib/puppet/jvm/master_spec.rb

Forgot when I tested https://github.com/puppetlabs/puppetserver/pull/1111 that the version we were failing against in PE for the Davis pipeline was not what we are testing in FOSS (so now FOSS is red [here](https://jenkins.puppetlabs.com/job/platform_puppetserver_integration-system_no-conditional_smoke-master/106/LAYOUT=ubuntu1604-64ma-64a,LDAP_TYPE=default,PLATFORM=default,label=beaker/testReport/junit/(root)/acceptance_suites_tests_authorization/default_rules_rb/))
Previously the master branch was pinned to 4.5.0 release of puppet in preparation for Couch hardening. This updates puppetserver#master to what is now promoted into Davis. This includes improvements to indirector REST API errors and the new OID arc for cert extensions.
Still failing to run these locally... (not they're …

Bump Puppet to latest agent in Davis (743255d)

---

acceptance/lib/helper.rb

Set version of puppet-agent (db533e0) in acceptance tests to one
that includes the puppet from our dev env (743255d).

(maint) Bump version of Puppet Agent used in Acceptance tests

---

acceptance/lib/helper.rb

I don't even... This is a few builds farther ahead than the last one (so should have similar content) but I **think** this link confirms that it has been promoted into PE and has been built against all of our desired platforms: http://agent-downloads.delivery.puppetlabs.net/2016.3/puppet-agent/1.5.1.123/repos/  Though at this point of frustration I wouldn't trust anything I say.

(maint) Update to new version of puppet-agent

---

project.clj

This commit bumps us up to ezbake 0.2.12, which includes a backport
of the master ezbake branch's change to stop setting
-XX:+HeapDumpOnOutOfMemoryError by default.

(SERVER-1304) Upgrade to ezbake 0.2.12

---

acceptance/suites/tests/authorization/hup_reloads_crl.rb

After revoking a certificate, HUP the server and see if the revoked certificate is accepted. It shouldn't be.

(SERVER-1380) Validate that the CRL is reloaded after HUPing the server

---

src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_core_test.clj

Moves the call to add-facter-jar-to-system-classloader out of
initialize-and-create-jruby-config into the jruby-puppet-service
Moves a logging statement out of initialize-and-create-jruby-config

(SERVER-1163) Refactor initialize-and-create-jruby-config

---

acceptance/lib/helper.rb

This bumps the version of the puppet-agent package used in acceptance
tests to 1.5.2.170.g236f05f which contains puppet at
fffcf8a6bf59f6cb2d1d9a555a8c6c28e5d33606 which is the same commit that
the puppet submodule is currently at.
Hopefully, this change will fix the 'scheduled_task' test failures
currently happening on Jankins.

(SERVER-1400) Bump puppet-agent package version

---

acceptance/lib/helper.rb

This updates puppet and the corresponding puppet-agent versions;
the hope is that this will fix the current failures in the
master branch, which appear to be related to us having been pinned
to a version of puppet that is no longer available on the build servers.

(MAINT) Update puppet version to ef8f234

---

acceptance/lib/helper.rb

Bump the puppet submodule to 257d5b2d6ed94def50e8d6e040302d1c87135947
which contains a fix for the scheduled_task tests which are failing on
Jankins.  Correspondingly, bump the puppet-agent package dependency to
1.5.2.176.g21e3a74.

(SERVER-1400) Bump puppet/puppet-agent dependencies

---

acceptance/suites/externalCA_tests/020-external-ca/030_revoke_agents.rb
acceptance/suites/tests/00_smoke/validate-syslog-logback.rb
acceptance/suites/tests/code_commands/code_scripts.rb

Now that TK has HUP support, we can replace {some|many|most} server restarts with server HUPs, which will reduce acceptance suite's total runtime. This change makes 3 such changes. There are restarts or starts and stops in the acceptance suite, but they seemed to part of the test in those cases. 
In local testing, these 3 changes reduced the runtime of an ubuntu1604-mda-redhat6-64a-windows2008r2 config from 29:05 to 20:51. Runtime for a redhat6-64mda-ubuntu1404-64a-windows2008r2-64a went from 23:53 to 22:46.  Not highly rigorous testing, but there ya go.

(MAINT) Replace server restarts with server HUPs

---

src/clj/puppetlabs/puppetserver/certificate_authority.clj
test/unit/puppetlabs/puppetserver/certificate_authority_test.clj

Flat out reject any CSRs with authorization extensions. For the
immediate future, such CSRs must be signed using the puppet cert tool.
This PR also adds a small helper to the CA tests to help make assertions about slingshot errors.

(SERVER-1307) reject CSRs with authorization extensions

---

acceptance/lib/helper.rb

The packages for the previous puppet-agent SHA we were pinned too were purged.
This commit updates us to the latest passing puppet-agent version off stable.

(maint) Bump puppet-agent version

---

acceptance/lib/helper.rb
spec/puppet-server-lib/puppet/jvm/master_spec.rb

The packages at the SHA for our previous puppet-agent pin were purged (they
get purged every 2 weeks), so this updates the puppet-agent pin to 1.5.2 (last
released) and puppet submodule to 4.5.2 (included in puppet-agent 1.5.2).

(maint) Update puppet-agent pin to 1.5.2

---

acceptance/README.md

Using `PUPPET_BUILD_VERSION` because setting `PUPPET_VERSION` didn't work outside of CI

(MAINT) Update to use PUPPET_BUILD_VERSION

---

src/clj/puppetlabs/puppetserver/certificate_authority.clj

The information captured in various vars in certificate_authority.clj is
duplicated in the puppet codebase. Creating a shared oids file isn't
easily achieveable today, so instead this commit adds a comment above
those vars in certificate_authority.clj explaining that any changes to
the oids need to be replicated in the puppet codebase.

(PUP-6335) Add note explaining duplication in certificate_authority.clj

---

documentation/configuration.markdown
documentation/services_master_puppetserver.markdown

Several log paths still distinguish paths between open source Puppet Server and Puppet Enterprise, and one uses Server 1.x paths. This PR updates these paths.

(SERVER-1414) Update log paths

---

acceptance/lib/helper.rb

This commit has not fully passed the the agent pipeline's CI. This commit (and it has not ran since) is failing on building packages for platforms that we do not test in our CI pipelines (I do not believe those failures are actually related to this change). It successfully built packages for the platforms that we test, and running Puppet's `acceptance/tests/ticket_3360_allow_duplicate_csr_with_option_set.rb` without this patch fails locally, but passes with this bump.

(maint) Bump Puppet & Agent to fix CI

---

test/integration/puppetlabs/services/jruby/jruby_puppet_pool_int_test.clj

This commit adds an initial GET request to the environments endpoint to
the `test-503-when-app-shuts-down` test.  Without this extra call, it
is more likely for the environment ping logic in the test to exhaust up to
the maximum configured 10 second wait if the initialization of the second
JRubyPuppet instance, the one servicing the environments requests, takes
a sufficiently long amount of time.  This would, in turn, cause
assertions related to the service stop to fail because the stop was not
far enough along before the assertions were made.

(SERVER-1440) Close up test-503-when-app-shuts-down race condition a bit

---

acceptance/lib/helper.rb

This is a workaround to make CI green while we locate and fix an apparent race condition. The behavior we are seeing is that after calling `file_sync_commit` and/or `wait_for_clients_to_sync` immediately following `hup_server`, some of tests, and only in CI, fail with ECONNREFUSED. It seems like puppetserver is ready before (at least) the file sync commit and status endpoints are. We can't capture it in local runs.

(MAINT) Add a sleep to hup_server

---

dev/bootstrap.cfg
dev/user_repl.clj
ezbake/system-config/services.d/bootstrap.cfg
project.clj
src/clj/puppetlabs/services/master/master_service.clj
test/integration/puppetlabs/services/legacy_routes/legacy_routes_test.clj
test/integration/puppetlabs/services/master/environment_classes_int_test.clj
test/unit/puppetlabs/services/config/puppet_server_config_service_test.clj
test/unit/puppetlabs/services/master/master_service_test.clj
test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj

Prior to this commit, the checkin for puppetserver would only run on
start up. This commit updates that functionality by using
trapperkeeper/scheduler to schedule a regular interval checkin job that
will run at start up, and then again every 24 hours.

(SERVER-1442) Update FOSS puppetserver checkin to be on interval

---

acceptance/lib/helper.rb

Sleeping at the end didn't end the race; reverting the commit

(MAINT) Revert commit 9ae8ee9

---

acceptance/lib/helper.rb

After HUPping the server, the `hup_server` method should wait until the server returns a HTTP 200 on the status endpoint. The current behavior, bailing after getting an HTTP 404 on the status endpoint, returns control from `hup_server` before the server has fully restarted. As a result, some file sync commit operations that occur immediately following a `hup_server` call fail with `ECONNREFUSED` because the server has not even finished shutting down. With this change,`ECONNREFUSED` doesn't occur and life is wonderful.

(MAINT) Wait for server to return 200 before returning

---

acceptance/lib/helper.rb
spec/puppet-server-lib/puppet/jvm/master_spec.rb

This commit bumps up the Puppet submodule and puppet package versions in
order to pick up a pin of the json-pure gem to '~> 1.8', which allows
the Ruby spec tests to continue to be run under Ruby 1.9.3.  Previously,
the version of the json-pure gem that was being installed was not
pinned.  The recently released version, 2.0.2, dropped support for
running under versions of Ruby earlier than 2.0.

(SERVER-1454) Bump puppet pins to pick up json-pure pin

---

acceptance/lib/helper.rb
spec/puppet-server-lib/puppet/jvm/master_spec.rb

This commit adjusts the puppet submodule and puppet-agent pins to track
current artifacts from the Ruby Puppet master branch - f93e63b and
ba39f2f, respectively - in order to pick up the json_pure changes.  A
prior commit had repinned these to artifacts tracking the Ruby Puppet
stable branch, which is inappropriate to do currently because changes
recently merged down to the Puppet Server stable branch need to track
the Ruby Puppet master branch.

(SERVER-1454) Repin puppet to master branch ba39f2f for json_pure fix

---

acceptance/suites/pre_suite/foss/70_install_puppet.rb

This commit ensures that the nss package is upgraded to the latest
available version before openjdk and puppetserver are installed during a
CI test run.  Prior to this change, the nss package was not upgraded,
which could lead to puppetserver erroring out with a
`java.lang.InternalError` at service startup - due to apparent version
conflicts between pre-3.21.0 versions of nss and openjdk 1.7.0_111 and
later.

(SERVER-1456) Upgrade nss before puppetserver install in CI pre-suite

---

acceptance/lib/helper.rb

Merge branch 'stable' into master at 82ae322e
* stable:
(SERVER-1454) Repin puppet to master branch ba39f2f for json_pure fix
(SERVER-1454) Bump puppet pins to pick up json-pure pin
(SERVER-1454) Bump puppet pins to pick up json-pure pin
(maint) Update puppet-agent pin to 1.5.2
(SERVER-1400) Bump puppet/puppet-agent dependencies
(SERVER-1400) Bump puppet-agent package version
(maint) Fix puppet version in JRuby spec test
(SERVER-1400) Update Puppet submodule to fffcf8a6
(SERVER-1304) Upgrade to ezbake 0.2.12
(SERVER-1378) fix warning from "gem list"
(MAINT) Merge up 2.3.x branch to stable
Conflicts:
- projects.clj - Kept the ps-version on master, 2.5.0-master-SNAPSHOT,
and not the one from stable, 2.5.0-stable-SNAPSHOT.
This only pulls in two sets of changes:
- Bumps to the Puppet …

Merge stable to master at 82ae322e

---

acceptance/suites/pre_suite/foss/70_install_puppet.rb

Merge branch '1.x' into stable
* 1.x:
(SERVER-1456) Upgrade nss before puppetserver install in CI pre-suite
Conflicts:
-   acceptance/suites/pre_suite/foss/70_install_puppet.rb - Small
conflicts in the "Install MRI Puppet Agents" steps, all resolved in
favor of the existing implementation on the "stable" branch.  Pulled
in the logic from 1.x to upgrade the nss package before installing
Puppet Server.

(SERVER-1456) Merge branch '1.x' into stable (for nss upgrade pre-suite step)

---

project.clj

This commit upgrades us to ezbake 0.4.3, which contains a fix for
a bug where the packages would create an empty pidfile at install
time, before the service was started.

(SERVER-1455) Ezbake 0.4.3, empty pidfile fix

---

project.clj

This merges the ezbake version bump (to 0.4.3) up from stable to master.

(SERVER-1455) merge up from stable

---

acceptance/lib/helper.rb

The modify_tk_config beaker command corrupts config files. This PR adds a new helper method, `apply_one_hocon_setting`, to the test library. It adds or updates a single hocon setting in a TK config file. PR also adds a helper method to _remove_ a single hocon setting, `delete_one_hocon_setting`.

(SERVER-1453) Create helper for adding/updating TK config files

---

acceptance/lib/helper.rb

This commit adds `EOFError` to the list of exceptions that `hup_server` eats. We weren't catching all of the possible errors we might get from the server when trying to connect while it is coming down or starting up. This is one; there might be more. Additional discussion in QENG-3393.

(QENG-3393) Teach hup_server to eat EOFError

---

acceptance/lib/helper.rb

This commit updates us to the latest versions of puppet/puppet-agent
that are passing CI.  These should be very close to the final
tagged versions for 1.6.0, so getting them into our CI now will
help make sure we're ready for release.

(MAINT) Update to latest green puppet-agent, prep for 1.6.0

---

project.clj

DO NOT MERGE UNTIL COORDINATING IN HIPCHAT!
This commit bumps our version number to 2.5.0 for release.  When CI runs against this commit it will produce the final maven artifacts for the 2.5.0 release automatically.

(FOR REVIEW) (SERVER-1426) Update version to 2.5.0 for release

---

documentation/_puppetserver_nav.html
documentation/bootstrap_upgrade_notes.markdown
documentation/configuration.markdown

The on-page nav for the bootstrap upgrade notes page is missing most of the headings, and a code block is rendering incorrectly there. Adjust the markdown to render correctly on the docs site.
Also, add the bootstrap upgrade page to the backup site nav, and update the configuration docs to note the changes.

(docs) Update bootstrap markdown, configuration doc

---

acceptance/lib/helper.rb

This commit allows the `journal -u` command to return with a failure.
This would happen if a service has no output for some reason. Although
this is not common, this is the case for puppetserver on sles 12. The
start and stop of this process is not recorded in the systemd journal.
As a result, `journalctl -u puppetserver` will fail even though the
puppetserver service is running successfully.

(maint) Do not fail if journalctl is empty

---

Gemfile

This commit adds the master_manipulator gem to the puppetserver Gemfile. This is the first of a series of commits to enable using QA's master_manipulator gem instead of test libraries embedded in the repos we test.

(QA-2605) Move QA test library to master_manipulator

---

documentation/config_logging_advanced.markdown

With the latest version of _puppetserver_, if I copy / paste the documentation you actually provide for converting access logs to JSON, I only get the following output in my log file:
```
{"@version":1}
```
without any information about the request made.
This patch corrects the documentation to obtain correct log using java _LogBack_.

Fixes documentation about advanced logging

---

documentation/bootstrap_upgrade_notes.markdown
documentation/configuration.markdown
documentation/external_ca_configuration.markdown
documentation/puppet_conf_setting_diffs.markdown
documentation/release_notes.markdown
documentation/restarting.markdown
documentation/tuning_guide.markdown

-   Rewrite and expand parts of the bootstrap upgrade notes.
-   Update references to bootstrap.cfg/ca.cfg across the docs.
-   Expand the release note warning.

(docs) Update & expand bootstrap.cfg/ca.cfg notes

---

Rakefile

Previously we installed all of Puppet's gem groups for JRuby testing.
Gems in the `extra` group have caused breakages in CI even though they
are unused in puppetserver testing.
This updates the Rakefile to exclude `extra` and `development` gem
groups from the installation during JRuby specs to improve CI stability.

(maint) Exclude unnecessary gem groups from JRuby testing

---

documentation/deprecated_features.markdown
documentation/puppet-api/v3/environment_classes.markdown

Supports [DOC-2646](https://tickets.puppetlabs.com/browse/DOC-2646).

(docs) Add resource_types deprecation notes.

---

acceptance/lib/helper.rb
acceptance/suites/tests/status_service/status_service.rb
dev/bootstrap.cfg
dev/puppetserver.conf.sample
dev/user_repl.clj
ezbake/config/conf.d/web-routes.conf
ezbake/system-config/services.d/bootstrap.cfg
project.clj

This commit adds the trapperkeeper-status service to Puppet Server and
registers an HTTP web-route for it at "/status".

(SERVER-1502) Add the trapperkeeper-status service and web route

---

src/clj/puppetlabs/puppetserver/shell_utils.clj

In some cases it would be advantageous to log a warning at application
startup (or fail to start entirely) if a command is invalid for some
reason. This is not possible while validate-command! is a private
function, so this commit removes the private annotation and moves it
into the public section of shell-utils.

(maint) Make shell-utils/validate-command! public

---

project.clj
test/integration/puppetlabs/services/jruby/jruby_puppet_pool_int_test.clj

This commit upgrades the jruby-utils dependency to 0.2.1, transitively
updating JRuby dependencies to 1.7.26.  Explicit JRuby dependencies were
removed since they can now be inherited from jruby-utils.

(SERVER-858) Upgrade to jruby-utils 0.2.1 / JRuby 1.7.26

---

acceptance/lib/helper.rb

This commit bumps the puppet submodule and package pin up to 4d95e13.

(MAINT) Bump puppet pin to 4d95e13

---

ezbake/config/logback.xml
project.clj
resources/ext/config/request-logging.xml

This commit updates puppetserver's logback file to limit the amount of space
log files can take up.
Since logback is handling log rotation now, `logrotate` is disabled through a new ezbake setting
---
This PR relies on SNAPSHOT builds of ezbake 02.x and trapperkeeper 1.1x, so those two will need to be released before this is merged
The new logback changes will be ported to the master branch as well

(SERVER-366) Limit log disk usage

---

acceptance/lib/helper.rb
spec/puppet-server-lib/puppet/jvm/master_spec.rb

This commit bumps the puppet-agent pin forward to bec3ff8 and
corresponding puppet submodule to 06fd34b.

(MAINT) Bump puppet-agent pin to bec3ff8

---

acceptance/lib/helper.rb

This commit bumps the puppet-agent pin to 1.6.2 and puppet submodule to
4.6.2.

(MAINT) Bump puppet/agent pin to 1.6.2 / 4.6.2

---

project.clj
test/unit/puppetlabs/services/jruby/jruby_interpreter_test.clj

This commit bumps the JRuby dependency up to 1.7.26, in order to resolve
SERVER-858 and SERVER-1408.

(SERVER-858) Bump JRuby to 1.7.26

---

project.clj

This commit bumps the version of Puppet Server in the project.clj file
for the 1.2.0 release.

(MAINT) Bump version for 1.2.0 release

---

project.clj

This commit bumps the version of Puppet Server in the project.clj file
for the 2.6.0 release.

(MAINT) Bump version for 2.6.0 release

---

project.clj

This commit bumps the project.clj version to 2.6.1-stable-SNAPSHOT for a
future potential release.

(MAINT) Bump version for 2.6.1-stable-SNAPSHOT

---

project.clj

This commit bumps the project.clj version to 1.2.1-SNAPSHOT for a future
potential release.

(MAINT) Bump version for 1.2.1-SNAPSHOT

---

acceptance/suites/pre_suite/foss/30_install_dev_repos.rb

Because the install_puppetlabs_dev_repo uses the same tmpdir under the
hood to prepare repos, if the contents of the repos are not the same,
they will end up causing package install failures, as was seen today
when a new Packages.bz2 file caused the second repo to be corrupted.
This commit manually cleans up the tmpdir to avoid this, until this can
be fixed in beaker itself.

(maint) Pass in a custom tmpdir to install_puppetlabs_dev_repos

---

src/clj/puppetlabs/services/config/puppet_server_config_core.clj

This commit updates the puppet-config-keys map to include
data_binding_terminus to be able to determine that puppet is configured
to use hiera.

(PE-17071) Include data_binding_terminus setting in puppet config keys

---

spec/puppet-server-lib/puppet/jvm/execution_spec.rb
src/ruby/puppetserver-lib/puppet/server/execution.rb

Prior to this commit, Puppet Server's implementation of `ExecutionStub`
would ignore the `:failonfail` option.  The documented behavior is to
raise a `Puppet::ExecutionFailure` if the command returns a non-zero
exit code.
This commit refactors the ExecutionStub code a bit to allow the
options hash to be passed in (which also required some refactoring
of the tests).  Then, if `:failonfail` is set, we raise the appropriate
error when the exit code is non-zero.

(SERVER-1570) ExecutionStub should raise error on failonfail

---

Gemfile

docker-api version 1.32.0 introduced a dependency on ruby >= 2.0.
This commit pins us to the older docker version in order to avoid
that dependency until we no longer have ruby 1.9.3 in our test
matrices.

(QENG-4425) Pin docker-api gem version

---

spec/fixtures/puppet-server-lib/puppet/jvm/execution_spec/echo_stdout_and_stderr.sh
spec/puppet-server-lib/puppet/jvm/execution_spec.rb
src/clj/puppetlabs/puppetserver/shell_utils.clj
src/java/com/puppetlabs/puppetserver/ShellUtils.java
src/ruby/puppetserver-lib/puppet/server/execution.rb

This commit modifies the ShellUtils java code to support the ability
to combine STDOUT/STDERR into a single stream, and modifies the
Puppet::Server::Execution implementation of the Puppet ExecutionStub
so that if the `:combine` option is set, STDOUT/STDERR will be
combined.

(SERVER-1571) Support `:combine` to merge STDOUT/STDERR

---

dev-resources/puppetlabs/puppetserver/shell_utils_test/env
src/clj/puppetlabs/puppetserver/shell_utils.clj
test/unit/puppetlabs/puppetserver/shell_utils_test.clj

A recent refactor resulted in a subtle change in behavior in the
clojure shellutils wrapper, wherein if you did not pass an
explicit list of environment variables to the command, you would
end up with an empty map of environment variables for the shell
command.  Prior to that refactor, you would instead have inherited
all of the environment variables from the java process, which is
the desired behavior.  This change broke some acceptance tests which
were relying on having access to environment variables such as PATH.
This commit changes the environment variable behavior back to the
previous setup, where the java environment variables will be passed
through to the shell command unless you explicitly override the
environment.

(SERVER-1571) ensure environment passed to clj shellutils

---

documentation/config_file_auth.markdown

The Puppet docs site's Jekyll handles Markdown indentation of code blocks that are inside of lists differently than GitHub does. These Markdown changes should fix rendering of these code blocks on the docs site without affecting it on GitHub.

(docs) (DOCUMENT-590) match-request formatting

---

documentation/config_logging_advanced.markdown
documentation/services_master_puppetserver.markdown
ezbake/config/logback.xml
resources/ext/config/request-logging.xml

This commit changes the logback log rolling policies to use gz instead
of zip for the archive format and 200MB instead of 10MB as the maximum
size for a log file.

(SERVER-1589) Change logback logs to 200MB maxFileSize and gz format

---

project.clj

This commit does the following:
* Updates to lein-ezbake 1.1.1 which fixes bugs preventing managed
dependencies from working.
* Adds in explicit `nil` versions to the dependencies listed in
our ezbake profile, because of technomancy/leiningen#2216

(SERVER-1591) Work around NPE w/ezbake & managed deps

---

dev/puppetserver.conf.sample
documentation/config_file_puppetserver.markdown
project.clj
resources/ext/build-scripts/gem-list.txt
resources/ext/build-scripts/install-vendored-gems.sh
resources/ext/config/conf.d/puppetserver.conf
resources/ext/ezbake.conf
src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj
test/integration/puppetlabs/services/jruby/jruby_puppet_pool_int_test.clj
test/unit/puppetlabs/puppetserver/ruby/http_client_test.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_core_test.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_testutils.clj
test/unit/puppetlabs/services/master/master_core_test.clj
test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj

This PR adds the `semantic_puppet` and `hocon` gems to the puppetserver package, by installing the gems at packing time and then including them in the package.  It also adds the ability to configure the `:gem-path`, which by default will now include both the new, vendored jruby gems directory, and the original jruby gems directory.
(I've built packages and run the smoke tests in beaker locally, so I think this is ready to go.)

(SERVER-1412) package gems

---

acceptance/suites/tests/service_framework/reload_updated_crl.rb

This commit loosens the string which is checked in the
reload_updated_crl test for an SSL connection failure on a run made
from a revoked agent.  The test previously checked for 'SSL_connect
SYSCALL returned=5' but the 'SYSCALL returned=5' part may or may not
occur depending upon how the agent detects the handshake failure.
Occasionally, it just appears as a 'Connection reset by peer -
SSL_connect' message instead.  This commit just loosens the text to
'SSL_connect', which should be good enough to determine that the
connection failed even if the exact nature of the failure is a bit
less precise.

(MAINT) Loosen SSL_connect error check in reload_updated_crl test

---

Gemfile

@rlinehan @camlow325 @cprice404 @nwolfe 
So here's a revert of the BHG work I submitted earlier. This is necessary because there is an implicit dependency between beaker-hostgenerator and beaker >=2 as @camlow325 suspected earlier today.
We shouldn't need to merge this up into stable because stable branch is on a modern version of beaker.
I'll work on making beaker-hostgenerator compatible with this branch of puppetserver and verify it works on my own fork of the repo before submitting another PR to revert this revert.

Revert beaker-hostgenerator upgrade

---

documentation/config_file_puppetserver.markdown
test/unit/puppetlabs/services/jruby/jruby_puppet_core_test.clj

This commit fixes a few docs/examples, and removes
an unused var in one of the jruby test namespaces.

(SERVER-1412) Minor clean-ups based on PR review

---

Gemfile

beaker-abs provides a custom hypervisor in support of the always-be-scheduling
backend resource allocator, which is necessary for the CI.Next job migration
work.

(QENG-4310) Add beaker-abs dependency.

---

project.clj

This commit bumps the lein-ezbake plugin dependency from 1.1.2 to 1.1.3.
This change re-adds the XXOutOfMemoryError java command line arg which
had unintentionally been dropped as part of the ezbake bump for service
reload functionality done for SERVER-1490.

(SERVER-1490) Bump lein-ezbake dep to 1.1.3

---

documentation/config_file_puppetserver.markdown
project.clj
test/integration/puppetlabs/services/jruby/jruby_puppet_pool_int_test.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_core_test.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_testutils.clj

This commit exposes the JRuby MRI `compat-version` as an experimental
configurable option.  The underlying work which enables this is all in
a new version of jruby-utils, 0.4.0, and this commit bumps the
dependency to this new version.

(SERVER-1585) Expose JRuby `compat-version` as an experimental option

---

locales/messages.pot
src/clj/puppetlabs/services/master/master_service.clj
test/unit/puppetlabs/services/master/master_service_test.clj

Prior to this commit, there was no way to opt-out of update checking and
telemetry data collection. This commit updates puppetserver to look for
an opt-out file on disk before checking for updates and sending
telemetry data.

(SERVER-1599) Enable Telemetry/Update check opt-out

---

acceptance/suites/tests/00_smoke/master_starts_if_agent_run_before_ssl_files_inited.rb
src/clj/puppetlabs/puppetserver/certificate_authority.clj
test/unit/puppetlabs/puppetserver/certificate_authority_test.clj

Previously, if a master public key were present but the master cert were
not at startup, Puppet Server would error out at startup with a "partial
state error" message.  This was problematic if an agent were run on the
master before the master had been started for the first time since the
initial agent run would create a public and private key for the master.
This PR changes the master cert initialization logic to generate the
cert from a public key already on disk, if one exists.  If the public
and private keys do not exist at startup, Puppet Server will still
create a public and private key for the master before generating the
cert, as has been done in the past.

(SERVER-528) Generate the master cert if keys already present at startup

---

acceptance/suites/tests/010-puppetserver-cli/subcommand/gem.rb
resources/ext/cli/gem.erb

The bump to EZBake 1.0+ causes cli subcommands to run with a default
umask of 027.  Previously, gems installed via the puppetserver gem
subcommand would have the world read bits for their gemspec files masked
out by this umask even though the gemspec files could be owned by the
root user.  This could cause puppetserver service, running as user
'puppet', to fail to load gems properly.
This commit sets the umask for the gem subcommand to 0022.  This should
allow gemspec files to be world-readable and, therefore, loadable by the
puppetserver service.

(SERVER-1601) Set umask for gem subcommand to 0022

---

Rakefile
resources/ext/build-scripts/gem-list.txt

This PR has two commits:
* First one just adds a fail fast to bakeNBeak so that it won't try to run the beaker tests if the packaging job fails.
* Second one adds the gems that @branan suggested that we will need for the puppet-agent ruby code to be able to handle i18n in the server.
I was able to build one set of packages and manually check the gem list via `puppetserver gem list` - it looked fine.  Most of my package runs are failing due to mirror/network issues, though.

(SERVER-1600) add gettext-related gems required for ruby i18n

---

documentation/known_issues.markdown

Reloads do work successfully now and [SERVER-15](https://tickets.puppetlabs.com/browse/SERVER-15) is closed, so I believe this section of the documentation about a known issue with config reloading can be removed.

Remove known issue about config reloads

---

project.clj

... which removes Fedora 21 as a build target platform.  lein-ezbake is
currently red in CI on the 1.x branch and this patch should fix it.

(maint) Upgrade to ezbake 0.2.15

---

.travis.yml
documentation/dev_running_from_source.markdown
ext/travisci/test.sh
project.clj

This PR adds options for configuring the min/max heap size which is
used when running lein project commands.  This allows for the heap size
to be bumped up to a significantly higher value for local development
purposes, with the benefit of significantly reducing the total run time
for the test suite.  An alternate min/max heap size can be configured
via either an environment variable, PUPPETSERVER_HEAP_SIZE, or a
profiles.clj setting, user.puppetserver-heap-size.

(SERVER-797) Allow jvm heap size to be configurable for dev/test

---

resources/ext/cli/gem.erb

Hi,
I bumped into the SSL issue related to SNI.
After adding -Djsse.enableSNIExtension=false to /etc/sysconfig/puppetserver, puppetserver gem install kept failing with 'handshake alert:  unrecognized_name'.
It looks like the gem wrapper script is not honoring the JAVA_ARGS defined under /etc/sysconfig/puppetserver.

puppetserver gem should honor JAVA_ARGS

---

acceptance/lib/helper.rb
spec/puppet-server-lib/puppet/jvm/master_spec.rb

Previously, JRuby spec tests were failing because of an inability to
install the public_suffix gem.  When the Puppet Gemfile was bundle
installed, version 2.5.0 of the addressable gem tried to pull in the
public_suffix gem, which requires Ruby 2.  JRuby spec tests, however,
run under MRI 1.9.3 compatibility mode, causing the install to fail.
This commit bumps the Puppet submodule up to 1ea537 and corresponding
puppet-agent package pin to 549d028.  This is being done in order to
pick up a change to the Puppet Gemfile, which pins the version of the
addressable gem to < 2.5.0.  Version 2.4.0 of the addressable gem can be
installed and used properly under MRI 1.9.3 compatibility mode.

(MAINT) Bump puppet submodule to 1ea537

---

Rakefile

Previously, the GEM_HOME and GEM_PATH variables for installing the
bundler gem from the Rakefile for JRuby spec tests were not set.
This could cause gem content from the default system Ruby to be
pulled in during installation, leading to some odd error messages
at best or possibly failure at worst.  This commit sets the GEM_HOME and
GEM_PATH variables to the local ./vendor directory to avoid potential
collisions with a system MRI Ruby, just as is done for the later bundle
install of gems from the Puppet submodule's Gemfile for the spec run.
This commit also avoids installing the 'extra' and 'development' gems
from the Puppet Gemfile since these are unnecessary for running the
JRuby spec tests.

(MAINT) Explicitly set GEM_HOME/PATH and avoid extra/dev gem install

---

documentation/_puppetserver_nav.html
documentation/config_file_product.markdown
documentation/configuration.markdown

-   Adds a new `config_file_product.markdown` doc for a `product.conf` file to configure/disable update checks and analytics (see discussion on #1260)
-   Adds a link to this new doc on the `configuration.markdown` doc and aux nav.
If we merge this, also merge updates to puppet-docs and either revert or don't merge #1260.

(docs) Add product.conf doc

---

ext/travisci/test.sh

This commit drops the heap size used for testing in Travis from 6 GB to
5 GB.  This is being done because JDK 8 builds under Travis are
frequently failing with a 'Cannot allocate memory' error, which may be
related to the heap size being too close to the total RAM available on
Travis CI nodes.

(MAINT) Drop heap size for Travis testing to 5 GB

---

resources/ext/config/conf.d/puppetserver.conf

Puppet clients use HTTPS rather than HTTP, fixing comments.

Correcting comments to use HTTPS rather than HTTP

---

acceptance/lib/helper.rb

Previously, the `puppet_server_collect_data` helper would, for Debian 8,
try to get stdout/stderr puppetserver log data from the
puppetserver-daemon.log file.  With the recent EZBake bump to 1.1.4,
Debian 8 now uses systemd.  For systemd-based packages, stdout/stderr
log data is directed to the system journal rather than the
puppetserver-daemon.log file.  This causes the helper to fail on Debian
8 when it tries to get the non-existent puppetserver-daemon.log file.
This commit changes the `puppet_server_collect_data` helper to get
stdout/stderr puppetserver log data from the journal instead of the
puppetserver-daemon.log file.

(MAINT) Adjust collect_data helper to use journal for Debian 8

---

acceptance/suites/tests/00_smoke/master_starts_if_agent_run_before_ssl_files_inited.rb

Previously, the `master_starts_if_agent_run_before_ssl_files_inited`
acceptance test was configured to run both for OSS and PE Puppet Server.
The test nukes the ssl directory so that an agent run can reconfigure
just the public and private key before the server is started up.  For
PE, the `ssl_crl_path` is configured at installation time.  The absence
of the CRL file after the test nukes it causes the server to fail to
startup.  Work to be done for SERVER-346 and SERVER-911 would allow for
the CRL file to properly be replaced at startup time during this
scenario.  Since that work has not yet been done, though, this commit
just skips the test when run under PE for now.

(MAINT) Skip agent_run_before_ssl_files_inited test on PE

---

acceptance/suites/tests/010-puppetserver-cli/subcommand/SERVER-297_common_behavior.rb
acceptance/suites/tests/010-puppetserver-cli/subcommand/gem.rb
acceptance/suites/tests/010-puppetserver-cli/subcommand/irb.rb
acceptance/suites/tests/010-puppetserver-cli/subcommand/ruby.rb

Previously, many of the subcommand acceptance tests explicitly required
the 'test/unit/assertions' path.  When running under Ruby 2.3.1 with
only the minitest gem (and not the test-unit gem) installed, this
path does not exist.  This causes the require and, therefore, the tests
to fail.
The minitest gem is pulled in by the beaker gem and defines the
assert_* functions that the tests use.  Rather than either adding the
'test-unit' gem to the Gemfile or changing the tests to require a valid
path in minitest instead, this commit just removes the
'test/unit/assertions' requires since the path should have already been
loaded when running under beaker anyway.  No other tests include require
statements to locate the assert_* functions, so this commit allows the
subcommand tests to follow the …

(MAINT) Remove 'test/unit/assertions' requires from subcommand tests

---

Gemfile

This commit bumps the beaker gem dependency in Puppet Server to a custom
version of beaker which is based on 3.3.0 but adds on support for
restarting the service via a `reload` action, when possible.

(SERVER-1629) Bump beaker gem dependency to custom 3.3.0+reload

---

acceptance/suites/tests/010-puppetserver-cli/subcommand/gem.rb
acceptance/suites/tests/010-puppetserver-cli/subcommand/irb.rb
acceptance/suites/tests/010-puppetserver-cli/subcommand/ruby.rb
documentation/subcommands.markdown
resources/ext/cli/gem.erb
resources/ext/cli/irb.erb
resources/ext/cli/ruby.erb

Previously, the value of the JAVA_ARGS environment variable, as a result
of work done for the Puppet Server 2.7.0 release, was passed along as
arguments to the Java process running the `gem` subcommand.  This was
problematic for cases where the JAVA_ARGS had been specifically tuned
with arguments for use when running the puppetserver service but
inappropriate for the `gem` command.  For example, Java args that enable
debug logging when included in the `gem` command could break the ability
to perform basic `gem` installs.
This commit changes the `gem` subcommand to source custom Java arguments
from a separate environment variable, `JAVA_ARGS_CLI`.  This commit also
adds the use of the `JAVA_ARGS_CLI` args to the ruby and irb subcommands,
which previously provided no mechanism for …

(SERVER-1644) Use JAVA_ARGS_CLI env var for Java args in subcommands

---

project.clj

DO NOT MERGE THIS YET.
This is the release commit for when we are ready to bump the version to 2.7.1.  Waiting for a green CI run before we merge, and I'll update the PR accordingly when we're ready.

(MAINT) Bump version to 2.7.1 for release

---

project.clj

DO NOT MERGE!
This should go in after our packages are all built and tested for the 2.7.1 release.

(MAINT) bump to 2.7.2 snapshot after release

---

acceptance/lib/helper.rb

CI has begun failing because the sha we were previously pinned to no longer
has artifacts on the builds server. 1.8.1 contains the changes we needed from the old sha

(MAINT) Pin tests to puppet-agent 1.8.1

---

acceptance/lib/helper.rb
documentation/gems.markdown
documentation/release_notes.markdown
documentation/services_master_puppetserver.markdown

Conflicts:
`acceptance/lib/helper.rb` - Updated puppet-agent versions to 1.8.1
`ruby/puppet` - updated puppet version to sha for 4.8.1

(MAINT) merge up from stable

---

acceptance/suites/tests/010-puppetserver-cli/subcommand/SERVER-297_common_behavior.rb
project.clj
test/integration/puppetlabs/services/jruby/jruby_puppet_pool_int_test.clj

Changes to jruby-utils make it so that the environment variables `HTTP_PROXY`,
`http_proxy`, `HTTPS_PROXY`, `https_proxy`, `NO_PROXY`, and `no_proxy` are now
passed through to the jruby scripting container, so that gems can be installed
in scenarios where a proxy is set.
This commit adds acceptance tests ensuring that when set those variables are
available when running `puppetserver ruby` and `puppetserver irb` (and thus
will also be available when running `puppetserver gem`).
Note that this cannot be merged until https://github.com/puppetlabs/jruby-utils/pull/32 has been merged and a new version of jruby-utils released.

(SERVER-377) Add tests for proxy-related environment variables

---

project.clj

This should pull in the resolution to SERVER-1670 (autorequires causing system ruby to be an rpm dependency).

(SERVER-1670) Bump lein-ezbake to fix dependency issues

---

Gemfile

This commit bumps the beaker pin for puppetserver acceptance testing to
~>3.5.0.  This allows us to utilize the 'reload' capability in
puppetserver for performance improvements when running acceptance tests.

(SERVER-1629) Bump beaker pin to 3.5.0

---

resources/ext/build-scripts/gem-list.txt

This bumps the gettext-setup gem version to 0.8, which allows the gem
user to specify which file format to expect for translation files.

(SERVER-1593) Update gettext-setup gem to 0.8

---

ext/project_data.yaml

Our ship automation that links in with the packaging repo requires both
project_data.yaml and build_data.yaml to exist in the ext directory. It
doesn't matter if these files have duplicate content, as long as they're
both there. This commit simply links project_data.yaml to
build_data.yaml so that the automation can execute successfully.

(maint) Link project_data.yaml to build_data.yaml

---

project.clj

Previously, any messages being logged by JRuby under Puppet Server would
be written to JRuby's default stderr logger, which is most commonly
routed to syslog / journal for the running service.  Also, debug-level
JRuby log messages would always be suppressed by the stderr logger.
Starting with this commit, Puppet Server configures an slf4j logger,
provided by jruby-utils, which allows JRuby log messages to be handled
by the logback framework, as is most other logging done under Puppet
Server (via Trapperkeeper).  The slf4j logger also enables debug
messages to be logged, depending upon the log level configured in the
logback.xml file.

(SERVER-1475) Configure an slf4j logger for JRuby

---

documentation/install_from_packages.markdown
documentation/release_notes.markdown

According to our contacts at SUSE, they prefer the all-caps
version of their name.

(maint) Correct SuSE -> SUSE

---

dev-resources/puppetlabs/puppetserver/shell_utils_test/echo_and_warn
src/java/com/puppetlabs/puppetserver/ShellUtils.java
test/unit/puppetlabs/puppetserver/shell_utils_test.clj

Previously, when ShellUtils was configured to combine both stderr and
stdout from the executed command, the combination of the two was
logged as a warn level message.  With the changes in this commit, none
of the info written to stdout is logged.  Only the info written to
stderr, if applicable, is logged.

(SERVER-1671) Don't log stdout from shell utils

---

project.clj

This commit upgrades the clj-parent dependency from 0.3.0 to 0.3.2 in
order to pick up a fix from trapperkeeper-status 0.7.1 where gc/cpu
metric collection could corrupt the status endpoint.

(MAINT) Upgrade to clj-parent 0.3.2

---

dev-resources/puppetlabs/services/master/environment_modules_int_test/puppet.conf
documentation/index.markdown
documentation/puppet-api/v3/environment_modules.json
documentation/puppet-api/v3/environment_modules.markdown
documentation/services_master_puppetserver.markdown
src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj
src/clj/puppetlabs/services/master/master_core.clj
src/clj/puppetlabs/services/protocols/jruby_puppet.clj
src/java/com/puppetlabs/puppetserver/JRubyPuppet.java
src/ruby/puppetserver-lib/puppet/server/master.rb
test/integration/puppetlabs/puppetserver/testutils.clj
test/integration/puppetlabs/services/jruby/module_info_test.clj
test/integration/puppetlabs/services/master/environment_modules_int_test.clj

This commit adds new endpoint into puppet-server: environment_modules
When a user makes a request against this endpoint with a given
envirnoment, puppet-server will use JRuby to determine what modules are
installed within puppet.

(SERVER-1696) Add new environment_modules v3 route

---

project.clj
test/integration/puppetlabs/services/master/environment_classes_int_test.clj

This commit bumps the clj-parent version from 0.3.2 to 0.3.3 in order to
pick up the `request-body-max-size` feature in
trapperkeeper-webserver-jetty9 1.7.0.  This commit also updates the
clj-i18n plugin dependency version to 0.6.0 for consistency with the
version of clj-i18n pulled in from the new clj-parent version.

(MAINT) Bump to clj-parent 0.3.3

---

test/unit/puppetlabs/puppetserver/shell_utils_test.clj

Previously, the `combines-stderr-and-stdout-correctly` test expected the
output order in which stderr and stdout was captured to match the order
in which the spawned executable wrote to each stream.  The order in
which the Java process receives content from the streams, however, is
not guaranteed to match the order in which the content was originally
written.  For this reason, the test was changed to allow the content
from the streams to arrive in either order.

(MAINT) Allow stderr/out in combined output test to be in either order

---

project.clj
test/integration/puppetlabs/services/jruby/jruby_puppet_pool_int_test.clj

This PR is in response to https://github.com/puppetlabs/jruby-utils/pull/34
It updates the jruby-utils dep to an unreleased version and updates the tests to work with the new changes 
The "503 during shutdown" tests have been modified to test for 503 after
shutdown, because it's no longer possible to pause the shutdown in the same
way
It can't be merged until a new jruby-utils is released with the new changes from https://github.com/puppetlabs/jruby-utils/pull/34

(PE-13552) Update tests for new jruby-utils-version

---

resources/ext/cli/gem.erb
resources/ext/cli/irb.erb
resources/ext/cli/ruby.erb

This commit adds -Djava.security.egd=/dev/urandom as an argument to the
Java command line for the gem, ruby, and irb subcommands.  This argument
was already being used in the Java command line for when puppetserver
runs as a service.  Performance for some operations like gem installs
appears to be significantly faster with this option in place.

(SERVER-1723) Use /dev/urandom for gem, ruby, and irb subcommands

---

project.clj
src/ruby/puppetserver-lib/puppet/server/http_client.rb
test/unit/puppetlabs/puppetserver/ruby/http_client_test.clj

This commit adds an option to the http_client Ruby post method for
specifying compression that should be applied to the request payload.
The only supported compression mode is `gzip`.  The new option, if
specified, is passed on through to the underlying http-client library.

(PDB-2640) Add `:compress` option to Ruby http_client post

---

src/ruby/puppetserver-lib/puppet/server/http_client.rb
test/integration/puppetlabs/services/jruby/jruby_puppet_pool_int_test.clj

This makes it so that if a `metric-id` request option is set for a GET
or POST request (the only two request types we support), it is passed through
to the http client's request options. Doing this also meant a small refactor
of some common logic between the `get` and `post` methods, as they both shared
most of the same logic for creating `RequestOptions`.

(PE-18345) Pass metric-id setting through to http client

---

project.clj
src/clj/puppetlabs/services/puppet_admin/puppet_admin_core.clj
test/integration/puppetlabs/services/puppet_admin/puppet_admin_int_test.clj

**This PR goes with** a jruby-utils PR which implements the timeout functionality: https://github.com/puppetlabs/jruby-utils/pull/40
---
This commit adds support for a timeout during a jruby pool flush through the
admin api.
Modifies the admin api routes to support returning a 503 if the timeout is
exceeded.
As a bonus it nukes a liberator resource too!
This shouldn't be merged until the corresponding jruby-utils PR is merged and a new release happens

(SERVER-1704) Support flush timeout setting for jruby pool

---

dev-resources/puppetlabs/services/master/master_service_test/ca_files_test/puppet.conf
dev-resources/puppetlabs/services/master/master_service_test/conf/puppet.conf
project.clj
src/clj/puppetlabs/services/jruby/jruby_metrics_service.clj
src/clj/puppetlabs/services/legacy_routes/legacy_routes_service.clj
src/clj/puppetlabs/services/master/master_core.clj
src/clj/puppetlabs/services/master/master_service.clj
test/integration/puppetlabs/services/legacy_routes/legacy_routes_test.clj
test/integration/puppetlabs/services/master/master_service_test.clj
test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj

This PR imports work done in pe-puppet-server-extensions for
wrapping the comidi routes for the master and legacy-routes services
with http-metrics.

(SERVER-1262) Wrap http metrics for comidi routes

---

src/ruby/puppetserver-lib/puppet/server/http_client.rb

Prior to Server 5, the `get` method of Puppet Server's http client class took
two required arguments. It was then updated to accept a third, optional
argument. However, Puppet's implementation of this class has a `get` method
that takes one required argument and two optional arguments. This commit
updates Puppet Server's implementation of this method to have the same
signature as Ruby Puppet's.
Similarly, the `post` method of Puppet Server's http client class had two
required arguments and one optional argument, but Puppet's implementation has
one required arguments and two optional arguments. This commit updates
Puppet Server's `post` method to make `headers` optional, to match Puppet's
implementation.

(maint) Update methods in http client to match Ruby version

---

ezbake/config/conf.d/metrics.conf
resources/ext/config/conf.d/puppetserver.conf

Previously, if a user had modified the puppetserver.conf file after
install of an older package, the new metrics section would not end up
being populated in the puppetserver.conf file after upgrade.  Because
the required server-id key would not be found in the metrics section,
puppetserver would error out on startup.
This commit moves the new metrics configuration from the
puppetserver.conf file to a metrics.conf file in packaging.  This is
being done both for consistency with PE Puppet Server in how the
metrics configuration is presented to users and to allow the required
server-id setting to be populated by default on a package install or
upgrade.

(SERVER-1744) Move metrics configuration into metrics.conf file

---

dev/bootstrap.cfg
ezbake/system-config/services.d/bootstrap.cfg
src/clj/puppetlabs/services/analytics/analytics_service.clj
src/clj/puppetlabs/services/master/master_service.clj
test/integration/puppetlabs/services/analytics/analytics_service_test.clj
test/integration/puppetlabs/services/master/master_service_test.clj

This commit moves the check-for-updates call to dujour out into a
separate analytics service.  This would hopefully allow for the OSS
master service to be reusable directly in PE Puppet Server once all of
the metrics-related work is ported down into OSS.

(SERVER-1743) Move check-for-updates call into analytics service

---

documentation/external_ca_configuration.markdown

Prior to this commit the ssl-crl-path config option was documented to be
equivalent to Apache's SSLCARevocationPath setting; but it is not.
Apache's config option allows you to specify a directory full of CRL
files (named via hash-value.rN).  Puppetserver supports using only one
CRL file.

(docs) Fix ssl-crl-path description

---

acceptance/suites/tests/authorization/default_rules.rb
dev/bootstrap.cfg
dev/puppetserver.conf
ezbake/config/conf.d/web-routes.conf
ezbake/system-config/services.d/bootstrap.cfg

This commit adds the metrics webservice to the bootstrap and web routing
configs for both dev and packaging.  This commit includes a simple
beaker test which just confirms that a successful response is received
when the metrics endpoint is queried - basically just ensuring that the
endpoint is registered and that requests aren't being denied by
insufficent authentication.

(SERVER-1753) Add metrics webservice to configuration

---

dev/puppetserver.conf
ezbake/config/conf.d/metrics.conf
project.clj
src/clj/puppetlabs/services/jruby/jruby_metrics_service.clj
src/clj/puppetlabs/services/master/master_service.clj
src/clj/puppetlabs/services/puppet_profiler/puppet_profiler_service.clj
test/integration/puppetlabs/puppetserver/bootstrap_testutils.clj
test/integration/puppetlabs/services/master/master_service_test.clj

This commits adds a list of default allowed metrics to puppetserver's master
service.
tk-metrics 1.0.0 added the ability for graphite exporting. The metrics service
can take a list of whitelisted metrics through a call to the
update-registry-settings service function during the init phase
Can't be merged until a new clj-parent release is made

(SERVER-1721) Add allowed metrics to master service

---

acceptance/lib/helper.rb
project.clj
resources/ext/build-scripts/gem-list.txt
spec/puppet-server-lib/puppet/jvm/master_spec.rb

Bump puppet submodule to latest passing commit on the master branch of puppet
(puppet 5).
The Gemfile for Puppet 5 pulls in a newer version of gettext-setup and hocon,
so update the versions of these in the list of gems to build too.
Bump hiera to latest release - 3.3.1.
Bump Puppet Server version to 5.0.0-master-SNAPSHOT.

(SERVER-1754) bump puppet submodule to 5

---

src/clj/puppetlabs/services/master/master_core.clj
src/clj/puppetlabs/services/master/master_service.clj
test/integration/puppetlabs/services/master/master_service_test.clj

This commit ports the jvm memory metrics and related tests from
pe-puppet-server-extensions
These metrics are a little redundant with the jvm metrics in the status
service, but they are documented and so we're porting them over to maintain
backwards compatibility

(SERVER-1752) Port memory metrics from PE

---

acceptance/lib/helper.rb
acceptance/suites/tests/metrics/collect_default_metrics.rb

This commit adds a beaker acceptance test, collect_default_metrics,
which sets up a Graphite server, configures Puppet Server to export
metrics to it, and confirms that the default set of metrics that the
server should export are actually exported.  This test is configured to
run on el-6 only because the underlying Puppet module used to setup the
Graphite server, cprice404/grafanadash, only supports el-6 at present.
I copied the bulk of this over from the Graphite beaker tests that we've
been running in PE Puppet Server.  See:
* ![collect_default_metrics test](https://github.com/puppetlabs/pe-puppet-server-extensions/blob/2017.2.0.1/acceptance/suites/tests/file_sync/x-collect_default_metrics.rb)
* ![metrics helpers](https://github.com/puppetlabs/pe-puppet-server-extensions/blob/2017.2.0.1/ …

(SERVER-1264) Add beaker graphite metrics tests

---

acceptance/suites/tests/metrics/collect_default_metrics.rb

Previously, the collect_default_metrics test errantly refered to the
variable 'agent', which can be an array of agents, rather than
'graphite', which is a single agent chosen from the array, as the target
for the installation of the graphite server package.  This led to an
error when running the test in a multi-agent configuration.  This commit
fixes the invalid references.

(SERVER-1264) Fix graphite test errors

---

acceptance/suites/tests/metrics/collect_default_metrics.rb

This commit corrects the server on which the graphite.pp manifest is
updated for the collect_default_metrics.rb test.  The test needs to
upload the manifest to the server where graphite is being installed but
was errantly uploading it to the master.  In a split configuration, the
master and graphite servers are different and so the test would
previously fail when attempting to upload the file to the wrong server.

(SERVER-1264) Use proper server when updating graphite in beaker test

---

dev-resources/puppetlabs/services/master/master_service_test/confdir/puppet.conf
src/clj/puppetlabs/services/master/master_core.clj
src/clj/puppetlabs/services/master/master_service.clj
src/clj/puppetlabs/services/protocols/master.clj
test/integration/puppetlabs/services/master/master_service_test.clj

Pull out specific http client metrics and add them to the master service
status endpoint under an `http-client-metrics` key.
Since other services (specifically, the pe-master service) may have http
client metrics that they would like to add to this list to be included in the
status, the metric ids to be included in the status are registered in an atom
in the service context, and there is a new service function
`add-metric-ids-to-http-client-metrics-list!` that will append metric ids to
this list.
Add these metrics to the list of `default-metrics-allowed` that will be exported to graphite.

(SERVER-1737) Add http client metrics to status

---

project.clj

This commit bumps the lein-ezbake plugin version from 1.1.7 to 1.1.8.
This is being done in order to fix a build dependency problem which was
previously causing SLES 12 builds to unintentionally not contain
vendored gems.

(MAINT) Bump lein-ezbake to 1.1.8

---

dev-setup

The dev-setup script doesn't do any error checking but a casual glance
indicates that any command failing should be a critical error. This
commit adds `set -e` which will cause the script to abort if any command
exits with a non-zero exit status.

(maint) Abort dev-setup script on error

---

documentation/config_file_puppetserver.markdown
resources/ext/config/conf.d/puppetserver.conf
src/clj/puppetlabs/services/puppet_profiler/puppet_profiler_core.clj
src/java/com/puppetlabs/puppetserver/MetricsPuppetProfiler.java
test/unit/puppetlabs/services/puppet_profiler/puppet_profiler_core_test.clj
test/unit/puppetlabs/services/puppet_profiler/puppet_profiler_service_test.clj

This commit defaults the Puppet profiler to true, and removes some
extraneous logging.
I've dropped a set of tests that seemed to be exercising the debug log statement in `MetricsPuppetProfiler.finish()`, if those need to be replaced instead of dropped let me know.

(SERVER-1761) Enable profiler by default

---

documentation/puppet-api/v3/environment_modules.json
documentation/puppet-api/v3/environment_modules.markdown
src/clj/puppetlabs/puppetserver/jruby_request.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj
src/clj/puppetlabs/services/master/master_core.clj
src/clj/puppetlabs/services/protocols/jruby_puppet.clj
src/java/com/puppetlabs/puppetserver/JRubyPuppet.java
src/ruby/puppetserver-lib/puppet/server/master.rb
test/integration/puppetlabs/services/master/environment_modules_int_test.clj

This commit adds new functionality to the environment_modules endpoint.
It now allows users to not specify a query param for the endpoint. If
one is not provided, puppetserver will return all modules for all
environments in a single request.
__TODO__:

(SERVER-1758) Add environment_modules endpoint

---

acceptance/lib/helper.rb

This commit bumps the puppet-agent pin to 7f71e72 and related puppet
submodule to 4b09fbc.

(MAINT) Bump puppet and puppet-agent versions 12-apr-2017

---

acceptance/lib/helper.rb

This commit bumps the puppet-agent pin to b04c9f4a and related puppet
submodule to 8e8866b.

(MAINT) Bump puppet and puppet-agent versions 17-apr-2017

---

project.clj

This commit bumps our lein-ezbake dependency from 1.2.0 to 1.2.1.  1.2.1
has a fix in it which should allow for the proper java 1.8 package
dependency to be resolved when we're building packages for SLES 12.

(MAINT) Bump to lein-ezbake 1.2.1

---

Gemfile

This commit bumps the beaker version used in the Gemfile from 3.5 to
3.15.  This is being done in order to pick up the updated platform code
name -> version matrix used in various beaker helpers, needed for use
with running tests for yakkety.

(MAINT) Bump beaker version to 3.15

---

Gemfile

Beaker 3.12.0 is causing problems for installing Puppet for the Puppet 3
compatibility tests on el 6. This commit changes the Beaker pin to 3.11.0
until we can get around the issue.

(maint) Change beaker pin to 3.11.0

---

documentation/dev_trace_func.markdown
project.clj

MaxPermSize was made a noop JVM argument in JDK8; since we no longer
support JDK7 we can omit this option entirely.

(maint) drop -XX:MaxPermSize

---

acceptance/lib/helper.rb

Update `puppetdb_supported_platforms` acceptance test helper to exclude
yakkety from the platforms we run PuppetDB smoke tests agains, since PuppetDB
doesn't support yakkety.

(maint) Don't run puppetdb acceptance tests on yakkety

---

test/integration/puppetlabs/services/master/environment_modules_int_test.clj

This commit uses the correct response maps if a unit test fails.

(maint) Fix failure message in unit tests

---

acceptance/lib/helper.rb
src/clj/puppetlabs/services/legacy_routes/legacy_routes_core.clj
src/clj/puppetlabs/services/master/master_core.clj
src/clj/puppetlabs/services/master/master_service.clj
test/integration/puppetlabs/puppetserver/testutils.clj
test/unit/puppetlabs/services/legacy_routes/legacy_routes_core_test.clj
test/unit/puppetlabs/services/master/master_core_test.clj

The `/puppet/v3/resource_types` endpoint was deprecated in Server 2.3.0 and is being
removed in Server 5. This commit removes it from the route tree, and removes
associated tests.
Also update the `PuppetResource` test schema which was out of date.

(SERVER-1251) remove resource types endpoint

---

acceptance/lib/helper.rb
acceptance/suites/pre_suite/foss/70_install_puppet.rb
acceptance/suites/pre_suite/puppet3_compat/70_install_puppet.rb

This is kinda gross because it's copy/paste, but I've done many worse things.
/cc @camlow325

(maint) install jdk8 for debian 8 for puppet3 compat

---

test/integration/puppetlabs/puppetserver/auth_conf_test.clj
test/integration/puppetlabs/puppetserver/testutils.clj
test/integration/puppetlabs/services/master/master_service_test.clj

Many of the puppetserver tests used pson as the content type in accept headers.
This commit changes them to json.
Some tests specifically test that using pson (and json) in an accept header will
work, and these tests have been left in place

(SERVER-1762) Use json in tests

---

ezbake/config/logback.xml

org.apache.http logs a ton of unhelpful things at DEBUG level that
should really be at TRACE. This commit updates the packaged logback.xml so tat
if the general log level is changed to `debug`, http client will remain at
`info` so as to not spam the logs.

(maint) Update packaged logback for http client logging

---

resources/ext/ezbake.conf

Previously, both openjdk-7-jre-headless and openjdk-8-jre-headless were
listed as build dependencies for Debian.  Since we'll no longer need to
be building for JDK 7 for Puppet 5+, this commit removes the
openjdk-7-jre-headless dependency.

(SERVER-1800) Remove openjdk-7-jre-headless as debian build dependency

---

project.clj

Previously, Puppet Server's JRuby dependencies were excluded from
jruby-utils and moved into profiles only (provided and jruby9k) in order
to avoid having the default dependencies from jruby-utils be included in
the puppet-server-release uberjar for ezbake packages.  This, however,
would be problematic for any consumer of the immediate puppetserver
artifact since those consumers would have to explicitly include/manage
the JRuby dependencies themselves.
In this commit, the jruby-deps for JRuby 1.7 are re-added as a standard
dependency but excluded in the ezbake profile.  This should allow the
standard puppetserver artifact to have reasonable JRuby 1.7 dependencies
by default again while still preserving the ability during an ezbake
build to separate JRuby dependencies for 1.7 and 9k into …

(SERVER-1630) Exclude jruby-deps only for ezbake

---

acceptance/suites/pre_suite/foss/70_install_puppet.rb

The `use-legacy-auth-conf` was added to the Puppet installation steps to
prevent breakage while we changed the default value. At this point we
should have fixed all of the acceptance tests that were relying on that
setting so this commit removes the setting shim.

(maint) don't use legacy auth.conf for acceptance

---

project.clj

Previously, for the jruby-utils dependency, explicit exclusions were
included for various jruby-related dependencies - jruby-core,
jruby-stdlib, jffi, and jnr.  jruby-utils itself, though, no longer has
any explicit dependencies for any of these.  Instead, the jruby-deps
dependency controls which/whether any of the jruby-related dependencies
are pulled in.  This commit removes the exclusions for these
dependencies from the jruby-utils dependency since they are no longer
needed.

(SERVER-1630) Remove jruby exclusions from jruby-utils dep

---

acceptance/lib/helper.rb
ext/jenkins/spec-jruby9k.sh
ext/jenkins/unit-clj-jruby9k.sh

This commit contains two changes for use in running JRuby 9k in CI:
1) Add Jenkins scripts for running Clojure unit and JRuby spec tests
under 9k.
2) Add a beaker pre-suite step for configuring the Puppet Server service
to run with JRuby 9k based on the configuration of a new environment
variable, USE_JRUBY_9K.  A value of "y" or "Y" for the variable would
enable 9K whereas any other value would lead to the default JRuby at
installation, 1.7.x, being used.

(SERVER-1775) Add support for running JRuby 9k in CI

---

project.clj

This commit bumps the tk-webserver-jetty9 version from 2.0.0 to 2.0.1.

(MAINT) Bump tk-webserver-jetty9 to 2.0.1

---

src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj

This commit adds an info-level log message during startup which outputs
the version of JRuby which is being used and the Ruby language version
that JRuby is currently emulating.

(MAINT) Add JRuby version log message

---

acceptance/suites/pre_suite/foss/30_install_dev_repos.rb
acceptance/suites/pre_suite/puppet3_compat/30_install_dev_repos.rb

The puppetserver and puppet agent setup for acceptance was starting to pick up a lot of organic growth; this adds some cleanup to those files.

(maint) Clean up acceptance puppet repo setup

---

src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj

Previously, if an exception were thrown before the jruby-puppet-service
had been completely initialized, a stop call to the service on shutdown
would lead to a separate exception being thrown and logged due to trying
to operate on a nil pool-context.
This commit changes the jruby-puppet-service stop logic to avoid trying
to flush the pool-context if it has not yet been created.  This avoids
having the exception be thrown and logged for the nil pool-context.

(MAINT) Don't flush non-initialized pool-context at shutdown

---

resources/ext/build-scripts/gem-list.txt

- 1.2.5 addresses loading files with UTF-8 characters in their path

(SERVER-1807) Update Hocon to 1.2.5

---

acceptance/suites/pre_suite/puppet3_compat/30_install_dev_repos.rb

Previously, the test step in the puppet3_compat pre_suite which
installed the puppetlabs dev repo referenced a non-existent variable,
host, causing the step to fail.  This commit fixes that line to
reference the intended variable, master.

(MAINT) Fix dev repo install for puppet3-compat suite

---

project.clj

This commit resolves a dependency conflict between JRuby and
org.ow2.asm via several related packaging changes.  Several dependencies
are bumped in this commit:
- jruby-deps (for 1.7) - 1.7.26-1 => 1.7.26-2
- jruby-deps (for 9k) - 9.1.8.0-1 => 9.1.9.0-1
- jruby-utils - 0.9.0 => 0.9.1
- clj-parent - 0.8.0 => 1.1.0
- ezbake - 1.3.0 => 1.4.0
The ezbake changes are needed to build the jruby-deps uberjars properly
along with the changes to resolve the org.ow2.asm conflict.
The new clj-parent version brings in the org.ow2.asm version, 5.0.3, which
resolves the dependency conflict.
The tk-webserver-jetty9 pin is removed because the latest version,
2.0.1, can now be picked up from the newer clj-parent version.

(SERVER-1803) Bump jruby deps and resolve org.ow2.asm conflict

---

spec/puppet-server-lib/puppet/jvm/puppet_config_spec.rb
src/ruby/puppetserver-lib/puppet/server/puppet_config.rb

This commit stops overriding the default `node_cache_terminus` for puppet
server's master application as `write_only_yaml` and removes the setting of
Puppet::Node's indirection cache_class. With this, Puppet::Node's indirection
never gets its cache class set and won't cache by default. Per PUP-6060, with
the advent of PuppetDB, workflows using lists of nodes are better off querying
it than these yaml files on the master, and since this was a `write_only` cache
we were always querying the node terminus for nodes anyway.

(SERVER-1819) don't set node_cache_terminus

---

spec/puppet-server-lib/puppet/jvm/puppet_config_spec.rb
src/ruby/puppetserver-lib/puppet/server/puppet_config.rb

38e0a0c stopped setting the node_cache_terminus setting value, and stopped
setting the cache_class to its result. This commit undoes the latter half of
that change - we return to setting the cache_class. This will still default to
nil since we aren't specifying the setting value, which will disable caching,
but it will enable users to easily revert to the 4.x behavior of caching by
specifying :node_cache_terminus => :write_only_yaml. Without this commit users
would have to augment their routes.yaml file with a `:node` key specifying the
cache_class.

(SERVER-1819) honor node_cache_terminus setting

---

acceptance/lib/helper.rb

This commit bumps the puppet-agent package version used for testing to
f9a1b77 and the corresponding Puppet submodule to 82e65ec.

(MAINT) Bump puppet-agent to f9a1b77, puppet submodule to 82e65ec

---

documentation/config_file_puppetserver.markdown
project.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_core.clj
src/clj/puppetlabs/services/jruby/jruby_puppet_service.clj
test/integration/puppetlabs/services/jruby/jruby_puppet_pool_int_test.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_core_test.clj
test/unit/puppetlabs/services/jruby/jruby_puppet_testutils.clj

This commit bumps the jruby-deps dependency for 1.7 from 1.7.26-2 to
1.7.27-1 and jruby-utils dep from 0.9.0 to 0.10.0.
This commit removes support for the jruby-puppet.compat-version setting.
The compat-version setting was introduced in Puppet Server 2.7.0 to
allow for JRuby to run under Ruby language version 2.0 instead of the
default version, 1.9.  Setting compat-version to "2.0" for JRuby 1.7.27,
however, was broken due to a regression - see:
https://github.com/jruby/jruby/issues/4613 - and is unlikely to be fixed
in the future.  For Puppet Server 5+, users will be able to, via the
JRUBY_JAR environment variable in packaging, configure JRuby 9k to be
used instead of JRuby 1.7 for Ruby language version 2+ support.
In conjunction with a corresponding jruby-utils bump, this commit causes …

(SERVER-1661) Bump JRuby dep to 1.7.27 and remove compat-version setting

---

.travis.yml
ext/travisci/secscan.sh

Enabling code scans for some basic security checks in Clojure code. Currently the script only looks for read-string instances and will be updated for additional patterns as needed.

(SERVER-1805) Enabling static code scans of clojure for security issues

---

acceptance/lib/puppetserver/acceptance/compat_utils.rb
acceptance/suites/compat_tests/020_backwards_compat/binary_file_test.rb
acceptance/suites/compat_tests/020_backwards_compat/content_file_test.rb
acceptance/suites/compat_tests/020_backwards_compat/custom_fact_output_test.rb
acceptance/suites/compat_tests/020_backwards_compat/external_fact_output_test.rb
acceptance/suites/compat_tests/020_backwards_compat/mount_point_binary_file_test.rb
acceptance/suites/compat_tests/020_backwards_compat/mount_point_source_file_test.rb
acceptance/suites/compat_tests/020_backwards_compat/recursive_directory_test.rb
acceptance/suites/compat_tests/020_backwards_compat/source_file_test.rb

Previously, each of the Puppet compat tests uploaded a site.pp file but
did not remove the file as each test completed.  This would lead to any
subsequent tests which did not replace the site.pp file having problems
when an agent run reused the file from the prior test - in particular
the puppetX_version_test.rb.  In this commit, the site.pp file is
cleaned up as part of each test's teardown.

(SERVER-1786) Remove site.pp file between Puppet compat tests

---

Rakefile

This commit sets the GEM_HOME and GEM_PATH for the 'gem install bundler'
command that the Rakefile uses for spec tests.  Not having these set may
cause paths from the default system ruby, which is usually a different
version than the language version JRuby is being run under, to be used.
Using system ruby paths with JRuby commands may otherwise lead to
compatibility problems at some point.

(MAINT) Set GEM_HOME and GEM_PATH for gem install bundler

---

acceptance/suites/pre_suite/puppet3_compat/70_install_puppet.rb

This adds a default value to puppet versions that we will use when
testing legacy compatability.
Previously we failed when no value was given, with this change we will
now log an info message.
Amended to apply to Puppetserver 2.7.x.

(SERVER-1786) Set default versions of puppet when testing legacy compat

---

Gemfile
acceptance/suites/pre_suite/puppet3_compat/70_install_puppet.rb

If we're running Puppet 3 compatibility tests the agent install type
doesn't matter, as we _must_ use the 'foss' install type. This commit
manually reconfigures the Puppet agent hosts to use the 'foss' install
type and ignore the '--aio' command line flag and config option as that
option can only meaningfully apply to the master node, and never the
agents under test.

(SERVER-1787) Puppet 3 agents must use foss install type

---

project.clj

This commit bumps the jruby-deps for 9k from 9.1.9.0-1 to 9.1.9.0-2.
This transitively pins to newer versions of jffi and jnr-ffi, 1.2.16 and
2.1.6, which have a fix for leaks around native memory allocations.  See
https://github.com/jnr/jnr-ffi/issues/117.

(SERVER-1821) Bump JRuby 9k dep to 9.1.9.0-2 for ffi memory leak fix

---

acceptance/suites/pre_suite/puppet4_compat/70_install_puppet.rb

Previously, when the Puppet 4 compatibility suite tried to install the
SLES 12 agent from the PC1 repo, it failed due to the GPG public key
associated with the package not being present on the host.  This commit
adds a step which installs the public key prior to the package install.
This is done for SLES 12 only because it isn't necessary for other
package managers.  yum and apt installs pull down the public key
automatically as part of the package install.

(SERVER-1786) Install Puppet GPG key for SLES 12 Puppet 4 compat agent

---

acceptance/suites/tests/service_framework/reload_updated_crl.rb

Previously, the `reload_updated_crl` acceptance test included a step for
PE which copied the file at the cacrl location over to the file at the
hostcrl location after a certificate was revoked.  The work done for
PE-19484 allowed for the hostcrl file to be updated automatically after
service restart for PE, as had already previously been the case for OSS
Puppet Server.  This commit removes the synchronization step from the
test since it is no longer necessary for PE.

(SERVER-911) Remove sync step for PE in reload crl test

---

src/clj/puppetlabs/services/jruby/puppet_environments.clj
test/unit/puppetlabs/services/jruby/puppet_environments_test.clj

The `EnvironmentRegistry.isExpired` method reified in the `environment-registry` fn will
try to return `nil` if an environment is unregistered. The java interface requires it
returns a boolean, and so an exception is thrown.
This commit changes the implementation of `isExpired` to return `true` if the environment
is unregistered, since returning `false` might indicate the cache entry is still valid,
when the registry doesn't actually know anything about the entry

(SERVER-715) environment registry isExpired returns nil

---

acceptance/lib/helper.rb

This commit bumps the puppet-agent and puppet submodule pins for testing
to e36cade and 78e175e respectively.

(MAINT) Bump puppet-agent to e36cade

---

ezbake/config/conf.d/auth.conf

This commit splits the /puppet/v3/file auth.conf rule into separate
rules for file_bucket_file, file_content, and file_metadata.  The
discrete rules reflect the minimal set of request methods which are
valid for each endpoint.

(SERVER-1808) Adjust file endpoint auth.conf rules for valid methods

---

src/clj/puppetlabs/services/master/master_core.clj
test/integration/puppetlabs/general_puppet/general_puppet_int_test.clj

I'm curious what folks think of this. Since it was just for one response of one endpoint I thought that simply updating the map returned would be the simplest solution, and since we're already directly returning a map with `:body` and `:status` it seemed weird to use the ring helpers to set the header.

(SERVER-1826) Send mime type with static file serving response

---

documentation/configuration.markdown

This commit adds a section to the `configuration.markdown` file about
configuring the version of JRuby that Puppet Server uses and referencing
the removal of support for the `jruby-puppet.compat-version` setting.

(SERVER-1779) Pre-docs for configuring JRuby version

---

acceptance/lib/helper.rb
src/clj/puppetlabs/services/config/puppet_server_config_core.clj
test/unit/puppetlabs/services/config/puppet_server_config_core_test.clj

This PR bumps the puppet submodule and puppet-agent versions for
testing to 27fdad2 and 4.99.0.269.g98208e4, respectively.
Previously, the Clojure unit tests contained a test for the value of the
Puppet archive_files setting.  Per changes in PUP-7260 which just landed
in Ruby Puppet, this setting no longer exists.  This commit changes the
test to instead validate the value of the autoflush setting.  The
specific setting being tested isn't important.  The test just proves
that a known expected default value for a setting can be retrieved from
Ruby Puppet.

(MAINT) Bump puppet-agent to 98208e4

---

acceptance/suites/tests/code_commands/code_scripts.rb

This PR adds a hiera-5 based, environment-specific hiera.yaml file
for use with the code_scripts.rb test.  This ensures that hiera lookups
will work properly with the default hiera 5 based yaml file which is now
installed with the puppet-agent.
This PR also includes some modifications to the code_scripts.rb
acceptance test which allow it to be run multiple times, as may be
needed for easier troubleshooting.  The commit uses temp directories
instead of hard-coded directories in a couple of spots and ensures that
proper directory ownership is set for some directories.

(MAINT) Add env-specific hiera.yaml file for code_scripts.rb test

---

src/clj/puppetlabs/services/ca/certificate_authority_core.clj
test/unit/puppetlabs/services/ca/certificate_authority_core_test.clj

This commit changes the default content-type which is returned when no
'accept' header is given for a certificate-status request from
'text/pson' to 'application/json'.  This is being done for consistency
with defaulting to 'application/json' in place of 'text/pson' elsewhere
for server endpoints in Puppet 5.  Support for roundtripping 'accept:
pson' or 'accept: text/pson' requests in responses as 'content-type:
pson' or 'content-type: text/pson', respectively, has been preserved.

(SERVER-1827) Change default cert-status content-type to json

---

project.clj

This commit bumps the jruby-deps dependencies for JRuby 9k to
9.1.11.0-1.

(SERVER-1840) Bump to JRuby 9.1.11.0-1

---

project.clj
src/ruby/puppetserver-lib/puppet/server/http_client.rb
test/integration/puppetlabs/services/jruby/jruby_puppet_pool_int_test.clj

Previously http-client would create url and url+method metrics for every
call which could become expensive in terms of memory on a production
system.
With the 0.9.0 release (brought in by clj-parent 1.2.1) we can disable this
behavior, which we do with this patch.

(TK-443) Disable http url based metrics

---

documentation/install_from_packages.markdown

This pull request updates package installation instructions for Puppetserver 5. Of note is the removal of unsupported platforms, removal of Puppetserver 2.6 specific documentation, and the addition of platform specific installation requirements and instructions.

(SERVER-1820) Update Puppetserver package installation docs

---

resources/ext/ezbake.conf

This commit bumps the minimum puppet-agent package version from 1.6.0 to
4.99.0 in preparation for the Puppet 5 release.

(MAINT) Bump minimum puppet-agent for packaging to 4.99.0

---

acceptance/lib/helper.rb

This commit bumps the puppet submodule and puppet-agent versions used for
testing to b1efa0a and 4.99.0.345.ge20bbc5, respectively. This version contains
a change to the catalog compiler terminus that allows puppet server to decode
doubly-encoded JSON over the wire from the agent.

(maint) Update puppet submodule to b1efa0a

---

documentation/config_file_puppetserver.markdown

This commit adds info for the new metrics-enabled setting in the
http-client section of the puppetserver.conf file to the
config_file_puppetserver.markdown doc.

(MAINT) Add http-client metrics-enabled setting to puppetserver.conf doc

---

documentation/config_file_logbackxml.markdown
documentation/config_file_puppetserver.markdown
documentation/configuration.markdown
documentation/deprecated_features.markdown
documentation/puppet-api/v3/static_file_content.markdown
documentation/release_notes.markdown

-   Removes Server 2.x release notes and points to the docs site as an archive.
-   Adds Server 5.0 release notes.
-   Updates related docs with relevant information.

(SERVER-1850) Server 5.0 release notes

---

project.clj

This commit removes the "master" tag from the puppetserver artifact
version in the project.clj file.  This is being removed because the
corresponding branch is now "5.0.x" and not "master".

(MAINT) Remove "master" from project version

---

acceptance/lib/helper.rb
acceptance/suites/pre_suite/foss/00_setup_environment.rb
acceptance/suites/pre_suite/foss/35_install_pdb.rb

This commit allows the PUPPET_BUILD_VERSION and PUPPETDB_BUILD_VERSION variables to be set to 'LATEST'. When those environment variables are set to 'LATEST' the version will be set based on the last successful build of puppetdb or puppet-agent.

(SERVER-1798) Support testing against puppetdb and puppet-agent nightly

---

acceptance/suites/pre_suite/puppet4_compat/70_install_puppet.rb

This commit replaces a bad reference to 'master' with 'agent' in the
70_install_puppet.rb acceptance test from the puppet4_compat suite.

(MAINT) Fix agent reference in 70_install_puppet acceptance test

---

documentation/install_from_packages.markdown

-   Use Puppet Platform name instead of Puppet Collections.
-   Use Puppet 5.0, not 2.4.
-   Fix list formatting issues.
Already approved by @justinstoller in PR #1444. This PR retargets 1444 to the 5.0.x branch.

(docs) Fix Server, Puppet version refs.

---

Rakefile

This commit honors the GEM_SOURCE environment variable as an extra gem source
for the bundler gem install done for JRuby spec testing.  If the
variable is not set, the internal puppet rubygems mirror is added as an
extra default gem source.  This should help reduce test run failures due
to intermittent issues seen when accessing the rubygems.org server.

(SERVER-1825) Add puppet rubygems mirror for bundler install

---

Rakefile

This commit adds a '--retry=3' argument to the bundle install command
used in the jruby spec tests.  This is being done to decrease the number
of failures due to connection problems.

(SERVER-1825) Add '--retry=3' arg to bundle install for jruby spec tests

---

project.clj

This commit removes the "-stable" modifier from the `ps-version` in the
project.clj file.  This is no longer needed for builds being produced
from the new '2.x' branch.

(MAINT) Remove "-stable" from the project.clj version

---

documentation/config_file_puppetserver.markdown
src/clj/puppetlabs/puppetserver/jruby_request.clj
src/clj/puppetlabs/services/request_handler/request_handler_service.clj
test/integration/puppetlabs/services/jruby/jruby_metrics_service_test.clj
test/integration/puppetlabs/services/jruby/jruby_puppet_pool_int_test.clj
test/unit/puppetlabs/services/request_handler/request_handler_core_test.clj

This patch implements a ring handler that rejects incoming requests to the
Puppet API with a 503 status code when the backlog of outstanding requests
exceeds a given limit. The handler can also be configured with a splay limit,
a random fraction of which is set as the value of a Retry-After header that is
returned with the 503 error.

(SERVER-1767) Limit concurrent requests to Puppet API

---

acceptance/lib/helper.rb

This commit bumps the puppet submodule and puppet-agent versions for
testing to f24e03659 and 4.99.0.403.g33cc892, respectively.

(MAINT) Bump puppet-agent to 33cc892e8f

---

acceptance/lib/helper.rb

When testing the upgrade path on Debian 8, Puppetserver 2.7.x pulls
in openjdk-7-jre-headless as a dependency. Upgrading Puppetserver to 5.x
pulls in openjdk-8-jre-headless but this Java version isn't necessarily
used. This commit adds a call to update-alternatives on Debian 8 to
ensure that we have the right jvm installed and active for testing.

(maint) Switch java version on Debian 8 upgrade tests

---

documentation/install_from_packages.markdown

Per PR #1452/commit b4b9938, remind Debian users who might have Java 7
installed that they must update the default `java` in use.

(docs) Debian might need to update default Java.

---

acceptance/lib/helper.rb
acceptance/suites/upgrade_tests/10_upgrade.rb

This commit bumps the puppet submodule and puppet-agent versions for
testing to 6cbfbb2 and 5.0.0.47.ge083c24, respectively.

(MAINT) Bump puppet-agent to e083c24b14

---

documentation/http_client_metrics.markdown
documentation/index.markdown
documentation/puppet_server_metrics.markdown
documentation/status-api/v1/services.markdown

Adds HTTP client metrics docs, and links to them from the nav and existing metrics docs.

(SERVER-1842) HTTP client metrics docs.

---

ezbake/config/logback.xml

Add status logging appender in logback file.
The tk-status service allows periodic logging of status data, but this requires
configuration in the logback file to ensure the log messages are sent to the
correct log file and don't clog up the main log file. See TK-400 for more
details.
This feature must be opted into through puppetservers TK conf files before it
has any effect, and has no impact on other logging behavior

(MAINT) Update logback status appender
